<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CLIENT'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
</script>
<style>
.image-box {
    text-align: center;
}
.image-box img {
     width: 125px;
    /* border-radius: 60%; */
    height: 125px;
    /* margin-top: 10px; */
    border: solid 1px #eee;
}
.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 30px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 35px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
        border: solid 1px #eee;
    width: 130px;
}
</style>
<div class="card">
 	<div class="card-content collapse show">
 		<div class="card-box">
        	<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CLIENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='add_client' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'customer','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('branch_id').get('value')==''){
					alert('Please Select Branch');
					dijit.byId('branch_id').focus();
					return false;
			    }
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
                if(dijit.byId('situ_status').get('value')==''){
					alert('Province situ_status');
					dijit.byId('situ_status').focus();
					return false;
			    }
			    dijit.byId('save_new').set('disabled',true); 
      			dijit.byId('save_close').set('disabled',true); 
				return true;

			} else {
				return false;
			}
		</script>
			<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("CLIENT");?></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("JOIN_ACCOUNT_INFO");?>
		                </a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel23" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("GUARANTOR_INFO");?>
		                </a>
		            </li>
		        </ul>
		    </div>
		    <div class="col-md-12">
		        <!-- Tab panels -->
		        <div class="tab-content vertical">
			        <!--Panel 1-->
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
	               		<div class="card-box">
							<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
				                   </label>
				                </div>
								<div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('id');?>
				                   		<?php echo $frm->getElement('branch_id');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NUM");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('client_no');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_KHMER");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('name_kh');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_ENG");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('name_en');?>
				                   </div>
				                </div>
				                
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('sex');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('dob_client');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SITU_STATUS");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('situ_status');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('nationality');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("JOB_TYPE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('job');?>
				                   </div>
				                </div>
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CONTACT_INFO");?> 
				                   </label>
				                </div>
								<div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('phone');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('province');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="district" required >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="commune" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="village" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STREET");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('street');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("HOUSE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('house');?>
				                   </div>
				                </div>
				            </div>
				            
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_DOCUMENT");?> 
				                   </label>
				                </div>
								
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="client_d_type" required/>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CODE_NUMBER");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('national_id');?>
				                   </div>
				                </div>
				                 <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ISSUE_DATE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('id_issuedate');?>
				                   </div>
				                </div>
				                 <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ISSUE_BY");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php  echo $frm->getElement('id_isseueby');?>
				                   </div>
				                </div>
				                 <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHOTO");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php 
												$images = $this->baseUrl().'/images/no-profile.png';
											?>
											<div class="account-image">
												<div class="image-box">
													<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
												</div>
												<div class="button_browse">
												<div id='preview'></div>	
														<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
														<input class="btn_borwse_image" type="file" id="photo" name="photo" />
												</div>
											</div>
				                   </div>
				                </div>
				            </div>
				            
				         </div>
				      </div>
				      <!--/.Panel 1-->
			          <!--Panel 2-->
			          <div class="tab-pane fade in " id="panel22" role="tabpanel">
			          	<div class="card-box">
							<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("JOIN_WITH");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('join_with');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('join_sex');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('dob_join_acc');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('join_nationality');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('relate_with');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEL");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('relate_tel');?>
				                   </div>
				                </div>
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
	                            <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="join_d_type" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CODE_NUMBER");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('join_nation_id');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ISSUE_DATE");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('join_id_issuedate');?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ISSUE_BY");?>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement('join_id_isseueby');?>
				                   </div>
				                </div>
				            </div>
				         </div>
			          </div>
			           <!--/.Panel 2-->
			            <!--Panel 3-->
			          <div class="tab-pane fade in " id="panel23" role="tabpanel">
			          		<div class="card-box">
								<div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SPOUSE_NAME");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $frm->getElement('spouse');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('guarantor_gender');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('dob_guarantor');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEL");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('guarantor_tel');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('guarantor_with');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<input id="guarantor_d_type" />
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("N_O");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $frm->getElement('spouse_nationid');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   </div>
					                </div>
					            </div>
					            
							
					            <div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ADDRESS");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('guarantor_address');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('desc');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php  echo $frm->getElement('status');?>
					                   </div>
					                </div>
					            </div>
					         </div>
			          </div>
			           <!--/.Panel 3-->
			       </div>
			   </div>
			   <div class="clearfix"></div>
			    <div class="card-box">
               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
						 iconClass="dijitIconClear" /> 
					 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
						 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
					<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
						 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		    		</div>
		    	</div>
		</form>
	</div>
</div>
<?php 
	echo $this->frm_popup_district;
	echo $this->frm_popup_village;
	echo $this->frm_popup_comm;
?>

<script type="text/javascript">
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#photo").change(function(){
    readURL(this);
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.data.ObjectStore");

var d_datastore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
	store: district_store,
	autoComplete: true,
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	value: "<?php echo $this->row['dis_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
		onChange: function() {
			district = dijit.byId('district').get('value');
			if(district==-1){
				showPopupdistrict();
				}
				filterCommune();
	    }
	}, "district");
	
	new dijit.form.FilteringSelect({
	store: commune_store,
	autoComplete: true,
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	value: "<?php echo $this->row['com_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
		onChange: function() {
			commune = dijit.byId('commune').get('value');
			if(commune==-1){
				showPopupCommune();
			}
			else{
				filterVillage();
			}
	}
	}, "commune");

	 
	new dijit.form.FilteringSelect({
	store: village_store,
	autoComplete: true,
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	class: 'fullside',
	value: "<?php echo $this->row['village_id'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			vill = dijit.byId('village').get('value');
			if(vill==-1){
				showPopupVillage();
			}
}
	}, "village");

	new dijit.form.FilteringSelect({
		store: d_datastore,
		autoComplete: true,          
		required: false,		           
		name: "client_d_type",
		id: "client_d_type",
		searchAttr: "name",
		class: 'fullside',
		value: "<?php echo $this->row['client_d_type'];?>",
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
			onChange: function() {
				client_d_type = dijit.byId('client_d_type').get('value');
				if(client_d_type==-1){
					doc_type=1;
					showPopupclientdtype();
				}
			}
		}, "client_d_type");

	new dijit.form.FilteringSelect({
		store: d_datastore,
		autoComplete: true,           
		required: false,		           
		name: "join_d_type",
		id: "join_d_type",
		searchAttr: "name",
		class: 'fullside',
		value: "<?php echo $this->row['join_d_type'];?>",
			onChange: function() {
				client_d_type = dijit.byId('join_d_type').get('value');
				if(client_d_type==-1){
					doc_type=2;
					showPopupclientdtype();
				}
			}
		}, "join_d_type");

	new dijit.form.FilteringSelect({
		store: d_datastore,//dojo.data.ObjectStore({objectStore: d_data}),
		autoComplete: true,
		required: false,		           
		name: "guarantor_d_type",
		id: "guarantor_d_type",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('guarantor_d_type').get('value');
				if(client_d_type==-1){
					doc_type=3;
					showPopupclientdtype();
				}
			}
		}, "guarantor_d_type");
	
	filterDistrict();
	filterCommune();
	filterVillage();

});
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		    dijit.byId('district').attr('value','<?php echo $this->row['dis_id'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		    dijit.byId('commune').attr('value','<?php echo $this->row['com_id'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': commune_id
		},
		handleAs:"json",
		load: function(data) {	
			village_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('village').set('store', village_store);
		    dijit.byId('village').attr('value','<?php echo $this->row['village_id'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});
}
client_submit = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'customer','action'=>'getclientnumberbybranch'));?>';
function getFunction(){
		branch_id = dijit.byId('branch_id').get('value');
		dojo.xhrPost({
			url:client_submit,	
			content:{ 
			    'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {	
				dijit.byId('client_no').attr('value',data);
			},
			error: function(err) {
			}
		});
}
client_village = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-village'));?>';
function addVillage(){
	if(dijit.byId('frm_village').validate()) {
		dojo.xhrPost({
			url:client_village,	
			form:dojo.byId('form_village'),
			handleAs:"json",
			load: function(data) {
				labelkh = dijit.byId('village_namekh').get('value');
				var villageItem1 = {					
						id: data,
						name:labelkh,
				};			
				addDataToSelectbox(dijit.byId('village'), village_store, villageItem1, data);	
				dijit.byId('frm_village').reset();
				dijit.byId('frm_village').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name:dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name:communekh,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var document_type_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-document-type'));?>';
function addNewDocumentType(){
	dojo.xhrPost({
		url:document_type_url,	
		content:{ 
		    'title_en':dijit.byId('clienttype_nameen').get('value'),
		    'title_kh':dijit.byId('clienttype_namekh').get('value'),
		    'type':23,
		},
		handleAs:"json",
		load: function(data) {	
			clienttypeen = dijit.byId('clienttype_nameen').get('value');
			clienttypekh = dijit.byId('clienttype_namekh').get('value');
			if(doc_type==1){
				document_type = dijit.byId('client_d_type');
				
			}else if(doc_type==2){
				document_type = dijit.byId('join_d_type');
			}else{
			}

			 var myNewItem1 = {					
						id: data,
						name: clienttypekh+'-'+clienttypeen
				};			
			addDataToSelectbox(document_type, d_datastore, myNewItem1, data);		
			dijit.byId('frm_clienttype').reset();
			dijit.byId('frm_clienttype').hide();
	
		},
		error: function(err) {
			alert(err);
		}
	});	
}
function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}
</script>