<?php	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Edit Pawn')); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	echo $this->frmpupopinfoclient;
	$data = $this->data;
?>
<style>
div.bgform {
    background: #91bef5;
    padding: 10px;
}
.dark-style div.bgform{
	 background: #262a3d;
}
</style>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('Edit Pawn');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'index','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				co_id = dijit.byId('co_id').get('value');
				client = dijit.byId('member').get('value');
				branch_id = dijit.byId('branch_id').get('value');
				if (branch_id=='' || branch_id==-1){
				   infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
				   dijit.byId('branch_id').focus();
				   return false;
				}
				if (client=='' || client==-1){
					infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?>');
					dijit.byId('member').focus();
					return false;
				}
				rs = checkValidateDate();
				if(rs==false){
				  return false;			
				}
				currency_type = dijit.byId('currency_type').get('value');
				if(currency_type==1){
					amount_loan = dijit.byId('total_amount').get('value');
					if(amount_loan<10000){
						infoMessageAlert('Loan Amount Must Than 10000 for Riel Currency!');
						return false;
					}

				}
				 dijit.byId('save_close').set('disabled',true); 
				 dijit.byId('save_view').set('disabled',true); 
				 loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CLIENT_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('branch_id');?>
									<input type="hidden" id="id" name="id" value="<?php echo $this->rs['id'];?>"/>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAWN_CODE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('loan_code');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_LEVEL");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('level');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="member" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_CODE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<div class="row">
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="customer_code" />
										 </div>
										 <div class="col-md-3 col-sm-3 col-xs-12">
											<input class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" onclick="filterClient();" class="full" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button"/>
										 </div>
									 </div>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("PRODUCT_DESCRIPTION");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRODUCT_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="product_id" /><?php //echo $frm->getElement('product_id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRODUCT_DESCRIPTION");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('description');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EST_VALUE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('estimatevalue');?>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("PHOTO");?></h5>
						</div>
						<div class="card-body">
							<?php 
								$images = $this->baseUrl().'/images/no-image.png';
								if (!empty($this->rs['images'])){
									$images = $this->baseUrl().'/images/pawnshop/'.$this->rs['images'];
								}
							?>
							<div class="d-flex align-items-start align-items-sm-center gap-4">
								<img src="<?php echo $images;?>" alt="user-avatar" class="d-block w-px-100 h-px-100 rounded" id="uploadedAvatar" />
								<div class="button-wrapper">
									<label for="photo" class="btn btn-primary me-2 mb-3" tabindex="0">
									  <span class="d-none d-sm-block"><?php echo $tr->translate("Upload");?></span>
									  <i class="ti ti-upload d-block d-sm-none"></i>
									  <input type="file" id="photo" name="photo" class="account-file-input" hidden accept="image/png, image/jpeg" />
									</label>
									<button type="button" class="btn btn-label-secondary account-image-reset mb-3">
									  <i class="ti ti-refresh-dot d-block d-sm-none"></i>
									  <span class="d-none d-sm-block"><?php echo $tr->translate("RESET");?></span>
									</button>
									<div class="text-muted">Allowed JPG, GIF or PNG. Max size of 800K</div>
								</div>
							</div>
							
						</div>
					</div>
	            </div>
	        </div>
			<div class="card card-form mb-4">
				<div class="card-header d-flex justify-content-between">
					<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("ព៌ត័មាន ដាក់បញ្ចាំ");?></h5>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12 bgform">
							<div class="row g-3">
							   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("ILLOAN_INFO");?> 
							   </label>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENCY");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('currency_type');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_AMOUNT");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('total_amount');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ADMIN_FEE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('admin_fee');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAMENT_METHOD");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('repayment_method');?>
							   </div>
							</div>
						 </div>
						 <div class="col-md-4 col-sm-4 col-xs-12 bgform">
							<div class="row g-3">
							   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("ILLOAN_INFO");?> 
							   </label>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TERM_INSTALL");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('payment_term');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAWNSHOP_DURATION");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('period');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_TYPE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest_type');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST RATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest_rate');?>
							   </div>
							</div>
						 </div>
						 <div class="col-md-4 col-sm-4 col-xs-12 bgform">
							<div class="row g-3">
							   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INFO_FUND");?> 
							   </label>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAWN_DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('release_date');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FIRST_PAYMENT");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('first_payment');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAWN_ENDDATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('date_line');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("បង្កាន់ដៃទទួលប្រាក់");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('receipt_num');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('status_using');?>
							   </div>
							</div>
						 </div>
					</div>
				</div>
			</div>
	        <div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
	    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id="save_close" value='saveclose' dojoType="dijit.form.Button" />
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-zoom-in" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' id="save_view"  value='savenew' dojoType="dijit.form.Button" />
	    		</div>
			</div>
		</form>
	</div>
</div>



<div class="dijitHidden">
<style>
	.print tr td{
	}
	.myblog{display: none !important;}
</style>
<?php 
$frm = $this->Form_Frmcallecterall;
?>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("COLLECTERALL_TYPE")?>', onCancel:hideDialog" id="frm_product" style="width:1000px">
		<div class="print" style="text-align:center;">
			<form id='frm_producttype' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="card card-form mb-4">
					<div class="card-header d-flex justify-content-between">
						<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="fa fa-cubes ms-n1 me-2"></i> <?php echo $tr->translate("COLLECTERALL_TYPE");?></h5>
					</div>
					<div class="card-body p-0">
						<div class="row">
							<div class="col-md-12 col-sm-12 col-xs-12 p-0">
								<div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12 text-start px-1" for="first-name"><?php echo $tr->translate("NAME_KH");?>
								   </label>
								   <div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('title_kh');?>
								   </div>
								</div>
								<div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12 text-start px-1" for="first-name"><?php echo $tr->translate("NAME_ENG");?>
								   </label>
								   <div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('title_en');?>
								   </div>
								</div>
								<div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12 text-start px-1" for="first-name"><?php echo $tr->translate("DATE");?>
								   </label>
								   <div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('date');?>
										<input dojoType="dijit.form.TextBox" type="hidden" value="1" name="status" id="status" />
		    			
								   </div>
								</div>
								<div class="row g-3">
								   <label class="control-label col-md-12 col-sm-12 col-xs-12 text-start px-1" for="first-name"><?php echo $tr->translate("ពត៍មានលម្អិត");?>
								   </label>
								</div>
								<div class="row g-3">
								   <div class="col-md-12 col-sm-12 col-xs-12">
										<input dojoType="dijit.form.Textarea" class="fullside height200" rows="200" id="description_product" name="description" value="" type="text">
								   </div>
								</div>
							</div>
						</div>
						<div class="clearfix"></div>
						<div class="card-box">
							<div class="col-sm-12 border-top mt-2 py-2 text-center">
								<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" onclick="addProductName();" value="save_proclose" name="save_proclose" id="save_proclose" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"  />
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់', onCancel:hideDialog" id="lbl_schedule" style="width:1000px">
		<div class="print" style="text-align:center;">
		<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" onclick="submintss();" label="<?php echo $tr->translate("SAVECLOSE");?>" name='save_close' id='save_closereceipt'  value='saveclose' dojoType="dijit.form.Button" />
		<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" onclick="showReceipt();" label="<?php echo $tr->translate("SAVE_PRINT");?>"  name='saveprint' value='saveprint' dojoType="dijit.form.Button" />
		<br />
		<br />
		<div id="t_amountmoneytype" name="t_amountmoneytype"></div>
		</div>
	</div>
</div>
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
<div class="dijitHidden" style="width: 23cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'បង្កាន់ដៃដាក់ទ្រពបញ្ចាំ ', onCancel:hideDialog" id="frm_receipt" style="width:24cm;">
		<div style="padding:5px;width:100%">
			<div id="rpt_print" class="print">
				<style>
					.myblog{display: table;}
						.fontbig{
							font-size: 15px;	
						}
						.fonttel{
							font-size: 18px;	
						}
						.pleft{
							width: 110px;	
						}
						.label{ font-weight: normal;font-size: 22px;}
						.lblvalue{ font: 16px 'Times New Roman','Khmer OS Battambang';
								border: 1px solid #000; 
								padding: 1px;
								line-height: 25px;
								text-align: left;
							   min-width:200px;
						}
						.lblsubvalue{
								font: 16px 'Times New Roman','Khmer OS Battambang';
								border: 1px solid #000; 
								padding: 1px 0px;
								line-height: 25px;
								text-align: left;
								width:34%;
						}
						.h{ margin-top:0px; line-height: 15px;
						  font-family: Arial Black;font-family:'Times New Roman','Khmer OS Muol Light';
						  }
					   .print td{ font:bold 12px 'Times New Roman','Khmer OS Battambang';}
					   .khmer{font:12px 'Times New Roman','Khmer OS Battambang';}
					   .one{white-space:nowrap;}
						table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
						</style>	
						<table class="print" cellspacing="0"  cellpadding="0" style="width:100%;height: 10cm;font-family:'Times New Roman','Khmer OS Battambang';font-size:16px;color:#000; padding:15px 10px 0px 5px; margin: 0px;">
							<tr>
								<td colspan="3">
									<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0; border:none;">
						            	<tr>
						                	<td width="35%" valign="top" style="padding:0;"><!-- <img src="<?php //echo $this->baseUrl();?>/images/logo.jpg" height="85px"> --></td>
						                	<td valign="top" align="center">
						                		<div class="h" ><?php echo $tr->translate("បង្កាន់ដៃដាក់ទ្រពបញ្ចាំ");?></div> 
						                		<div class="h" style="padding-top:10px;"><?php echo $tr->translate(" PAWN TICKET RECEIPT");?></div> 
						                	</td>
						                    <td width="35%">
						                    	
						                    </td>
						                </tr> 
						            </table>
								</td>
							</tr>
							<tr>
								<td colspan="3" valign="top">
									<table width="100%">
										<tr>
											<td width="50%" valign="top">
												<table width="100%" style="text-align:left !important;" >
													<tr>
														<td>&nbsp;<?php echo $tr->translate("PAWN_CODE");?></td>
														<td class="lblvalue one khmerbold"><strong>&nbsp;<label id="lb_receipt_no" ></label></strong></td>
													</tr>
													<tr>
														<td>&nbsp;កាលបរិច្ឆេទ</td>
														<td class="lblvalue one khmerbold">&nbsp;<?php  $today = date("j/m/Y, g:i a");echo $today; ?></td>
													</tr>
													<tr>
														<td>&nbsp;ឈ្មោះអតិថិជន</td>
														<td class="lblvalue one khmerbold"><span id="lb_customername" ></span></td>
													</tr>
													<tr>
														<td style="white-space: nowrap;">&nbsp;ប្រភេទទ្រព្យបញ្ចាំ</td>
														<td class="lblvalue one khmerbold" style="height:105px; white-space: normal;max-width: 100%;" valign="top">&nbsp;<span id="lb_producttype" ></span></td>
													</tr>
												</table>
											</td>
											<td width="50%" valign="top">
												<table width="100%">
													<tr>
														<td width="120px">&nbsp;ចំនួនប្រាក់ខ្ចី</td>
														<td class="lblvalue one khmerbold">&nbsp;<span id="lb_loanamount"></span></td>
													</tr>
													<tr>
														<td>&nbsp;អាត្រាការប្រាក់</td>
														<td class="lblvalue one khmerbold">&nbsp;<span id="lb_interest_rate"></span></td>
													</tr>
													<tr>
														<td>&nbsp;ការប្រាក់ត្រូវបង់</td>
														<td class="lblvalue one khmerbold">&nbsp;<span id="lb_total_interest"></span></td>
													</tr>
													<tr>
														<td>&nbsp;ថ្ងៃបញ្ចាំ </td>
														<td class="one khmerbold">
															<table width="100%">
																<tr>
																	<td width="50%" class="lblsubvalue one khmerbold"><span id="lb_start_date"></span></td>
																	<td style="white-space: nowrap;">&nbsp;រយៈពេលបញ្ចាំ</td>
																	<td class="lblsubvalue one khmerbold">&nbsp;<span id="lb_period" style="white-space:nowrap;"></span></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td style="white-space: nowrap;">&nbsp;ថ្ងៃបង់ប្រាក់ដំបូង</td>
														<td class="lblvalue one khmerbold"><strong>&nbsp;<span id="lb_firstpayment" style="white-space:nowrap;"></span></strong></td>
													</tr>
													<tr>
														<td>&nbsp;ផុតកំណត់</td>
														<td class="lblvalue one khmerbold"><strong>&nbsp;<span id="lb_end_date" style="white-space:nowrap;"></span></strong></td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr height="100px">
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Muol Light';white-space: nowrap;">គណនេយ្យករ  <div class="h" style="margin-left:7px !important;">ACCOUNTANT</div> </td>
								<td width="30%" class="one khmerbold" align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Muol Light';border-left: 1px solid #fff !important; border-right: 1px solid #fff !important;">អ្នកធានា <div class="h" style="margin-left:7px !important;">GUARANTOR</div></td>
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Muol Light';">អ្នកដាក់ទ្រព្យ <div class="h" style="margin-left:7px !important;">PAWNER OF LOAN</div>
							    </td>
							</tr>
							<tr >
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Battambang';white-space: nowrap;"><label id="lblAccountName">&nbsp;<?php echo $this->user_name;?></label> </td>
								<td width="30%" class="one khmerbold" align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Battambang';border-left: 1px solid #fff !important; border-right: 1px solid #fff !important;"><label id="lblGuarantor">&nbsp;</label></td>
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Battambang';"><label id="lblClient">&nbsp;</label>
							    </td>
							</tr>
							<tr>
								<td colspan="3" style="border: solid 1px #000;padding: 0;"></td>
							</tr>
							<tr style="font-size: 10px;border:1px solid #000;">
							    <td class="khmerbold" valign="top" style=""><span><?php echo $data['client_company_name'];//$tr->translate("BRAND_TITLE");?></span></td>
							    <td class="khmerbold" valign="top" colspan="2" style="">
								    <div style="font-family:'Times New Roman','Khmer OS Battambang';">
								    	<span id="footrecieptAddress"><?php //echo $data['branch-add-client'];//$tr->translate("ADDRESS_COMPANY");?></span>
								    </div>
								    <span><span id="footrecieptPhone"><?php //echo $data['tel-client'];//$tr->translate("TEL_COMPANY");?></span></span>
							    </td>
							</tr>
					</table>
					<div style="border:1px dotted #000;margin: 20px 0px;"></div>
					<table class="print myblog" cellspacing="0"  cellpadding="0" style="width:100%;height: 10cm;font-family:'Times New Roman','Khmer OS Battambang';font-size:16px;color:#000; padding:15px 10px 0px 5px; margin: 0px;">
							<tr>
								<td colspan="3">
									<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0;border:none;">
						            	<tr>
						                	<td width="35%" valign="top" style="padding:0;"><!--<img src="<?php //echo $this->baseUrl();?>/images/logo.jpg" height="85px"> --></td>
						                	<td valign="top" align="center">
						                		<div class="h" ><?php echo $tr->translate("បង្កាន់ដៃដាក់ទ្រពបញ្ចាំ");?></div> 
						                		<div class="h"  style="padding-top:10px;"><?php echo $tr->translate("PAWN TICKET RECEIPT");?></div> 
						                	</td>
						                    <td width="35%">
						                    </td>
						                </tr> 
						            </table>
								</td>
							</tr>
							<tr>
								<td colspan="3" valign="top" style="">
									<table width="100%">
										<tr>
											<td width="50%" valign="top">
												<table width="100%" style="text-align:left !important;" >
													<tr>
														<td>&nbsp;<?php echo $tr->translate("PAWN_CODE");?></td>
														<td class="lblvalue one khmerbold"><strong>&nbsp;<label id="lb_receipt_no1" ></label></strong></td>
													</tr>
													<tr>
														<td>&nbsp;កាលបរិច្ឆេទ</td>
														<td class="lblvalue one khmerbold">&nbsp;<?php  $today = date("j/m/Y, g:i a");echo $today; ?></td>
													</tr>
													<tr>
														<td>&nbsp;ឈ្មោះអតិថិជន</td>
														<td class="lblvalue one khmerbold"><span id="lb_customername1" ></span></td>
													</tr>
													<tr>
														<td style="white-space: nowrap;">&nbsp;ប្រភេទទ្រព្យបញ្ចាំ</td>
														<td class="lblvalue one khmerbold" style="height:105px;" valign="top">&nbsp;<span id="lb_producttype1" ></span></td>
													</tr>
												</table>
											</td>
											<td width="50%" valign="top" style="">
												<table width="100%">
													<tr>
														<td width="120px">&nbsp;ចំនួនប្រាក់ខ្ចី</td>
														<td class="lblvalue one khmerbold">&nbsp;<span id="lb_loanamount1"></span></td>
													</tr>
													<tr>
														<td>&nbsp;អាត្រាការប្រាក់</td>
														<td class="lblvalue one khmerbold">&nbsp;<span id="lb_interest_rate1"></span></td>
													</tr>
													<tr>
														<td>&nbsp;ការប្រាក់ត្រូវបង់</td>
														<td class="lblvalue one khmerbold">&nbsp;<span id="lb_total_interest1"></span></td>
													</tr>
													<tr>
														<td>&nbsp;ថ្ងៃបញ្ចាំ </td>
														<td>
															<table width="100%">
																<tr>
																	<td width="50%" class="lblsubvalue one khmerbold"><span id="lb_start_date1"></span></td>
																	<td style="white-space: nowrap;">&nbsp;រយៈពេលបញ្ចាំ</td>
																	<td class="lblsubvalue one khmerbold">&nbsp;<span id="lb_period1" style="white-space:nowrap;"></span></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td style="white-space:nowrap;">&nbsp;ថ្ងៃបង់ប្រាក់ដំបូង</td>
														<td class="lblvalue one khmerbold"><strong>&nbsp;<label id="lb_firstpayment1" style="white-space:nowrap;"></label></strong></td>
													</tr>
													<tr>
														<td>&nbsp;ផុតកំណត់</td>
														<td class="lblvalue one khmerbold"><strong>&nbsp;<label id="lb_end_date1" style="white-space:nowrap;">dara</label></strong></td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr height="100px">
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Muol Light';white-space: nowrap;">គណនេយ្យករ  <div class="h" style="margin-left:7px !important;">ACCOUNTANT</div> </td>
								<td width="30%" class="one khmerbold" align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Muol Light';border-left: 1px solid #fff !important; border-right: 1px solid #fff !important;">អ្នកធានា <div class="h" style="margin-left:7px !important;">GUARANTOR</div></td>
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Muol Light';">អ្នកដាក់ទ្រព្យ <div class="h" style="margin-left:7px !important;">PAWNER OF LOAN</div>
							    </td>
							</tr>
							<tr >
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Battambang';white-space: nowrap;"><span id="lblAccountName1">&nbsp;<?php echo $this->user_name;?></span> </td>
								<td width="30%" class="one khmerbold" align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Battambang';border-left: 1px solid #fff !important; border-right: 1px solid #fff !important;"><span id="lblGuarantor1">&nbsp;</span></td>
							    <td width="35%" class="one khmerbold"  align="center" valign="top" style="font-family:'Times New Roman','Khmer OS Battambang';"><span id="lblClient1">&nbsp;</label>
							    </td>
							</tr>
							<tr>
								<td colspan="3" style="border: solid 1px #000;padding: 0;"></td>
							</tr>
							<tr style="font-size: 11px;border:1px solid #000;">
							    <td class="khmerbold" valign="top" style=""><span><?php echo $data['client_company_name'];//$tr->translate("BRAND_TITLE");?></span></td>
							    <td class="khmerbold" valign="top" colspan="2" style="">
								    <div style="font-family:'Times New Roman','Khmer OS Battambang';">
								    	<span id="footrecieptAddress1" ><?php //echo $data['branch-add-client'];//$tr->translate("ADDRESS_COMPANY");?></span>
								    </div>
								    <span><span id="footrecieptPhone1"><?php //echo $data['tel-client'];//$tr->translate("TEL_COMPANY");?></span></span>
							    </td>
							</tr>
					</table>
					
			</div>
		</div>
	<div align="center">
	<button dojoType="dijit.form.Button" class="button-class button-danger" iconClass="glyphicon glyphicon-remove" type="button" onclick="hideDialog();"><?php echo $tr->translate("CANCEL");?></button>
	<button dojoType="dijit.form.Button" class="button-class button-primary" iconClass="glyphicon glyphicon-print" type="button" onclick="doPrint();"><?php echo $tr->translate("PRINT");?></button>		 
	</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
</div>
</div>
<?php //echo $this->frmpupoploantype;?>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">	
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dijit.form.Textarea");
function chechPaymentMethod(){
}
function submintss(){
	 dijit.byId('save_close').set('disabled',true); 
	 dijit.byId('save_closereceipt').set('disabled',true);
	 dijit.byId('save_view').set('disabled',true);
	$( '#frm_add_tran' ).submit();
}
function showReceipt(){
	 dojo.byId("lb_receipt_no").innerHTML = dijit.byId("loan_code").get('value');
	 dojo.byId("lb_loanamount").innerHTML = dojo.number.format(dijit.byId("total_amount").get('value'),2)+' '+dijit.byId('currency_type').attr('displayedValue');
	
	 dojo.byId("lb_producttype").innerHTML = dijit.byId("product_id").attr('displayedValue')+" : "+$("#description").val();

	 //dojo.byId("lb_interest_rate").innerHTML = dijit.byId("interest_rate").get('value')+ ' %';
	 total_amount = dijit.byId('total_amount').get("value");
	 interest_type = dijit.byId('interest_type').get("value");
	 
	 total_interest = dijit.byId('interest_rate').get("value");
	 if(interest_type==1){
		interest_rate = dijit.byId('interest_rate').get("value")+ ' %';
	 	total_interest= total_amount*total_interest/100;
	 }else{
		 interest_rate = dijit.byId('interest_type').attr('displayedValue');
	 }
	 dojo.byId("lb_interest_rate").innerHTML = interest_rate;
	 dojo.byId("lb_total_interest").innerHTML = total_interest+' '+dijit.byId('currency_type').attr('displayedValue');;
	 dojo.byId("lb_customername").innerHTML =dijit.byId('member').attr('displayedValue');
	 dojo.byId("lb_start_date").innerHTML =dijit.byId("release_date").attr('displayedValue');
	 dojo.byId("lb_period").innerHTML =dijit.byId("period").attr('displayedValue')+" ខែ";
	 dojo.byId("lb_firstpayment").innerHTML =dijit.byId("first_payment").attr('displayedValue');
	 dojo.byId("lb_end_date").innerHTML =dijit.byId("date_line").attr('displayedValue');

	 dojo.byId("lb_receipt_no1").innerHTML = dijit.byId("loan_code").get('value');
	 dojo.byId("lb_loanamount1").innerHTML = dojo.number.format(dijit.byId("total_amount").get('value'),2)+' '+dijit.byId('currency_type').attr('displayedValue');
	 dojo.byId("lb_interest_rate1").innerHTML = interest_rate;
	 dojo.byId("lb_producttype1").innerHTML = dijit.byId("product_id").attr('displayedValue')+" : "+$("#description").val();
	 dojo.byId("lb_total_interest1").innerHTML = total_interest+' '+dijit.byId('currency_type').attr('displayedValue');;
	 dojo.byId("lb_customername1").innerHTML =dijit.byId('member').attr('displayedValue');
	 dojo.byId("lb_start_date1").innerHTML =dijit.byId("release_date").attr('displayedValue');
	 dojo.byId("lb_period1").innerHTML =dijit.byId("period").attr('displayedValue')+" ខែ";
	 dojo.byId("lb_firstpayment1").innerHTML =dijit.byId("first_payment").attr('displayedValue');
	 dojo.byId("lb_end_date1").innerHTML =dijit.byId("date_line").attr('displayedValue');
	 dojo.byId("lblClient").innerHTML =dijit.byId('member').attr('displayedValue');
	 dojo.byId("lblClient1").innerHTML =dijit.byId('member').attr('displayedValue');
	 dijit.byId("frm_receipt").show();
	
}

function calCulateAdminFee(){
	p_income="<?php echo $this->setting['adminfee']?>";
	t_admin=dijit.byId('total_amount').get('value');
	adminfee=(p_income*(t_admin/100));
	dijit.byId('admin_fee').attr('value',adminfee);
}

r=0;
var url_previewloan = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'index','action'=>'addpawnshoptest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()) {
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id=='' || branch_id==-1){
			infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
			dijit.byId('branch_id').focus();
			return false;
		}
		
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?>');
			dijit.byId('member').focus();
			return false;
		}
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				HideloadingBlock();
				temp='';	
			     fund_title=0;thead='';fund_title=0;
				 		temp='<table class="collape tablesorter" style="font-size:13px; width:970px !important; " id="table">'
						temp+='<tr><th><?php echo $tr->translate("NUM");?></th>';
						temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
					    temp+='<th><?php echo $tr->translate("ប្រាក់ដើមជំពាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						temp+='<th><?php echo $tr->translate("ការប្រាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ត្រូវបង់សរុប");?></th>';
						 temp+='<th><?php echo $tr->translate("ចំនួនថ្ងៃ");?></th>';
				var t_principal_permonth=0;
				var t_total_payment=0;
				var t_total_interest=0;
				for(i=0;i<data.length;i++){
			        r++;
			        t_principal_permonth = parseFloat(t_principal_permonth)+parseFloat(data[i].principal_permonth);
			        t_total_interest = parseFloat(t_total_interest) + parseFloat(data[i].total_interest);
			        t_total_payment = parseFloat(t_total_payment) + parseFloat(data[i].total_payment);
					    temp+='<tr><td align="center">'+r+'</td>';
						d = new Date(data[i].date_name);
						temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						temp+='<td>'+data[i].total_principal+'</td>';
						temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						temp+='<td>'+dojo.number.format(data[i].total_payment,2)+'</td>';
						temp+='<td>'+data[i].amount_day+'</td></tr>';
				 }
				temp+='<tr style=" background: #e7ecf7;"><td align="center"><?php echo $tr->translate("TOTAL");?></td>';
				temp+='<td colspan="2"></td>';
				temp+='<td><strong>'+dojo.number.format(t_principal_permonth,2)+'</strong></td>';
				temp+='<td><strong>'+dojo.number.format(t_total_interest,2)+'</strong></td>';
				temp+='<td><strong>'+dojo.number.format(t_total_payment,2)+'</strong></td>';
				temp+='<td></td></tr>';
				temp+='</table>';
				dojo.byId('t_amountmoneytype').innerHTML = temp;
				dijit.byId("lbl_schedule").show();
			},
			error: function(err) {
				HideloadingBlock();
				infoMessageAlert("You can not preview this loan number!");
			}
	   });
	}else{
		infoMessageAlert("You can not preview this loan number!");
	}	
}
    function checkValidateDate(){
     }
    function setDefaultPaymentAmount(){
		}
	
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
		window.frames["print_frame"].window.focus();
		window.frames["print_frame"].window.print();
		$( "#frm_add_tran" ).submit();
		hideDialog();
	}
	function hideDialog() {		
		dijit.byId("frm_receipt").hide();
		//saveTrans(); 
	}
</script>
<script type="text/javascript">


var client_store  = getDataStorefromJSON('id','name', [] );
var client_number_store  = getDataStorefromJSON('id','name', [] );//getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode($this->recieverlist));?> );
var product_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->product_store));?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,12);
		filterClient();
		dijit.byId("product_id").attr("value",'<?php echo $this->rs['product_id'];?>');
		dijit.byId("receipt_num").set("readOnly",true);
	  });
	new dijit.form.FilteringSelect({
	store: client_store,
	queryExpr: "*${0}*",
	autoComplete: false,                     
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			dijit.byId('customer_code').attr('value',member);
		}
}
	}, "member");

	new dijit.form.FilteringSelect({
	store: client_number_store,
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: product_store,
		autoComplete: true,            
		required: false,		           
		name: "product_id",
		id: "product_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			pro_id = dijit.byId('product_id').get('value');
			if(pro_id==-1){
				dijit.byId("frm_product").show();
			}else{
			}
	    }
		}, "product_id");
		
	let e = document.getElementById("uploadedAvatar");
	const l = document.querySelector(".account-file-input")
	  , c = document.querySelector(".account-image-reset");
	if (e) {
		const r = e.src;
		l.onchange = ()=>{
			l.files[0] && (e.src = window.URL.createObjectURL(l.files[0]))
		}
		,
		c.onclick = ()=>{
			l.value = "",
			e.src = r
		}
	}
});
</script>
<script type="text/javascript">
function filterClient(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('member').query.branch_id = branch_id;
		dijit.byId('customer_code').query.branch_id = branch_id;
		dijit.byId('customer_code').reset();
		getLoanByBranch();
		getAllClientByBranch(branch_id);
		getAllClientNumberByBranch(branch_id);
}
function addProductName(){
	if(dijit.byId('frm_producttype').validate()) {
		dijit.byId('save_proclose').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'pawnproduct','action'=>'addprotype')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_producttype"),	
				handleAs:"json",	    
				load: function(data){
					dijit.byId("frm_product").hide();
					var dataItem1 = {					
							id: data,
							name:dijit.byId("title_kh").get("value"),
					};			
					addDataToSelectbox(dijit.byId('product_id'), product_store, dataItem1, data);	
				},
				error: function(e) {
					dijit.byId("frm_product").hide();
				}
			});
	}
}
var url_getclient = '<?php echo $this->url(array('module'=>'pawnshop','controller'=>'customer','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		    dijit.byId("member").attr("value",<?php echo $this->rs['customer_id'];?>);
		    dijit.byId("customer_code").attr("value",<?php echo $this->rs['customer_id'];?>);
		    
		},
		error: function(err) {
			infoMessageAlert(err);
		}
	});
	
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'saving','controller'=>'customer','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	return false;
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		infoMessageAlert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
		},
		error: function(err) {	
		}
	});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}

</script>
<?php 
echo $this->frmpupoploantype;
?>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	date_release=dijit.byId("release_date").get('value');
	var a = new Date(date_release);
	
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('date_line').attr('value',epx_date);
	CalculateWidthdraw();
}
function calCulateEndDate(){	
}
function CalculateDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("release_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("release_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function CalculateWidthdraw(){
}
function getFirstPayment(){
	amount_date = dijit.byId('period').get("value");
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
	
	pay_term = dijit.byId('payment_term').get("value");
	if(pay_term==3){//month
		var month = a.getMonth()+1+1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (1)); 
		var month = a.getMonth() + 1;
	}
	mm = month%12;
	var year = parseInt(month/12);
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+year;
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function loading(){
    loadingBlock()
}
</script>
