<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PAWNSHOP"));
	$frm = $this->frm_search;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	
	$url_payment = $this->baseUrl()."/pawnshop/payment/add/id/";
	$url_dach = $this->baseUrl()."/pawnshop/dach/index/id/";
	$url_agreement = $this->baseUrl()."/report/pawn/agreement/id/";
	$url_receipt = $this->baseUrl()."/report/pawn/pawnticketreceipt/id/";
	$url_schedule = $this->baseUrl()."/report/pawn/rpt-paymentschedules/id/";
	$urlPaymenthistory = $this->baseUrl()."/report/pawn/paymenthistory/id/";
	$url_reschedule = $this->baseUrl()."/pawnshop/reschedule/add/id/";
?>

<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-american-sign-language-interpreting"></i>&nbsp;<?php echo $tr->translate('PAWNSHOP');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('members');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("product_id");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("completed_status");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("dach_status");?>
					</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>

<script src="<?php echo $baseurl;?>/js/help.js"></script>	
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var client_store  = getDataStorefromJSON('id','name', [] );

var url_getclient = '<?php echo $this->url(array('module'=>'saving','controller'=>'customer','action'=>'getclientbybranch')); ?>';
function filterClient(){
	branch_id=dijit.byId("branch_id").get("value");
	if(branch_id<0 || branch_id==''){
		return false;
	}
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
			
		}
	});
}

require(["dojo/ready"], function(ready){
		new dijit.form.FilteringSelect({
			store: client_store,
			autoComplete: true,
			query: {
				branch_id: "-1"
			},            
			required: false,		           
			name: "member",
			id: "member",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				member = dijit.byId('member').get('value');
				if(member==-1){
					showPopupclient();
				}else{
					dijit.byId('customer_code').attr('value',member);
				}
		}
	}, "member");
});


var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			
			var newPageTitle="";
			var actionType=1;
			var m = "clicked: " + key;
			 if(key=="payment"){
				url='<?php echo $url_payment;?>';
				actionType=2;
			}else if(key=="dach"){
				url='<?php echo $url_dach;?>';
				actionType=2;
			}else if(key=="reschedule"){
				url='<?php echo $url_reschedule;?>';
				actionType=2;
			}else if(key=="agreement"){
				url='<?php echo $url_agreement;?>';
				newPageTitle="<?php echo $tr->translate("AGREEMENT");?>";
			}else if(key=="receipt"){
				url='<?php echo $url_receipt;?>';
				newPageTitle="<?php echo $tr->translate("PAWN_RECEIPT");?>";
			}else if(key=="schedule"){
				url='<?php echo $url_schedule;?>';
				newPageTitle="<?php echo $tr->translate("SCHEDULE_PAYMENT");?>";
			}else if(key=="paymenthistory"){
				url='<?php echo $urlPaymenthistory;?>';
				newPageTitle="<?php echo $tr->translate("RPT_PAYMENT_HISTORY");?>";
			}
			 
			if(actionType==1){
				addTab(newPageTitle,url+row+'?inFrame=true');
			}else{
				gotoAction();
			}
		},
		items: {
			"payment": {name: "<?php echo $tr->translate("ADD_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
			"dach": {name: "<?php echo $tr->translate("DACH_PRODUCT");?>", icon: "fa-money"},
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text"},
			"schedule": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
			"receipt": {name: "<?php echo $tr->translate("PAWN_RECEIPT");?>", icon: "fa-print"},
			"reschedule": {name: "<?php echo $tr->translate("REPAYMENTSCHEDULE");?>", icon: "fa-calendar"},
			"paymenthistory": {name: "<?php echo $tr->translate("RPT_PAYMENT_HISTORY");?>", icon: "fa-money"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_self');
}
</script>