<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;

$this->headTitle($tr->translate("EDIT_CAPITALRESOURCE")); 
echo $this->headTitle();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('EDIT_CAPITALRESOURCE');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'capitalresource','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					dijit.byId("save_close").set("disabled",true);
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
	    	<div class="row">
	        	<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('brance')?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('date')?>
	                   </div>
	                </div>
					<div class="row g-3">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ប្រាក់ដុល្លា");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('usa')?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ប្រាក់រៀល");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('reil')?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ប្រាក់បាត");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('bath')?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('note');echo $frm->getElement('id');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('status')?>
	                   </div>
	                </div>
	                <div class="clearfix"></div>
				    <div class="card-box">
		               <div class="col-sm-12 border-top mt-2 py-2 text-center">
		               			<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="បិទ" label="<?php echo $tr->translate("SAVE");?>" name="save_close" id="save_close" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
			    		</div>
			    	</div>
	            </div>
	        </div>
		</form>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.DateTextBox");
</script>
