<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CO'));
?>	
<?php  $techer= $this->frm_co;?>
<script>
	dojo.require("dijit/form/DateTextBox");
	dojo.require("dijit/form/NumberTextBox");
</script>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-users"></i>&nbsp;<?php echo $tr->translate('ADD_CO');?></h5>
		<ul class="nav nav-tabs card-header-tabs" role="tablist">
          <li class="nav-item">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#panel21" role="tab" aria-selected="true"><i class="ti-xs ti ti-user me-1"></i> <?php echo $tr->translate('CO_INFO');?></button>
          </li>
          <li class="nav-item">
            <button class="nav-link " data-bs-toggle="tab" data-bs-target="#panel22" role="tab" aria-selected="false"><i class="ti-xs ti ti-coin me-1"></i> <?php echo $tr->translate('SALARY_INFO');?></button>
          </li>
        </ul>
	</div>
	<div class="card-body">
		<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('branch_id').get('value')==''){
					infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> ');
					dijit.byId("branch_id").focus();
					return false;
			    }
				if(dijit.byId("position").get("value")==""){
					infoMessageAlert('<?php echo $tr->translate("Please Select Position Name");?> ');
					dijit.byId("position").focus();
					return false;
				}
				loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
			<div class="tab-content tab-form">
				<div class="tab-pane fade active show" id="panel21" role="tabpanel">
					<div class="row">
						<!-- CO_NAME  -->
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CO_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('branch_id');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STAFF_CODE");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('co_id'); echo $techer->getElement('id');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_KH");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('name_kh');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_EN");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('first_name');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('co_sex');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POB");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('pob');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('national_id');?>
									   </div>
									</div>
								</div>
							</div>
						 </div>
						 <!--/. CO_NAME  -->
						 
						 <!-- NATIONAL_ID  -->
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CONTACT_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('tel');?>
									   </div>
									</div>
								   <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EMAIL");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('email');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENT_ADDRESS");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('address');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POSITION");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('position');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DEGREE");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('degree');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DEPARTMENT");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('department_id');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FINGER_PRINT");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('figer_print_id');?>
									   </div>
									</div>
								</div>
							</div>
						 </div>
						 <!--/. NATIONAL_ID  -->
						 
						 <!-- OTHER_IFO  -->
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("OTHER_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="d-flex align-items-start align-items-sm-center gap-4">
									  <img src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt="user-avatar" class="d-block w-px-100 h-px-100 rounded" id="uploadedAvatar" />
									  <div class="button-wrapper">
										<label for="photo" class="btn btn-primary me-2 mb-3" tabindex="0">
										  <span class="d-none d-sm-block"><?php echo $tr->translate("Upload new photo");?></span>
										  <i class="ti ti-upload d-block d-sm-none"></i>
										  <input type="file" id="photo" name="photo" class="account-file-input" hidden accept="image/png, image/jpeg" />
										</label>
										<button type="button" class="btn btn-label-secondary account-image-reset mb-3">
										  <i class="ti ti-refresh-dot d-block d-sm-none"></i>
										  <span class="d-none d-sm-block"><?php echo $tr->translate("RESET");?></span>
										</button>

										<div class="text-muted">Allowed JPG, GIF or PNG. Max size of 800K</div>
									  </div>
									</div>
								</div>
							</div>
						   
						 </div>
						 <!--/. OTHER_IFO  -->
					</div>
				</div>
				<div class="tab-pane fade" id="panel22" role="tabpanel">
					<div class="row">
						<!-- CONTRACT_INFO  -->
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CONTRACT_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CONTRACT_NO");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('contract_no');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE_START_WORK");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('start_date');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE_END_CONTRACT");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('end_date');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
						<!--/. CONTRACT_INFO  -->
						
						<!-- WORK_INFO  -->
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("WORK_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SHIFT");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('shift');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("WORKING_TIME");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('workingtime');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ANNUAL_LIVES");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('annual_lives');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
						<!--/. WORK_INFO  -->
						
						<!-- CONTRACT_INFO  -->
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("SALARY_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BASIC_SALARY");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('basic_salary');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
									   </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('note');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
						<!--/. CONTRACT_INFO  -->
					</div>
				</div>
			</div>
	        
	        
	         <!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-2 py-2 text-center">
					<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button"  iconClass="dijitIconClear"/>
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"  />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button"  />
    			</div>
    		</div>
	    	<!--/. Button Save  -->
		</form>
	</div>
</div>


<?php  echo $this->frmpopupdepartment;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">

$( document ).ready(function() {
   let e = document.getElementById("uploadedAvatar");
        const l = document.querySelector(".account-file-input")
          , c = document.querySelector(".account-image-reset");
        if (e) {
            const r = e.src;
            l.onchange = ()=>{
                l.files[0] && (e.src = window.URL.createObjectURL(l.files[0]))
            }
            ,
            c.onclick = ()=>{
                l.value = "",
                e.src = r
            }
        }
});

dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.date.locale");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

	function calculateDay(){
		start_date = dijit.byId("start_date").get('value');
		var a=new Date(start_date);
		m=a.getMonth()+1;
		d=a.getDate();
		if(d<15){
			m=m-1;
		}
		t_day=18*(12-m)/12;
		dijit.byId('annual_lives').attr('value',t_day);
	}
	function Checktime(type){
		workingtime_id=dijit.byId("workingtime").get("value");
		shift_id=dijit.byId("shift").get("value");
		if(type==1){
			if(workingtime_id==1){
				dijit.byId("shift").attr('value',1);
				dijit.byId("workingtime").set('readOnly',true);
			}
			else if(workingtime_id==2){
				dijit.byId("shift").attr('value',2);
			}
			else if(workingtime_id==3){
				dijit.byId("shift").attr('value',2);
			}
		}else{
			if(shift_id==1){
				dijit.byId("workingtime").attr('value',1);
				dijit.byId("workingtime").set('readOnly',true);
			}
			else if(shift_id==2){
				dijit.byId("workingtime").attr('value',2);
				dijit.byId("workingtime").set('readOnly',false);
			}
			else if(shift_id==2){
				dijit.byId("workingtime").attr('value',3);
				dijit.byId("workingtime").set('readOnly',false);
			}
		}
	}

	function popupDepartment(){
		var department_id = dijit.byId('department_id').get('value');
		if(department_id==-1){
			dijit.byId('department').show();
		}
	}

	var departmentStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr: "*${0}*",             
	    id: "department_id",
	    name: "department_id",  
	    class: 'fullside',  
	    onChange: function() {          
	    	popupDepartment();
	    } 
	}, "department_id");
	function addNewDepartment(){
		var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'co','action'=>'addnewdepartment')); ?>';
		dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_department"),		    
				handleAs:"json", 
				load: function(data) {	
					departmentStore  = getDataStorefromJSON('id','name', data.datastore);	
				    dijit.byId('department_id').set('store', departmentStore);
				    dijit.byId('department_id').set('value', data.id);
				    
					dojo.byId('frm_department').reset(); 
					dijit.byId('department').hide();
				},
				error: function(e) {
					infoMessageAlert("Your message could not be sent, please try again!.");
				}
			});
	}
var url_staffcode = '<?php echo $this->url(array('module'=>'payroll','controller'=>'co','action'=>'getstaffcode')); ?>';
	function getStaffCode(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('co_id').attr('value','');
		if(branch_id==''){
			infoMessageAlert('Please Select Branch');
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url:url_staffcode,	
			content:{ 
			    'branch_id':branch_id,
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('co_id').attr('value',data);
			},
			error: function(err) {
			}
		});
	}

</script>
