<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("CO_NAME"));
$frm = $this->frm_co;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
    	<div class="card-box">
    		<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <table width=60%>
			   	<tr>
				   <td><?php echo $frm->getElement("adv_search");?></td>
				   <td width="35%"><?php echo $frm->getElement("degree");?></td>
				   <td><?php echo $frm->getElement('status_search');?></td>
				   <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</tr>
			   </table>
			    
			</form>
    	</div>
    	<div class="card-box">
    		<?php echo $this->list;?>
    	</div>
    </div>
</div>

