<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<title> <?php echo $tr->translate("ADD_PRODUCT_TYPE")?></title>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-cubes" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('ADD_PRODUCT_TYPE');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'pawnshop','controller'=>'pawnproduct','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="row">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_KH");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('title_kh')?>
	                   </div>
		           </div>
		           <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_ENG");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('title_en')?>
	                   </div>
		           </div>
		           <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('date')?>
	                   </div>
		           </div>
		           <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('status')?>
	                   </div>
		           </div>
		       	</div>
		       	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION");?> 
	                   </label>
		           </div>
		           <div class="row g-3">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<?php echo $frm->getElement('description')?>
	                   </div>
		           </div>
		        </div>
		    </div>
		    <div class="clearfix"></div>
			<div class="card-box">
               	<div class="col-sm-12 border-top mt-2 py-2 text-center">
		    		<input type="reset" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button"/>
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button"  />
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
</script>