<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_DEPARTMENT_INFO'));
?>	
<?php  $frm = $this->frm_department;?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('EDIT_DEPARTMENT_INFO');?></h5>
	</div>
	<div class="card-body">
		<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
	    		<div class="row">
					<div class="col-md-6 col-sm-6 col-xs-12">
		                <div class="row g-3">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?> :
		                   </label>
		                    <div class="col-md-7 col-sm-7 col-xs-12">
		                    	<?php echo $frm->getElement('department_kh');?>
		                    	<?php echo $frm->getElement('id');?>
		                   </div>
		                </div>
		                <div class="row g-3">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
		                   </label>
		                    <div class="col-md-7 col-sm-7 col-xs-12">
		                    	<?php echo $frm->getElement('status');?>
		                   </div>
		                </div>
						<!-- Button Save  -->
						<div class="clearfix"></div>
						<div class="card-box">
							<div class="col-sm-12 border-top mt-2 py-2 text-center">
								<input type="submit" class="button-class button-primary " iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button"  />
							</div>
						</div>
						<!--/. Button Save  -->
		                
		            </div>
	          </div>
		</form>
	</div>
</div>