<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$xchange= $this->Loanxchange_list;
$frm = $this->frm_search;
$client = $this->client;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("Report Transfer-Withdrawal");?></title>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Transfer-Withdrawal Report');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               <?php echo $frm->getElement('currency_type');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("start_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("end_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               <?php echo $frm->getElement('status');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
    </form>
    <div id="divPrint">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Times New Roman','Khmer OS Battambang';
		}
		table tr td ul li{list-style: none;line-height: 25px;}
		th{padding: 5px;}
		table { page-break-inside:auto }
		  tr{ page-break-inside:avoid; page-break-after:auto; font-family: 'Times New Roman','Khmer OS Battambang';}
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		.border_bottom {
		    border-bottom: 1px solid #000;
		}
	</style>
	<table style="font-family: font-family: 'Times New Roman','Khmer OS Battambang';; width:100%;"  >
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0;border:none;" >
		            	<tr>
		                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
		                	<td width="60%" valign="top">
		                	     <ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("Transfer-Withdrawal Report");?></li>
		                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
				    </table>
				 </td>
			</tr>
			<tr>
		    	<td id="exportExcel">
		            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; white-space: nowrap; " width="100%" cellspacing="0">
		                 <thead>
							 <tr class="style" align="center" style="font-weight:bold; line-height: 24px; background:#ccd9ff; font-size:12px; font-family: 'Khmer OS Content'">
			                    <td><?php echo $tr->translate("NUM");?></td>
			                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
			                    <td><?php echo $tr->translate("ឈ្មោះ​អ្នក​ផ្ញើរ");?></td>
			                    <td><?php echo $tr->translate("លេខអ្នកផ្ញើរ");?></td>
			                    <td><?php echo $tr->translate("លេខ​​​អ្នក​ទទួល");?></td>
			                    <td><?php echo $tr->translate("ប្រភេទ​ប្រតិបត្តិការណ៍");?></td>
			                    <td><?php echo $tr->translate("ប្រភេទ​ប្រាក់");?></td>
			                    <td><?php echo $tr->translate("ចំនួនទឺកប្រាក់");?></td>
			                    <td><?php echo $tr->translate("កម្រៃជើងសារ");?></td>
			                    <td><?php echo $tr->translate("កម្រៃជើងសារសរុប");?></td>
			                    <td><?php echo $tr->translate("ថ្ងៃ​ប្រតិបត្តិ");?></td>                    
			                </tr>
						</thead>
		                <?php
							$commision_dollar=0;$commision_riel=0;
							$tcommision_dollar=0;$tcommision_riel=0;
							$tcommision_bath=0;$commision_bath=0;
							$dollar_transfer=0;$dollar_widthdraw=0;
							$riel_transfer=0;$riel_widthdraw=0;
							$bath_transfer=0;$bath_widthdraw=0;
							$i=1;
		                if(!empty($xchange))foreach ($xchange as $row){?>
		               <tr style="font-size: 11px;" align="left">
		               		<td style="text-align: center;"><?php echo $i++;?></td>
		               		<td>&nbsp;<?php ?></td>
		               		<td>&nbsp;<?php echo $row['sender_name']?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $row['sender_tel']?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $row['reciever_tel'];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $row['tran_type'];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $row['currencty_type'];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo number_format($row['amount_tranfer'],2);?>&nbsp;</td>
							<td>&nbsp;<?php echo number_format($row['commission'],3);?>&nbsp;</td>
							<td>&nbsp;<?php echo number_format($row['total_commission'],3);?>&nbsp;</td>
		               		<td>&nbsp;<?php echo date('d-m-Y',strtotime($row['send_date']))?>&nbsp;</td>
		               </tr>
		               <?php 
		               if($row['curr_type']==1){//kh
		               		$commision_riel=$commision_riel+$row['commission'];
		               		$tcommision_riel=$tcommision_riel+$row['total_commission'];
		               		if($row['transaction_type']==0){//transfer
		               			$riel_transfer=$riel_transfer+$row['amount_tranfer'];
		               		}else{//widthdraw
		               			$riel_widthdraw=$riel_widthdraw+$row['amount_tranfer'];
		               		}
		               }elseif($row['curr_type']==2){//dollar
		               		$commision_dollar=$commision_dollar+$row['commission'];
		               		$tcommision_dollar=$tcommision_dollar+$row['total_commission'];
		               		if($row['transaction_type']==0){//transfer
		               			$dollar_transfer=$dollar_transfer+$row['amount_tranfer'];
		               		}else{//widthdraw
		               			$dollar_widthdraw=$dollar_widthdraw+$row['amount_tranfer'];
		               		}
					   }else{//bath
						   	$commision_bath=$commision_bath+$row['commission'];
						   	$tcommision_bath=$tcommision_bath+$row['total_commission'];
						   	if($row['transaction_type']==0){//transfer
						   		$bath_transfer=$bath_transfer+$row['amount_tranfer'];
						   	}else{//widthdraw
						   		$bath_widthdraw=$bath_widthdraw+$row['amount_tranfer'];
						   	}
					   }
		              }
					?>
		            </table>
		       		<br />
		       		<table style=" font-size:11px; width:70%;margin:0 auto;" cellspacing="0">
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                    <td align="right">&nbsp;</td>
		                    <td></td>
		                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("Transfer");?></span>&nbsp;</td>
		                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("Withdrawal");?></span></td>
		                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("កម្រៃជើងសារ");?></span></td>
		                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("កម្រៃជើងសារសរុប");?></span></td>
		                     <td align="right">&nbsp;</td>
		                 </tr>
		                 
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
		                    <td align="right"></td>
		                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($dollar_transfer,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($dollar_widthdraw,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($commision_dollar,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($tcommision_dollar,2);?>&nbsp;</td>
		                    <td align="right">&nbsp;</td>
		                 </tr>
	                 
	                 	<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
		                    <td align="right"></td>
		                    <td align="right"><?php echo $tr->translate("REILS");?></td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($riel_transfer,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($riel_widthdraw,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($commision_riel,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($tcommision_riel,2);?>&nbsp;</td>
		                    <td align="right">&nbsp;</td>
		                 </tr>
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
		                    <td align="right"></td>
		                    <td align="right"><?php echo $tr->translate("BATH");?></td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($bath_transfer,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($bath_widthdraw,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($commision_bath,2);?>&nbsp;</td>
		                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($tcommision_bath,2);?>&nbsp;</td>
		                    <td align="right">&nbsp;</td>
		                 </tr>
		                 
	                 </table>
		              <br />
		       		<?php echo $this->footerReport;?>
		    	</td>
	     </tr>
	  </table>
	</div>
</div>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	
</div>