<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_ZONE_AREA'));
?>	
<?php  $frm = $this->frm_zone;?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('EDIT_ZONE_AREA');?></h5>
	</div>
	<div class="card-body">
		<form action="<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					return true;
				} else {
					return false;
				}
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('branch_id');?>
	                   </div>
	                </div>
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ZONE_NUMBER");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('zone_number');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ZONE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('zone_name'); echo $frm->getElement('id');?>
	                   		
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('status');?>
	                   </div>
	                </div>
					
					<!-- Button Save  -->
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
							<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="submitButton" name="submitButton" id="submitButton" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"   />
						</div>
					</div>
					<!--/. Button Save  -->
					
	            </div>
	        </div>
		</form>
	</div>
</div>
