<?php
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('TRANSFERCOLOAND')); 
	echo $this->headTitle();
	$frm = $this->frm_transfer;

?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-route"></i>&nbsp;<?php echo $tr->translate('TRANSFERCOLOAND');?></h5>
	</div>
	<div class="card-body">
    	<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoloand','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit">			
  					if(this.validate()) {
    					if(dijit.byId('branch_name').get('value')==''){
     						infoMessageAlert('Please Select Branch');
     						dijit.byId('branch_name').focus();
    						 return false;
   						}
						if(dijit.byId('co_code').get('value')==''){
     						infoMessageAlert('Please Select Co code');
     						dijit.byId('co_code').focus();
     						return false;
   						}
    					if(dijit.byId('name_co').get('value')==''){
     						infoMessageAlert('Please Select Name Co');
     						dijit.byId('name_co').focus();
     						return false;
   						}

   						if(dijit.byId('loan_number').get('value')==''){
     						infoMessageAlert('Please Select Loan Number');
     						dijit.byId('loan_number').focus();
     						return false;
   						}
						loadingBlock();
						dijit.byId("btn_save").set("disabled",true);
    					dijit.byId("btn_save_close").set("disabled",true);
    					return true;
   					}else {
    					return false;
   					}
				</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('branch_name');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO_CODE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('co_code');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('name_co');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('Date');?>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CO_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_NO");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('loan_number');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('Note');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('status');?>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	        </div>
	        <div class="card-box">
	        	<div class="col-sm-12 border-top mt-2 py-2 text-center">
	        		<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" onclick="submitDataClose()" value="រក្សាទុក" name="btn_save_close" id="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="រក្សាទុក & ចាកចេញ" name="btn_save" id="btn_save" label="<?php echo $tr->translate('SAVENEW');?>" id="submitButton_Save" dojoType="dijit.form.Button" />
	    		</div>
	        </div>
		</form>
    </div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
			
		}else if(type==2){
			id = dijit.byId("name_co").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("loan_client").get('value');		
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}else if(type==5){
			to = dijit.byId("loan_number").get('value');
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}
	}

	function submitDataClose(){
		if(dijit.byId('branch_name').get('value')==''){
		     infoMessageAlert('Please Select Branch');
		     dijit.byId('branch_name').focus();
		     return false;
		   	}
			if(dijit.byId('co_code').get('value')==''){
		     infoMessageAlert('Please Select Co code');
		     dijit.byId('co_code').focus();
		     return false;
		   	}
		    if(dijit.byId('name_co').get('value')==''){
		     infoMessageAlert('Please Select Name Co');
		     dijit.byId('name_co').focus();
		     return false;
		   	}

		   if(dijit.byId('loan_number').get('value')==''){
		     infoMessageAlert('Please Select Loan Number');
		     dijit.byId('loan_number').focus();
		     return false;
		   	}
		if(dijit.byId('frm_add_tran').validate()) {
			dijit.byId('btn_save').set('disabled',true);
			dijit.byId('btn_save_close').set('disabled',true);
			var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoloand','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_add_tran"),		    
				load: function(data) {
					infoMessageAlert('<?php echo $tr->translate('INSERT_SUCCESS');?> !',1);
					window.location.href ="<?php echo $this->baseUrl();?>/loan/transfercoloand";
				},
				error: function(e) {
				}
			});
		}
	}
</script>
