<?php
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('TRANSFER_CO')); 
	echo $this->headTitle();
	$frm = $this->frm_transfer;

?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
 			<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-exchange" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_TRANSFER_CO');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoloand','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit">			
  					if(this.validate()) {
    					if(dijit.byId('branch_name').get('value')==''){
     						alert('Please Select Branch');
     						dijit.byId('branch_name').focus();
    						 return false;
   						}
						if(dijit.byId('co_code').get('value')==''){
     						alert('Please Select Co code');
     						dijit.byId('co_code').focus();
     						return false;
   						}
    					if(dijit.byId('name_co').get('value')==''){
     						alert('Please Select Name Co');
     						dijit.byId('name_co').focus();
     						return false;
   						}

   						if(dijit.byId('loan_number').get('value')==''){
     						alert('Please Select Loan Number');
     						dijit.byId('loan_number').focus();
     						return false;
   						}
						dijit.byId("btn_save").set("disabled",true);
    					dijit.byId("btn_save_close").set("disabled",true);
    					return true;
   					}else {
    					return false;
   					}
				</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BRANCH_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('branch_name');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('co_code');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('name_co');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('Date');?>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CO_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_NO");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('loan_number');?>
	                   </div>
	                </div>
	                <!-- 
	                <div class="form-group" style="display: none;">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("CUSTOMER_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  //echo $frm->getElement('loan_client');?>
	                   </div>
	                </div>
	                 -->
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('Note');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('status');?>
	                   </div>
	                </div>
	            </div>
	        </div>
	        <div class="card-box">
	        	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	        		<input type="button" onclick="submitDataClose()" value="រក្សាទុក" name="btn_save" id="btn_save" label="<?php echo $tr->translate('SAVENEW');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
					<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" id="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
	    		</div>
	        </div>
		</form>
    </div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
			
		}else if(type==2){
			id = dijit.byId("name_co").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("loan_client").get('value');		
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}else if(type==5){
			to = dijit.byId("loan_number").get('value');
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}
	}

	function submitDataClose(){
		if(dijit.byId('branch_name').get('value')==''){
		     alert('Please Select Branch');
		     dijit.byId('branch_name').focus();
		     return false;
		   	}
			if(dijit.byId('co_code').get('value')==''){
		     alert('Please Select Co code');
		     dijit.byId('co_code').focus();
		     return false;
		   	}
		    if(dijit.byId('name_co').get('value')==''){
		     alert('Please Select Name Co');
		     dijit.byId('name_co').focus();
		     return false;
		   	}

		   if(dijit.byId('loan_number').get('value')==''){
		     alert('Please Select Loan Number');
		     dijit.byId('loan_number').focus();
		     return false;
		   	}
		if(dijit.byId('frm_add_tran').validate()) {
			dijit.byId('btn_save').set('disabled',true);
			dijit.byId('btn_save_close').set('disabled',true);
			var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoloand','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_add_tran"),		    
				load: function(data) {
					alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
					window.location.href ="<?php echo $this->baseUrl();?>/loan/transfercoloand";
				},
				error: function(e) {
				}
			});
		}
	}
</script>
