
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("TRANSFERCOLOAND"));
$frm = $this->frm_transfer;

?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-route"></i>&nbsp;<?php echo $tr->translate('TRANSFERCOLOAND');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('note');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('branch_name');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('loan_number');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('loan_client');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('co_code');?>
			   		</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('name_co');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
require(["dojo/ready"], function(ready){
	 ready(function(){
		 
	  });
});
	function getClientInfo(type){
		//alert(type);
		if(type==1){						
			
			
		}else if(type==2){
		
		}
		else if(type==3){		
			to = dijit.byId("loan_client").get('value');		
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}else if(type==5){
			to = dijit.byId("loan_number").get('value');
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}
	}
</script>

