
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("TRANSFER_CO"));
$frm = $this->frm_transfer;

?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'transfercoloand','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			  	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('note');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('branch_name');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('loan_number');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('loan_client');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('co_code');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			   	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php  echo $frm->getElement('name_co');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			</form>
		</div>
		<div class="card-box">
			 <?php echo $this->list;?>
		</div>
	</div>
</div>


<script type="text/javascript">
require(["dojo/ready"], function(ready){
	 ready(function(){
		 
	  });
});
	function getClientInfo(type){
		//alert(type);
		if(type==1){						
			
			
		}else if(type==2){
		
		}
		else if(type==3){		
			to = dijit.byId("loan_client").get('value');		
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}else if(type==5){
			to = dijit.byId("loan_number").get('value');
			dijit.byId("loan_number").attr('value',to);
			dijit.byId("loan_client").attr('value',to);
		}
	}
</script>

