<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_HOLIDAY'));
?>	
<?php  $holiday= $this->frm_holiday;?>
<script>
       dojo.require("dijit.form.DateTextBox");
       dojo.require("dijit/form/NumberTextBox");
</script>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-calendar-time"></i>&nbsp;<?php echo $tr->translate('ADD_HOLIDAY');?></h5>
	</div>	
	<div class="card-body">
		<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'holiday','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post"
		 enctype="application/x-www-form-urlencoded">
		 	<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
                	dijit.byId("save_new").set("disabled",true);
					dijit.byId("save_close").set("disabled",true);
					return true;
				} else {
					return false;
				}
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("HOLIDAY_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $holiday->getElement('holiday_name');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("START_DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $holiday->getElement('start_date');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AMOUNT_DAY");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $holiday->getElement('amount_day');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("END_DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $holiday->getElement('end_date');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $holiday->getElement('note');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $holiday->getElement('status');?>
	                   </div>
	                </div>
					
					<!-- Button Save  -->
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
							<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
							<input type="button" onclick="submitDataClose()" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"   />
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button"   />
						</div>
					</div>
					<!--/. Button Save  -->
					
	            </div>
	         </div>
		</form>
	</div>
</div>

<?php $base_url = Application_Form_FrmMessage::getUrl("/"); ?>
<script>
function CalculateDate(){
	pay_type = dijit.byId('start_date').value;
	amount_day = dijit.byId('amount_day').get('value');
	
	if(isNaN(amount_day)){
		//alert('សូមបញ្ចលចំនួនរយៈពេល !');
		dijit.byId('amount_day').focus();
	}else{
		start_date = dijit.byId("start_date").value;
		var a = new Date(start_date);
		
		var mm = a.getMonth() + 1;
		var dd = a.getDate()+parseInt(amount_day)-1;
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);
}
}

function submitDataClose(){
	if(dijit.byId('add_techer').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'other','controller'=>'holiday','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_techer"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/other/holiday";
			},
			error: function(e) {
			}
		});
	}
}
</script>