<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Change Password')); 
echo $this->headTitle();
?>
<div class="card">
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="fa fa-key" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('Change Password');?></h5>
		<span id="message" style="color: red; display: block;"></span>
	</div>
	<div class="card-body">
		<form action="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">				
				if(this.validate()) {
					if(dojo.byId('new_password').value != dojo.byId('new_con_password').value ){
						alert('សូមពិនិត្រ ពាក្យសំងាត់ទាំង 2 របស់អ្នក មិនដូចគ្នាទេ, សូមបញ្ចូល ម្តងទៀត..');
						dojo.byId('new_password').value = '';
						dojo.byId('new_con_password').value = '';
						dijit.byId('new_password').focus();
						return false;
					}	
					loadingBlock();				
					return true;
				}
				return false;
			</script>
	    	<div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENT_PASSWORD");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input type="password" required="true" name="password" id="password" placeholder="ពាក្យសំងាត់ កំពុងប្រើប្រាស់" 
											regExp="\w{6,}" invalidMessage="ពាក្យសំងាត់យ៉ាងតិច មាន 6 តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នកភ្លេចបំពេញ  ពាក្យសំងាត់ កំពុងប្រើប្រាស់!" style="width: 100%;"/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NEW_PASSWORD");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input type="password" required="true" name="new_password" id="new_password" placeholder="ពាក្យសំងាត់ ថ្មី" 
											regExp="\w{6,}" invalidMessage="ពាក្យសំងាត់យ៉ាងតិច មាន 6 តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នកភ្លេចបំពេញ ពាក្យសំងាត់ ថ្មី!" style="width: 100%;"/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMFIRM_PASSWORD");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input type="password" required="true" name="new_con_password" id="new_con_password" placeholder="បញ្ជាក់ពាក្យសំងាត់  ថ្មី"
											regExp="\w{6,}" invalidMessage="ពាក្យសំងាត់យ៉ាងតិច មាន 6 តួអក្សរ" 
											dojoType="dijit.form.ValidationTextBox"  missingMessage="អ្នកភ្លេចបំពេញ បញ្ជាក់ ពាក្យសំងាត់ ថ្មី!" style="width: 100%;"/>
	                   </div>
	                </div>
	                <div class="clearfix"></div>
               		<div class="col-sm-12 border-top mt-2 py-2 text-center">
		    			<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="រក្សាទុក" label="<?php echo $tr->translate("SAVE");?>" id="submitButton" dojoType="dijit.form.Button"  /> 
	    			</div>
	            </div>
	        </div>
		</form>
	</div>
</div>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');	
</script>
