<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$baseUrl = $this->baseUrl()."/";
	
	$key = new Application_Model_DbTable_DbKeycode();
	$dataInfo=$key->getKeyCodeMiniInv(TRUE);
		
	$clientTitle= $tr->translate("CUSTOMER_BRANCH");
	if(!empty($dataInfo['schooolNameKh'])){
		$clientTitle= $dataInfo['schooolNameKh'];
	}
	$clientTitleEn="";
	if(!empty($dataInfo['schooolNameEng'])){
		$clientTitleEn= $dataInfo['schooolNameEng'];
	}
	$defaultLogo = $this->baseUrl()."/images/logo.png";
	if(!empty($dataInfo['logo'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$dataInfo['logo'])){
			$defaultLogo = $this->baseUrl().'/images/logo/'.$dataInfo['logo'];
		}
	}
	
	$this->headTitle($this->data["system_name"].'--Loan Management System');
	echo $this->headTitle();
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="<?php echo $baseUrl;?>images/icon.ico" type="image/x-icon"/>
	
	<script src="<?php echo $baseUrl;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<script>dojoConfig = {parseOnLoad: true}</script>
	<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>js/dojo-1.6.1/dijit/themes/soria/soria.css"/>
	<script>	
		require(["dojo/parser", "dijit/form/Form", "dijit/form/Button", "dijit/form/ValidationTextBox","dijit/form/FilteringSelect"]);
	</script>
    <!-- Font Awesome -->
    <link href="<?php echo $this->baseUrl();?>/admin/assets/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->baseUrl();?>/admin/assets/css/custom.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl();?>/admin/assets/css/external-template.css" rel="stylesheet">
  </head>
<style type="text/css">
		.container {
    padding: 0;
    width: auto;
}.dijitInputInner {
    color: #000;
}
		.fullside {
		    width: 99%;
		    height: 30px;
		}
		.dijitArrowButtonInner, .dijitIconSearch {
		    margin-top: 6px !important;
		}
		.dijitTextBox, .dijitValidationTextBox, .dijitInputField, .dijitInputContainer, .dijitInputInner, dijitReset, .dijitRight, .dijitButtonNode, .dijitArrowButton, .dijitDownArrowButton, .dijitArrowButtonContainer {
		    height: 30px;
		}
		.tundra .dijitButtonText {
		    line-height: 24px;
		}
		.tundra .dijitInputContainer INPUT, .tundra .dijitTextBox {
		    color: #000000;
		    font-size: 16px;
		}
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.f_style{
			font-family:'NiDA Khmer Empire';
		    font-size:14px;
			text-shadow: 1px 1px 1px #0B404A;
		}
		.t_shadow{ text-shadow: 1px 1px 1px #0B404A;}
		.login_wrapper.login-wrapper .login_content form .dijitValidationTextBoxError .dijitValidationIcon {
			border: none !important;
			box-shadow: none !important;
			color: rgb(255 255 255 / 15%);
			width: 16px !important;
			margin: 0 !important;
			border-radius: 0;
		}
		
	</style>
  <body class="soria login">
	<div class="gradient-bg"></div>
	<div class="wave-line-bg"></div>
    <div class="login-page">
		<div class="main-title">
			<p class="titlepage"><?php echo $this->data["system_name"];?> <br /> <strong>Loan Management System</strong></p>
		</div>
		<div class="login-content">
			<div class="loginBlog">
				<div class="login-box">
					<div class="content">
						<p  class="login-title">សូមស្វាគមន៍ /  <strong>Welcome</strong></p>
						<div  class="instruction-box">
							<h3 ><?php echo $this->data['client_company_name']?></h3>
							<div class="client_info">
								<ul>
									<li><i class="fa fa-home" aria-hidden="true"></i> <?php echo $this->data['branch-add-client'];	?> </li>
									<li><i class="fa fa-phone" aria-hidden="true"></i> <?php echo $this->data['tel-client'];	?> </li>
									<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <?php echo $this->data['email_client']?></li>
									<li><i class="fa fa-globe" aria-hidden="true"></i> <?php echo $this->data['client_website']?></li>
								</ul>
							</div>
						</div>
						<br />
						<div  class="instruction-box">
							<div class="contact_info">
								<ul>
									<li><strong><?php echo $tr->translate("POWERED_BY")?></strong> : </li>
									<li><i class="fa fa-phone" aria-hidden="true"></i> <?php echo $this->data['branch-tel'];	?> </li>
									<li><i class="fa fa-globe" aria-hidden="true"></i> <?php echo $this->data['website']?></li>
									
									<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <?php echo $this->data['branch_email']?></li>
								</ul>
							</div>
						</div>
						<div class="copyright">
							&copy រក្សាសិទ្ធិគ្រប់យ៉ាង
									<a title="<?php echo $this->data['power_by']?>" class="copyright" href="http://<?php echo $this->data['website']?>" target="_blank">
										<strong><?php echo $this->data['power_by']?></strong></a>
						</div>
					</div>
				</div>
			</div>
			<div class="loginFormBlog">
				<div class="login_wrapper login-wrapper">
					<div class="login-left">
						<div class="logo">
							<img src="<?php echo $defaultLogo;?>" alt="<?php echo $clientTitle;?> Logo">
						</div> 
						<div class="gdt-name-kh"><?php echo $this->data['client_company_name']?></div>
					</div>
					<div class="login-right">
						<div class="login-right-wrapper">
							<div class="loginTitle">
							  <h4><i class="fa fa-lock" aria-hidden="true"></i> ប្រព័ន្ធសុវត្ថិភាព / <strong>Security System</strong></h4>
							  <small><?php echo $this->msg;?></small>
							</div>
							<div class="animate form login_form">
								
							  <section class="login_content">

								<form id="frmLogin" dojoType="dijit.form.Form" method="post" action="">
									<script type="dojo/method" event="onSubmit">				
										if(this.validate()) {						
											return true;
										}
										return false;
									</script>
							
								  <h1><?php echo $tr->translate("SECURITY_SYSTEM");?></h1>
								  <div class="formControl-login">
									<input class="fullside" type="text" required="true" name="txt_user_name" id="txt_user_name" placeholder="<?php echo $tr->translate("ACCOUNT_NAME");?>" data-dojo-type="dijit/form/ValidationTextBox" missingMessage="<?php echo $tr->translate("PLEASE_FILL_ACCOUNT_NAME");?> ! "  />
								  </div>
								  <div class="formControl-login">
									<input class="fullside" type="password" required="true" name="txt_password" id="txt_password" placeholder="<?php echo $tr->translate("PASSWORD");?>" data-dojo-type="dijit/form/ValidationTextBox" missingMessage="<?php echo $tr->translate("PLEASE_ENTER_PASSWORD");?>!" />
								  </div>
								  <div class="formControl-login text-left">
									<select class="fullside" data-dojo-type="dijit/form/FilteringSelect" name="lang" id="lang" style="width: 150px"  onchange="changeLange();" > 
										<option value="1" <?php if($this->rslang==1){echo"selected";}?>>ខ្មែរ</option> 
										<option value="2" <?php if($this->rslang==2){echo"selected";}?>>English</option> 
									</select>
								  </div>
								  <div class="formControl-login">
									<input class=" button-class button-primary" iconClass="glyphicon glyphicon-log-in" type="submit" value="<?php echo $tr->translate("LOGIN");?>" label="<?php echo $tr->translate("LOGIN");?>" data-dojo-type="dijit/form/Button" /> 
								  </div>
								  <div class="clearfix"></div>

								</form>
							  </section>
							</div>
						</div>
					</div>
				</div>
			</div>
		
		</div>
    </div>
  </body>
  
  <style>
	.dijitTextBox, .dijitValidationTextBox, .dijitInputField, .dijitInputContainer, .dijitInputInner, dijitReset, .dijitRight, .dijitButtonNode, .dijitArrowButton, .dijitDownArrowButton, .dijitArrowButtonContainer {
		    height: 30px;
		}
	.dijitInputInner {
		color: #000;
	}
	.login_wrapper.login-wrapper .login_content form  .dijitArrowButtonInner{
		width:13px;
	}
	
	
  </style>
  <script type="text/javascript">
			var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
			function changeLange(){
				lang = dijit.byId("lang").get("value");
				dojo.xhrPost({
					url: url_changelang,
				    content :{ 
						    'lange':lang,
					},	
					handleAs:"json",
					load: function(data) {
						location.reload();
					},
					error: function(err) {
					}
				});
			}
	</script>
</html>
