<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("REPAYMENTSCHEDULE"));
	$frm = $this->frm_search;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$url_agreement = $this->baseUrl()."/report/pawn/agreementextra/id/";
?>

<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('REPAYMENTSCHEDULE');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('members');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("product_id");?>
			   		</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('currency_type');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
   <div class="card-body">
	  <?php echo $this->list;?>
	</div>
</div>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var client_store  = getDataStorefromJSON('id','name', [] );

	/*function getmemberIdGroup(){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}
	function checkMember(){
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}*/
var url_getclient = '<?php echo $this->url(array('module'=>'saving','controller'=>'customer','action'=>'getclientbybranch')); ?>';
function filterClient(){
	branch_id=dijit.byId("branch_id").get("value");
	if(branch_id<0 || branch_id==''){
		return false;
	}
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
			
		}
	});
}

require(["dojo/ready"], function(ready){
		new dijit.form.FilteringSelect({
			store: client_store,
			autoComplete: true,
			query: {
				branch_id: "-1"
			},            
			required: false,		           
			name: "member",
			id: "member",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				member = dijit.byId('member').get('value');
				if(member==-1){
					showPopupclient();
				}else{
					dijit.byId('customer_code').attr('value',member);
				}
		}
	}, "member");
});

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="agreement"){
				url='<?php echo $url_agreement;?>';
			}
			addTab("<?php echo $tr->translate("AGREEMENT_EXTRA");?>",url+row+'?inFrame=true');
		},
		items: {
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT_EXTRA");?>", icon: "fa-file-text"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_self');
}
</script>