<?php
	
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm;
	$this->headTitle($tr->translate('Despite Capital Agent'));
	echo $this->headTitle();
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Despite Capital Agent');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='frm_add_exch' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if($('#identity').val()==""){
					alert('<?php echo $tr->translate("Empty Capital Currency To Input")?>');
					return false;
				}
				dijit.byId("savenew").set("disabled",true);
				dijit.byId("saveclose").set("disabled",true);
				return true;
			} else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("Agent Information");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Agent Name");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('agent_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Currency");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('currency');?>
	                   </div>
	                </div>
	           </div>
	           <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("Despite Capital Information");?> 
	                   </label>
	                </div>
	                <div class="form-group">
						 	<table style="margin: 0 auto; width: 100%; border-collapse: collapse; border: 1px #ccc solid;" >
						 		<thead>
						 			<tr id="head-title" class="head-td">
						 				<th><?php echo $tr->translate("NUM")?></th>
										 <th><?php echo $tr->translate("Currency")?></th>
										 <th><?php echo $tr->translate("Amount")?></th>
										 <th><?php echo $tr->translate("DELETE")?></th>
									</tr>
						 		</thead>
								<tbody id="table_row" >
								</tbody>
						</table>
						<input type="hidden" name="identity" id="identity"  value="" >
	                </div>
	           </div>
	       </div>
	       <div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	    			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
					 iconClass="dijitIconClear"/>
					<input type="submit"  label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button"
					 iconClass="dijitIconDelete"/>
					<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"
					 iconClass="dijitIconNewTask"/>
	    		</div>
			</div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("DO_YOU_WANT_TO_DEL")?>'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4><?php echo $tr->translate("DO_YOU_WANT_TO_DEL")?></h4>
			<input type="hidden" name="recorddelete" id="recorddelete" dojoType="dijit.form.TextBox" />
			<button onclick="dijit.byId('deleteForm').hide();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
			<button onclick="newdeleteRecord('',1);" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.CheckBox");     
	dojo.require("dojo.number");
	
	dojo.require("dijit.Dialog");
	dojo.require("dojo.parser");
	dojo.require("dojo.NodeList-manipulate");
	var record_no=1;
	var urlCurrencyRow ='<?php echo $this->baseUrl()."/tellerandexchange/capitalexchange/getcurrencyrow";?>'
	function addRowCurrency(type=null){
		currency = dijit.byId('currency').get('value');
		if(currency=='' || currency==-1 ){
			dijit.byId('currency').focus();
			return false;
		}
		dojo.xhrPost({
			url:urlCurrencyRow,	
			content:{ 
			    'currency':currency,'record_no':record_no,
			},		    
			handleAs:"json",
			load: function(data) {
				record_no=record_no+1;
				
					var iden = $("#identity").val();
					var arrays = iden.split(',');
					 if(arrays!=""){
						 for(var i=0;i< arrays.length;i++) {
								///alert(arrays[i]+" "+currency)
							 readychoose = dijit.byId('currency_id'+arrays[i]).get('value');
							 if(readychoose==currency){
									alert("<?php echo $tr->translate("Choosen ready")?>");
								 return false;
							 }
						}
					}
					
				tmp='<tr id="row'+data.newrowid+'" style="background: #fff; border: solid 1px #bac;">';
				tmp+="</tr>";
					dojo.query("#table_row").append(tmp);
			
				dojo.html.set(dojo.byId("row"+data.newrowid),data.stringrow , {
			     parseContent: true,
				});
				
				if($("#identity").val()!='') {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+data.newrowid);
				} else {
					$("#identity").val(data.newrowid);
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	 function newdeleteRecord(index,type=''){

		 if(type==''){
			 dijit.byId("recorddelete").attr('value',index);
			 dijit.byId('deleteForm').show();
		 }else{

			index = dijit.byId("recorddelete").get('value');
			var identity = $('#identity').val();
			var arrays = identity.split(',');
			
			for(var i=0;i<arrays.length;i++) {
				if(arrays[i] == index) arrays.splice(i,1);
			}
			var strings = arrays.join(',');
			$('#identity').val(strings);
			dojo.query("#row"+index).remove();
			dijit.byId('deleteForm').hide();
		 }
	}
</script>