<?php
	
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm;
	$this->headTitle($tr->translate('Despite Capital Agent'));
	echo $this->headTitle();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-moneybag"></i>&nbsp;<?php echo $tr->translate('Despite Capital Agent');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_exch' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if($('#identity').val()==""){
					infoMessageAlert('<?php echo $tr->translate("Empty Capital Currency To Input")?>');
					return false;
				}
				dijit.byId("savenew").set("disabled",true);
				dijit.byId("saveclose").set("disabled",true);
				loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("Agent Information");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Agent Name");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('agent_id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Currency");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('currency');?>
							   </div>
							</div>
						</div>
					</div>
	           </div>
	           <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("Despite Capital Information");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
								<table style="margin: 0 auto; width: 100%; border-collapse: collapse; border: 1px #ccc solid;" >
									<thead>
										<tr id="head-title" class="head-td">
											<th><?php echo $tr->translate("NUM")?></th>
											 <th><?php echo $tr->translate("Currency")?></th>
											 <th><?php echo $tr->translate("Amount")?></th>
											 <th><?php echo $tr->translate("DELETE")?></th>
										</tr>
									</thead>
									<tbody id="table_row" >
									</tbody>
								</table>
								<input type="hidden" name="identity" id="identity"  value="" >
							</div>
						</div>
					</div>
	           </div>
	       </div>
	       <div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
	    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"/>
					<input type="submit"  class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" />
	    		</div>
			</div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("DO_YOU_WANT_TO_DEL")?>'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4><?php echo $tr->translate("DO_YOU_WANT_TO_DEL")?></h4>
			<input type="hidden" name="recorddelete" id="recorddelete" dojoType="dijit.form.TextBox" />
			<button class="button-class button-danger " iconClass="glyphicon glyphicon-remove" onclick="dijit.byId('deleteForm').hide();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
			<button class="button-class button-primary" iconClass="glyphicon glyphicon-ok" onclick="newdeleteRecord('',1);" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.CheckBox");     
	dojo.require("dojo.number");
	
	dojo.require("dijit.Dialog");
	dojo.require("dojo.parser");
	dojo.require("dojo.NodeList-manipulate");
	var record_no=1;
	var urlCurrencyRow ='<?php echo $this->baseUrl()."/tellerandexchange/capitalexchange/getcurrencyrow";?>'
	function addRowCurrency(type=null){
		currency = dijit.byId('currency').get('value');
		if(currency=='' || currency==-1 ){
			dijit.byId('currency').focus();
			return false;
		}
		dojo.xhrPost({
			url:urlCurrencyRow,	
			content:{ 
			    'currency':currency,'record_no':record_no,
			},		    
			handleAs:"json",
			load: function(data) {
				record_no=record_no+1;
				
					var iden = $("#identity").val();
					var arrays = iden.split(',');
					 if(arrays!=""){
						 for(var i=0;i< arrays.length;i++) {
								///infoMessageAlert(arrays[i]+" "+currency)
							 readychoose = dijit.byId('currency_id'+arrays[i]).get('value');
							 if(readychoose==currency){
									infoMessageAlert("<?php echo $tr->translate("Choosen ready")?>");
								 return false;
							 }
						}
					}
					
				tmp='<tr id="row'+data.newrowid+'" style="background: #fff; border: solid 1px #bac;">';
				tmp+="</tr>";
					dojo.query("#table_row").append(tmp);
			
				dojo.html.set(dojo.byId("row"+data.newrowid),data.stringrow , {
			     parseContent: true,
				});
				
				if($("#identity").val()!='') {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+data.newrowid);
				} else {
					$("#identity").val(data.newrowid);
				}
			},
			error: function(err) {
				infoMessageAlert(err);
			}
		});
	}
	 function newdeleteRecord(index,type=''){

		 if(type==''){
			 dijit.byId("recorddelete").attr('value',index);
			 dijit.byId('deleteForm').show();
		 }else{

			index = dijit.byId("recorddelete").get('value');
			var identity = $('#identity').val();
			var arrays = identity.split(',');
			
			for(var i=0;i<arrays.length;i++) {
				if(arrays[i] == index) arrays.splice(i,1);
			}
			var strings = arrays.join(',');
			$('#identity').val(strings);
			dojo.query("#row"+index).remove();
			dijit.byId('deleteForm').hide();
		 }
	}
</script>