<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
$this->headTitle($tr->translate('ADD_OTHER_INCOME'));
echo $this->headTitle();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-sign-in"></i>&nbsp;<?php echo $tr->translate('ADD_OTHER_INCOME');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
              	 	branch_id = dijit.byId('branch_id').get('value');
					if(branch_id==0 || branch_id==""){
						alert("<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>");
						dijit.byId("branch_id").focus();
						return false;
					}
                    loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('branch_id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECIEPT_NO");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('reciept_no');?>
							   </div>
							</div>
						</div>
					</div>
	           	</div>
	           	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("TITLE_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENCY");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('currency_type');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Date');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CATEGORY");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('category_id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INVOICE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('invoice');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('account_id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_AMOUNTS");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('total_amount');?>
							   </div>
							</div>
						</div>
					</div>
	           	</div>
	           	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("DESCRIPTION");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Description');?>
							   </div>
							</div>
						</div>
					</div>
	           	</div>
	       </div>
	       <div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
	    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" onclick="submitDataClose()" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" />
	    		</div>
			</div>	
		</form>
	</div>
</div>

<script type="text/javascript">
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
dojo.require("dijit.form.Textarea");
var	url_getreceiptno = '<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'income','action'=>'getrecieptno'));?>';
function getReceiptNo(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0 || branch_id==""){
		return false;
	}
	dojo.xhrPost({
		url: url_getreceiptno,	
		content:{ 
			'branch_id': branch_id
		},
		handleAs:"json",
		load: function(data) {	
		    dijit.byId('reciept_no').set('value', data);
		},
		error: function(err) {
		}
	});
}

function submitDataClose(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0 || branch_id==""){
		alert("<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>");
		dijit.byId("branch_id").focus();
		return false;
	}
	if(dijit.byId('frm_add_tran').validate()) {
		loadingBlock();
		var url_submit = '<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'income','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !',1);
				window.location.href ="<?php echo $this->baseUrl();?>/tellerandexchange/income";
			},
			error: function(e) {
			}
		});
	}
}
</script>
