<?php 

$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("IL_DISBURSE"));
$frm = $this->frm_search;

$url_Payment = $this->baseUrl()."/loan/payment/add/id/"; 
$url_edit = $this->baseUrl()."/loan/index/edit/id/";
$url_agreement = $this->baseUrl()."/report/loan/agreement/id/";
$url_schedule = $this->baseUrl()."/report/loan/rpt-paymentschedules/id/";
$url_reschedule = $this->baseUrl()."/loan/repaymentschedule/add/id/";
$url_badloan = $this->baseUrl()."/loan/badloan/add/id/";
$url_PaymenHistory = $this->baseUrl()."/report/loan/paymenthistory/id/";
$url_Callateral = $this->baseUrl()."/report/groupmember/calleteral-letter/id/";

$url_givereceive_letter = $this->baseUrl()."/report/loan/givereceive-letter/id/";
$url_givereceive_doc_letter = $this->baseUrl()."/report/loan/givereceive-doc-letter/id/";
$url_comfirm_letter = $this->baseUrl()."/report/loan/comfirm-letter/id/";
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('IL_DISBURSE');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("client_name");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("repayment_method");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('co_id');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
					</div>
				</div>
				<div class="row g-3">
					
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('pay_every');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('status');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
   <div class="card-body">
	  <?php echo $this->list;?>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>


<script>
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var newPageTitle="";
			var actionType=1;
			var m = "clicked: " + key;
			if(key=="payment"){
				url='<?php echo $url_Payment;?>';
				actionType=2;
			}else if(key=="edit"){
				url='<?php echo $url_edit;?>';
				actionType=2;
			}else if(key=="agreement"){
				url='<?php echo $url_agreement;?>';
				newPageTitle="<?php echo $tr->translate("AGREEMENT");?>";
			}else if(key=="calleteral-letter"){
				url='<?php echo $url_Callateral;?>';
				newPageTitle="<?php echo $tr->translate("CALLETERAL_LETTER");?>";
			}else if(key=="comfirm-letter"){
				url='<?php echo $url_comfirm_letter;?>';
				newPageTitle="<?php echo $tr->translate("COMFIRM_LETTER");?>";
			}else if(key=="givereceive-letter"){
				url='<?php echo $url_givereceive_letter;?>';
				newPageTitle="<?php echo $tr->translate("GIVE_RECEIVE_LETTER");?>";
			}else if(key=="givereceive-doc-letter"){
				url='<?php echo $url_givereceive_doc_letter;?>';
				newPageTitle="<?php echo $tr->translate("GIVE_RECEIVE_DOC_LETTER");?>";
			}else if(key=="schedulePay"){
				url='<?php echo $url_schedule;?>';
				newPageTitle="<?php echo $tr->translate("SCHEDULE_PAYMENT");?>";
			}else if(key=="reschedule"){
				url='<?php echo $url_reschedule;?>';
				newPageTitle="<?php echo $tr->translate("REPAYMENTSCHEDULE");?>";
			}else if(key=="badloan"){
				url='<?php echo $url_badloan;?>';
				actionType=2;
			}else if(key=="PaymenHistory"){
				url='<?php echo $url_PaymenHistory;?>';
				newPageTitle="<?php echo $tr->translate("PAYMENT_HISTORY");?>";
			}
			if(actionType==1){
				addTab(newPageTitle,url+row+'?inFrame=true');
			}else{
				gotoAction();
			}
		},
		items: {
			"payment": {name: "<?php echo $tr->translate("ADD_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text"},
			"calleteral-letter": {name: "<?php echo $tr->translate("CALLETERAL_LETTER");?>", icon: "fa-file-text"},
			"comfirm-letter": {name: "<?php echo $tr->translate("COMFIRM_LETTER");?>", icon: "fa-file-text"},
			"givereceive-letter": {name: "<?php echo $tr->translate("GIVE_RECEIVE_LETTER");?>", icon: "fa-file-text"},
			"givereceive-doc-letter": {name: "<?php echo $tr->translate("GIVE_RECEIVE_DOC_LETTER");?>", icon: "fa-file-text"},
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			"schedulePay": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
			"reschedule": {name: "<?php echo $tr->translate("REPAYMENTSCHEDULE");?>", icon: "fa-calendar"},
			"PaymenHistory": {name: "<?php echo $tr->translate("PAYMENT_HISTORY");?>", icon: "fa-money", accesskey: "c o p y"},
			"badloan": {name: "<?php echo $tr->translate("BADLOAN");?>", icon: "fa-times"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_self');
}
</script>