<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LOAN_IL"));
$frm = $this->frm_search;

$url_Payment = $this->baseUrl()."/loan/payment/add/id/"; 
$url_agreement = $this->baseUrl()."/report/loan/agreement/id/";
$url_schedule = $this->baseUrl()."/report/loan/rpt-paymentschedules/id/";
$url_reschedule = $this->baseUrl()."/loan/repaymentschedule/add/id/";
$url_badloan = $this->baseUrl()."/loan/badloan/add/id/";
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
        	<div class="card pb-10 pt-10 pl-10 pr-10">
               	<div class="card-content collapse show">
               		<div class="card-box">
						<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
						   <div class="form-group">
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement("adv_search");?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('branch_id');?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement("client_name");?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement("repayment_method");?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('co_id');?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('currency_type');?>
						   		</div>
						   	</div>
						   	<div class="form-group">
						   		
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('pay_every');?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('start_date');?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('end_date');?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<?php echo $frm->getElement('status');?>
						   		</div>
						   		<div class="col-md-2 col-sm-2 col-xs-12">
						   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
						   		</div>
						   	</div>
						</form>
					</div>
					<div class="card-box">
						<?php echo $this->list;?>
					</div>
				</div>
			</div>

<script>
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			 if(key=="payment"){
				url='<?php echo $url_Payment;?>';
			}else if(key=="agreement"){
				url='<?php echo $url_agreement;?>';
			}else if(key=="schedulePay"){
				url='<?php echo $url_schedule;?>';
			}else if(key=="reschedule"){
				url='<?php echo $url_reschedule;?>';
			}else if(key=="badloan"){
				url='<?php echo $url_badloan;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"payment": {name: "<?php echo $tr->translate("ADD_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text"},
			"schedulePay": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
			"reschedule": {name: "<?php echo $tr->translate("REPAYMENTSCHEDULE");?>", icon: "fa-calendar"},
			"badloan": {name: "<?php echo $tr->translate("BADLOAN");?>", icon: "fa-times"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>