<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Add Exchange Money'));
	echo $this->headTitle();
?>	
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-replace"></i>&nbsp;<?php echo $tr->translate('Add Exchange Money');?></h5>
	</div>
	<div class="card-body">

		<form id='frm_add_exch' action="<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					if(dijit.byId('recieve_money').get('value') < dijit.byId('from_amount').get('value') || dijit.byId('return_money').get('value') < 0){
						infoMessageAlert('សូមពិនិត្រ ទឹកប្រាក់ដែលទទួលបានម្តង ទៀត..');
						dijit.byId('recieve_money').focus();
						return false;
					}
					dijit.byId('save_close').set('disabled',true);
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("ព៌ត័មាន ទាក់ទង នឹង អត្រាប្តូរប្រាក់");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <div class="col-md-12 col-sm-12 col-xs-12">
								   <table class="tbtable" style="margin:10px auto; width: 90%;border-collapse: collapse;border:2px solid #d2d2d2;" border="2" cellspacing='0'>									
									<tr class="tbheader">
										<th>និមិត្តសញ្ញា</th>
										<th>ទិញចូល</th>
										<th>លក់ចេញ</th>
									</tr>
									<?php $i=1;if (!empty($this->allExchangeRate)) foreach ($this->allExchangeRate as $rs){
										$class="second";
										if ($i==1){
											$i=0;
											$class="first";
										}else {
											$i = 1;
										}
										?>
									<tr class="<?php echo $class;?>">
										<td><?php echo $rs['fromCurr']." - ".$rs['toCurr']?></td>
										<td><label id="DB"><?php echo number_format($rs['rate_in'],2)?></label></td>
										<td><label id="BD"><?php echo number_format($rs['rate_out'],2)?></label></td>
									</tr>
									<?php }?>
								</table>
							   </div>
							</div>	
						</div>	
					</div>	
	            </div>
	            <div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("ព៌ត័មាន ទាក់ទង នឹង ទឹកប្រាក់");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" required="true" class="fullside" id="statusDate" name="statusDate" value="<?php echo date("Y-m-d");?>" type="text">
										<input type="hidden" value="" class="fullside" readonly="readonly" required="required" id="statusinout" name="statusinout" dojoType="dijit.form.TextBox" />
							   </div>
							</div>	
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ពីប្រភេទលុយ");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="from_amount_type" >
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ទៅជាប្រភេទលុយ");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="to_amount_type" >
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("អត្រាប្តូរប្រាក់");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name="rate"  id="rate"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="required:true, readOnly:true,name:'rate',class:'fullside',constraints:{pattern:'#,###.##'},missingMessage:'អ្នកភ្លេចបំពេញ  អត្រាប្តូរប្រាក់!',
											invalidMessage:'អត្រាប្តូរប្រាក់ មិនត្រឹមត្រូវ!'">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-12 col-sm-12 col-xs-12 special_cus" for="first-name"><?php echo $tr->translate("អតិថិជនពិសេស");?>
									<input style=" padding: 0; margin: 0; height: auto;" id="special_cus" name="special_cus" dojoType="dijit.form.CheckBox" value="1"
											 onChange="changRateTextbox();">
							   </label>
							</div>
							
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?>
								<span id="lbl_from_amount" class="special_cus"></span>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" onKeyup="return_money();" name="from_amount" id="from_amount"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="required:true,																		
											name:'from_amount',
											class:'fullside',
											constraints:{pattern:'#,###.##'},
											missingMessage:'អ្នកភ្លេចបំពេញ ចំនួនទឹកប្រាក់!',
											invalidMessage:'ចំនួនទឹកប្រាក់ មិនត្រឹមត្រូវ!'">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?>
									<span id="lbl_to_amount" class="special_cus"></span>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name="to_amount" id="to_amount"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="required:true,																		
											name:'to_amount',
											class:'fullside',
											constraints:{pattern:'#,###.##'},
											missingMessage:'អ្នកភ្លេចបំពេញ ចំនួនទឹកប្រាក់!',
											invalidMessage:'ចំនួនទឹកប្រាក់ មិនត្រឹមត្រូវ!'">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ប្រាក់ទទួលបាន");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name="recieve_money" id="recieve_money"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="required:true,									
											name:'recieve_money',
											class:'fullside',
											constraints:{pattern:'#,###.##'},
											missingMessage:'អ្នកភ្លេចបំពេញ ប្រាក់ទទួលបាន!',
											invalidMessage:'ប្រាក់ទទួលបាន មិនត្រឹមត្រូវ!'">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ប្រាក់អាប់");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name="return_money" id="return_money"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="								
											name:'return_money',
											class:'fullside',
											constraints:{pattern:'#,###.##'},
											value:'0',	
											readOnly:true,
											invalidMessage:'ប្រាក់ទទួលបាន មិនត្រឹមត្រូវ!'">
							   </div>
							</div>
						</div>
					</div>
	            </div>
	         </div>
	         
	        <div class="clearfix"></div>
			<div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
					<input type="hidden" name="inv_no" value="<?php echo $this->inv_no;?>">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" id="save_close" name="save_close" value="រក្សាទុក" label="<?php echo $tr->translate("SAVE");?>" id="submitButton" dojoType="dijit.form.Button" />
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="រក្សាទុក & បោះពុម្ព" label="<?php echo $tr->translate("SAVE_PRINT");?>" id="busyButton" dojoType="dijit.form.Button" onclick="printSave();"/> 
				</div>
	    	</div>
		</form>
	</div>
</div> 
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:8cm;" data-dojo-props="title:'របាយការណ៍ ប្តូរ', onCancel:hidePopup" id="terms" >
		<div id="divPrint" style="width: 7cm; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 12px;	
				}
				.fonttel{
					font-size: 11px;
				}
				.pleft{
					width: 110px;	
				}
				.font_khmer{font-family:'Khmer os Battambang';}
			</style>	
			<table style="width: 7cm; font-size: 8pt; padding: 0px; margin: 0px; line-height: 15px;">
				 <tr>
					   	<td align="center" colspan="3">	
					   	<table  width="100%" cellspacing="0" cellpadding="0">
					   		<tr style="line-height:10px;">
					   			<td width="36%" rowspan="2" style="valign:top;"><img style="margin-top: 1px;" src="<?php echo $base_url;?>images/logobrand.jpg" height="34px;"/></td>
						   		<td colspan="2" align="right"><strong style="font-size:12px;font-family:'Khmer MEF2';text-align:right;"><?php echo $tr->translate("CUSTOMER_LABEL");?></strong></td>
							</tr>
					   	</table>
			            </td>	   	        
				   </tr> 
				   <tr>
					   	<td align="center" colspan="3" style="font-family:'Khmer MEF2';"><?php echo $tr->translate("BUSINESS_NAMEKH");?></td>	   	        
				   </tr>            
				   <tr>
						<td align="center" colspan="3" style="font-size: 8pt;">
							<?php echo $tr->translate("BUSINESS_NAMEEN");?><br/>
							<strong class="fontbig"><?php echo $this->keycode['tel-client'];?></strong>
						</td>
				   </tr>
				   <tr>
					   <td align="right" colspan="3" style="font-size: 8pt;">
							<?php echo'Date: '. date("h:i d/m/Y");?>
					  </td>
				  </tr>
				   <tr style="border-bottom:1px solid #000; font-size:8px;">
						<td class="pleft" style="border-bottom:1px solid #000;">
							<label id="lblinvioice" style="font-size:10px;font-family:'Khmer MEF2';"><?php echo $this->keycode['exchange_reciept']; ?></label>
						</td>
						<td align="right" colspan="2" style="font-size: 8pt;border-bottom:1px solid #000;" class='font_khmer'>
							ឈ្មោះបុគ្គលិក៖ <?php print($this->user_name);?>
						</td>
				   </tr>
				   <tr>
						<td class="font_khmer">
							ចំនួនទឹកប្រាក់ប្តូរ
						</td>
						<td>:</td>
						<td align="right" style="white-space: nowrap;">
							<strong ><label id="rpt_from_amount"></label></strong>
						</td>
				   </tr>
				   <tr>
						<td class="font_khmer">អត្រាប្តូរប្រាក់</td>
						<td>:</td>
						<td align="right" style="white-space: nowrap;">
							<strong ><label id="rpt_rate"></label></strong>
						</td>
				   </tr>
				   <tr>
						<td class="font_khmer">
							ចំនួនទឹកប្រាក់ប្តូរសរុប
						</td>
						<td>:</td>
						<td align="right" style="white-space: nowrap;">
							<strong style="font-size:10px;"><label id="rpt_to_amount"></label></strong>
						</td>
				   </tr>
				   <tr>
						<td class="font_khmer">
							ចំនួនទឹកប្រាក់ទទួល
						</td>
						<td>:</td>
						<td align="right">
							<strong style="font-size:10px;"><label id="rpt_recieve"></label></strong>
						</td>
				   </tr>
				   <tr>
						<td class="font_khmer">ចំនួនទឹកប្រាក់អាប់</td>
						<td>:</td>
						<td align="right">
							<strong style="font-size:10px;"><label id="rpt_change"></label></strong>
						</td>
				   </tr>
				   <tr style="border:1px solid #000;">
						<td colspan="3" align="center" style="border-top: 2px dashed #000;padding-top:5px;" class="font_khmer">
							<?php echo $this->keycode['comment'];?>
						</td>			
				   </tr>
				   <tr>
						<td colspan="3" style="border-bottom: 1px solid #000;">
						</td>			
				   </tr>
				   <tr>
						<td colspan="3">
							<label style="font-weight:bold; font-size:9px; ">Powered By: Cam App Technology | Tel 012 40 41 92</label>
						</td>	
				   </tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button class="button-class button-danger" iconClass="glyphicon glyphicon-remove" dojoType="dijit.form.Button" showLabel="false" type="button" onclick="hidePopup();"><?php echo $tr->translate("CANCEL");?></button>
		<button class="button-class button-primary" iconClass="glyphicon glyphicon-print" dojoType="dijit.form.Button" showLabel="false" type="button" onclick="doPrint();"><?php echo $tr->translate("PRINT");?></button>
		
	</div>
</div>
<style>
	.panel{
		min-height: 444px;
		border:1px solid #6464d6;
	}
	.tbtable{	
		 text-align: center;
	    font-size: 20px;
	    color: #fff;
	    line-height: 37px;
	    font-weight: bolder;
	}
	.tbtable .tbheader{
		background-color: #dddddd;
		height: 60px; 
		color: #000;
	}
	.tbtable .first{
		background-color: #008 ; 
	}
	.tbtable .second{
		background-color: #E5A909 ; 
	}
	.special_cus{
		color: RED;
	}
</style>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.CheckBox");     
	dojo.require("dojo.number");
	
	dojo.require("dijit.Dialog");
	
	 var calcSysble = "*";
	 var lblrateid = "";
	 var toCurrencyType = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode(array()));?>
	 });
	dojo.ready(function(){		
		var curency_type_data = new dojo.store.Memory({
		       data: <?php print_r(Zend_Json::encode($this->currency));?>
		 });
		 
		new dijit.form.FilteringSelect({autoComplete: false,
queryExpr: "*${0}*",
	        id: "to_amount_type",
	        name: "to_amount_type",
	        class: 'fullside',
	        searchAttr: "name",
	        missingMessage:"អ្នកភ្លេចបំពេញ ប្រភេទលុយ!",
	        onChange: function() {
	        	getRateValue();
	        }
	    }, "to_amount_type");
	    
		new dijit.form.FilteringSelect({
	        store: dojo.data.ObjectStore({objectStore: curency_type_data}),autoComplete: false,
queryExpr: "*${0}*",
	        id: "from_amount_type",
	        name: "from_amount_type",
	        class: 'fullside',
	        searchAttr: "name",
	        missingMessage:"អ្នកភ្លេចបំពេញ ប្រភេទលុយ!",
	        onChange: function() {
	        	clearText(true);
	        	getExchangeFromTypeToType();
	        }
	    }, "from_amount_type");

		dojo.connect(dojo.byId("from_amount"), "onkeyup", function(evt){			
			if(!dojo.byId("special_cus").checked){
				//if(dojo.byId("rate").value != dojo.byId(lblrateid).innerHTML){		
					//dojo.byId("rate").value = dojo.byId(lblrateid).innerHTML;
				//}
			}
			total();
	    });
		dojo.connect(dojo.byId("to_amount"), "onkeyup", function(evt){
			rev_total();
	    });	

		dojo.connect(dojo.byId("rate"), "onkeyup", function(evt){
			total();
	    });

		dojo.connect(dojo.byId("recieve_money"), "onkeyup", function(evt){
			return_money();
	    });	
	});   

	function clearText(exp){
		if(exp !== true){
			dojo.byId('to_amount_type').value="";
		}
        dojo.byId('rate').value="";
        dojo.byId('to_amount').value="";
        dojo.byId('from_amount').value="";
        dojo.byId('recieve_money').value="";
        dojo.byId('return_money').value=0;
        dijit.byId("special_cus").attr("checked", false);
        dojo.byId("lbl_to_amount").innerHTML = "";
        //changRateTextbox();
	}

	function return_money(){
		var r_m=0;
		amount = dijit.byId('from_amount').get('value');
		recieve_money =	dijit.byId('recieve_money').get('value');
		if(dijit.byId('recieve_money').get('value') >= amount){
			rm = recieve_money - amount;
			dojo.byId("return_money").value = dojo.number.format(dojo.number.round(rm,2));
		}else{
			dijit.byId('recieve_money').set('value',dojo.number.format(dojo.number.round(amount,2)));
			dojo.byId("return_money").value = dojo.number.format(dojo.number.round(0,2));
		}
	}
	function total(){
		tt=0;
		r_money=0;
		amount = dijit.byId('from_amount').get('value');
		rate = dijit.byId('rate').get('value');
		
		if(isNaN(rate)){
			rate = 0;
		}
		if (calcSysble === "*"){
			tt = amount * rate;
		}
		else{
			tt = amount / rate;			
		}
		dojo.byId("to_amount").value = dojo.number.format(dojo.number.round(tt,2));
		dojo.byId("recieve_money").value = dojo.number.format(dojo.number.round(amount,2));
		return_money();
	}
	function rev_total(){
		tt=0;
		r_money=0;
		amount = dijit.byId('to_amount').get('value');
		rate = dijit.byId('rate').get('value');
		if(isNaN(rate)){
			rate = 0;
		}
		if (calcSysble === "*"){
			tt = amount / rate;
		}
		else{
			tt = amount * rate;	
		}
		dojo.byId("from_amount").value = dojo.number.format(dojo.number.round(tt,2));
		dojo.byId("recieve_money").value = dojo.number.format(dojo.number.round(tt,2));
		return_money();
	}
	function printSave(){		
		if(dijit.byId('frm_add_exch').validate()) {
			if(dijit.byId('recieve_money').get('value') < dijit.byId('from_amount').get('value') || dijit.byId('return_money').get('value') < 0){
				infoMessageAlert('សូមពិនិត្រ ទឹកដែលទទួលបានម្តង ទៀត..');
				dijit.byId('recieve_money').focus();
				return false;
			}
			showDialog();			
		}
	}
	function showDialog() {		
		var from_type = dojo.byId("from_amount_type").value;
		var to_type = dojo.byId("to_amount_type").value;
		var css_s = "<label class='fonttel'>";
		var css_e = "</label>"
		dojo.byId("rpt_from_amount").innerHTML = dojo.byId("from_amount").value +" "+ from_type;		
		dojo.byId("rpt_rate").innerHTML = dojo.byId("rate").value +" "+ to_type;
		dojo.byId("rpt_to_amount").innerHTML = css_s + dojo.byId("to_amount").value + css_e +" "+ to_type;
		dojo.byId("rpt_recieve").innerHTML = css_s + dojo.byId("recieve_money").value + css_e + " " + from_type;
		dojo.byId("rpt_change").innerHTML = css_s + dojo.byId("return_money").value + css_e + " " + from_type;
		dijit.byId("terms").show();
	}
	// Hide the dialog
	function hideDialog() {		
		dijit.byId("terms").hide();
		dijit.byId('frm_add_exch').submit();
	}
	function hidePopup() {		
		dijit.byId("terms").hide();
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	function changRateTextbox(){		
		if(dojo.byId("special_cus").checked){
			dijit.byId("rate").setAttribute('readOnly', false);
		}
		else{
			dijit.byId("rate").setAttribute('readOnly', true);
		}
	}
	var urlToExchange = '<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'index','action'=>'gettoexchange')); ?>';
	function getExchangeFromTypeToType(){
		from_amount_type = dijit.byId('from_amount_type').get('value');
		dojo.xhrPost({
			url:	urlToExchange,
			content:{
				'from_amount_type':from_amount_type
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('to_amount_type').reset('value');
				toCurrencyType = new dojo.store.Memory({
				       data: data
				 });
			    dijit.byId('to_amount_type').set('store',toCurrencyType);
			},
			error: function(err) {
				infoMessageAlert(err);
			}
		});
	}
	var urlRateValue = '<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'index','action'=>'getratevalue')); ?>';
	function getRateValue(){
		from_amount_type = dijit.byId('from_amount_type').get('value');
		to_amount_type = dijit.byId('to_amount_type').get('value');
		if(to_amount_type==""){
			return false;
		}
		dojo.xhrPost({
			url:	urlRateValue,
			content:{
				'from_amount_type':from_amount_type,'to_amount_type':to_amount_type
				},
			handleAs:"json",
			load: function(data) {
				var statusInOut="in";
				if(data.fromto=='fromto'){
					calcSysble="*";
					statusInOut="in";
				}else{
					calcSysble="/";
					statusInOut="out";
				}
				dijit.byId('statusinout').set('value',statusInOut);
				dijit.byId('rate').set('value',dojo.number.format(dojo.number.round(data.rate,2)));
				dojo.byId("lbl_from_amount").innerHTML = dijit.byId('from_amount_type').attr('displayedValue');
				dojo.byId("lbl_to_amount").innerHTML = dijit.byId('to_amount_type').attr('displayedValue');
			},
			error: function(err) {
				infoMessageAlert(err);
			}
		});
	}
</script>