<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Spread Rate page'));
	echo $this->headTitle();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-exchange"></i>&nbsp;<?php echo $tr->translate('Spread Rate page');?></h5>
		<div class="justify-content-between align-items-center ">
			<div class="row g-3">
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button class="button-class button-primary " iconclass="glyphicon glyphicon-tasks" dojoType="dijit.form.Button" showLabel="true" onClick="location.href = '<?php echo $this->baseUrl()."/tellerandexchange/spread/quickchange";?>';"  type="button"><?php echo $tr->translate("Exchange Rate Board");?></button>
				</div>
			</div>
		</div>
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>
