<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('POSITION_INFO'));
?>	
<?php  $techer= $this->frm_position;?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-sitemap"></i>&nbsp;<?php echo $tr->translate('POSITION_INFO');?></h5>
	</div>
	<div class="card-body">
		<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
	    	<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POSITION_KH");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $techer->getElement('position_kh');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POSITION_EN");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $techer->getElement('position_en');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $techer->getElement('status');?>
	                   </div>
	                </div>
					
					<!-- Button Save  -->
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
							<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" value="សំអាត" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
							<input type="button" class="button-class button-primary " iconClass="glyphicon glyphicon-floppy-remove" onclick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate("SAVECLOSE")?>" dojoType="dijit.form.Button" />
							<input type="submit" class="button-class button-primary " iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate("SAVENEW")?>" dojoType="dijit.form.Button"  />
						</div>
					</div>
					<!--/. Button Save  -->
			
	             </div>
	          </div>
		</form>
	</div>
</div>

<script>
function submitDataClose(){
	if(dijit.byId('add_techer').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'position','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_techer"),		    
			load: function(data) {
				infoMessageAlert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/loan/position";
			},
			error: function(e) {
			}
		});
	}
}
</script>