<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_POSITION'));
?>	
<?php  $techer= $this->frm_position;?>
<div class="card">
	<div class="card-content collapse show">
		<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
               		<div class="col-sm-12 border-botom">
		    			<div class="col-sm-8 pd-0">
		    				<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_POSITION');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POSITION_KH");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $techer->getElement('position_kh');?><?php echo $techer->getElement('id');?>
	                   </div>
	                </div>
	              
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POSITION_EN");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $techer->getElement('position_en');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $techer->getElement('status');?>
	                   </div>
	                </div>
	                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
	    		</div>
	             </div>
	          </div>
		</form>
	</div>
</div>
