<?php
	$this->headTitle('Loan Management System | Sale Card'); 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.NumberTextBox');
	
	dojo.ready(function(){		
		var txtamount = dojo.byId("amount");
			dojo.connect(txtamount, "onkeyup", function(evt){
			tt=0;
			gv=0;
			amount = dijit.byId('amount').get('value');
			type_money = dijit.byId('type_money').get('value');
			//dollar
			commission = amount*0.04;
			 dijit.byId('commission').attr('value',commission);
	    });	
	});   
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-credit-card" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SALECARD');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'salecard','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					if(dijit.byId('total').get('value') < 0 || dijit.byId('total').get('commission') ){
						alert('សូម​ពិនិត្រ ទឹកប្រាក់​​ដែល​​ទទួល​បាន​ម្តង ​ទៀត..');
						dijit.byId('recieve_money').focus();
						return false;
					}
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("ព៌ត័មាន នៃការលក់");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="title" id="title" placeholder="ចំណង់ជើង" class='fullside'
								dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="អ្នក​ភ្លេច​បំពេញ​  ចំណង់ជើង" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" id="note"
								 data-dojo-Type="dijit.form.TextBox"   
								 data-dojo-props="class:'fullside',
												 name:'note'"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("កាល​បរិច្ឆេទលក់");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php									
								    $newdate = date('Y-m-d', mktime(date('h'), date('i'), date('s'), date('m'), date('d')+45, date('Y')));
								?>
								<input type="text" name="date" id="date" value="<?php echo  date("Y-m-d");?>" 
								dojoType="dijit.form.DateTextBox" required="true" missingMessage="អ្នក​ភ្លេច​បំពេញ​ កាល​បរិច្ឆេទ វេ!" 
								 rangeMessage='កាល​បរិច្ឆេទ  វេ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ផុតកំណត់​ ' class='fullside'
								constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  $newdate;?>'}" 
								onchange="dijit.byId('epx_date').constraints.min = arguments[0];"/>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("ព៌ត័មាន ទាក់​ទង នឹង​ ទឹកប្រាក់");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENCY_TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select  name="type_money" id="type_money" class='fullside' dojoType="dijit.form.FilteringSelect" missingMessage="អ្នក​ភ្លេច​បំពេញ​  ប្រភេទ​លុយ!" required="true"> 
									<?php foreach ($this->currency as $key => $cur) : ?>
										<option value="<?php echo $cur['id'];?>"><?php echo $cur['name'];?></option>
									<?php endforeach;?> 
								</select> 
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ចំនួន​ទឹក​ប្រាក់លក់បាន");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="amount" id="amount"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'amount',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("កម្រៃសេវាជាទទួលបាន");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name='commission' id="commission"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,
									name:'commission',
									class:'fullside',
									constraints:{pattern:'#,###.###'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ថ្លៃសេវា!',
									invalidMessage:'ថ្លៃសេវា​ មិន​ត្រឹម​ត្រូវ!'">	
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	            	 <div class="form-group">
	            	 	<img style=" width: 100%;" src="<?php echo $this->baseurl();?>/images/sellcard.jpg" />
	            	 </div>
	            </div>
	        </div>
	        <div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	    			<input type="submit" value="រក្សាទុក" label="រក្សាទុក និង បិទ" name='saveclose' id="submitButton" dojoType="dijit.form.Button" 
					 iconClass="dijitEditorIcon dijitEditorIconSave" />
					 <input type="submit" value="រក្សាទុក" label="រក្សាទុក និងបន្ថែមថ្មី" name='savenew' dojoType="dijit.form.Button" 
					 iconClass="dijitEditorIcon dijitEditorIconSave" />
	    		</div>
			</div>	
		</form>
	</div>
</div>	 
