<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$this->headTitle($tr->translate('EDIT_SALECARD')); 
	echo $this->headTitle();
?>	
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-device-mobile-message"></i>&nbsp;<?php echo $tr->translate('EDIT_SALECARD');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'salecard','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					if(dijit.byId('total').get('value') < 0 || dijit.byId('total').get('commission') ){
						infoMessageAlert('សូមពិនិត្រ ទឹកប្រាក់ដែលទទួលបានម្តង ទៀត..');
						dijit.byId('recieve_money').focus();
						return false;
					}
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("SALE_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name="title" id="title" placeholder="ចំណង់ជើង" class='fullside'
										dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs['title'];?>" required="true" missingMessage="អ្នកភ្លេចបំពេញ ចំណង់ជើង" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" id="note"
										 data-dojo-Type="dijit.form.TextBox"   
										 data-dojo-props="class:'fullside',
										 value:'<?php echo $this->rs['note'];?>',
														 name:'note'"/>
									  <input type="hidden" id="id"
										 data-dojo-Type="dijit.form.TextBox"   
										 data-dojo-props="class:'fullside',
										 value:'<?php echo $this->rs['id'];?>',
														 name:'id'"/>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("កាលបរិច្ឆេទលក់");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php									
											$newdate = date('Y-m-d',strtotime($this->rs['sale_date']));
										?>
										<input type="text" name="date" id="date" value="<?php echo $newdate ?>" 
										dojoType="dijit.form.DateTextBox" required="true" missingMessage="អ្នកភ្លេចបំពេញកាលបរិច្ឆេទ វេ!" 
										 rangeMessage='កាលបរិច្ឆេទ  វេ មិនអាចតូចជាង កាលបរិច្ឆេទ ផុតកំណត់' class='fullside' />
							   </div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("ព៌ត័មាន ទាក់ទង នឹងទឹកប្រាក់");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENCY_TYPE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<select name="type_money" id="type_money" class='fullside' dojoType="dijit.form.FilteringSelect" missingMessage="អ្នកភ្លេចបំពេញ ប្រភេទលុយ!" required="true"> 
											<?php foreach ($this->currency as $key => $cur) : ?>
												<option value="<?php echo $cur['id'];?>" <?php if ($cur['id']==$this->rs['curr_type']){ echo 'selected="selected"';}?> ><?php echo $cur['name'];?></option>
											<?php endforeach;?> 
										</select> 
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ចំនួនទឹកប្រាក់លក់បាន");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name="amount" id="amount"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="required:true,																		
											name:'amount',
											value:'<?php echo $this->rs['amount_sale'];?>',
											class:'fullside',
											constraints:{pattern:'#,###.##'},
											missingMessage:'អ្នកភ្លេចបំពេញចំនួនទឹកប្រាក់!',
											invalidMessage:'ចំនួនទឹកប្រាក់មិនត្រឹមត្រូវ!'">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("កម្រៃសេវាជាទទួលបាន");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" name='commission' id="commission"  data-dojo-type="dijit.form.NumberTextBox"
											data-dojo-props="required:true,
											name:'commission',
											value:'<?php echo $this->rs['commission'];?>',
											class:'fullside',
											constraints:{pattern:'#,###.###'},
											missingMessage:'អ្នកភ្លេចបំពេញថ្លៃសេវា!',
											invalidMessage:'ថ្លៃសេវាមិនត្រឹមត្រូវ!'">	
							   </div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	            	 <div class="row g-3">
	            	 	<img style=" width: 100%;" src="<?php echo $this->baseurl();?>/images/sellcard.jpg" />
	            	 </div>
	            </div>
	        </div>
	        <div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
					 <input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="រក្សាទុក" label="<?php echo $tr->translate("SAVE");?>" name='savenew' dojoType="dijit.form.Button" />
	    		</div>
			</div>	
		</form>
	</div>
</div>	 
<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.NumberTextBox');
	
	dojo.ready(function(){		
		var txtamount = dojo.byId("amount");
			dojo.connect(txtamount, "onkeyup", function(evt){
			tt=0;
			gv=0;
			amount = dijit.byId('amount').get('value');
			type_money = dijit.byId('type_money').get('value');
			//dollar
			commission = amount*0.04;
			 dijit.byId('commission').attr('value',commission);
	    });	
	});   
</script>	