<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_callteral;
echo $this->frm_popup_callecteral;
echo $this->headTitle($tr->translate("CLIENT_COLLTERAL"));
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	dojo.require("dijit.Dialog");
</script>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('CLIENT_COLLTERAL');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'group','controller'=>'callteral','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				var rowId = $('#record_row').val();
				if(rowId!=''){ 
					var rowIDArray = rowId.split(',');
					for(var n = 0; n < rowIDArray.length; n++){
					var row_id = dijit.byId('collect_type'+rowIDArray[n]).get('value');
						if(row_id=='' || row_id==-1){
							alert("<?php echo $tr->translate("Please Select Collteral Type");?>!");
							dijit.byId('collect_type'+rowIDArray[n]).focus();
							return false;
							}
						}
					}				
				 if(dijit.byId('branch_id').get('value')==''){
				     alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> !');
                         dijit.byId('branch_id').focus();
                         return false;
                 }
				if(dijit.byId('co_name').get('value')==''){
				         alert('<?php echo $tr->translate("Please Select Staff");?> !');
                         dijit.byId('co_name').focus();
                         return false;
                 }
                 if(dijit.byId('client_name').get('value')==''){
				         alert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?> !');
                         dijit.byId('client_name').focus();
                         return false;
                 }
                  if(dijit.byId('record_row').get('value')==''){
				         alert('<?php echo $tr->translate("Please Select collateral must be record");?>!');
                         return false;
                 }
				return true;
			}else {
				return false;
			}
			</script>
	    	<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('branch_id');echo $frm->getElement('id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_NO");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<input id="loan_number" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COLLTERAL_CODE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('cod_cal');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STAFF_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('co_name');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('note');?>
							   </div>
							</div>			                
						</div>			                
					</div>			                
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CUSTOMER_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
								<input id="client_name" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('date_estate');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Stutas');?>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("GUARANTOR_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AND_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('name');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('names');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SPOUSE_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('owner');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('and_name');?>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	        </div>
	        <div class="card-box">
	        	<div class="row g-3">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                    	<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
						<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
							<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
						</table>
						<input iconClass="dijitIconClear" type="button" onClick="addCollecteral();" label="<?php echo $tr->translate('ADD');?>" dojoType="dijit.form.Button"/>
                    </div>
                </div>
	        </div>
			
			<!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-2 py-2 text-center">
		    		<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close"  id="save_close"  label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button"   />
					
					
    			</div>
    		</div>
	    	<!--/. Button Save  -->
			
		</form>
	</div>
</div>
<?php 
echo $this->frmpupopclient;
echo $this->frmPopupCO;
?>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
var loan_store  = getDataStorefromJSON('id','name',);
var client_store  = getDataStorefromJSON('id','name',);
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	store: client_store,
	required: true,		           
	name: "client_name",
	id: "client_name",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	value:'<?php echo $this->client_id;?>',
	class: 'fullside',
	onChange: function() {
		getClientInfo(2);
}
	}, "client_name");

	innitialize();

	new dijit.form.FilteringSelect({
		store: loan_store,
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			getLoanInfomation();
		}
	}, "loan_number");
	filterClient();
	//getloanbyBranch();
});

function filterClient(){
	getloanbyBranch();
	getClientByBranch();
}
function getClientInfo(type){
	customer_code= dijit.byId('client_name').get('value');
	if(type==1){
		addCollecteral();
	}else{
	}
	getClientInfomation();	
}
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_clientinfo = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientinfo')); ?>';
function getClientInfomation(){
	client_id = dijit.byId('client_name').get('value');
	if(client_id=="" || client_id==-1){
		dijit.byId('name').attr('value',"");
		dijit.byId('names').attr('value',"");
		dijit.byId('owner').attr('value',"");
		dijit.byId('and_name').attr('value',"");
		return false;
	}
		dojo.xhrPost({
	    url: url_clientinfo,	
		content:{ 
			'client_id':client_id
			},		    
		handleAs:"json",
		load: function(data) {	
			dijit.byId('name').attr('value',data.join_with);
			dijit.byId('names').attr('value',data.relate_with);
			dijit.byId('owner').attr('value',data.spouse_name);
			dijit.byId('and_name').attr('value',data.guarantor_with);
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");				        
		}
	});
}
function popupCheckCO(){
	if(dijit.byId('co_name').get('value')==-1){
		 dijit.byId('frm_co').show();
	}
}

temp='';
fund_title=0;
r = 0;
collect_option = '<?php echo $this->collect_option;?>';
owner_option = '<?php echo $this->owner_type;?>';
function addCollecteral(){
		r++;
		if(fund_title!=1){
			thead='<th><?php echo $tr->translate("DEL");?></th>';
			thead+='<th><?php echo $tr->translate("COLETERAL_TYPE");?></th>';
			thead+='<th><?php echo $tr->translate("OWNER_TYPE");?></th>';
			thead+='<th><?php echo $tr->translate("OWNER_NAME");?></th>';
			thead+='<th><?php echo $tr->translate("NUMBER_COLLTERAL");?></th>';
			thead+='<th><?php echo $tr->translate("SIGN_DATE");?></th>';
			thead+='<th><?php echo $tr->translate("ISSUE_BY");?> </th>';
			dojo.query("#head_title").append(thead);
			fund_title=1;
        }
		temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		temp+='<td><select style=" width:90%;background:#fff; padding-left:5px;" id="collect_type'+r+'" name="collect_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="showPopCallecteral('+r+')"  >'+collect_option+'</select></td>';
	    temp+='<td><select style=" width:90%; background:#fff; padding-left:5px;" id="owner_type'+r+'" name="owner_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="setOwnerNameCollecteralById('+r+')">'+owner_option+'</select></td>';
		temp+='<td><input style=" width:90%;" type="text" required="true" name="owner_name'+r+'" id="owner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
		temp+='<td><input style=" width:90%;" type="text"  name="number_collteral'+r+'" id="number_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
		temp+='<td><input constraints='+'{datePattern:"dd/MM/yyyy"}'+'  style=" width:90%;" type="text"  name="issue_date'+r+'" id="issue_date'+r+'" value="<?php echo date('Y-m-d'); ?>" dojoType="dijit.form.DateTextBox"/></td>';
		temp+='<td><input type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.TextBox" /></td>';
		tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
		tmp+="</tr>";
			dojo.query("#t_amountmoneytype").append(tmp);
			dojo.html.set(dojo.byId("row_capital"+r),temp, {
		    parseContent: true,
		     
		});
		if(dijit.byId("record_row").get('value')!="") {
			var ids = dijit.byId("record_row").value;
			dijit.byId("record_row").attr('value',ids+','+r);
		} else { dijit.byId("record_row").attr('value',r);}
		label = dijit.byId('client_name').attr('displayedValue');
		dijit.byId('owner_name'+r).attr('value',label);
}
function innitialize(){
		<?php if(!empty($this->rows)) {
		foreach($this->rows AS $i=>$rs){?>
	r++;
	if(fund_title!=1){
		thead='<th><?php echo $tr->translate("DEL");?></th>';
		thead+='<th><?php echo $tr->translate("COLETERAL_TYPE");?></th>';
		thead+='<th><?php echo $tr->translate("OWNER_TYPE");?></th>';
		thead+='<th><?php echo $tr->translate("OWNER_NAME");?></th>';
		thead+='<th><?php echo $tr->translate("NUMBER_COLLTERAL");?></th>';
		thead+='<th><?php echo $tr->translate("SIGN_DATE");?></th>';
		thead+='<th><?php echo $tr->translate("NOTE");?> </th>';
		fund_title=1;
		dojo.query("#head_title").append(thead);
}
	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
	temp+='<td><select style=" width:90%;background:#fff; padding-left:5px;" id="collect_type'+r+'" name="collect_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="showPopCallecteral('+r+')"  >'+collect_option+'</select></td>';
    temp+='<td><select style=" width:90%; background:#fff; padding-left:5px;" id="owner_type'+r+'" name="owner_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="setOwnerNameCollecteralById('+r+')">'+owner_option+'</select></td>';
	temp+='<td><input style=" width:90%;" type="text" required="true" name="owner_name'+r+'" id="owner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
	temp+='<td><input style=" width:90%;" type="text" name="number_collteral'+r+'" id="number_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
	temp+='<td><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' style=" width:90%;" type="text"  name="issue_date'+r+'" id="issue_date'+r+'" dojoType="dijit.form.DateTextBox"/></td>';
	temp+='<td><input type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.TextBox" /></td>';
	tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		dojo.html.set(dojo.byId("row_capital"+r),temp, {
	    parseContent: true,
	     
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
	dijit.byId('collect_type'+r).attr('value',<?php echo $rs['collecteral_type'];?>);
	dijit.byId('owner_type'+r).attr('value',<?php echo $rs['owner_type'];?>);
	dijit.byId('owner_name'+r).attr('value','<?php echo $rs['owner_name'];?>');
	dijit.byId('number_collteral'+r).attr('value','<?php echo $rs['number_collecteral'];?>');
	dijit.byId('issue_date'+r).attr('value','<?php echo $rs['issue_date'];?>');
	dijit.byId('note'+r).attr('value','<?php echo $rs['note'];?>');
	<?php }}?>
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
}
function setOwnerNameCollecteralById(index){
	label='';
	owner_type = dijit.byId('owner_type'+index).get('value');
	if(owner_type==1){
		label = dijit.byId('client_name').attr('displayedValue');
	}else{
		label = dijit.byId('owner').get('value');
	}
	dijit.byId('owner_name'+index).attr('value',label);
}
function showPopCallecteral(r){
    if(dijit.byId('collect_type'+r).get("value")==-1){
    	dijit.byId('call_pop').show();
    	$("#row_value").val(r);
    }
}

var data_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->call_all));?> );
var url_add_service =  '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add-callteral-type'));?>';
function addCallteral(){
if(dijit.byId('frm_call_add').validate()){
	dojo.xhrPost({
			url:url_add_service,
			form: dojo.byId("frm_call_add"),
			handleAs:"json",
			load: function(data) {
			var Itemmake = { 
		        id: data,
		        name: dijit.byId('title_kh').get('value')
		         };
			num=$("#row_value").val();
		    addDataToSelectbox(dijit.byId('collect_type'+num), data_store, Itemmake, data);
		    dijit.byId('frm_call_add').reset();
		  	dijit.byId("call_pop").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_loan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallloanbybranch')); ?>';
function getloanbyBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==null){
		var loan_store  = getDataStorefromJSON('id','name',);
		dijit.byId('loan_number').set('store', loan_store);
		return false;
	}
	dojo.xhrPost({
		url:url_loan,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value'),
		},
		handleAs:"json",
		load: function(data) {
			loan_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('loan_number').set('store', loan_store);
		    dijit.byId('loan_number').attr('value', '<?php echo $this->loan_id;?>');
		},
		error: function(err) {
			
		}
	});
}
var url_loaninfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getLoanInfomation(){
	loan_number = dijit.byId('loan_number').get('value');
	dijit.byId('client_name').reset();
	if(loan_number=="" || loan_number==-1){
		return false;
	}
		dojo.xhrPost({
	    url: url_loaninfo,	
		content:{ 
			'loan_id':loan_number
			},		    
		handleAs:"json",
		load: function(data) {	
			dijit.byId('client_name').attr('value',data.customer_id);
		},
		error: function(err) {
		}
	});
}
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getClientByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_name').reset();
	if(branch_id=='' || branch_id==null){
		var client_store  = getDataStorefromJSON('id','name',);
		dijit.byId('client_name').set('store', client_store);
		return false;
	}
	dojo.xhrPost({
		url: url_getclient,	
		content:{ 
		    'branch_id':branch_id,
		},
		handleAs:"json",
		load: function(data) {
			
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('client_name').set('store', client_store);
		    dijit.byId('client_name').attr('value', '<?php echo $this->client_id;?>');
		},
		error: function(err) {
			
		}
	});
}
</script>