<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_changeCollteral;
echo $this->headTitle($tr->translate("CHANGE_COLLTERAL_INFO"));
$row = $this->row;
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
</script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.data.ObjectStore");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
</script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<style>	
.collteral{
	color:blue;
}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>

<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('CHANGE_COLLTERAL_INFO');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'group','controller'=>'changecollteral','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				var rowId = $('#record_row').val();
    			if(rowId!=''){ 
					var rowIDArray = rowId.split(',');
					for(var n = 0; n < rowIDArray.length; n++){
					var row_id = dijit.byId('tocollect_type'+rowIDArray[n]).get('value');
					if(row_id==''){
							infoMessageAlert("<?php echo $tr->translate("Please Select Collteral Type");?>!");
							dijit.byId('tocollect_type'+rowIDArray[n]).focus();
							return false;
						}
					}
				}
				if(dijit.byId('branch_id').get('value')==''){
                    infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> ');
                    dijit.byId('branch_id').focus();
                    return false;
                }
                if(dijit.byId('client_name').get('value')==''){
                    infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?> !');
                    dijit.byId('client_name').focus();
                    return false;
                }
               if(dijit.byId('record_row').get('value')==''){
                    infoMessageAlert('<?php echo $tr->translate("Can not submit without record");?> !');
                    return false;
                }
				return true;
			}else {
				return false;
			}
			</script>
	    	<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">
							 <div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('branch_id');echo $frm->getElement('id');?>
									<input dojoType="dijit.form.TextBox"  id="owner" name="owner" value="" type="hidden">
									<input dojoType="dijit.form.TextBox"  id="client_coll" name="client_coll" value="" type="hidden">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_NO");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<input id="loan_number" />
							   </div>
							</div>
							 <div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME")?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<input id="client_name" /><?php //echo $frm->getElement('client_name');?>
							   </div>
							</div>
							<!-- 
							<div class="row g-3">
							   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
							   </label>
							</div>
							<div class="row g-3">
								<div class="col-md-12 col-sm-12 col-xs-12" style=" border: 1px solid #ccc;width:100%; height:auto; min-height:50px;font:12px;padding: 2px 5px;">
									<span id="display_info">&nbsp;</span>
							   </div>
							</div>
							 -->
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("DATE");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('note');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('date');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Stutas');?>
							   </div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("RETURN_COLLTERAL_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECEIVER_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('giver_name');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("GIVER_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('receiver_name');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('_note');?>
							   </div>
							</div>
						</div>
					</div>
	             </div>
	        </div>
	        <div class="card-box">
	        	<div class="row g-3">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                    	<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
						<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
									<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
						</table>
                    </div>
                </div>
	        </div>
			
			<!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-2 py-2 text-center">
					<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" value="សំអាត" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"/>
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate("GO_EDIT")?>" dojoType="dijit.form.Button" />
				</div>
    		</div>
	    	<!--/. Button Save  -->
			
		</form>
	</div>
</div>
<?php 
echo $this->frm_popup_callecteral;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dijit.form.DateTextBox");
var loan_store  = getDataStorefromJSON('id','name',);
var client_store  = getDataStorefromJSON('id','name',);

dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		store: loan_store,
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			getLoanInfomation();
			getClientCollateral()
		}
	}, "loan_number");
	
	new dijit.form.FilteringSelect({
		store: client_store,
		required: true,		           
		name: "client_name",
		id: "client_name",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
		}
	}, "client_name");

	
	temp='';
	fund_title=0;
	r = 0;
	collect_option = '<?php echo $this->collect_option;?>';
	owner_option = '<?php echo $this->owner_type;?>';
	//innitialize();
	//getClientInfomation();
	filterClient();
	});


function filterClient(){
	getloanbyBranch();
	getClientByBranch();
}
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
		infoMessageAlert("Your message could not be sent, please try again!.");
				        
		}
	});
}
function popupCheckCO(){
	if(dijit.byId('co_name').get('value')==-1){
		 dijit.byId('frm_co').show();
	}
}

var url_clientinfo = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientinfo')); ?>';
function getClientInfomation(){
		dojo.xhrPost({
	    url: url_clientinfo,	
		content:{ 
			'client_id':dijit.byId('client_name').get('value')
			},		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('display_info').innerHTML="<span class='collteral'> ឈ្មោះអតិថជន​ ​:  </span>"+data.client_number+', '+data.name_kh+', '+data.name_en+",<span class='collteral'> នឹងឈ្មោះ : "+data.join_with+" ត្រូវជា  "+data.relate_with+
			" អ្នកធានា ឈ្មោះ "+data.spouse_name+" ត្រូវជា"+data.guarantor_with+"</span>";
			dijit.byId('owner').attr('value',data.spouse_name);
		},
		error: function(err) {
				infoMessageAlert(err);        
		}
	});
}

function innitialize(){
	<?php if(!empty($this->rows)) {
		foreach($this->rows AS $i=>$rs){?>
			r++;
			if(fund_title!=1){
				thead='<td><?php echo $tr->translate("NUM");?></td>';
				thead+='<td><?php echo $tr->translate("COLETERAL_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_NAME");?></td>';
				thead+='<td><?php echo $tr->translate("NUMBER_COLLTERAL");?></td>';
				thead+='<td><?php echo $tr->translate("COLETERAL_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_NAME");?></td>';
				thead+='<td><?php echo $tr->translate("NUMBER_COLLTERAL");?></td>';
				thead+='<td><?php echo $tr->translate("SIGN_DATE");?></td>';
				thead+='<td><?php echo $tr->translate("ISSUE_BY");?> </td>';
				
				fund_title=1;
				dojo.query("#head_title").append(thead);
	        }
			temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" >'+r+'<input type="hidden" name="de_id'+r+'" id="de_id'+r+'" dojoType="dijit.form.TextBox"/></td>';
			temp+='<td><select class="fullside" style="background:#fff; padding-left:5px;" readonly="true" id="collect_type'+r+'" name="collect_type'+r+'" dojoType="dijit.form.FilteringSelect"  >'+collect_option+'</select></td>';
		    temp+='<td><select class="fullside" style=" background:#fff; padding-left:5px;" readonly="true" id="owner_type'+r+'" name="owner_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="setOwnerNameCollecteralById('+r+')">'+owner_option+'</select></td>';
			temp+='<td><input class="fullside" style="  type="text" required="false"  readonly="true" name="owner_name'+r+'" id="owner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			temp+='<td><input class="fullside" style=" type="text" required="false" readonly="true" name="number_collteral'+r+'" id="number_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';

			temp+='<td><select class="fullside" style=" width:130px;background:#fff; padding-left:5px;" id="tocollect_type'+r+'" name="tocollect_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="showPopCallecteral('+r+')" >'+collect_option+'</select></td>';
		    temp+='<td><select class="fullside" style="background:#fff; padding-left:5px;" id="toowner_type'+r+'" name="toowner_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="setOwnerNameCollecteralById('+r+')">'+owner_option+'</select></td>';
			temp+='<td><input  class="fullside" style="  type="text" required="false" name="toowner_name'+r+'" id="toowner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			temp+='<td><input class="fullside" type="text" style=" name="tonumber_collteral'+r+'" id="tonumber_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			temp+='<td><input class="fullside" type="text"  name="issue_date'+r+'" id="issue_date'+r+'" value="<?php echo date("Y-m-d",strtotime($rs['issue_date']));?>" dojoType="dijit.form.DateTextBox"/></td>';
			temp+='<td><input class="fullside" type="text" name="tonote'+r+'" id="tonote'+r+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="coid'+r+'" id="coid'+r+'" dojoType="dijit.form.TextBox" /> </td>';
			tmp='<tr style="border:1px solid #ccc; font-size:11px !important" id="row_capital'+r+'">'
			tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			     
			});
			if(dijit.byId("record_row").get('value')!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
			
			dijit.byId('collect_type'+r).attr('value',<?php echo $rs['from_collateral_type'];?>);
			dijit.byId('owner_type'+r).attr('value',<?php echo $rs['from_owner_id'];?>);
			dijit.byId('owner_name'+r).attr('value','<?php echo $rs['from_owner_name'];?>');
			dijit.byId('number_collteral'+r).attr('value','<?php echo $rs['from_number_collateral'];?>');

			dijit.byId('tocollect_type'+r).attr('value',<?php echo $rs['collateral_type'];?>);
			dijit.byId('toowner_type'+r).attr('value',<?php echo $rs['owner_id'];?>);
			dijit.byId('toowner_name'+r).attr('value','<?php echo $rs['toowner_name'];?>');
			dijit.byId('tonumber_collteral'+r).attr('value','<?php echo $rs['number_collateral'];?>');
			dijit.byId('tonote'+r).attr('value','<?php echo $rs['note'];?>');
			dijit.byId('de_id'+r).attr('value','<?php echo $rs['id'];?>');
			dijit.byId('coid'+r).attr('value',<?php echo $rs['client_coll_id'];?>);
			
			//dijit.byId('client_coll').attr('value',<?php //echo $rs['client_coll_id'];?>);
			//setOwnerNameCollecteralById(r);
			
		<?php }}?>
		
}
function setOwnerNameCollecteralById(index){
	label='';
	owner_type = dijit.byId('toowner_type'+index).get('value');
	if(owner_type==1){
		label = dijit.byId('client_name').attr('displayedValue');
	}else{
		label = dijit.byId('owner').get('value');
	}
	//dijit.byId('owner_name'+index).attr('value',label);
	dijit.byId('toowner_name'+index).attr('value',label);
}

function showPopCallecteral(r){
	//infoMessageAlert('hello');
    if(dijit.byId('tocollect_type'+r).get("value")==-1){
    	dijit.byId('call_pop').show();
    	$("#row_value").val(r);
    }
}

var data_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->call_all));?> );
var url_add_service =  '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add-callteral-type'));?>';
function addCallteral(){
if(dijit.byId('frm_call_add').validate()){
	//language = dijit.byId('add_title').get('value');
	dojo.xhrPost({
			url:url_add_service,
			form: dojo.byId("frm_call_add"),
			handleAs:"json",
			load: function(data) {
				//infoMessageAlert(data);
			var Itemmake = { 
		        id: data,
		        name: dijit.byId('title_kh').get('value')
		         };
			num=$("#row_value").val();
		    addDataToSelectbox(dijit.byId('tocollect_type'+num), data_store, Itemmake, data);
			//dijit.byId("").
		    dijit.byId('frm_call_add').reset();
		  	dijit.byId("call_pop").hide();
			},
			error: function(err) {
				infoMessageAlert(err);
			}
		});
	}
}
var oldloan_id = "<?php echo $row['loan_id']; ?>";
var url_clientcall = '<?php echo $this->url(array('module'=>'group','controller'=>'callteral','action'=>'getclientcollateralbyloan')); ?>';
function getClientCollateral(){
	fund_title=0;
	dojo.query("#showrecord").append('');
	loan_number = dijit.byId('loan_number').get('value');
	if(loan_number=='' || loan_number==null){
		return false;
	}
	if(loan_number==oldloan_id){
		innitialize();
		return false;
	}
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
		dojo.xhrPost({
	    url: url_clientcall,	
		content:{ 
			'loan_id':loan_number
			},		    
		handleAs:"json",
		load: function(data) {	
			if(data==''){
				infoMessageAlert('No Collateral To Change !');
			}
			for(i=0;i<data.length;i++){
		
			r++;
			if(fund_title!=1){
				thead='<td><?php echo $tr->translate("DEL");?></td>';
				thead+='<td><?php echo $tr->translate("COLETERAL_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_NAME");?></td>';
				thead+='<td><?php echo $tr->translate("NUMBER_COLLTERAL");?></td>';
				thead+='<td><?php echo $tr->translate("COLETERAL_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_TYPE");?></td>';
				thead+='<td><?php echo $tr->translate("OWNER_NAME");?></td>';
				thead+='<td><?php echo $tr->translate("NUMBER_COLLTERAL");?></td>';
				thead+='<td><?php echo $tr->translate("SIGN_DATE");?></td>';
				thead+='<td><?php echo $tr->translate("ISSUE_BY");?> </td>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
	        }
			temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			temp+='<td><select class="fullside" style=" width:120px;background:#fff; padding-left:5px;" readonly="true" id="collect_type'+r+'" name="collect_type'+r+'" dojoType="dijit.form.FilteringSelect"  >'+collect_option+'</select></td>';
		    temp+='<td><select class="fullside" style=" width:110px; background:#fff; padding-left:5px;" readonly="true" id="owner_type'+r+'" name="owner_type'+r+'" dojoType="dijit.form.FilteringSelect" >'+owner_option+'</select></td>';
			temp+='<td><input class="fullside" style="  type="text"  readonly="true" name="owner_name'+r+'" id="owner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			temp+='<td><input class="fullside" style=" type="text" required="false" readonly="true" name="number_collteral'+r+'" id="number_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';

			temp+='<td><select class="fullside" style=" width:130px;background:#fff; padding-left:5px;"  id="tocollect_type'+r+'" name="tocollect_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="showPopCallecteral('+r+')"  >'+collect_option+'</select></td>';
		    temp+='<td><select class="fullside" style=" width:90px; background:#fff; padding-left:5px;"  id="toowner_type'+r+'" name="toowner_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="setOwnerNameCollecteralById('+r+')">'+owner_option+'</select></td>';
			temp+='<td><input class="fullside" style=" width:90%;" type="text" required="false"  name="toowner_name'+r+'" id="toowner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			temp+='<td><input class="fullside" type="text" style="width:110px"  name="tonumber_collteral'+r+'" id="tonumber_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			temp+='<td><input class="fullside" type="text" constraints="{datePattern:'+"'dd/MM/yyyy'"+'}" name="issue_date'+r+'" id="issue_date'+r+'" dojoType="dijit.form.DateTextBox"/></td>';
			temp+='<td><input class="fullside" style="  type="text" name="tonote'+r+'"  id="tonote'+r+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="coid'+r+'" id="coid'+r+'" dojoType="dijit.form.TextBox" /> </td>';

			
			tmp='<tr style="border:1px solid #ccc; font-size:11px !important" id="row_capital'+r+'">'
			tmp+="</tr>";
			
				dojo.query("#t_amountmoneytype").append(tmp);
				
			dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			});
			if(dijit.byId("record_row").get('value')!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
			
				dijit.byId('collect_type'+r).attr('value',data[i].collecteral_type);
				dijit.byId('owner_type'+r).attr('value',data[i].owner_type);
				dijit.byId('owner_name'+r).attr('value',data[i].owner_name);
				dijit.byId('toowner_name'+r).attr('value',data[i].owner_name);
				
				dijit.byId('number_collteral'+r).attr('value',data[i].number_collecteral);
				dijit.byId('coid'+r).attr('value',data[i].id);
				dijit.byId('client_coll').attr('value',data[i].client_coll);
				setOwnerNameCollecteralById(r);
			}
		},
		error: function(err) {
		}
	});
}

var url_loan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallloanbybranch')); ?>';
var oldbranch_id = "<?php echo $row['branch_id']; ?>";
function getloanbyBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('loan_number').reset();
	if(branch_id=='' || branch_id==null){
		var loan_store  = getDataStorefromJSON('id','name',);
		dijit.byId('loan_number').set('store', loan_store);
		return false;
	}
	dojo.xhrPost({
		url:url_loan,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value'),
		},
		handleAs:"json",
		load: function(data) {
			loan_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('loan_number').set('store', loan_store);
		    if(oldbranch_id==branch_id){
		   	 	dijit.byId('loan_number').set('value', '<?php echo $row['loan_id']; ?>');
		    }
		},
		error: function(err) {
			
		}
	});
}
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getClientByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_name').reset();
	if(branch_id=='' || branch_id==null){
		var client_store  = getDataStorefromJSON('id','name',);
		dijit.byId('client_name').set('store', client_store);
		return false;
	}
	dojo.xhrPost({
		url: url_getclient,	
		content:{ 
		    'branch_id':branch_id,
		},
		handleAs:"json",
		load: function(data) {
			
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('client_name').set('store', client_store);
		    if(oldbranch_id==branch_id){
		   	 	dijit.byId('client_name').set('value', '<?php echo $row['client_id']; ?>');
		    }
		},
		error: function(err) {
			
		}
	});
}
var url_loaninfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getLoanInfomation(){
	loan_number = dijit.byId('loan_number').get('value');
	dijit.byId('client_name').reset();
	dijit.byId('giver_name').attr('value',"");
	if(loan_number=="" || loan_number==-1){
		return false;
	}
		dojo.xhrPost({
	    url: url_loaninfo,	
		content:{ 
			'loan_id':loan_number
			},		    
		handleAs:"json",
		load: function(data) {	
			dijit.byId('client_name').attr('value',data.customer_id);
			dijit.byId('giver_name').attr('value',data.customer_name);
		},
		error: function(err) {
		}
	});
}
</script>
