<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("CHANGE_COLLTERAL_INFO"));
	$frm=$this->frm_changeCollteral;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-cubes"></i>&nbsp;<?php echo $tr->translate('CHANGE_COLLTERAL_INFO');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			    <div class="row g-3">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('adv_search');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<input id="loan_number" /><?php //echo $frm->getElement('client_name');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<input id="client_name" /><?php //echo $frm->getElement('client_name');?>
					</div>
				</div>
				<div class="row g-3">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('status_search');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dijit.form.DateTextBox");

var loan_store  = getDataStorefromJSON('id','name',);
var client_store  = getDataStorefromJSON('id','name',);
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		store: loan_store,
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
		}
	}, "loan_number");
	
	new dijit.form.FilteringSelect({
		store: client_store,
		required: false,		           
		name: "client_name",
		id: "client_name",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
		}
	}, "client_name");
	 ready(function(){
		 filterClient();
	});
	
});
function filterClient(){
	getloanbyBranch();
	getClientByBranch();
}
var url_loan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallloanbybranch')); ?>';
function getloanbyBranch(){
	
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('loan_number').reset();
	if(branch_id=='' || branch_id==null){
		var loan_store  = getDataStorefromJSON('id','name',);
		dijit.byId('loan_number').set('store', loan_store);
		return false;
	}
	
	dojo.xhrPost({
		url:url_loan,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value'),
		},
		handleAs:"json",
		load: function(data) {
			loan_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('loan_number').set('store', loan_store);
		    dijit.byId('loan_number').set('value', '<?php echo $this->search['loan_number'];?>');
		    
		},
		error: function(err) {
			
		}
	});
}
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getClientByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_name').reset();
	if(branch_id=='' || branch_id==null){
		var client_store  = getDataStorefromJSON('id','name',);
		dijit.byId('client_name').set('store', client_store);
		return false;
	}
	dojo.xhrPost({
		url: url_getclient,	
		content:{ 
		    'branch_id':branch_id,
		},
		handleAs:"json",
		load: function(data) {
			
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('client_name').set('store', client_store);
		    dijit.byId('client_name').set('value', '<?php echo $this->search['client_name'];?>');
		},
		error: function(err) {
			
		}
	});
}
</script>
