<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$rows=$this->calleteral_list;
	
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbgb = new Application_Model_DbTable_DbGlobal();
?>
<meta charset="utf-8">
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("CALLETERAL_LETTER");?></title>

<div class="reportblog">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CALLETERAL_LETTER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>	
		<style>
		.noneprint{
			display: table-cell !important; 
		}
.reff{ font-size: 20px !important; line-height:34px !important;}
		#divPrint tr td h2, #divPrint p,#divPrint pre,#divPrint span,#divPrint td span,#divPrint td{ font-size: 20px !important; line-height:34px !important;}
		#padding-left-p-2{
		 padding-left: 105px !important;	
		}
		</style>
		<div id="divPrint" style="width: 100%;">
			<style>
			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			tr td h2,p,pre,span{ font-size: 14px ; line-height:24px; font-weight: normal;  margin: 0;}
			#divPrint th{padding: 5px;}
			#divPrint ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold; list-style-type: none;}
			#divPrint td ul li{list-style: none; }
			.padding-left{
						padding-left: 18px;
						}
			</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="20%"></td>
			                	<td width="60%" align="center" valign="top" >
			                	    <span style="line-height: 30px; font-family:'Khmer OS Muol Light';">
									 	ព្រះរាជាណាចក្រកម្ពុជា
									 	<br>
										  ជាតិ សាសនា ព្រះមហាក្សត្រ
									  </span>
									  <br>
									 <img src="<?php echo $this->baseUrl()."/";?>images/agreementsign.JPG" style="width: 80px;height: 17px;"><br>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td>
			            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
			                <?php //if(empty($this->calleteral_list)){?>
			                 <tr align="center" style="font-weight:bold; padding:5px 0px; ">
			                    <td colspan="2" style="font-family:'Times New Roman','Khmer OS Battambang';text-align: left; border:1px solid #fff; border-bottom: 1px solid #000;" valign="top">
			                    	 <p style="font-weight:200; color:blue; font-family:'Times New Roman','Khmer OS Muol Light';text-decoration: underline;">បង្កាន់ដៃតម្កល់ទ្រព្យធានា</p>
								     <p style="font-weight:200; color:blue; font-family:'Times New Roman','Khmer OS Muol Light'; text-decoration: underline;">ក.អត្តសញ្ញាណ</p>
										<br />
									 <p>១.អតិថិជនឈ្មោះ <span style="font-family:'Times New Roman','Khmer OS Muol Light'; padding: 0 10px; "><?php echo $rows[0]['name_kh']?></span> <span style="font-family:'Times New Roman','Khmer OS Muol Light';">និង</span> <span style="font-family:'Times New Roman','Khmer OS Muol Light'; padding: 0 10px; "><?php echo $rows[0]['join_with'];?></span></p>
									 <p>២.ម្ចាស់កម្មសិទ្ធិឈ្មោះ...........<strong style="font-weight: bold;"><?php //echo $rows[0]['spouse_name']?></strong>..........................	<span style="font-family:'Times New Roman','Khmer OS Muol Light';">និង</span> .....................................</p>
										<br />
									 <p><span class="padding-left">&nbsp;</span>ដាក់ទ្រព្យធានាឫដាក់បញ្ចាំលើបា្រក់កម្ចី  <span style="padding:0px 10px;width:15px; height: 15px; border:1px solid #000;">&nbsp;</span> ផ្ទាល់ខ្លួន 	<span style="padding:0px 10px;margin-left:15px;width:20px; height: 15px; border:1px solid #000;">&nbsp;</span> ជំនួសឲ្យកូនបំណុល ដែលបានខ្ចីបា្រក់ ។</p> 
									 <p style=" font-weight:200; color:blue; font-family:'Times New Roman','Khmer OS Muol Light';line-height: 15px; text-decoration: underline;">ខ.ប្រភេទលិខិតសម្គាល់ទ្រព្យធានា</p>
									 <?php if(!empty($rows))foreach ($rows as $key =>$row){?>
									 	<p style="font-weight:200; font-family:'Times New Roman','Khmer OS Battambang';">
									 	<?php echo $dbgb->getNumberInkhmer($key+1);?> .<?php echo $row['collecteral_title_kh'];?>លេខៈ <span style="padding: 0 10px;"><?php echo $row['number_collecteral'];?></span> 
									 	ចុះថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($row['issue_date'])));?> ខែ<?php echo $month[date("m",strtotime($row['issue_date']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($row['issue_date'])));?> 
									 	ចេញដោយ 
									 	<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $row['note'];?></span>។
									 	</p>
									 <?php }?>
			                    </td>
			                </tr>
			                 <tr>
			                	<td align="center" valign="top" width="50%">
			                	    <p> 
										ថ្ងៃទី..........ខែ............ឆ្នាំ..............
			                	  	</p> 
			                		<p>ស្នាមមេដៃស្តាំអ្នកទទួលប្លង់</p>
									<p style="height:70px;"></p>
									<p><span style="width: 85%; display: inline-block; border-bottom: dashed 1px #000;">&nbsp;</span></p>
									
									<p> 
										ថ្ងៃទី..........ខែ............ឆ្នាំ..............
			                	  	</p> 
			                		<p>ស្នាមមេដៃស្តាំអ្នកប្រគល់ឲ្យប្លង់វិញ</p>
									<p style="height:70px;"></p>
									<p><span style="width: 85%; display: inline-block; border-bottom: dashed 1px #000;">&nbsp;</span></p>
									<br />
			                	</td>
			                	<td align="center" valign="top">
			                	     <p>ថ្ងៃទី..........ខែ............ឆ្នាំ..............</p> 
			                	     <p>ស្នាមមេដៃស្តាំអ្នកប្រគល់ប្លង់</p>
									 <p style="height:70px;"></p>
									<p><span style="width: 85%; display: inline-block; border-bottom: dashed 1px #000;">&nbsp;</span></p>
									
									 <p>ថ្ងៃទី..........ខែ............ឆ្នាំ..............</p> 
			                	     <p>ស្នាមមេដៃស្តាំអ្នកទទួលយកប្លង់វិញ</p>
									 <p style="height:70px;"></p>
									<p><span style="width: 85%; display: inline-block; border-bottom: dashed 1px #000;">&nbsp;</span></p>
									<br />
			                	</td>
			                </tr>
			                <tr>
			                	<td colspan="2" style="border-left: solid 1px #fff; border-right: solid 1px #fff;">
			                	   &nbsp;
			                	</td>
			                </tr>
			                <tr>
			                	<td align="center" valign="top" height="200px">
			                	   
			                	</td>
			                	<td align="center" valign="top">
			                	
			                	</td>
			                </tr>
			                <tr>
			                	<td colspan="2" style="border: 1px solid #fff;border-top: 1px solid #000;" valign="top">
			                	១-ម្ចាស់កម្មសិទ្ធិត្រូវរក្សាបង្កាន់ដៃនេះសម្រាប់ដកយកប័ណ្ណកម្មសិទ្ធិរបស់ខ្លួន<br />
								២-មានតែអ្នកដែលបានដាក់បញ្ចាំទេទើបមានសិទ្ធិដកយកប័ណ្ណកម្មសិទ្ធនេះវិញ <br />
								៣-ម្ចាស់កម្មសិទ្ធិអាចយកប័ណ្ណក្មសិទ្ធិវិញលុះត្រាតែសងរួចបំណុល
			                	 </td>
			                </tr>
			              </table>
			    	</td>
			    </tr>
			</table>
			</div>
</div>
