<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$rpt_client = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client'));
	$rpt_callteral = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral'));
	$rpt_change_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-change'));
	$rpt_client_blacklist = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-clientblacklist'));
	$rpt_return_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-returncollteral'));
?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  </style>
	<title><?php echo $tr->translate("GROUPMEMBER");?></title>
	<div class="card">
		<div class="card-content collapse show">
			<div class="card-box report-list">
				<h3 style="font-family:'khmer os muol light';font-size:14px;text-align: center; color: #666;padding:2px 0;"><?php echo $tr->translate("GROUPMEMBER");?></h3><hr>
				<!--border-bottom:2px solid #F1F1F1;-->
				<div class="row top_tiles">
			
				   <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $rpt_client;?>">
						<div title="<?php echo $tr->translate("LIST_OF_CLIENT");?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate("LIST_OF_CLIENT");?></h3>
						</div>
						</a>
			        </div>
					
					<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $rpt_callteral;?>">
						<div title="<?php echo $tr->translate("REPORT_CALLETERAL");?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate("REPORT_CALLETERAL");?></h3>
						</div>
						</a>
			        </div>
					
					<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $rpt_change_call;?>">
						<div title="<?php echo $tr->translate("REPORT_CHANGE_CALLETERAL");?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate("REPORT_CHANGE_CALLETERAL");?></h3>
						</div>
						</a>
			        </div>
					
					<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $rpt_return_call;?>">
						<div title="<?php echo $tr->translate("REPORT_RETURN_CALLETERAL");?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate("REPORT_RETURN_CALLETERAL");?></h3>
						</div>
						</a>
			        </div>
					
					<!--
					<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php //echo $rpt_client_blacklist;?>">
						<div title="<?php //echo $tr->translate("REPORT_CLIENT_BLACKLIST");?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php //echo $tr->translate("REPORT_CLIENT_BLACKLIST");?></h3>
						</div>
						</a>
			        </div>
					-->
				</div>
			</div>
		</div>
	</div>
  <div style="clear: both;"></div>