<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$frm=$this->frm_returnCollteral;
?>

<head>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_RETURN_CALLETERAL");?></title>
</head>
<body> 
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_RETURN_CALLETERAL');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form action=""	dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="row g-3">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('adv_search');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('branch_id');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('start_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('end_date');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('btn_search');?>
               </div>
            </div>
        </div>
     </form>
     <div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 20px;font-size: 12px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			th{padding: 5px;}
			
			table.content-data { page-break-inside:auto }
			table.content-data  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;" >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_RETURN_CALLETERAL");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php if(!empty($this->result['start_date'])){?><?php echo date("d-M-Y",strtotime($this->result['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->result['end_date']));}?></h2>
                	</td>
                    <td width="20%"></td>
                </tr> 
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" class="content-data" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
               <?php if(empty($this->calleteral_list)){?>
               <thead>
                <tr>
                	<td colspan="5">&nbsp;<span ><?php echo $tr->translate("CUSTOMER_NAME");?> </span></td>
                </tr>
                 <tr class="style" align="center" style="font-weight:bold; line-height: 14px; background: #ccd9ff;  font-size:12px; padding:5px 0px; ">
                    <th><?php echo $tr->translate("NUM");?> </th>
                    <th><?php echo $tr->translate("BRANCH_NAME");?> </th>
                    <th><?php echo $tr->translate("GIVER_NAME");?> </th>   
                    <th><?php echo $tr->translate("RECEIVER_NAME");?> </th>                
                    <th><?php echo $tr->translate("COLETERAL_TYPE");?> </th>
                    <th><?php echo $tr->translate("NUMBER_COLLTERAL");?> </th>
                    <th><?php echo $tr->translate("ISSUE_DATE");?> </th>
                    <th><?php echo $tr->translate("DATE");?> </th>
                    <th><?php echo $tr->translate("NOTE");?> </th>
                </tr>
                </thead>
            	<?php }?>
                   <?php  
                    $id='';
	               if(!empty($this->calleteral_list)) foreach($this->calleteral_list as $key =>$row){

	              
               ?>
                <?php 
                if($id!=$row['client_id']){
                ?>
                <?php if($key>0){?>
                <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                
                <?php } ?>
             <?php ?>
             <thead>
                <tr>
                	<td colspan="9">&nbsp;<span style="text-align:center; font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("CUSTOMER_NAME");?> </span><?php  echo $row['client_code']." - ".$row['owner_name']; ?></td>
                </tr>
				
                 <tr class="style" align="center" style="font-weight:bold; line-height: 14px; background: #ccd9ff;  font-size:12px; padding:5px 0px; ">
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUM");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("GIVER_NAME");?> </td>                   
                    <td style="padding:5px 0px;"><?php echo $tr->translate("RECEIVER_NAME");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("COLETERAL_TYPE");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUMBER_COLLTERAL");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("ISSUE_DATE");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("DATE");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NOTE");?> </td>
                </tr>
				</thead>
                <?php }
               
                ?>
					<tr class="style" >
						<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['giver_name']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['receiver_name'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['collecteral_type']." - ".$row['re_owner_type'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['number_collteral']?>&nbsp;</td>
						<td>&nbsp;<?php echo date('d/m/Y',strtotime($row['issue_date'])) ;?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['date']?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['note']?>&nbsp;</td>
					</tr>
				<?php 
				$id = $row['client_id'];
}?>
              <br />
             
    	</td>
    </tr>
</table>
<br />
<?php echo $this->footerReport;?>
</div>
</div>
