<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_village;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$frms=$this->frm_client;
?>
<title><?php echo $tr->translate("REPORT_CLIENT");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_CLIENT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form action=""	dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('branch_id');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frms->getElement('province');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<input id="district" >
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<input id="commune" >
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('status');?>
               </div>
            </div>
        </div>
        <div class="card-box">
			<div class="form-group">
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('start_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('end_date');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement("btn_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
               </div>
            </div>
        </div>
     </form>
     <div id="divPrint">
		<style>
			.style{
				line-height: 20px;font-size: 9px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			th{padding: 3px 5px;}
			
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;"  >
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
		            	<tr>
		                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
		                	<td width="60%" valign="top">
		                	<h2 style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></h2>
		                	<h2 style="text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_CLIENT");?></h2>
		                	<h2 style="text-align:center; font-size:13px;"><?php if(!empty($this->result['start_date'])){?><?php echo date("d-M-Y",strtotime($this->result['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->result['end_date']));}?></h2>
		                	</td>
		                    <td width="20%"></td>
		                </tr>  
					</table>
				</td>
			</tr>
		</table>
		<table id="exportExcel"  width="100%" border="1" style="border-collapse:collapse;font-size: 10px;" bordercolor="black">   
	    	<thead>
				<tr style="background: #ccd9ff;">
		    		<th colspan="12"><?php echo $tr->translate("CLIENT_INFO");?></th>
		    		<th colspan="3"><?php echo $tr->translate("Join Account Info");?></th>
		    		<th rowspan="2"><?php echo $tr->translate("DATE");?></th>
		    	</tr> 	
		    	<tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; background: #ccd9ff; font-size:12px; padding:5px 0px; ">
			       <th><?php echo $tr->translate("NUM");?></th>
			       <th><?php echo $tr->translate("BRANCH_NAME");?></th>
			       <th><?php echo $tr->translate("CLIENT_NUM");?></th>
			       <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
			       <th><?php echo $tr->translate("SEX");?></th>
			       <th><?php echo $tr->translate("DATOFBIRTH");?></th>
			       <th><?php echo $tr->translate("SITU_STATUS");?></th>
			       <th><?php echo $tr->translate("NATIONAL_ID");?></th>
		           <th><?php echo $tr->translate("NUMBER");?></th>
		           <th><?php echo $tr->translate("JOB_TYPE");?></th>
			       <th><?php echo $tr->translate("PHONE");?></th>
			       <th width="150px;"><?php echo $tr->translate("ADDRESS");?></th>
			       <th><?php echo $tr->translate("JOIN_WITH");?></th>
			       <th><?php echo $tr->translate("NATIONAL_ID");?></th>
			       <th><?php echo $tr->translate("NUMBER");?></th>       
		          </tr>
	          </thead>
          <?php if(!empty($this->client_list)) foreach($this->client_list as $key =>$row){?>
				   <tr style="font-size: 9px;line-height: 14px;" align="center">	   
					   <td><?php echo $key+1; ?></td>
				       <td ><?php echo $row['branch_name']?></td>
				       <td style="white-space: nowrap;" ><?php echo $row['client_number']?></td>
					   <td align="left"><?php echo $row['client_name'];?></td>
					   <td ><?php echo $row['sex']?></td>
					   <td>&nbsp;<?php echo date("d/m/Y",strtotime($row['dob']));?></td>
					   <td>&nbsp;<?php echo $row['situation']?></td>
			           <td>&nbsp;<?php echo $row['doc_name']?></td>
			           <td>&nbsp;<?php echo $row['id_number']?></td>
			           <td>&nbsp;<?php echo $row['job']?></td>
					   <td><?php echo $row['phone']?></td>
					   <td style="line-height:15px;text-align: left">&nbsp;<?php echo "#".$row['house'].",St".$row['street'].", ".$row['village_name'].", ".$row['com_name'].", ".$row['dis_name'].", ".$row['pro_name']?></td>
					   <td><?php echo empty($row['join_with'])?"-":$row['join_with']?></td>
					   <td><?php echo empty($row['joint_doc_type'])?"-":$row['joint_doc_type']?></td>
					   <td><?php echo empty($row['join_nation_id'])?"-":$row['join_nation_id']?></td>
					   <td><?php echo date("d/m/Y",strtotime($row['create_date']))?></td>			  
				   </tr>
		  <?php }?>
    	</table>
    	<br />
	  	<?php echo $this->footerReport;?>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dijit.form.DateTextBox");
dojo.ready(function(){
	dijit.byId('province').attr('value',<?php echo $this->result['province'];?>);	
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		pro_id:"<?php echo $this->result['province'];?>"
	},            
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	value: "<?php echo $this->result['district'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district");
	

	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		//district_id: "-1"
		district_id: "<?php echo $this->result['district'];?>"
	},            
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	value: "<?php echo $this->result['commune'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			filterVillage();
  }
	}, "commune");

	var village_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->village));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: village_data}),
	autoComplete: true,
	query: {
		commune_id:"<?php echo $this->result['commune'];?>"
	},            
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	value: "<?php echo empty($this->result['village'])?0:$this->result['village'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
}
	}, "village");

	
	
});
function filterDistrict(){
	dijit.byId('district').query.pro_id = dijit.byId('province').get('value');
}
function filterCommune(){
	dijit.byId('commune').query.district_id = dijit.byId('district').get('value');
}
function filterVillage(){
	id =dijit.byId('commune').get('value');
	dijit.byId('village').query.commune_id = dijit.byId('commune').get('value');
}

</script>