<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Edit Label"));
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom" style="text-align: left;">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Edit Label');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="<?php echo $this->url(array('module'=>'setting','controller'=>'Label','action'=>'edit')); ?>" method="post" enctype="application/x-www-form-urlencoded" >
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label bold col-md-12 col-sm-12 col-xs-12 col-xs-12" for="first-name"><?php echo $tr->translate("Label Name");?> :
	                   </label>
	                </div>
	                <div class="row g-3">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<input type="text" required="true" name="label_name"​  
															dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs['keyValue'];?>"
															missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពិស្ដាជាខ្មែរ!" class="fullside" />
							<input type="hidden" name="id" value="<?php echo $this->rs['code'];?>"  />
	                   </div>
	                </div>
	                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	                	<input type="submit" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 
		    		</div>
	            </div>
	        </div>
		</form>
    </div>
</div>
