<?php
	 $tr = Application_Form_FrmLanguages::getCurrentlanguage();	
    echo $this->headTitle($tr->translate('TRANSFER_CO_CO')); 
	$frm = $this->frm_transfer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
.form-group.noteblog {
    background: #e6eefc;
    padding: 10px;
    border: solid 1px #eee;
}
.form-group.noteblog ul {
    padding: 0;
    margin: 0;
    list-style-type: none;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-exchange " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TRANSFER_CO_CO');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferco','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
  			if(this.validate()) {
   				 if(dijit.byId('branch_name').get('value')==''){
     				alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> ');
     				dijit.byId('branch_name').focus();
     				return false;
   				 }
				if(dijit.byId('formc_co').get('value')==''){
					 alert('<?php echo $tr->translate("Please Select CO Name");?> ');
     				 dijit.byId('formc_co').focus();
    				 return false;
   				}
				if(dijit.byId('to_co').get('value')==''){
    	 			alert('<?php echo $tr->translate("Select To CO");?> ');
     				dijit.byId('to_co').focus();
     				return false;
   				}
				if(dijit.byId('formc_co').get('value')== dijit.byId('to_co').get('value')){
					alert('<?php echo $tr->translate("Can not transfer the same co");?> ');
					dijit.byId('to_co').focus();
					return false;
				}
    			loadingBlock();
    			return true;
   			}else {
    			return false;
  			 }
		</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BRANCH_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('branch_name');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_CO");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('formc_co');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('Note');?>
	                   </div>
	                </div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CO_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TO_CO");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('to_co');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('Date');?>
	                   </div>
	                </div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
	             	<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("សម្គាល់");?> 
	                   </label>
	                </div>
					<div class="form-group noteblog">
			        	<span>&nbsp;រាល់ទិន្នន័យទាំងអស់នឹងត្រូវបានផ្ទេរពី COចាស់មក CO ថ្មីដូចជា ៖</span>
		        		<ul >
				        	<li>១. ប្រាក់បានបង់ពីមុន ទាំងអស់</li>
				        	<li>២. កម្ចីដែលបានទំលាក់ទាំងអស់</li>
				        	<li>៣. តារាងកាលវិភាគដែលត្រូវបង់ ទាំងអស់</li>
			        	</ul>
					</div>
				</div>
	         </div>
	         <div class="card-box">
	         	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" id="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
						<input type="submit" value="រក្សាទុក" name="btn_save" id="btn_save" label="<?php echo $tr->translate('SAVENEW');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		    		</div>
	         </div>
		</form>
    </div>
 </div>
 
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
require(["dojo/ready"], function(ready){
	ready(function(){
		 var branch_id = dijit.byId('branch_name');
		 branch_id.on('change', function(evt) {
			 getAllCo(branch_id);
		});
	});
});
var url_co = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-coname')); ?>';
function getAllCo(branch_id){
	 var branch_id = dijit.byId('branch_name').get('value');
	dojo.xhrPost({
		url:url_co,	
		content:{ 
			'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			co_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('formc_co').set('store', co_store);
		    dijit.byId('to_co').set('store', co_store);
		},
		error: function(err) {
		}
	});
}
function getClientInfo(){}
</script>
