
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("TRANSFER_CO_CO"));
$frm = $this->frm_transfer;

?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<section class="inputmask" >
	<div class="row">
    	<div class="col-sm-12">
        	<div class="card pb-10 pt-10 pl-10 pr-10">
               	<div class="card-content collapse show">
               		<div class="card-box">
						<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferco','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
						   	<table width="100%">
						  	<tr>
						  	    <td><?php  echo $frm->getElement('note');?></td>
						  		<td><?php  echo $frm->getElement('branch_name');?></td>
						  		<td><?php  echo $frm->getElement('co_code');?></td>	
						  		<td><?php  echo $frm->getElement('name_co');?></td>
						  	</tr>
						  	<tr>
						  		<td><?php echo $frm->getElement('start_date');?></td>
						  		<td><?php echo $frm->getElement('end_date');?></td>
						  		 <td><?php echo $frm->getElement('status');?></td>
						  		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
						  	</tr>
						  </table>
						</form>
					</div>
					<div class="card-box">
						<?php echo $this->list; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
