<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DISTRICT'));
?>	
<?php  $frm= $this->frm_district;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
 			<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_DISTRICT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province_name').get('value')==''){
				 alert('<?php echo $tr->translate('Please Select Province');?>');
				 dijit.byId('province_name').focus();
                 return false;
                }
				loadingBlock();
				dijit.byId("save_close").set("disabled",true);
				dijit.byId("save_new").set("disabled",true);
				return true;
			} else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("code");?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT_NAME");//$tr->translate("DISTRICT_NAME_KHMER");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("district_namekh");?>
	                   </div>
	                </div>
	                <!-- 
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("DISTRICT_NAME_EN");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  //echo $frm->getElement('district_name');?>
	                   </div>
	                </div>
	                 -->
	                 <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('province_name');?>
	                   </div>
	                </div>
	                <div class="row g-3">
		                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		                	<input type="reset" iconClass="dijitIconClear" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button"/>
							<input type="button" onclick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
							<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
			    		</div>
		    		 </div>
	            </div>
	         </div>
		</form>
	</div>
</div>
<script>
function submitDataClose(){
	if(dijit.byId('province_name').get('value')==''){
		 dijit.byId('province_name').focus();
		 alert('<?php echo $tr->translate('Please Select Province');?>');
       return false;
      }
	
	if(dijit.byId('add_techer').validate()) {
		loadingBlock();
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_techer"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/other/district";
			},
			error: function(e) {
			}
		});
	}
}
</script>