<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_DISTRICT'));
?>	
<?php  $frm= $this->frm_district;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
 			<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_DISTRICT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
               		if(dijit.byId('province_name').get('value')==''){
				 		alert('<?php echo $tr->translate('Please Select Province');?>');
                 		return false;
                	}
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("code");?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT_NAME");//$tr->translate("DISTRICT_NAME_KHMER");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("district_namekh");?>
	                   		<?php  echo $frm->getElement('id');?>
	                   </div>
	                </div>
	               <!-- 
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("DISTRICT_NAME_EN");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  //echo $frm->getElement('district_name');?>
	                   </div>
	                </div>
	                -->
	                 <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('province_name');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $frm->getElement('status');?>
	                   </div>
	                </div>
	                <div class="row g-3">
		                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		                	<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
							<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
			    		</div>
		    		 </div>
	            </div>
	         </div>
		</form>
	</div>
</div>

