  <?php 
	  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	  $session_user=new Zend_Session_Namespace(SYSTEM_SES);
	  $url_report=$session_user->report_url;
  ?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 60px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <title><?php echo $tr->translate("RPT_PAWNSHOP");?></title>
<div class="card">
	<div class="card-header text-center">
		<h5 class="card-title mb-0"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('RPT_PAWNSHOP');?></h5>
    </div>
	<div class="card-body">
		<div class="row  report-list">
			<?php
				$db_user=new Application_Model_DbTable_DbUsers();
				$url_report=$db_user->getAclReport(1,'pawn');
				if(!empty($url_report)){
				foreach($url_report as $rs){
					if($rs['action']=='rpt-paymentschedules' || $rs['action']=='index'  || $rs['action']=='paymenthistory'){continue;}
				?>
				<div class="col-xs-12 col-sm-6 col-lg-3 mb-1 px-2">
					<a title="<?php echo $tr->translate(strtoupper($rs['label']));?>" href="<?php echo $this->url(array("module"=>'report',"controller"=>'pawn','action'=>$rs['action']));?>">
						<div class="card card-border-shadow-primary">
						  <div class="card-body">
							<div class="d-flex align-items-center mb-2 pb-1">
							  <div class="avatar me-2">
								<span class="avatar-initial rounded bg-label-primary"><i class="ti ti-license ti-md"></i></span>
							  </div>
							  <h4 class="ms-1 mb-0"><?php echo $tr->translate(strtoupper($rs['label']));?></h4>
							</div>
						  </div>
						</div>
					</a>
				</div>
			<?php 
					}	
				}	
			?>
		</div>
	</div>
</div>

	
  
  <div style="clear: both;"></div>