<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PAY_OFF"));
	$frm = $this->frm_search;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
<form method="post">
	<table style="font-family: 'Khmer OS Content';width:100%;margin: 0 auto;" >
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id');?></td>
			<td><?php echo $frm->getElement('members');?></td>
			<td><?php echo $frm->getElement('product_id');?></td>
		</tr>
		<tr>
		    <td><?php echo $frm->getElement('currency_type');?></td>
			<td><?php echo $frm->getElement('start_date');?></td>
			<td><?php echo $frm->getElement('end_date');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
</form>
	<div id="divPrint">
	<style>
	.style{
		line-height: 20px;font-size: 12px !important;
		font-family: 'Khmer OS Battambang';
	}
	.style1:hover{ background: #ccc;}
	table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
	table { page-break-inside:auto }
	  tr{ page-break-inside:avoid; page-break-after:auto; }
	#header {
	  display: table-header-group;
	  page-break-inside:avoid; page-break-after:auto;
	}
	thead tr td{
		text-align: center;
		font-weight: bold;
	}
	</style>
	<table width="100%">
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
	                	<td width="60%" valign="top">
	                	   <ul>
	                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
	                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_PAYOFF");?></li>
	                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
	                		</ul>
	                	</td>
	                    <td width="20%"></td>
	                </tr> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%">
	                			<tr class='style'>
	                				<td class="style" style="font-size: 7px;">
	                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
										<br /><?php echo $tr->translate("TEL_COMPANY");?>
	                				</td>
	                				<td width="65%"></td>
	                			</tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; white-space: nowrap;" cellspacing="0">
	                <thead>
					<tr class="style" bgcolor="#ccc" align="center" style="font-weight:bold; background:#ccd9ff; line-height: 14px; padding:3px 0px; ">
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAWN_NUMBER");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td> 
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("LEVEL");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td> 
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("INTEREST_RATE");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
	                    <td colspan="5" ><?php echo $tr->translate("TOTAL_PAYMENTED");?>&nbsp;</td>
	                    <td rowspan="2" ><?php echo $tr->translate("RECEIPT");?>&nbsp;</td>
	                    <td rowspan="2"><?php echo $tr->translate("TOTAL_PAYMENTED");?>&nbsp;</td>
	                    <td rowspan="2"><?php echo $tr->translate("DAY_PAYMENT");?>&nbsp;</td>
	                </tr>
	                <tr class="style" bgcolor="#ccc" style="background:#ccd9ff;">
	                	<td>&nbsp;<?php echo $tr->translate("OS_AMOUNT");?>&nbsp;</td>                    
	                    <td>&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>                    
	                    <td>&nbsp;<?php echo $tr->translate("SERVICE CHARGE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("PAYMENT");?>&nbsp;</td>
	                </tr>
	                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$amt_r6 = 0;$amt_loanday = 0;
	                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$amt_d6 = 0;$amt_loanweek = 0;
	                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$amn_b6 = 0;$amt_loanmonth = 0;
	                ?>
	                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
	                <?php 
	//                 		if($rs['pay_term']==1){
	//                 			$amt_loanday = $amt_loanday+1;
	//                 		}elseif($rs['pay_term']==2){
	//                 			$amt_loanweek = $amt_loanweek+1;
	//                 		}else{
	                			$amt_loanmonth = $amt_loanmonth+1;
	//                 		}
			               if($rs['curr_type']==1){
			               		$amt_r1 = $amt_r1+$rs['principal_paid'];
			               		$amt_r2 = $amt_r2+$rs['interest_paid'];
			               		$amt_r3 = $amt_r3+$rs['penalize_paid'];
			               		$amt_r5 = $amt_r5+$rs['service_paid'];
			               		$amn_r4 = $amt_r5+$rs['total_paymentpaid'];
			               }elseif($rs['curr_type']==2){
								$amt_d1 = $amt_d1+$rs['principal_paid'];
								$amt_d2 = $amt_d2+$rs['interest_paid'];
								$amt_d3 = $amt_d3+$rs['penalize_paid'];
								$amt_d5 = $amt_d5+$rs['service_paid'];
								$amt_d4 = $amt_d5+$rs['total_paymentpaid'];
			               }else{
			               		$amn_b1 = $amn_b1+$rs['principal_paid'];
								$amn_b2 = $amn_b2+$rs['interest_paid'];
								$amn_b3 = $amn_b3+$rs['penalize_paid'];
								$amn_b5 = $amn_b5+$rs['service_paid'];
								$amn_b4 = $amn_b5+$rs['total_paymentpaid'];
			               }
	               ?>
	                <tr class="style style1" style="font-family: 'Khmer OS Content';">
	               		<td style="font-size: 12px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["client_number"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["client_name"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["loan_level"];?></td>
	               		<td style="font:bolder 11px Arial ;text-align: center;​">&nbsp;&nbsp;<?php echo number_format($rs["total_capital"],2).''.$rs['currency_type'];?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;<?php echo $rs['total_duration'].$rs['term_type'];?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center; white-space:nowrap; ">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center; white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
	               		<td style="font-size: 10px;">&nbsp;&nbsp;<?php echo number_format( $rs["principal_amount"],2).' '.$rs['currency_type'];?></td>               		
	               		<td style="font-size: 10px;">&nbsp;&nbsp;<?php echo number_format($rs["interest_amount"],2).' '.$rs['currency_type'];?></td>
	               		<td style="font-size: 10px;">&nbsp;&nbsp;<?php echo number_format($rs["penelize"],2).' '.$rs['currency_type'];?></td>               		
	               		<td style="font-size: 10px;">&nbsp;&nbsp;<?php echo number_format($rs["service_chargeamount"],2).' '.$rs['currency_type'];?></td>
	               		<td style="font-size: 10px; border-right:3px double #000;">&nbsp;&nbsp;<?php echo number_format($rs["total_payment"],2).' '.$rs['currency_type'];?></td>
	               		<td style="font-size: 10px;">&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
	               		<td style="font-size: 10px;">&nbsp;&nbsp;<?php echo number_format($rs["total_paymentpaid"],2).' '.$rs['currency_type'];?></td>
	               		<td style="font-size: 10px;text-align: center; white-space:nowrap;"><?php echo date("d-M-Y",strtotime($rs["date_payment"]));?></td>
	                </tr>
	                <?php }?>
					</thead>
	            </table>
	            <br /><br />
	             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
	                 <tr class="style style1" bgcolor="#ccc"  style="font-weight:bold; background:#ccd9ff; line-height: 24px; text-align: center;">
	                    <td><?php echo $tr->translate("FOR_LOAN_TYPE");?></td>
	                    <td><?php echo $tr->translate("CURRENT_TYPE");?></td>
	                    <td><?php echo $tr->translate("TOTAL_PRINCEPLE");?></td>                    
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
	                    <td><?php echo $tr->translate("TOTAL_PENELIZE");?></td>
	                    <td><?php echo $tr->translate("TOTAL SERVICE CHARGE");?></td>
	                    <td><?php echo $tr->translate("TOTAL_PAYMENTED");?></td>
	                   <!--  <th><?php //echo $tr->translate("TOTAL_PAYMENT");?></td> -->
	                </tr>
	                 <tr class="style style1" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
	                     <td>&nbsp;<?php echo $tr->translate("DAY")." = ".$amt_loanday;?></td>
	                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1+$amt_d2+$amt_d3+$amt_d5,2);?>&nbsp;</td>
	                 </tr>
	                 <tr class="style style1" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
	                    <td>&nbsp;<?php echo $tr->translate("WEEK")." = ".$amt_loanweek?></td>
	                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1+$amt_r2+$amt_r3+$amt_r5,2);?>&nbsp;</td>
	                </tr>
	                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
	                   <td>&nbsp;<?php echo $tr->translate("MONTH")." = ".$amt_loanmonth;?>&nbsp;</td>
	                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
	                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
	                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
	                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
	                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
					   <td>&nbsp;&nbsp;<?php echo number_format($amn_b1+$amn_b2+$amn_b3+$amn_b5,2);?>&nbsp;</td>
	                </tr>
	              </table>
	               <br />
	               <table align="center" width="100%">
					   <tr >
				        <td style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></td>
				        <td></td>
				        <td style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></td>
				        <td></td>
				        <td style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
				</table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>