<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('REPORT_PAWN_WRITE_OFF'));
 $frm = $this->frm_loan;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('REPORT_PAWN_WRITE_OFF');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('adv_search');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('members');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('product_id');?>
				   </div>
				</div>
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px;}
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				
				table.content-data { page-break-inside:auto }
				table.content-data  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
				table.tb-footer{
					font-family: 'Times New Roman','Khmer OS Battambang'; 
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:12px;
					width:100%;
				}
				table.tb-footer tr.style-head{
					line-height: 24px; 
					text-align: center; 
					background: #ccd9ff;
				}
				.border_bottom {
					border-bottom: 1px solid #000;
				}
			</style>
			<table width="100%" >
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
							<tr>
								<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
								<td width="60%" valign="top">
									<ul>
										<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_PAWN_WRITE_OFF");?></li>
										<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
							<tr>
								<td colspan="3">
									<table width="100%">
										<tr class='style'>
											<td class="style" style="font-size: 10px;">
												<?php echo $tr->translate("ADDRESS_COMPANY");?>
												<br /><?php echo $tr->translate("TEL_COMPANY");?>
											</td>
											<td width="65%"></td>
										</tr>
									</table>
								  </td>
							   </tr>   
						</table>
					</td>
				</tr>
				<tr>
					<td id="exportExcel">
						<table class="content-data" border="1"  cellspacing="0">
							<?php 
								  $amt_r = 0;
								  $amt_d = 0;
								  $amn_b = 0;
								  $count_d = 0;$count_r=0;$count_b=0;
							?>
							<thead>
								<tr class="style-head" >
									<td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PHONE");?> / <?php echo $tr->translate("ADDRESS");?>&nbsp;</td> 
									<td>&nbsp;&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?></td> 
									<td><?php echo $tr->translate("INTEREST RATE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PAWN_DATE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PAWN_ENDDATE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PRODUCT_NAME");?>&nbsp;</td> 
									<td>&nbsp;<?php echo $tr->translate("EST_VALUE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("DATE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td> 
								</tr>
							</thead>
							<?php 
								$record = 0; if(!empty($this->LoanCollectionco_list))
								foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
							<?php 
							  if($rs["curr_type"]==1){//reil
								$count_r=$count_r+1;
								$amt_r = $amt_r+$rs["loan_amount"];
							  }elseif($rs["curr_type"]==2){
								$amt_d = $amt_d+$rs["loan_amount"];
								$count_d=$count_d+1;
							  }else{
								$amn_b = $amn_b+$rs["loan_amount"];
								$count_b = $count_b+1;
							  }
							?>
								<tr class="style-rowdata hover">
									<td align="center">&nbsp;<?php echo $record; ?>&nbsp;</td>
									<td style="font-size: 12px;">&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
									<td style="font-size: 12px;">&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
									<td style="font-size: 12px;">&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
									<td style="line-height: 18px; white-space: normal !important;max-width: 150px;width: 150px;padding: 5px;overflow-wrap: break-word;">
									<?php 
											echo $rs["phone"];
											echo empty($rs['village_name'])?"":",".$rs['village_name'];
											echo empty($rs['commune_name'])?"":",".str_replace("Commune","",$rs['commune_name']);
											echo empty($rs['district_name'])?"":",".$rs['district_name'];
											echo empty($rs['province_en_name'])?"":",".$rs['province_en_name'];
										?>
									</td>
									<td align="center">&nbsp;<strong><?php echo number_format($rs["loan_amount"],2);?></strong>&nbsp;<?php echo $rs['currency_type'];?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo $rs['total_duration'].$rs['term_type'];//$rs['pay_term'];?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
									<td >&nbsp;<?php echo $rs["product_name"];?>&nbsp;</td>
									<td style="text-align: center;background:#eeeeee;"><strong><?php echo $rs["est_amount"];?></strong></td>
									<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_dach"]));?>&nbsp;</td>
									<td >&nbsp;<?php echo $rs["note_dach"];?>&nbsp;</td>
								</tr>
							<?php }?>
						 </table>
						 <br />
						<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
							<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td align="right">&nbsp;</td>
								<td></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("PAWN_NUMBER");?></span>&nbsp;</td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCEPLE");?></span></td>
								<td align="right">&nbsp;</td>
							</tr>
							<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_d;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							</tr>
							<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("REILS");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_r;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							</tr>
							<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("BATH");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_b;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							</tr>
						 </table>
						<br />
						<?php echo $this->footerReport;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>