<?php 
	$filter = $this->frm_search;
	$dayin_khmer = $this->day_inkhmer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
	$db = new Report_Model_DbTable_DbLoan();
	$tran = $this->tran_schedule;
	$client = $this->client;											
?>
<?php  
	$end_dat=$this->date_show;
?>
<?php 
	$db_keycode = new Application_Model_DbTable_DbKeycode();
	$key_code= $db_keycode->getSystemSetting(9);
	$free_day=$key_code['value'];
	
	$keyvalue = $db_keycode->getKeyCodeMiniInv();
	$interest_penalty = $keyvalue['interst_late'];
?>
<style>
	.hover:hover{ background:#ccc;}
	table.content-data thead tr.style-head,
	table.tb-footer tr.style-head {
	   font-weight: bold !important;
	}
</style>
<title><?php  echo $tr->translate("RPTPAWNSHOPCOLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPTPAWNSHOPCOLLECT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('adv_search');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('branch_id');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('members');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('start_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('end_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
	</form>
	<div id="divPrint">
		<style>
			.style{
				line-height: 20px;font-size: 13px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			table tr td ul li{list-style: none;line-height: 25px;}
			th{padding: 5px;}
			table.content-data { page-break-inside:auto }
			table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			thead tr td{
				text-align: center;
			}
			table.content-data{
				border-collapse:collapse;
				width:100%;
				border:1px solid #000; 
				font-family:'Times New Roman','Khmer OS Battambang';
				font-size:13px;
				white-space: nowrap;
				margin:0 auto;
			}
			table.content-data thead tr.style-head {
			   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #ccd9ff;
				text-align: center;
			}
			table.content-data tr.style-rowdata {
				font-size:12px; 
				height: 23px;
			}
			
			table.tb-footer{
				font-family: 'Times New Roman','Khmer OS Battambang'; 
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:12px;
				width:100%;
			}
			table.tb-footer tr.style-head{
				line-height: 24px; 
				text-align: center; 
				background: #ccd9ff;
			}
			.border_bottom {
				border-bottom: 1px solid #000;
			}
		</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0 auto;padding:0px; border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
			                	<td width="60%" valign="top">
			                	<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("RPTPAWNSHOPCOLLECT");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:inherit;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("D-d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
		                		</ul>
		                    </td>
			                    <td width="20%"><strong style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><label id="lbl_customer"></label></strong></td>
			                </tr>
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td id="exportExcel">
			             <table class="content-data" border="1"​  cellspacing="0">
			             <thead>
			                 <tr class="style-head" >
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("SPOUSE_NAME");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PRODUCT");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PHONE")." / ".$tr->translate("ADDRESS");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAID_TIME");?>&nbsp;</td>
			                    <td colspan="3">&nbsp;<?php echo $tr->translate("PAYMENT");?>&nbsp;</td>
			                    <td rowspan="2"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
				                
				                <td rowspan="2">&nbsp;<?php echo $tr->translate("LATE_DAY");?>&nbsp;</td>
			                 ​​​	<td rowspan="2">&nbsp;<?php echo $tr->translate("LATE");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAY_DATE");?>&nbsp;</td>
			                </tr>
			                <tr class="style-head" >
			                    <td><?php echo $tr->translate("OS_AMOUNT");?></td>
			                    <td><?php echo $tr->translate("INTEREST");?></td>
			                    <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
			                 </tr>
			               </thead> 
			                <?php $amt_r1 = 0;$tir = 0;
				                $amt_r2 = 0;
				                $amt_r3 = 0;
			                	$amt_r4 = 0;
			                	$amt_r5 = 0;
			                	$total_r=0;
		                	    $amt_d1 = 0;$amt_d2 = 0;
		                	    $amt_d3 = 0;$amt_d4 = 0;
		                	    $amt_d5 = 0;$total_b=0;
		                	    $amn_b1 = 0;
		                	    $amn_b2 = 0;$amt_b1=0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
		                	  
		                	    $result=0;
		
		                	    $dbc = new Application_Model_DbTable_DbGlobal();
				           ?>
			               <?php if(!empty($tran))foreach($tran as $key =>$row){
				               	$loan_number = $row["loan_number"];
			               	?>
			               	<tr class="style-rowdata hover" align="center">
			                    <td >&nbsp;<?php echo ($key+1<10)?"0":"";echo $key+1; ?>&nbsp;</td>
			                    <td align="left">&nbsp;<?php echo $row['branch_kh'];?>&nbsp;</td>
			                    <td align="left">&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
								 <?php $rsc = $dbc->getClientSavingByType(null,$row['client_id'],1);?>
			                     <td align="left" style="min-width:60px;">&nbsp;<?php echo $row['client_name'];?>&nbsp;</td>
			                     <td align="left" style="min-width:60px;">&nbsp;<?php echo $row['guarantor_name'];?>&nbsp;</td>
			                     <td align="left">&nbsp;<?php echo $row['productTitle'];?>&nbsp;</td>
			                     <td align="left" style="line-height: 18px; white-space: normal !important;max-width: 150px;width: 150px;padding: 5px;overflow-wrap: break-word;">
			                     <?php 
			                     		echo empty($rsc['phone_number'])?"":$rsc['phone_number'];
										echo empty($rsc['village_name'])?"":" ".$rsc['village_name'];
										echo empty($rsc['commune_name'])?"":','.str_replace("Commune", "", $rsc['commune_name']);
										echo empty($rsc['district_name'])?"":','.$rsc['district_name'];
										echo empty($rsc['province_en_name'])?"":','.$rsc['province_en_name'];
								?>
			                     </td>
			                    <?php $str_day = date('D',strtotime($row['date_payment']));
			                    	$day_as_khmer = $dayin_khmer[$str_day];
			                    ?>
			                    <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['times']."/".$row['total_duration'];?>&nbsp;</td>
			                    <td align="center">&nbsp;<?php echo ($row['principle_after']); ?>&nbsp;</td>
			                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest_after'],2));?>&nbsp;</td>
			                    <td align="center">&nbsp;<?php 
			                    $total_pay=($row['principle_after']+$row['total_interest_after']);
			                    if($row['last_pay_date']==null or $row['last_pay_date']==""){
			                    	$total_day=strtotime($end_dat)-strtotime($row['date_payment']);
			                    	$amount_lateday=$total_day/(60*60*24)-$free_day;
			                    	$late_day = $total_day/(60*60*24);
			                    }else {
			                    	$total_day=strtotime($end_dat)-strtotime($row['last_pay_date']);
			                    	$amount_lateday=$total_day/(60*60*24);
			                    	$late_day = $total_day/(60*60*24);
			                    }
			                    $pay_term=$row['collect_typeterm'];
			                    if($amount_lateday<0){
			                    	$amount_lateday=0;
			                    	$result=0;
			                    }
			                    else {
			                    	$total_late=($row['principle_after']+$row['total_interest_after']);
			                    }
			                    $penelize=0;
			                    echo str_replace('.00', '', number_format($penelize,2));?>&nbsp;
			                    </td>
			                    <td><strong><?php $total_payment =$row['principle_after']+$row['total_interest_after'];
			                    	echo str_replace('.00', '', number_format($total_payment,2))." ";?></strong><?php echo $row['currencyname'];?></td>
			                    <td>&nbsp;0&nbsp;</td>
			                    <td>&nbsp;&nbsp;</td>
			                    <td>&nbsp;<?php echo date_format(date_create($row["date_payment"]),'d-m-Y');?>&nbsp;</td>
			                </tr>
				                <?php 
						               if($row['currency_type']==1){
						               		$amt_r1 = $amt_r1+$row['principle_after'];
						               		$amt_r2 = $amt_r2+$row['total_interest_after'];
						               		$amt_r3 = $amt_r3+$penelize;
						               		$amt_r4 = $amt_r4+$total_payment;
						               		$total_r=$amt_r4;
						               }elseif($row['currency_type']==2){
											$amt_d1 = $amt_d1+$row['principle_after'];
											$amt_d2 = $amt_d2+$row['total_interest_after'];
											$amt_d3 = $amt_d3+$penelize;
											$amt_d4 = $amt_d4+$total_payment;
											$total_d=$amt_d4;
						               }else{
						               		$amn_b1 = $amn_b1+$row['principle_after'];
											$amn_b2 = $amn_b2+$row['total_interest_after'];
											$amn_b3 = $amn_b3+$penelize;
											$amn_b4 = $amn_b4+$total_payment;
											$total_b=$amn_b4;
						               }
			               }
				         ?>
		                <?php $i=1; $currentlate = 0;?>
		                <tr class="style-rowdata hover" align="center">
		                	<td colspan="15" style="font-family:'Times New Roman','Khmer OS Muol Light'; background: #ccd9ff; text-align: center;">&nbsp;<?php echo$tr->translate("RPTPAWNLATE");?>&nbsp;</td>
		                </tr>
		                <?php if(!empty($this->loanlate_list)){?>
		               <?php foreach ($this->loanlate_list as $index => $rs){ ?>
		               		<?php $end_dat = $this->list_end_dates;
			               			$total_pay=($rs['principle_after']+$rs['total_interest_after']);
			               			if ($rs['last_pay_date']==null or $rs['last_pay_date']==""){
			               				$total_day=strtotime($end_dat)-strtotime($rs['date_payment']);
			               				$amount_lateday=$total_day/(60*60*24)-$free_day;
			               				$total_late_day=$total_day/(60*60*24);
			               			}else {
			               				$total_day=strtotime($end_dat)-strtotime($rs['date_payment']);
			               				$total_late_day=$total_day/(60*60*24);
			               				$amount_lateday=$total_day/(60*60*24);
			               			}
			               			$currentlate =$total_day/(60*60*24);
			               			if($amount_lateday<0){
			               				$amount_lateday=0;
			               				$result=0;
			               			}
			               			else {
			               				$total_late=($rs['principle_after']+$rs['total_interest_after']);
			               				$result=$total_pay*($interest_penalty*(($rs['interest_rate']/100)/30))*($amount_lateday);
			               			}
			               			$penelize=0;
			               			$total_payment =$rs['principle_after']+$rs['total_interest_after'];
		               			?>
		               <?php if($currentlate>0){?>
		               <tr class="style-rowdata hover" align="center">
		               		<td style="text-align: center;"><?php echo $i++;?></td>
		               		<td>&nbsp;<?php echo $rs["branch_namekh"];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
		               		<!-- <td>&nbsp;<?php //echo $rs["client_number"];?>&nbsp;</td> -->
		               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
		               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["guarantor_name"];?>&nbsp;</td>
		               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["productTitle"];?>&nbsp;</td>
		               		<td style="line-height: 18px; white-space: normal !important;max-width: 150px;width: 150px;padding: 5px;overflow-wrap: break-word;">
		               		 <?php 
			                     		echo empty($rs['phone'])?"":$rs['phone'];
										echo empty($rs['village_name'])?"":" ".$rs['village_name'];
										echo empty($rs['commune_name'])?"":','.str_replace("Commune", "", $rs['commune_name']);
										echo empty($rs['district_name'])?"":','.$rs['district_name'];
										echo empty($rs['province_en_name'])?"":','.$rs['province_en_name'];
								?>
		               		</td>
		               		<td align="center">&nbsp;&nbsp;<?php echo $rs['times']."/".$rs['total_duration'];?> &nbsp;</td>
		               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["principle_after"],2).' ';?><?php echo $rs['currency_type'];?>&nbsp;</td>
		               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_interest_after"],2).' ';?><?php echo $rs['currency_type'];?>&nbsp;</td>
		               		<td align="right" style="white-space: nowrap;"><strong >&nbsp;<?php echo number_format($penelize,2).' ';?></strong><?php echo $rs['currency_type'];?>&nbsp;</td>
		               		<td align="right" style="white-space: nowrap;"><strong >&nbsp;<?php echo number_format($total_payment,2).' ';?></strong><?php echo $rs['currency_type'];?>&nbsp;</td>
		               		<td align="center">&nbsp;<?php echo number_format($total_late_day,0)." Days";?>&nbsp;</td>
		               		<td align="center">&nbsp;<?php echo $rs["amount_late"]." ដង";?>&nbsp;</td>
		               		<td align="center">&nbsp;<?php echo date_format(date_create($rs["date_payment"]),'d-m-Y');?>&nbsp;</td>
		                </tr>
		                <?php }?>
		                <?php 
				               if($rs['curr_type']==1){
				               		$amt_r1 = $amt_r1+$rs['principle_after'];
				               		$amt_r3 = $amt_r3+$rs['total_interest_after'];
				               		$amt_r4 = $amt_r4+$total_payment;
				               }elseif($rs['curr_type']==2){
									$amt_d1 = $amt_d1+$rs['principle_after'];
									$amt_d2 = $amt_d2+$rs['total_interest_after'];
									$amt_d4 = $amt_d4+$total_payment;
				               }else{
									$amt_b1 = $amt_b1+$rs['principle_after'];
									$amn_b3 = $amn_b3+$rs['total_interest_after'];
									$amn_b4 = $amn_b4+$total_payment;
				               }
				               $amount_days = strtotime($this->list_end_dates)-strtotime($rs["date_payment"]);
				               $amount_days =  floor($amount_days/(60*60*24));
		               ?>
		                <?php }
		                }?>
			            </table>
			            
			    	</td>
			    </tr>
			</table>
			<br />
			<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
                    <td align="right">&nbsp;</td>
                    <td></td>
                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCIPLE");?></span>&nbsp;</td>
                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_INTEREST");?></span></td>
                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PAYMENT");?></span></td>
                    <td align="right">&nbsp;</td>
                 </tr>
                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
                    <td align="right"></td>
                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                    <td align="right">&nbsp;</td>
                 </tr>
                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
                    <td align="right"></td>
                    <td align="right"><?php echo $tr->translate("REILS");?></td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
                    <td align="right">&nbsp;</td>
                 </tr>
                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
                    <td align="right"></td>
                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b1,2);?>&nbsp;</td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                    <td align="right">&nbsp;</td>
                 </tr>
             </table>
             <br />
			<?php echo $this->footerReport;?>
	</div>
</div>
<script>
dojo.require("dojo.html");
	dojo.ready(function(){		
		co_id = dijit.byId('co_id').get('value');
		if(co_id>0){
			document.getElementById('lbl_customer').innerHTML=dijit.byId('co_id').attr('displayedValue');;
		}
	});
function popupCheckCO(){
}
</script>