<?php 
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
</style>
<title><?php echo $tr->translate("LOAN_PAWN_OUTSTADING");?></title>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('LOAN_PAWN_OUTSTADING');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('adv_search');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('members');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('product_id');?>
				   </div>
				</div>
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<select class="fullside" name="status_use" id="status_use" dojoType="dijit.form.FilteringSelect" >
							<option value="-1" <?php if($this->statusopt==-1){echo "selected";}?> >ជ្រើសរើសស្ថានការណ៏កម្ចី</option>
							<option value="0" <?php if($this->statusopt==0){echo "selected";}?> >តែកម្ចីដំណើរការ</option>
							<option value="1" <?php if($this->statusopt==1){echo "selected";}?> >ទាំងកម្ចីដំណើការនិងខូច</option>
						</select>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint" style="width: 100%;">
			<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table tr td ul li{list-style: none;line-height: 25px;}
					th{padding: 5px;}
					
					table.content-data { page-break-inside:auto }
					table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
			</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
							<tr>
								<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
								<td width="60%" valign="top">
									<ul>
										<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:15px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("LOAN_PAWN_OUTSTADING");?></li>
										<li style="text-align:center; font-size:15px;"><?php echo date('D-d-m-Y',strtotime($this->fordate));?></li>
									</ul></td>
								<td width="20%"></td>
							</tr> 
						</table>
					</td>
				</tr>
				<tr>
					<td id="exportExcel">
						<table class="content-data" border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px; white-space: nowrap;" width="100%" cellspacing="0">
							<thead>
							 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; padding: 2px 0px;background:#ccd9ff;">
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</th>
								<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
								<th><?php echo $tr->translate("EST_VALUE");?></th>
								<th style="padding:2px 0px;"> &nbsp;<?php echo $tr->translate("RELEASE_DATE");?>&nbsp;</th>
								<th>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("PERCENTAGE");?>&nbsp;</th>
								<th style="padding:2px 0px;">&nbsp;<?php echo $tr->translate("NOT_TO_REPAY");?>&nbsp;</th>
							</tr>
							</thead>
						   <?php 
							   $db = new Report_Model_DbTable_DbLoan();
							   $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
							   $result_b=0;$result_r=0;$result_d=0;$count_d=0;
							   $count_r=0;$count_b=0;$amt_loanmonth=0;$amt_loanweek=0;
							   $amt_loanday=0;
							   $i=0;
							   
							   $monthDolar=0;
							   $weekDolar=0;
							   $dayDolar=0;
							   
							   $monthRiel=0;
							   $weekRiel=0;
							   $dayRiel=0;
							   
							   $monthBath=0;
							   $weekBath=0;
							   $dayBath=0;
							   
						   if(!empty($this->outstandloan))foreach($this->outstandloan as $key =>$row){?>
						   <?php 
								$total_receive= $row['total_principaid'];
								if($total_receive>=$row['total_capital']){
									continue;
								}
								if($row['termborrow']==1){
									$amt_loanday=$amt_loanday+1;
								}elseif($row['termborrow']==2){
									$amt_loanweek=$amt_loanweek+1;
								}else{
									$amt_loanmonth = $amt_loanmonth+1;
								}
								$i++;
								
							   if($row['curr_type']==1){
									$amt_r = $amt_r+$row['total_capital'];
									$amn_r = $amn_r+$total_receive;
									$result_r=number_format(($amn_r/$amt_r)*100,2).' %';
									$count_r=$count_r+1;
									
									if($row['termborrow']==1){
										$dayRiel=$dayRiel+1;
									}elseif($row['termborrow']==2){
										$weekRiel=$weekRiel+1;
									}else{
										$monthRiel = $monthRiel+1;
									}
							   }elseif($row['curr_type']==2){
									$amt_d = $amt_d+$row['total_capital'];
									$amn_d = $amn_d+$total_receive;
									$result_d=number_format(($amn_d/$amt_d)*100,2).' %';
									$count_d=$count_d+1;
									
									if($row['termborrow']==1){
										$dayDolar=$dayDolar+1;
									}elseif($row['termborrow']==2){
										$weekDolar=$weekDolar+1;
									}else{
										$monthDolar = $monthDolar+1;
									}
							   }else{
									$amt_b = $amt_b+$row['total_capital'];
									$amn_b = $amn_b+$total_receive;
									$result_b=number_format(($amn_b/$amt_b)*100,2).' %';
									$count_b=$count_b+1;
									
									if($row['termborrow']==1){
										$dayBath=$dayBath+1;
									}elseif($row['termborrow']==2){
										$weekBath=$weekBath+1;
									}else{
										$monthBath = $monthBath+1;
									}
							   }
						   ?>
								<tr align="center" class="hover">
									<td>&nbsp;<?php echo $i; ?>&nbsp;</td>
									<td style="line-height: 12px; white-space: nowrap;">&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
									<td align="left" style="font-size:12px; line-height: 13px; white-space: nowrap;">&nbsp;<?php echo $row['client_khname']; ?>&nbsp;</td>
									<td style="white-space:nowrap;">&nbsp;<?php echo $row['product_name']; ?>&nbsp;</td>
									<td style="white-space:nowrap;">&nbsp;<?php echo $row['est_amount']; ?>&nbsp;</td>
									<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_release']));?>&nbsp;</td>
									<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_line']));?>&nbsp;</td>
									<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
									<td style="white-space: nowrap;">&nbsp;<?php echo number_format($row['total_duration']).$row['termborrow'];?>&nbsp;</td>
									<td style="white-space:nowrap; text-align: center;">&nbsp;<?php echo $row['total_principaid'];?>&nbsp;</td>
									<td>&nbsp;<?php echo (round(($total_receive/$row['total_capital']),2)*100).' %'; ?>&nbsp;</td>
									<td>&nbsp;<?php echo number_format(($row['total_capital']-$total_receive),2).' '.$row['currency_type'];?>&nbsp;</td>
								</tr>
							<?php }?>
						</table>
						<br />
						<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td rowspan="2" align="right">&nbsp;</td>
								<td rowspan="2"></td>
								<td colspan="3" align="center"><span class="border_bottom"><?php echo $tr->translate("PAWN_NUMBER");?></span></td>
								<td rowspan="2">&nbsp;</td>
								<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("LOAN_AMOUNT");?></span>&nbsp;</td>
								<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?></span></td>
								<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("PERCENTAGE");?></span></td>
								<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("NOT_TO_REPAY");?></span></td>
								<td rowspan="2" align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
								<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
								<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
							</tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="center"><?php echo $monthDolar;?></td>
								<td align="center"><?php echo $dayDolar;?></td>
								<td align="center" style="font-weight:bold;"><?php echo $monthDolar+$dayDolar;?></td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_d;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d-$amn_d,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("REILS");?></td>
								<td align="center"><?php echo $monthRiel;?></td>
								<td align="center"><?php echo $dayRiel;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthRiel+$dayRiel;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_r;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r-$amn_r);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("BATH");?></td>
								<td align="center"><?php echo $monthBath;?></td>
								<td align="center"><?php echo $dayBath;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthBath+$dayBath;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_b;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b-$amn_b);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px;border-top: 4px double #000 !important;">
								<td align="right"></td>
								<td align="right"></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanmonth;?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanday;?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanmonth+$amt_loanday;?>&nbsp;</td>
								<td colspan="7">&nbsp;</td>
							 </tr>
						</table>
						  <br />
						<?php echo $this->footerReport;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>