<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលស់ប្រាក់ដើម",4=>"បង់ផ្តាច់");
?>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("REPORT_LOAN_PAYMENT");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<form method="post">
		<table style="font-family: 'Khmer OS Content';width:100%; margin: 0 auto;" >
			<tr>
				<td><?php echo $frm->getElement('adv_search');?></td>
				<td><?php echo $frm->getElement('branch_id');?></td>
				<td><?php echo $frm->getElement('members');?></td>
				<td><?php echo $frm->getElement('product_id');?></td>
			</tr>
			<tr>
			    <td><?php echo $frm->getElement('currency_type');?></td>
				<td><?php echo $frm->getElement('start_date');?></td>
				<td><?php echo $frm->getElement('end_date');?></td>
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			</tr>
		</table>
	</form>
<div id="divPrint">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		.stylehover:hover{background: #ccc;}
		table tr td ul li{list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 2px;}
		table {page-break-inside:auto }
		      tr{ page-break-inside:avoid; page-break-after:auto; }
		      #header {
		        display: table-header-group;
		        page-break-inside:avoid; page-break-after:auto;
		      }
thead tr td{
				text-align: center;
				font-weight: bold;
			}
	</style>
<?php $client_id = null;?>
<?php $principle_r = 0;$interst_r = 0;$penalize_r = 0;$service_charge_r = 0;$balane_r = 0;
                	  $principle_b = 0;$interst_b = 0;$penalize_b = 0;$service_charge_b = 0;$balane_b = 0;
                	 $principle_d = 0; $interst_d = 0; $penalize_d= 0; $service_charge_d = 0;$balane_d = 0;
                	 $i=1;
                	?>
		<table width="100%">
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
		            	<tr>
		                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
		                	<td width="60%" valign="top">
		                         <ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_PAYMENT");?></li>
		                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
		                		</ul>
		                 </td>
		                    <td width="20%"></td>
		                </tr> 
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td>
		    		<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse; border: 1px solid #000;" cellspacing="0">
						<?php if(!empty($this->loantotalcollect_list)) {
			              	foreach ($this->loantotalcollect_list as $index => $rs){
			              		if ($client_id!=$rs["client_id"]) {
			              		?>
			              	<tr style="background: #eaedf5">
			              		<td colspan="14" class="style">&nbsp;​
			              		<?php 
			              			
			              				 echo $tr->translate("LOAN_NO").':'.$rs["loan_number"].','.$tr->translate("CUSTOMER_NAME").':'.$rs["client_name"].',';
			              				 echo $tr->translate("SEX").':';
			              					if (!empty($rs['sex']) AND $rs['sex']==1){
			              					echo "M";
			              				}
			              				else {
			              					echo "F";
			              				}
			              			
			              				$client_id=$rs["client_id"];
			              			?>&nbsp;​
			              	</td>
			              	</tr>
							<thead>
			                <tr bgcolor="#ccc" class="style" align="center" style="padding:5px 0;height: 20px; white-space: nowrap; background: #ccd9ff;">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("PAID_PRINCIPAL");?>&nbsp;</td>                   
			                    <td>&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("SERVICE CHARGE");?>&nbsp;</td>	 
			                    <td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>                   
			                    <td>&nbsp;<?php echo $tr->translate("PAY_DATE");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("RECIEPT_NO");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("PAYMENTED");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("INPUT_DATE");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("PAYMENT_OPTION");?>&nbsp;</td>
			                </tr>
							</thead>
			                <?php }?>              
		             <?php 
				               if($rs['currency_type']==1){
				               		$principle_r = $principle_r+$rs["principal_paid"];
				               		$interst_r = $interst_r+$rs["interest_paid"];
				               		$penalize_r = $penalize_r+$rs["penalize_paid"];
				               		$service_charge_r = $service_charge_r+$rs["service_paid"];
				               }elseif($rs['currency_type']==2){
									$principle_d = $principle_d+$rs["principal_paid"];
									$interst_d = $interst_d+$rs["interest_paid"];
									$penalize_d = $penalize_d+$rs["penalize_paid"];
									$service_charge_d = $service_charge_d+$rs["service_paid"];
				               }else{
				               		$principle_b = $principle_b+$rs["principal_paid"];
									$interst_b = $interst_b+$rs["interest_paid"];;
									$penalize_b = $penalize_b+$rs["penalize_paid"];;
									$service_charge_b = $service_charge_b+$rs["service_paid"];
				               }
		               ?>
		                <tr class="style stylehover" style="font-family: 'Khmer OS Content';white-space: nowrap;" width="100%">
		               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
		               		<td>&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
		               		<td>&nbsp;&nbsp;<?php echo number_format($rs["principal_paid"],2).' '.$rs['currency_typeshow'];?></td>               		
		               		<td>&nbsp;&nbsp;<?php echo number_format($rs["interest_paid"],2).' '.$rs['currency_typeshow'];?></td>
		               		<td>&nbsp;&nbsp;<?php echo number_format($rs['penalize_paid'],2).' '.$rs['currency_typeshow'];?></td>
		               		<td>&nbsp;&nbsp;<?php echo number_format($rs["service_paid"],2).' '.$rs['currency_typeshow'];?></td>
		               		<td>&nbsp;&nbsp;<?php echo number_format($rs["total_paymentpaid"],2);?>
		               		<td>&nbsp;&nbsp;<?php echo date('d-m-Y',strtotime($rs["date_payment"]));?></td>
		               		<td>&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
		               		<td>&nbsp;&nbsp;<?php echo number_format($rs['total_paymentpaid'],2);?></td>
		               		<td>&nbsp;&nbsp;<?php echo date("d-m-Y",strtotime($rs['date_input']));?></td>
		               		<td style="font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;<?php echo @$opt[$rs["payment_option"]];?>&nbsp;</td>
		               		
		                </tr>
		                <?php }}?>
		                <tr>
		                	<td colspan="14" style="border-left:1px solid #fff;border-right:1px solid #fff;">&nbsp;</td>
		                </tr>
		            </table>
		            <table  width="100%" border="1" style="border-collapse:collapse; border: 1px solid #000;" cellspacing="0">
		                 <thead>
		                  <tr bgcolor="#ccc" class="style stylehover" style="font-weight:bold; background: #ccd9ff; line-height: 24px; text-align: center;" >
			                    <td style="padding:5px 0px; text-align: left;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</td>
			                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_PRINCIPLE");?>&nbsp;</td>
			                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_INTEREST");?>&nbsp;</td>
			                    <td style="padding:5px 0px;"colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_PENELIZE");?>&nbsp;</td>
			                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?>&nbsp;</td>
			                    <td style="padding:5px 0px;" colspan="4">&nbsp;<?php echo $tr->translate("TOTAL_PAYMENTED");?>&nbsp;</td>	                    
			                </tr>
			              </thead>               
		                <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
		                    <td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?></td>
		                    <td colspan="2">&nbsp;<?php echo number_format($principle_b,2);?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo number_format($interst_b,2);?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo number_format($penalize_b,2);?>&nbsp;</td>
							<td colspan="2">&nbsp;<?php echo number_format($service_charge_b,2);?>&nbsp;</td>
							<td colspan="4">&nbsp;<?php echo number_format($principle_b+$interst_b+$penalize_b+$service_charge_b,2);?>&nbsp;</td>
		                </tr>
						 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
		                    <td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
		                    <td colspan="2">&nbsp;<?php echo number_format($principle_d,2);?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo number_format($interst_d,2);?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo number_format($penalize_d,2);?>&nbsp;</td>
							<td colspan="2">&nbsp;<?php echo number_format($service_charge_d,2);?>&nbsp;</td>
							<td colspan="4">&nbsp;<?php echo number_format($principle_d+$interst_d+$penalize_d+$service_charge_d,2);?>&nbsp;</td>
		                </tr>
		                <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
		                    <td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?></td>
		                    <td colspan="2">&nbsp;<?php echo number_format($principle_r,2);?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo number_format($interst_r,2);?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo number_format($penalize_r,2);?>&nbsp;</td>
							<td colspan="2">&nbsp;<?php echo number_format($service_charge_r,2);?>&nbsp;</td>
							<td colspan="4">&nbsp;<?php echo number_format($principle_r+$interst_r+$penalize_r+$service_charge_r,2);?>&nbsp;</td>
		                </tr>
		                
		            </table>
		              <br />
	               <table align="center" width="100%">
					   <tr style="font-size: 12px;">
					        <td style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
				</table>
		    	</td>
		    	</tr>
		</table>
	</div>
</div>