<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"រំលស់ដើម",4=>"បង់ផ្តាច់");
	$session_user=new Zend_Session_Namespace(SYSTEM_SES);
	$level =$session_user->level;
	$data = $this->data;
?>
<title><?php echo $tr->translate("RPT_PAWN_PAYMENT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<style>
	.hover:hover{ background:#ccc;}
	table.content-data thead tr.style-head,
	table.tb-footer tr.style-head {
	   font-weight: bold !important;
	}
	.noneprint{
		display: table-cell !important; 
	}
</style>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('RPT_PAWN_PAYMENT');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('adv_search');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('members');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('product_id');?>
				   </div>
				</div>
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
				   </div>
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint">
			<style type="text/css">
				.style{
					line-height: 20px;font-size: 13px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				.style1:hover{ background: #ccc; }
				table tr td ul li{list-style: none;line-height: 25px; }
				table.content-data { page-break-inside:auto }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				a.repLink.btn {
					color: #008;
					font-size: 10px;
					font-weight: 600;
				}
				thead tr td{
						text-align: center;
					}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
				table.tb-footer{
					font-family: 'Times New Roman','Khmer OS Battambang'; 
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:12px;
					width:100%;
				}
				table.tb-footer tr.style-head{
					line-height: 24px; 
					text-align: center; 
					background: #ccd9ff;
				}
				.border_bottom {
					border-bottom: 1px solid #000;
				}
			</style>
			<table width="100%">
				<tr>
					<td align="center" valign="top">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';"style="margin:0;padding:0;">
							<tr>
								<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="80px"></td>
								<td width="60%" valign="top">
									<ul>
										<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $data['client_company_name'];?><?php //echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("RPT_PAWN_PAYMENT");?></li>
										<li style="text-align:center; font-size:14px;"><?php if (!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
									</ul>
							   </td>
								<td width="20%"></td>
							</tr> 
						</table>
					</td>
				</tr>
				<tr>
					<td id="exportExcel">
						<table  class="content-data"  border="1"  cellspacing="0">
							   <thead>
								<tr class="style-head" >
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</td>	  
									<td rowspan="2">&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td>                  
									<td rowspan="2">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("PRODUCT");?>&nbsp;</td>
									<?php 
										$colspan=5;
									?>
									<td colspan="<?php echo $colspan;?>">&nbsp;<?php echo $tr->translate("PAYMENTED");?>&nbsp;</td>    
									<td rowspan="2" style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo $tr->translate("PAY_DATE");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("INPUT_DATE");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("PAID_TIME");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("RECIEPT_NO");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("PAYMENT_OPTION");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("BY_USER");?>&nbsp;</td>
								</tr>
								<tr class="style-head" >
									<td align="center">&nbsp;<?php echo $tr->translate("PRINCIPAL");?>&nbsp;</td> 
									<td align="center">&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo $tr->translate("SERVICE CHARGE");?>&nbsp;</td>	                    
									<td align="center">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
								</tr>
								</thead>
							<?php 
								$amt_r1 = 0; $amn_r2 = 0; $amn_r3 = 0;$amt_r4 = 0;$amn_r5 = 0;
								$amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
								$amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;
								$i=1;$oldloan_number='';
								$saving_amountr = 0;$saving_amountd = 0;$saving_amountb = 0;
								$total_d=0;$total_b=0;$total_r=0;
							?>
							<?php $is_set =0; if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
							<?php 
							   $interest=0;
							   $interest_amount=0;
							   if($rs['currency_type']==1){
									$amt_r1 = $amt_r1+$rs['principal_paid'];
									$amn_r2 = $amn_r2+$rs['interest_paid'];
									$amn_r3 = $amn_r3+$rs['penalize_paid'];
									$amn_r5 = $amn_r5+$rs['service_paid'];
									$total_r=$amt_r1+$amn_r2+$amn_r3+$amn_r5;
							   }elseif($rs['currency_type']==2){
									$amt_d1 = $amt_d1+$rs['principal_paid'];
									$amt_d2 = $amt_d2+$rs['interest_paid'];
									$amt_d3 = $amt_d3+$rs['penalize_paid'];
									$amt_d5 = $amt_d5+$rs['service_paid'];
									$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
							   }else{
									$amn_b1 = $amn_b1+$rs['principal_paid'];
									$amn_b2 = $amn_b2+$rs['interest_paid'];
									$amn_b3 = $amn_b3+$rs['penalize_paid'];
									$amn_b5 = $amn_b5+$rs['service_paid'];
									$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
							   }
						   ?>
							<tr class="style-rowdata hover context-menu-one" oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" >
								<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>                 		
								<td>&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs["proTitle"];?>&nbsp;</td>
								<td align="center" >&nbsp;<strong><?php echo number_format($rs['principal_paid'],2);?></strong>&nbsp;<?php echo $rs['currency_typeshow'];?>&nbsp;</td>               		
								<td align="center" >&nbsp;<strong><?php echo number_format($rs['interest_paid'],2);//.' '.$rs['currency_typeshow'];?></strong>&nbsp;</td>
								<td align="center" >&nbsp;<strong><?php echo number_format($rs['penalize_paid'],2);//.' '.$rs['currency_typeshow'];?></strong>&nbsp;</td>
								<td align="center" >&nbsp;<strong><?php echo number_format($rs['service_paid'],2);//.' '.$rs['currency_typeshow'];?></strong>&nbsp;</td>
								<td align="center" >&nbsp;<strong><?php echo number_format($rs["total_paymentpaid"],2).' '.$rs['currency_typeshow'];;?></strong>&nbsp;</td> 
								<td align="center" style=" border-right:3px double black; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_payment"]));?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_input"]));?>&nbsp;</td>
								<td align="center" >&nbsp;<strong><?php echo $rs["paid_times"];?></strong>&nbsp;</td> 
								<td align="center">&nbsp;<strong><?php echo $rs["receipt_no"];?></strong>&nbsp;</td>
								<td style="font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;<?php echo @$opt[$rs["payment_option"]];?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $rs["user_name"]; ?>&nbsp;</td>
							</tr>
							<?php }?>
							 <?php 
								$r1=0; $b1=0;$d1=0;
							?>
							<!-- កុំលុបព្រោះទុកបូកជាមួយនិងថ្លៃសេវាពេលចេញកម្ចី -->
							<?php if(!empty($this->LoanFee_list)) foreach ($this->LoanFee_list as $key => $row){ ?>
							<?php 
								if($row['currency_type']==1){
									$r1 = $r1+$row['admin_fee'];
							   }elseif($row['currency_type']==2){
									$d1 = $d1+$row['admin_fee'];
							   }else{
									$b1 = $b1+$row['admin_fee'];
							   }
							 ?>
							<?php }?>
							
							
							<?php 
							$rescheduldFeeR=0;
							$rescheduldFeeD=0;
							$rescheduldFeeB=0;
							if (!empty($this->rescheduleFee)) foreach ($this->rescheduleFee as $rs){
								if($rs['currency_type']==1){
									$rescheduldFeeR = $rescheduldFeeR+$rs['total_adminfee'];
								}elseif($rs['currency_type']==2){
									$rescheduldFeeD = $rescheduldFeeD+$rs['total_adminfee'];
								}else{
									$rescheduldFeeB = $rescheduldFeeB+$rs['total_adminfee'];
								}
							}
	// 		                echo $rescheduldFeeB." ".$rescheduldFeeD." ".$rescheduldFeeR;exit();
							?>
						</table>
						<br />
						<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td align="right">&nbsp;</td>
								<td></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("PRINCIPAL");?></span>&nbsp;</td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_INTEREST");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("AMIN_FEE");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
								 <td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($d1+$rescheduldFeeD,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d1+$amt_d2+$amt_d3+$amt_d5+$d1+$rescheduldFeeD,2);//$total_d?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("REILS");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r5,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($r1+$rescheduldFeeR,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r1+$amn_r2+$amn_r3+$amn_r5+$r1+$rescheduldFeeR,2);//$total_r?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("BATH");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($b1+$rescheduldFeeB,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b1+$amn_b2+$amn_b3+$amn_b5+$b1+$rescheduldFeeB,2);//+$total_b?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
						 
						 </table>
						  <br />
						  <?php echo $this->footerReport;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<?php 
$url_receipt = $this->baseUrl()."/report/pawn/recieptpayment/id/";
?>
<script>
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="reciept"){
				url='<?php echo $url_receipt;?>';
			}
			addTab("<?php echo $tr->translate("PAYMENT_RECEIPT");?>",url+row+'?inFrame=true');
			//gotoAction();
		},
		items: {
			"reciept": {name: "<?php echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-file-text", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_self');
}
 </script>
