<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("REPORT_EXPECT_INCOME"));
$filter = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_EXPECT_INCOME');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('adv_search');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('branch_id');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('members');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('product_id');?>
               </div>
           	</div>
           	<div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('currency_type');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('start_date');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('end_date');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
           	</div>
        </div>
	</form>
<div id="divPrint">
	<style type="text/css">
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Times New Roman','Khmer OS Battambang';
		}
		table tr td ul li{list-style: none;line-height: 25px; }
		th{padding: 2px;}
		table { page-break-inside:auto }
	  	tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		thead tr td{
			text-align: center;
		}
		table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data thead tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:12px; 
			height: 23px;
		}
		
		table.tb-footer{
			font-family: 'Times New Roman','Khmer OS Battambang'; 
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:12px;
			width:100%;
		}
		table.tb-footer tr.style-head{
			line-height: 24px; 
			text-align: center; 
			background: #ccd9ff;
		}
	</style>
	<table width="100%">
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
	                	<td width="60%" valign="top">
	                		<ul>
	                			<li style="text-align:center; font-size:18px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
	                			<li style="text-align:center; font-size:15px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_EXPECT_INCOME");?></li>
	                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
							</ul>
	                	</td>
	                    <td width="20%"></td>
	                </tr> 
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table class="tb-footer" border="1" cellspacing="0">
	               <thead>
		               <tr class="style-head" >
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</td> 
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>                   
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("PAWN_AMOUNT");?>&nbsp;</td> 
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("PAWN_DATE");?>&nbsp;</td>
		                    <td rowspan="2" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("END_DATE");?>&nbsp;</td>
		                    <td colspan="4" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("ប្រាក់ត្រូវប្រមូល");?>&nbsp;</td>
		                    <td colspan="3" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("តារាងប្រាក់មិនទាន់បង់");?>&nbsp;</td>
		                </tr>
		                <tr class="style-head" >
		                	<td style="font-size:12px;">&nbsp;<?php echo $tr->translate("PRINCIPAL");?>&nbsp;</td> 
		                    <td style="font-size:12px;">&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
		                    <td style="font-size:12px;">&nbsp;<?php echo $tr->translate("TOTAL_PAYMENT");?>&nbsp;</td>
		                    <td style="font-size:12px;">&nbsp;<?php echo $tr->translate("DAY_PAYMENT");?>&nbsp;</td>
		                    <td style="font-size:12px;">&nbsp;<?php echo $tr->translate("PRINCIPAL");?>&nbsp;</td> 
		                    <td style="font-size:12px;">&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
		                    <td style="font-size:12px;">&nbsp;<?php echo $tr->translate("TOTAL_PAYMENT");?>&nbsp;</td>
		                </tr>
	                </thead>
	                <?php 
	                	  $amt_r1 = 0;
	                	  $amt_d1 = 0;
	                	  $amn_b1 = 0; 
	                	  $p_r = 0;
	                	  $p_d = 0;
	                	  $p_b = 0;
	                	  
	                	  $ramt_r1 = 0;
	                	  $ramt_d1 = 0;
	                	  $ramn_b1 = 0;
	                	  $rp_r = 0;
	                	  $rp_d = 0;
	                	  $rp_b = 0;
	                ?>
	                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
	                <?php 
			               if($rs['currency_type']==1){
				               	$p_r = $p_r+$rs['principal_permonth'];
				               	$amt_r1 = $amt_r1+$rs['total_interest'];
				               	
				               	$rp_r = $rp_r+$rs['principle_after'];
				               	$ramt_r1 = $ramt_r1+$rs['total_interest_after'];
			               }elseif($rs['currency_type']==2){
			               		$p_d = $p_d+$rs['principal_permonth'];
								$amt_d1 = $amt_d1+$rs['total_interest'];
								
								$rp_d = $rp_d+$rs['principle_after'];
								$ramt_d1 = $ramt_d1+$rs['total_interest_after'];
			               }else{
			               		$p_b = $p_b+$rs['principal_permonth'];
			               		$amt_d1 = $amt_d1+$rs['total_interest'];
			               		
			               		$rp_b = $rp_b+$rs['principle_after'];
			               		$ramt_d1 = $ramt_d1+$rs['total_interest_after'];
			               }
	               ?>
	                <tr class="style-rowdata hover">
	               		<td style="font-size: 12px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
	               		<td style="font-size: 12px;">&nbsp;&nbsp;<?php echo $rs["name_kh"];?></td>
	               		
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["total_capital"],2).''.$rs['currency_typeshow'];?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
	               		
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["principal_permonth"],2);?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2);?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["principal_permonth"]+$rs["total_interest"],2);?></td>
	               		<td style="font-size: 12px;text-align: center;"><?php echo date("d-m-Y",strtotime($rs["date_payment"]));?></td>
	               		
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["principle_after"],2);?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["total_interest_after"],2);?></td>
	               		<td style="font-size: 12px;text-align: center;">&nbsp;&nbsp;<?php echo number_format($rs["principle_after"]+$rs["total_interest_after"],2);?></td>
	                </tr>
	                <?php }?>
	            </table>
	            <br />
	             <table class="tb-footer" border="1"​ cellspacing="0">
	                <thead>
	                	<tr class="style-head" align="center">
		                 	<td rowspan="2">&nbsp;<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</td>
		                 	<td colspan="3" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("ប្រាក់ត្រូវប្រមូល");?>&nbsp;</td>
		                    <td colspan="3" style="font-size: 12px;">&nbsp;<?php echo $tr->translate("តារាងប្រាក់មិនទាន់បង់");?>&nbsp;</td>
		                 </tr>
		                 <tr class="style-head" align="center">
		                    <td>&nbsp;<?php echo $tr->translate("TOTAL_PRINCIPLE");?>&nbsp;</td>
		                    <td>&nbsp;<?php echo $tr->translate("TOTAL_INTEREST");?>&nbsp;</td>
		                    <td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
		                    <td>&nbsp;<?php echo $tr->translate("TOTAL_PRINCIPLE");?>&nbsp;</td>
		                    <td>&nbsp;<?php echo $tr->translate("TOTAL_INTEREST");?>&nbsp;</td>
		                    <td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
		                </tr>
					</thead>
	                 <tr>
	                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($p_d,2);?>$&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($amt_d1,2);?>$&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($p_d+$amt_d1,2);?>$&nbsp;</td>
	                    
	                    <td>&nbsp;<?php echo number_format($rp_d,2);?>$&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($ramt_d1,2);?>$&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($ramt_d1+$rp_d,2);?>$&nbsp;</td>
	                </tr>
	                 <tr>
	                    <td>&nbsp;<?php echo $tr->translate("REILS");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($p_r,2);?>R&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($amt_r1,2);?>R&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($amt_r1+$p_r,2);?>R&nbsp;</td>
	                    
	                    <td>&nbsp;<?php echo number_format($rp_r,2);?>R&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($ramt_r1,2);?>R&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($ramt_r1+$rp_r,2);?>R&nbsp;</td>
	                </tr>
	                 <tr>
	                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($p_b,2);?>B&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($amn_b1,2);?>B&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($amn_b1+$p_b,2);?>B&nbsp;</td>
	                    
	                    <td>&nbsp;<?php echo number_format($rp_b,2);?>B&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($ramn_b1,2);?>B&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($ramn_b1+$rp_b,2);?>B&nbsp;</td>
	                </tr>
	              </table>
	               <table align="center" width="100%">
					   <tr style="font-size: 14px;">
					        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
				</table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>
