<?php 
	$filter = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
	$url_client = $this->url(array('module'=>'report','controller'=>'pawn','action'=>'rpt-paymentschedules'));
	$url_contract = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-updatepayment'));
	$session_user=new Zend_Session_Namespace(SYSTEM_SES);
	$level = $session_user->level;
?>
<style>
.hover:hover{ background: #ccc;}
.noneprint{
	display: table-cell !important; 
}
</style>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("PAWN_DISBURSE");?></title>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('PAWN_DISBURSE');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('adv_search');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('branch_id');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('members');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('product_id');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('completed_status');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('dach_status');?>
				   </div>
				</div>
				<div class="row g-3">
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('currency_type');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('start_date');?>
				   </div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $filter->getElement('end_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 30px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px; }
				th{padding: 1px;}
				table.content-data { page-break-inside:auto }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				a.repLink.btn {
					color: #008;
					font-weight: 600;
					font-size: 10px;
				}
				.btn{
					height: 40px;
					min-width: 50px;	
				}
				thead tr td{
					text-align: center;
					font-weight: bold;
				}
				.border_bottom {
					border-bottom: 1px solid #000;
				}
				tr.redRow {
					background: #ff000026;
				}
				tr.greenRow {
					background: #a8f1a969;
				}
			</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;">
							<tr>
								<td width="25%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
								<td width="50%" valign="top">
									<ul>
										<li style="text-align:center; font-size:18px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("PAWN_DISBURSE");?></li>
										<li style="text-align:center; font-size:16px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
									</ul>
								</td>
								<td width="25%"></td>
							</tr> 
						</table>
					</td>
				</tr>
				<tr>
					<td id="exportExcel">
						<table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
						   <thead>
							 <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;line-height: 30px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
								<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								<td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
								<td rowspan="2">&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</td>
								<td rowspan="2">&nbsp;<?php echo $tr->translate("CLIENT_NO");?>&nbsp;</td>
								<td rowspan="2">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
								
								<td colspan="10">&nbsp;<?php echo $tr->translate("Pawnshop Infomation");?>&nbsp;</td>
							</tr>
							 <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;line-height: 30px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
								<td>&nbsp;<?php echo $tr->translate("LOAN_LEVEL");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ADMIN_FEE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("PAWN_AMOUNT");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("INTEREST RATE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("PAWNSHOP_DURATION");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("PAWN_DATE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("END_DATE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("PRODUCT_NAME");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("EST_VALUE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("DESCRIPTION");?>&nbsp;</td>
							</tr>
							</thead>
						   <?php 
						   $amt_r = 0;$amt_d = 0;$amt_b = 0; 
						   $count_ld=0;$count_lr=0;$count_lb=0;
						   $r=0;$b=0;$d=0;
						   
						   $monthDolar=0;
						   $weekDolar=0;
						   $dayDolar=0;
							
						   $monthRiel=0;
						   $weekRiel=0;
						   $dayRiel=0;
							
						   $monthBath=0;
						   $weekBath=0;
						   $dayBath=0;
						   
						   if(!empty($this->loanrelease_list))foreach($this->loanrelease_list as $key =>$row){?>
						   <?php 
						  if($row['curr_type']==1){
								$amt_r = $amt_r+$row['total_capital'];
								$count_lr=$count_lr+1;
								$r = $r+$row['admin_fee'];
								
								if($row['term_type']==1){
									$dayRiel=$dayRiel+1;
								}elseif($row['term_type']==2){
									$weekRiel=$weekRiel+1;
								}else{
									$monthRiel = $monthRiel+1;
								}
								
						   }elseif($row['curr_type']==2){
								$amt_d = $amt_d+$row['total_capital'];
								$count_ld=$count_ld+1;
								$d = $d + $row['admin_fee'];
								
								if($row['term_type']==1){
									$dayDolar=$dayDolar+1;
								}elseif($row['term_type']==2){
									$weekDolar=$weekDolar+1;
								}else{
									$monthDolar = $monthDolar+1;
								}
								
						   }else{
								$amt_b = $amt_b+$row['total_capital'];
								$count_lb=$count_lb+1;
								$b = $b + $row['admin_fee'];
								
								if($row['term_type']==1){
									$dayBath=$dayBath+1;
								}elseif($row['term_type']==2){
									$weekBath=$weekBath+1;
								}else{
									$monthBath = $monthBath+1;
								}
						   }
						   ?>
							<tr align="center" style="line-height: 18px; white-space: nowrap;" class="<?php if($row['is_dach']==1){echo "redRow";} if($row['is_completed']==1){echo "greenRow";} ?> hover context-menu-one" oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" >
								<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
								<td >&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
								<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
								<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
								<td align="left" style="line-height:15px;min-width:90px; ">
								&nbsp;<?php echo $row['client_khname']; ?>&nbsp;
								</td>	
								<td>&nbsp;<?php echo $row['loan_level'];?>&nbsp;</td>
								<td>&nbsp;<?php echo $row['admin_fee'];?>&nbsp;</td>
								<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $row['interest_rate'];?>&nbsp;</td>
								<td>&nbsp;<?php echo number_format($row['total_duration'],0).$row['term_type'];?>&nbsp;</td>
								<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?>&nbsp;</td>
								<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_line']));?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $row['product_name']; ?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $row['est_amount']; ?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $row['product_description']; ?>&nbsp;</td>
							</tr>
							<?php }?>
						</table>
						<br />
						<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td rowspan="2" align="right">&nbsp;</td>
								<td rowspan="2"></td>
								<td colspan="3" align="center"><span class="border_bottom"><?php echo $tr->translate("PAWN_NUMBER");?></span></td>
								<td rowspan="2">&nbsp;</td>
								<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("ADMIN_FEE");?></span></td>
								<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_AMOUNT");?></span></td>
								<td rowspan="2" align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
								<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
								<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
							</tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="center"><?php echo $monthDolar;?></td>
								<td align="center"><?php echo $dayDolar;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_ld;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("REILS");?></td>
								<td align="center"><?php echo $monthRiel;?></td>
								<td align="center"><?php echo $dayRiel;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_lr;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="center"><?php echo $monthBath;?></td>
								<td align="center"><?php echo $dayBath;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_lb;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px;border-top: 4px double #000 !important;">
								<td align="right"></td>
								<td align="right"></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthDolar+$monthRiel+$monthBath;?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $dayDolar+$dayRiel+$dayRiel;?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo count($this->loanrelease_list);?>&nbsp;</td>
								<td colspan="7">&nbsp;</td>
							 </tr>
						</table>
		              <br />
		              <?php echo $this->footerReport;?>	
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<?php 
	$url_schedule=$this->url(array("module"=>'report',"controller"=>"pawn","action"=>'rpt-paymentschedules'))."?id=";
	$url_editschedule=$this->url(array("module"=>'report',"controller"=>"pawn","action"=>'rpt-updatepayment'))."?id=";
	$url_agreement=$this->url(array("module"=>'report',"controller"=>"pawn","action"=>'agreement'))."?id=";
	$url_pawnticketreceipt=$this->url(array("module"=>'report',"controller"=>"pawn","action"=>'pawnticketreceipt'))."?id=";
?>
<script>
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="schedule"){
				url='<?php echo $url_schedule;?>';
			}else if(key=="editschedule"){
				url='<?php echo $url_editschedule;?>';
			}else if(key=="agreement"){
				url='<?php echo $url_agreement;?>';
			}else if(key=="pawnticketreceipt"){
				url='<?php echo $url_pawnticketreceipt;?>';
			}
			gotoAction();
		},
		items: {
			"schedule": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar", accesskey: "c"},
			"editschedule": {name: "<?php echo $tr->translate("EDIT_SCHEDULE_PAYMENT");?>", icon: "fa-edit",},
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text",},
			"pawnticketreceipt": {name: "<?php echo $tr->translate("PAWN_RECEIPT");?>", icon: "fa-file-text",},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
 </script>