<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលស់ប្រាក់ដើម",4=>"បង់ផ្តាច់");
?>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<title><?php echo $tr->translate("REPORT_LOAN_PAYMENT");?></title>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('REPORT_LOAN_PAYMENT');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('adv_search');?>
				   </div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('members');?>
				   </div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('product_id');?>
				   </div>
			   </div>
			   <div class="row g-3">
				   <div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
				   </div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
				   </div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				.stylehover:hover{background: #ccc;}
				table tr td ul li{list-style: none;line-height: 25px; }
				th{padding: 2px;}
				table.content-data {page-break-inside:auto }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
					   display: table-header-group;
					   page-break-inside:avoid; page-break-after:auto;
				  }
				 thead tr td{
					text-align: center;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
				table.tb-footer{
					font-family: 'Times New Roman','Khmer OS Battambang'; 
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:12px;
					width:100%;
				}
				table.tb-footer tr.style-head{
					line-height: 24px; 
					text-align: center; 
					background: #ccd9ff;
				}
				.border_bottom {
					border-bottom: 1px solid #000;
				}
			</style>
	<?php $client_id = null;?>
	<?php $principle_r = 0;$interst_r = 0;$penalize_r = 0;$service_charge_r = 0;$balane_r = 0;
						  $principle_b = 0;$interst_b = 0;$penalize_b = 0;$service_charge_b = 0;$balane_b = 0;
						 $principle_d = 0; $interst_d = 0; $penalize_d= 0; $service_charge_d = 0;$balane_d = 0;
						 $i=1;
						?>
			<table width="100%">
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0; border:none;">
							<tr>
								<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
								<td width="60%" valign="top">
									 <ul>
										<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOAN_PAYMENT");?></li>
										<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
									</ul>
							 </td>
								<td width="20%"></td>
							</tr> 
						</table>
					</td>
				</tr>
				<tr>
					<td>
						<table id="exportExcel" class="content-data" border="1" cellspacing="0">
							<?php if(!empty($this->loantotalcollect_list)) {
								foreach ($this->loantotalcollect_list as $index => $rs){
									if ($client_id!=$rs["client_id"]) {
									?>
								<thead>
									<tr style="background: #eaedf5">
										<td colspan="14" class="style" style="text-align: left;">&nbsp;
										<?php 
											
												 echo $tr->translate("CUSTOMER_NAME").':'.$rs["client_name"].',';
												 echo $tr->translate("SEX").':';
													if (!empty($rs['sex']) AND $rs['sex']==1){
													echo "M";
												}
												else {
													echo "F";
												}
											
												$client_id=$rs["client_id"];
											?>&nbsp;
										</td>
									</tr>
									<tr class="style-head" >
										<td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("PAWN_CODE");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("PAID_PRINCIPAL");?>&nbsp;</td>                   
										<td>&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("SERVICE CHARGE");?>&nbsp;</td>	 
										<td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>                   
										<td>&nbsp;<?php echo $tr->translate("PAY_DATE");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("RECIEPT_NO");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("PAYMENTED");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("INPUT_DATE");?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("PAYMENT_OPTION");?>&nbsp;</td>
									</tr>
								</thead>
								<?php }?>              
						 <?php 
								   if($rs['currency_type']==1){
										$principle_r = $principle_r+$rs["principal_paid"];
										$interst_r = $interst_r+$rs["interest_paid"];
										$penalize_r = $penalize_r+$rs["penalize_paid"];
										$service_charge_r = $service_charge_r+$rs["service_paid"];
								   }elseif($rs['currency_type']==2){
										$principle_d = $principle_d+$rs["principal_paid"];
										$interst_d = $interst_d+$rs["interest_paid"];
										$penalize_d = $penalize_d+$rs["penalize_paid"];
										$service_charge_d = $service_charge_d+$rs["service_paid"];
								   }else{
										$principle_b = $principle_b+$rs["principal_paid"];
										$interst_b = $interst_b+$rs["interest_paid"];;
										$penalize_b = $penalize_b+$rs["penalize_paid"];;
										$service_charge_b = $service_charge_b+$rs["service_paid"];
								   }
						   ?>
							<tr class="style-rowdata hover" >
								<td align="center">&nbsp;<?php echo $i++; ?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
								<td align="right">&nbsp;<?php echo number_format($rs["principal_paid"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>               		
								<td align="right">&nbsp;<?php echo number_format($rs["interest_paid"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
								<td align="right">&nbsp;<?php echo number_format($rs['penalize_paid'],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
								<td align="right">&nbsp;<?php echo number_format($rs["service_paid"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
								<td align="right">&nbsp;<?php echo number_format($rs["total_paymentpaid"],2);?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo date('d-m-Y',strtotime($rs["date_payment"]));?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
								<td align="right">&nbsp;<?php echo number_format($rs['total_paymentpaid'],2);?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs['date_input']));?>&nbsp;</td>
								<td style="<?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;<?php echo @$opt[$rs["payment_option"]];?>&nbsp;</td>
								
							</tr>
							<?php }}?>
							<tr>
								<td colspan="14" style="border-left:1px solid #fff;border-right:1px solid #fff; border-bottom:1px solid #fff;">&nbsp;</td>
							</tr>
						</table>
						<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
								<td align="right">&nbsp;</td>
								<td></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCIPLE");?></span>&nbsp;</td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_INTEREST");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PENELIZE");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?></span></td>
								<td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PAYMENTED");?></span></td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($principle_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($interst_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($penalize_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($service_charge_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($principle_d+$interst_d+$penalize_d+$service_charge_d,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							  <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("REILS");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($principle_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($interst_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($penalize_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($service_charge_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($principle_r+$interst_r+$penalize_r+$service_charge_r,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
								
							  <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("BATH");?></td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($principle_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($interst_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($penalize_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($service_charge_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($principle_b+$interst_b+$penalize_b+$service_charge_b,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 
						</table>
						  <br />
					   <?php echo $this->footerReport;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>