<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_PRODUCT'));
	
	$user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$session_user=new Zend_Session_Namespace(SYSTEM_SES);
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$rs = $this->rspro;
	
?>		
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('EDIT_PRODUCT');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					var identity = $('#identity').val();
					if(identity==""){
						infoMessageAlert('<?php echo $tr->translate("Please insert amount product to stock");?>');
						return false;
					}
					dijit.byId('savenew').set('disabled',true);
		    		dijit.byId('saveclose').set('disabled',true);
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="row">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("PRODUCT_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ITEM_NAME");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input class="fullside" dojoType="dijit.form.ValidationTextBox" required="1" id="name" name="name" value="<?php echo $rs['item_name'];?>" type="text">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ITEM_CODE");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input class="fullside" dojoType="dijit.form.TextBox" id="pro_code" name="pro_code" value="<?php echo $rs['item_code'];?>" type="text">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TYPE");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="product_type" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRODUCT_CATEGORY");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="category_id" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COST_PRICE");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input class="fullside" dojoType="dijit.form.NumberTextBox" required="true" id="cost_price" name="cost_price" value="<?php echo $rs['cost_price'];?>" type="text">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SOLD_PRICE");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input class="fullside" dojoType="dijit.form.NumberTextBox" required="true" id="selling_price" name="selling_price" value="<?php echo $rs['selling_price'];?>" type="text">
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> 
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="status" id="status" >
										<option value="1" <?php if ($rs['status']==1){ echo 'selected="selected"';}?> ><?php echo $tr->translate('ACTIVE');?></option>
										<option value="0" <?php if ($rs['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE');?></option>
									</select>
							   </div>
							</div>
							<div class="row g-3">
								<label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?></label>
							</div>
							<div class="row g-3">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<input class="fullside" style="min-height:50px;" dojoType="dijit.form.Textarea" id="description" name="description" value="<?php echo $rs['note'];?>" type="text">
							   </div>
							</div>
							
						</div>
					</div>
	             </div>
	             <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("QTY_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
								<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
								<input type="hidden" name="id" id="id" value="<?php echo $rs['id'];?>" >
								<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-plus" onclick="checkbranch();" label="<?php echo $tr->translate("ADD_BRANCH")?>"  dojoType="dijit.form.Button" />
							</div>
						</div>
					</div>
	             </div>
	         </div>
	        <div class="clearfix"></div>
			<div class="card-box">
             	<div class="col-sm-12 border-top mt-2 py-2 text-center">
		    		<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("GO_EDIT")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" />
	    		</div>
	    	</div>
		</form>
	</div>
</div>
	
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_pro_cate" >
		<form id='frm_add_pro_cate' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<div class="card">
				<div class="card-header">
					<h5 class="card-title mb-0"><i class="fa fa-sitemap"></i>&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?></h5>
				</div>
				<div class="card-body">
					<div class="row g-3">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input class="fullside"  dojoType="dijit.form.ValidationTextBox" name="cat_name" id="cat_name" type="text" required="required" />
	                   </div>
	                </div>
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
							<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save" name="go_save" id="go_save" label="<?php echo $tr->translate("GO_SAVE");?>" dojoType="dijit.form.Button"  onclick="addProCate();"/>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/Dialog"]);
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Textarea");

var cate_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_cate));?> );
protype_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_protype));?> );

$('#product_id').submit(function() {
	category = $("#category").val();
    if(category==''){
        infoMessageAlert("សូមជ្រើសរើស ប្រភេទផលិតផល! ");
        $('#category').select2('open');
        return false;
    }
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;
	    
	}
});
dojo.ready(function(){	
	new dijit.form.FilteringSelect({
		store: cate_store,
		required: false,		           
		name: "category_id",
		id: "category_id",
		searchAttr: "name",
		autoComplete: false,
		value:"<?php echo $rs['cate_id'];?>",
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			category_id = dijit.byId('category_id').get('value');
		    if(category_id==-1){
		   		dijit.byId("popup_pro_cate").show();
		    }
	}
		}, "category_id");
	new dijit.form.FilteringSelect({
		store: protype_store,
		required: false,		           
		name: "product_type",
		id: "product_type",
		value:"<?php echo $rs['product_type'];?>",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
			
	    }
		}, "product_type");
	checkbranch();
	 //initailize();
});
	index = 0;
	function totalQty(index){
		o_measure = $('#qty_unit').val();
		unit_qty = $('#current_qty_'+index).val();
		other_qty = $('#other_qty_'+index).val();
		total_other_qty = parseFloat(other_qty)/parseFloat(o_measure);
		total_qty = parseFloat(unit_qty)+ total_other_qty;
		$('#total_qty_'+index).val(total_qty);
	}
var template = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
branch_opt = '';
function addNewProLocation(){
		col++;no++;
		template='';
		if(title!=1){    
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("BRANCH_NAME");?></th>';
			temp+='<th ><?php echo $tr->translate("CURRENT_QTY");?></th>';
			temp+='<th ><?php echo $tr->translate("ចំនួនជិតអស់ពីស្តុក");?></th>';
			temp+='<th><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		 }
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center"><select id="branch_id'+col+'" name="branch_id'+col+'" dojoType="dijit.form.FilteringSelect">'+branch_opt+'</select></td>';
			template+='<td width="20%"><input dojoType="dijit.form.NumberTextBox" type="text" required="true" id="total_qty_'+col+'" name="total_qty_'+col+'" value="" /></td>';
			template+='<td width="25%"><input type="text"  name="alert_qty'+col+'" class="fullside" id="alert_qty'+col+'" dojoType="dijit.form.NumberTextBox" /></td>';
			template+='<td width="25%"><input type="text"  name="remark'+col+'" class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
}
function initailize(){
	<?php if(!empty($this->rs_location)){
		foreach($this->rs_location as $row){
	?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("BRANCH_NAME");?></th>';
		temp+='<th ><?php echo $tr->translate("CURRENT_QTY");?></th>';
		temp+='<th ><?php echo $tr->translate("ចំនួនជិតអស់ពីស្តុក");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="50px" align="center"><select id="branch_id'+col+'" name="branch_id'+col+'" readonly ="readonly" dojoType="dijit.form.FilteringSelect">'+branch_opt+'</select></td>';
		template+='<td width="20%"><input dojoType="dijit.form.NumberTextBox" type="text" required="true" id="total_qty_'+col+'" name="total_qty_'+col+'" value="" /></td>';
		template+='<td width="25%"><input type="text"  name="alert_qty'+col+'" class="fullside" id="alert_qty'+col+'" dojoType="dijit.form.NumberTextBox" /></td>';
		template+='<td width="25%"><input type="text"  name="remark'+col+'" class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" /><input type="hidden"  name="detailid'+col+'" class="fullside" id="detailid'+col+'" dojoType="dijit.form.TextBox" /></td>';

	    tmp='<tr id="row'+col+'">';
	    tmp+="</tr>";
	    dojo.query("#table_row").append(tmp);

	    if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	dijit.byId('branch_id'+col).attr('value',<?php echo $row['location_id']?>);
	dijit.byId('total_qty_'+col).attr('value',<?php echo $row['qty']?>);
	dijit.byId('alert_qty'+col).attr('value',<?php echo $row['qty_warning']?>);
	dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
	dijit.byId('detailid'+col).attr('value','<?php echo $row['id']?>');
	<?php } }?>
}
var first=1;
var url_checkbranch = '<?php echo $this->url(array('module'=>'installment','controller'=>'product','action'=>'getlocation')); ?>';
function checkbranch(){
	loadingBlock();
		dojo.xhrPost({
			url:url_checkbranch,
			form: dojo.byId("frm_add_tran"),
			handleAs:"json",
			load: function(data) {
				
				if(data==''){
					infoMessageAlert('<?php echo $tr->translate("No More Branch Available");?>');
					HideloadingBlock();
					return false;
				}
				branch_opt = data;
				if(first==1){
					initailize();
					first = 2;
				}else{
					addNewProLocation();
				}
				HideloadingBlock();
				
			},
			error: function(err) {
				 infoMessageAlert(err);
			}
		});
  }
function deleteRecord(index,type) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	function getPopupCategory(){
		val = $('#category').val();
		if(val==-1){
			$('#categorypopup').modal('show');
		}
	}
	<?php $url_add_category =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-category')); ?>
	function addNewCategory(){
		var cat_name  = $("#cat_name").val();
		$.ajax({
			url: "<?php echo $url_add_category;?>",
			type: "post",
			data: $('#frmCat').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				 $('#category').append($("<option></option>").attr("value",rs['cat_id']).attr("selected",true).text(cat_name));                       
				 $("#category").select2();
				$('#categorypopup').modal('hide');
			},
			error:function(err){
				infoMessageAlert("faile insert");
			}
		});
	}
var url_addcate = '<?php echo $this->url(array('module'=>'installment','controller'=>'product','action'=>'add-category')); ?>';
function addProCate(){
		if(dijit.byId('frm_add_pro_cate').validate()){	
			dijit.byId('go_save').set('disabled',true);
			dojo.xhrPost({
				url:url_addcate,
				form: dojo.byId("frm_add_pro_cate"),
				handleAs:"json",
				load: function(data) {
					var Itemmake = { 
						     id: data,
							 name: dijit.byId('cat_name').get('value')
						};
				 	addDataToSelectbox(dijit.byId('category_id'), cate_store, Itemmake, data);
				    dijit.byId('frm_add_pro_cate').reset();
				    dijit.byId("popup_pro_cate").hide();
				    dijit.byId('go_save').set('disabled',false);
				},
				error: function(err) {
					  dijit.byId("popup_pro_cate").hide();
					  dijit.byId('go_save').set('disabled',false);
				}
			});
		 }
	  }
</script>