<?php 
	$frm = $this->formFilter;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$urlEdit = $this->baseUrl()."/installment/product/edit/id/";
	$url_copy = $this->baseUrl()."/installment/product/copy/id/";
?>
<title><?php echo $tr->translate("PRODUCT");?></title>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-cubes" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('PRODUCT');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("product_type");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("category");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
   <div class="card-body">
	  <?php echo $this->list;?>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<script>
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			 if(key=="copy"){
				url='<?php echo $url_copy;?>';
			 }else if(key=="edit"){
				url='<?php echo $url_copy;?>';
			}
			gotoAction();
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", },
			"copy": {name: "<?php echo $tr->translate("Copy");?>", icon: "copy", accesskey: "c o p y"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_self');
}
</script>