<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("VIEW_LOAN_RESCHEDULE"));
$frm = $this->frm_search;
?>

<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-calendar"></i>&nbsp;<?php echo $tr->translate('VIEW_LOAN_RESCHEDULE');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			    <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("client_name");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("repayment_method");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('co_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('currency_type');?>
			   		</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('pay_every');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>

<script>
dojo.require("dijit.form.DateTextBox");
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}
</script>