<?php
	 $tr = Application_Form_FrmLanguages::getCurrentlanguage();	
    echo $this->headTitle($tr->translate('ADD_TRANSFER_ZONE')); 
	$frm = $this->frm_transfer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
</script>

<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-map-pin-up"></i>&nbsp;<?php echo $tr->translate('TRANSFERZONE');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferzone','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
 				 if(this.validate()) {
   					 if(dijit.byId('branch_name').get('value')==''){
    					 infoMessageAlert('Please Select Branch');
   						  dijit.byId('branch_name').focus();
  						   return false;
   						}
   					 if(dijit.byId('to_co').get('value')==''){
     					infoMessageAlert('Please Select From CO');
    					 dijit.byId('to_co').focus();
    					 return false;
   						}
					if(dijit.byId('to_co_code').get('value')==''){
    					 infoMessageAlert('Please Select To CO ');
    					 dijit.byId('to_co_code').focus();
    					 return false;
   					}
					if(dijit.byId('zone_name').get('value')==''){
						infoMessageAlert('Please Select Zone Name');
      					  dijit.byId('zone_name').focus();
      					  return false;
					}
					dijit.byId('btn_save').set('disabled',true);
					dijit.byId('btn_save_close').set('disabled',true);
   					 return true;
   				}else {
  					  return false;
 				  }
				</script>
    			<div class="row">
	    			<!-- BRANCH_INFO  -->
					<div class="col-md-4 col-sm-4 col-xs-12">
						 <div class="card card-form mb-4">
							<div class="card-header d-flex justify-content-between">
								<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
							</div>
							<div class="card-body">
								<div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('branch_name');?>
								   </div>
								</div>
								 <div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('Date');?>
								   </div>
								</div>
								<div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ZONE_NAME");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('zone_name');?>
								   </div>
								 </div>
							 </div>
						 </div>
	               	</div>
	               	<!--/. BRANCH_INFO  -->
	               	
	               	<!-- CO_INFO  -->
					<div class="col-md-4 col-sm-4 col-xs-12">
						 <div class="card card-form mb-4">
							<div class="card-header d-flex justify-content-between">
								<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CO_INFO");?></h5>
							</div>
							<div class="card-body">
								<div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TO_CO");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('to_co_code');?>
								   </div>
								</div>
								 <div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TO_CO");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('to_co');?>
								   </div>
								</div>
								 <div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('Note');?>
								   </div>
								</div>
								 <div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<?php echo $frm->getElement('status');?>
								   </div>
								</div>
							</div>
						</div>
	               	</div>
	               	<!--/. CO_INFO  -->
	            </div>
    		</div>
    		 <!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    		<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" onclick="submitDataClose()" value="រក្សាទុក" name="btn_save" id="btn_save" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="រក្សាទុក & ចាកចេញ" name="btn_save_close"  id="btn_save_close" label="<?php echo $tr->translate('SAVENEW');?>" id="submitButton_Save" dojoType="dijit.form.Button"  />
    			</div>
    		</div>
	    	<!--/. Button Save  -->
		</form>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("formc_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
			
		}else if(type==2){
			id = dijit.byId("formc_co").get('value');
			dijit.byId("formc_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("to_co").get('value');		
			dijit.byId("to_co_code").attr('value',to);
			dijit.byId("to_co").attr('value',to);
		}else if(type==4){
			to = dijit.byId("to_co_code").get('value');
			dijit.byId("to_co_code").attr('value',to);
			dijit.byId("to_co").attr('value',to);
		}
	}

	function submitDataClose(){
		if(dijit.byId('branch_name').get('value')==''){
		     infoMessageAlert('Please Select Branch');
		     dijit.byId('branch_name').focus();
		     return false;
		   	}
		    if(dijit.byId('to_co').get('value')==''){
		     infoMessageAlert('Please Select From CO');
		     dijit.byId('to_co').focus();
		     return false;
		   	}
			if(dijit.byId('to_co_code').get('value')==''){
		     infoMessageAlert('Please Select To CO ');
		     dijit.byId('to_co_code').focus();
		     return false;
		   	}
			if(dijit.byId('zone_name').get('value')==''){
				infoMessageAlert('Please Select Zone Name');
		        dijit.byId('zone_name').focus();
		        return false;
			}
		if(dijit.byId('frm_add_tran').validate()) {
			dijit.byId('btn_save').set('disabled',true);
			dijit.byId('btn_save_close').set('disabled',true);
			var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'transferzone','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_add_tran"),		    
				load: function(data) {
					infoMessageAlert('<?php echo $tr->translate('INSERT_SUCCESS');?> !',1);
					window.location.href ="<?php echo $this->baseUrl();?>/loan/transferzone";
				},
				error: function(e) {
				}
			});
		}
	}
	
</script>
