  <?php 
	  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	  $session_user=new Zend_Session_Namespace(SYSTEM_SES);
	  $url_report=$session_user->report_url;
  ?>
  <title><?php echo $tr->translate("Installment Report");?></title>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 60px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>

	<div class="card">
		<div class="card-content collapse show">
			<div class="card-box report-list">
			<h3 style="font-family:'khmer os muol light';font-size:14px;text-align: center; color: #666;padding:2px 0;"><?php echo $tr->translate("Installment Report");?></h3><hr>
				<!--border-bottom:2px solid #F1F1F1;-->
				<div class="row top_tiles">
			<?php
				$db_user=new Application_Model_DbTable_DbUsers();
				$url_report=$db_user->getAclReport(1,'installments');
				 if(!empty($url_report)){
					foreach($url_report as $rs){
						if($rs['action']=='agreement' || $rs['action']=='index'){continue;}
						if($rs['action']=='purchasedetail' || $rs['action']=='index'){
							continue;
						}
						if($rs['action']=='saleinvoice' || $rs['action']=='index' || $rs['action']=='generalsaleinvoice'){
							continue;
						}
						if($rs['action']=='saleschedule' || $rs['action']=='index' || $rs['action']=='paymenthistory'){
							continue;
						}
						
					?>
				   <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $this->url(array("module"=>'report',"controller"=>'installments','action'=>$rs['action']));?>">
						<div title="<?php echo $tr->translate(strtoupper($rs['label']));?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate(strtoupper($rs['label']));?></h3>
						</div>
						</a>
			        </div>
					<?php 
					}	
				}	?>
				</div>
			</div>
		</div>
	</div>
  <div style="clear: both;"></div>