<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Report Inventory"));
	 $frm = $this->formFilter;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Report Inventory');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('branch_id');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement("product_type");?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement("category");?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('status');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
	</form>
	<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px; }
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				
				table.content-data { page-break-inside:auto }
				table.content-data  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
				table.tb-footer{
					font-family: 'Times New Roman','Khmer OS Battambang'; 
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:12px;
					width:100%;
				}
				table.tb-footer tr.style-head{
					line-height: 24px; 
					text-align: center; 
					background: #ccd9ff;
				}
			</style>
			<table width="100%" >
				<thead>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="30%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="40%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light';white-space: nowrap;"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("Report Inventory");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo date("d-m-Y");?></li>
			                		</ul>
			                    </td>
			                    <td width="30%"></td>
			                </tr> 
			            </table>
			       </td>
			    </tr>
			    </thead>
			    <tr>
			    	<td id="exportExcel">
			            <table class="content-data"  border="1" cellspacing="0">
			                <thead>
				               <tr class="style-head" align="center" >
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("PRODUCT_CATEGORY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CURRENT_QTY");?>&nbsp;</td> 
				                    <td>&nbsp;<?php echo $tr->translate("COST_PRICE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("SOLD_PRICE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
				                </tr>
			                </thead>
			                <?php 
			                	$location="";
			                	$gTotalCost=0;
			                	$gTotalPrice=0;
			                    if(!empty($this->inventory))
			                	foreach ($this->inventory as $key => $rs){ 
				                	$totalCost = $rs["cost_price"] * $rs["qty"];
				                	$totalSoldPrice = $rs["selling_price"] * $rs["qty"];
				                	
				                	$gTotalCost = $gTotalCost +$totalCost;
				                	$gTotalPrice = $gTotalPrice +$totalSoldPrice;
			                    ?>
			                    <?php 
			                    if ($location != $rs['location_id']){
			                    ?>
			                     <tr class="style hover" style=" line-height:20px; ">
			                     	<td colspan="11" align="center" style="font-weight: 600; "><?php echo $rs["branch_namekh"];?></td>
			                     </tr>
			                    <?php }$location = $rs['location_id'];?>
				                <tr class="style-rowdata hover">
				               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["categoryName"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["item_code"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["item_name"];?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo $rs["qty"];?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["cost_price"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php  echo number_format($totalCost,2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["selling_price"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($totalSoldPrice,2);?>&nbsp;</td>
				               		<td >&nbsp;<?php echo $rs["note"];?>&nbsp;</td>
				               		<td align="center" >&nbsp;<?php if ($rs["status"]==1){ echo $tr->translate("ACTIVE");}else{ echo $tr->translate("DEACTIVE");};?>&nbsp;</td>
				                </tr>
			                <?php }?>
			                	<tr style="border-bottom: solid 1px #fff;border-left: solid 1px #fff;border-right: solid 1px #fff;">
			                		<td colspan="9" align="right"><?php echo $tr->translate("Grand Total Cost");?>&nbsp;</td>
			                		<td colspan="2" align="right">&nbsp;<strong><?php echo "$ ".number_format($gTotalCost,2)?></strong>&nbsp;</td>
			                	</tr>
			                	<tr style="border-bottom: solid 1px #fff;border-left: solid 1px #fff;border-right: solid 1px #fff;">
			                		<td colspan="9" align="right"><?php echo $tr->translate("Grand Total Price");?>&nbsp;</td>
			                		<td colspan="2" align="right">&nbsp;<?php echo "$ ".number_format($gTotalPrice,2)?>&nbsp;</td>
			                	</tr>
			             </table>
			    	</td>
			    </tr>
			</table>
			<br />
			<?php echo $this->footerReport;?>
	</div>
</div>