<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("NEARLY OUT STOCK REPORT"));
 $frm = $this->formFilter;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('NEARLY OUT STOCK REPORT');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("category");?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('status');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 14px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px;}
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				
				table.content-data { page-break-inside:auto }
				table.content-data  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
			</style>
			<table width="100%" >
				<thead>
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0; border:none;">
							<tr>
								<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
								<td width="60%" valign="top">
									<ul>
										<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("NEARLY OUT STOCK REPORT");?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
						</table>
					</td>
				</tr>
				</thead>
				<tr>
					<td id="exportExcel">
						<table class="content-data" border="1" cellspacing="0">
							<thead>
								<tr class="style-head" ><tr class="style-head" >
									<td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PRODUCT_CATEGORY");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("CURRENT_QTY");?>&nbsp;</td> 
									<td>&nbsp;<?php echo $tr->translate("COST_PRICE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
								</tr>
							</thead>
							<?php 
								$location="";
								$gTotalCost=0;
								$gTotalPrice=0;
								if(!empty($this->inventory)) 
								foreach ($this->inventory as $key => $rs){ 
									$totalCost = $rs["cost_price"] * $rs["qty"];
									$totalSoldPrice = $rs["selling_price"] * $rs["qty"];
									
									$gTotalCost = $gTotalCost +$totalCost;
									$gTotalPrice = $gTotalPrice +$totalSoldPrice;
								?>
								<?php 
								if ($location != $rs['location_id']){
								?>
								 <tr class="style hover" style=" line-height:20px; ">
									<td colspan="9" align="center"><?php echo $rs["branch_namekh"];?></td>
								 </tr>
								<?php }$location = $rs['location_id'];?>
								<tr class="style-rowdata hover">
									<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $rs["categoryName"];?>&nbsp;</td>
									<td>&nbsp;<?php echo $rs["item_code"];?>&nbsp;</td>
									<td>&nbsp;<?php echo $rs["item_name"];?>&nbsp;</td>
									<td align="center" style="background: #ff3a3a;">&nbsp;<?php echo $rs["qty"];?>&nbsp;</td>
									<td align="right" >&nbsp;<?php echo number_format($rs["cost_price"],2);?>&nbsp;</td>
									<td align="right">&nbsp;<?php  echo number_format($totalCost,2);?>&nbsp;</td>
									<td>&nbsp;<?php echo $rs["note"];?>&nbsp;</td>
									<td align="center">&nbsp;<?php if ($rs["status"]==1){ echo $tr->translate("ACTIVE");}else{ echo $tr->translate("DEACTIVE");};?>&nbsp;</td>
								</tr>
							<?php }?>
								<tr style="border-bottom: solid 1px #fff;border-left: solid 1px #fff;border-right: solid 1px #fff;">
									<td colspan="7" align="right"><?php echo $tr->translate("Grand Total Cost");?>&nbsp;</td>
									<td colspan="2" align="right">&nbsp;<strong><?php echo "$ ".number_format($gTotalCost,2)?></strong>&nbsp;</td>
								</tr>
						 </table>
					</td>
				</tr>
			</table>
			<br />
			 <?php echo $this->footerReport;?>
		</div>
	</div>
</div>