<?php 
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frms = $this->formFilter;
?>
<meta charset="utf-8">
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<title><?php echo $tr->translate("LOAN_INSTALMENT_OUTSTADING");?></title>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('LOAN_INSTALMENT_OUTSTADING');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="card-box">
					<div class="row g-3">
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('adv_search');?>
						 </div>
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('branch_id');?>
						 </div>
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('shop_id');?>
						 </div>
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('members');?>
						 </div>
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frms->getElement('category');?>
						 </div>
					</div>
					<div class="row g-3">
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="product_type" id="product_type" >
								<option value="-1"><?php echo $tr->translate('PRODUCT_TYPE');?></option>
								<?php if (!empty($this->producttype)) foreach ($this->producttype as $pt){?>
								<option value="<?php echo $pt['id'];?>" <?php if ($this->search['product_type']==$pt['id']){ echo 'selected="selected"';}?>><?php echo $pt['name'];?></option>
								<?php }?>
							</select>
						 </div>
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('start_date');?>
						 </div>
						 <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('end_date');?>
						 </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					   </div>
					</div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 20px;font-size: 12px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			table tr td ul li{list-style: none;line-height: 25px;}
			th{padding: 5px;}
			table.content-data { page-break-inside:auto }
			table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			table.content-data{
				border-collapse:collapse;
				width:100%;
				border:1px solid #000; 
				font-family:'Times New Roman','Khmer OS Battambang';
				font-size:13px;
				white-space: nowrap;
				margin:0 auto;
			}
			table.content-data thead tr.style-head {
			   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #ccd9ff;
				text-align: center;
			}
			table.content-data tr.style-rowdata {
				font-size:12px; 
				height: 23px;
			}
			
			table.tb-footer{
				font-family: 'Times New Roman','Khmer OS Battambang'; 
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:12px;
				width:100%;
			}
			table.tb-footer tr.style-head{
				line-height: 24px; 
				text-align: center; 
				background: #ccd9ff;
			}
			.border_bottom {
				border-bottom: 1px solid #000;
			}
		</style>
			<table style="font-family: 'Khmer OS Content'; width:100%;">
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="60%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:15px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("LOAN_INSTALMENT_OUTSTADING");?></li>
			                			<li style="text-align:center; font-size:15px;"><?php echo date('D-d-m-Y',strtotime($this->fordate));?></li>
			                		</ul></td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td id="exportExcel">
			            <table class="content-data" border="1"​  cellspacing="0">
			                <thead>
			                	<tr class="style-head" >
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("SHOP_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("INSTALLMENT_NO");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CATEGORY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("PRODUCT");?>&nbsp;</td>
				                    <td> &nbsp;<?php echo $tr->translate("SOLD_DATE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("END_DATE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("TOTAL_INSTALLMENT_AMOUNT");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("INSTALLMENT_DURATION")." (".$tr->translate('MONTH').")";?>&nbsp;</td>
				                   	<td>&nbsp;<?php echo $tr->translate("PAID");?>&nbsp;</td>
				                   	<td>&nbsp;<?php echo $tr->translate("PERCENTAGE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("NOT_TO_REPAY");?>&nbsp;</td>
				                </tr>
			                </thead>
			               <?php 
			               	   $db = new Report_Model_DbTable_DbLoan();
				               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
				               $result_b=0;$result_r=0;$result_d=0;$count_d=0;
				               $count_r=0;$count_b=0;$amt_loanmonth=0;$amt_loanweek=0;
				               $amt_loanday=0;
				               $number = 0;
			               	if(!empty($this->outstandloan))foreach($this->outstandloan as $key =>$row){?>
			               	<?php 
						            if($row['total_principaid']==$row['selling_price']){
						              continue;
						            }
						            $number ++;
						            $installmentPrice = $row['selling_price'] - $row['paid'];
			               			$total_receive= $row['total_principaid']- $row['paid'];
				             	    $amt_d = $amt_d+$installmentPrice;
				               		$amn_d = $amn_d+$total_receive;
				               		$result_d=number_format(($amn_d/$amt_d)*100,2).' %';
									$count_d=$count_d+1;
			              	 ?>
								<tr class="style-rowdata hover" align="center">
									<td align="center">&nbsp;<?php echo $number; ?>&nbsp;</td>
									<td align="left">&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['shop_name']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['sale_no'];?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['client_kh']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['cateName']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['item_name']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo date('d-m-Y',strtotime($row['date_sold']));?>&nbsp;</td>
									<td>&nbsp;<?php echo date('d-m-Y',strtotime($row['date_line']));?>&nbsp;</td>
									<td align="right">&nbsp;<?php echo number_format($installmentPrice,2);//.' '.$row['currency_type']; ?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo number_format($row['duration']);//.$row['termborrow'];?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo $row['total_principaid']- $row['paid'];?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo ($installmentPrice==0)?$total_receive:(round(($total_receive/$installmentPrice),2)*100).' %'; ?>&nbsp;</td>
									<td align="right">&nbsp;<?php echo number_format(($installmentPrice-$total_receive),2);?>&nbsp;</td>
								</tr>
							<?php }?>
			            </table>
			            <br />
			            <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                    <td align="right">&nbsp;</td>
			                    <td align="center">&nbsp;</td>
			                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("INSTALLMENT_AMOUNT");?></span></td>
			                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?></span></td>
			                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("PERCENTAGE");?></span></td>
			                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("NOT_TO_REPAY");?></span></td>
			                    <td align="right">&nbsp;</td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
			                    <td align="right"></td>
			                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tr->translate("INSTALLMENT_NUMBER");?>:&nbsp;<?php echo $count_d;?>&nbsp;</td>
			                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
			                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
			                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_d;?>&nbsp;</td>
			                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d-$amn_d,2);?>&nbsp;</td>
			                    <td align="right">&nbsp;</td>
			                 </tr>
	                 </table>
			         <br />
			             <?php echo $this->footerReport;?>
			    	</td>
			    </tr>
			</table>
		</div>
	</div>
</div>