<?php 
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
$db = new Report_Model_DbTable_DbLoan();

$tran = $this->tran_schedule;
$client = $this->client;											
?>
<?php  
	$end_dat=$this->date_show;
?>
<?php 
	$db_keycode = new Application_Model_DbTable_DbKeycode();
	$key_code= $db_keycode->getSystemSetting(9);
	$free_day=$key_code['value'];
	
	$keyvalue = $db_keycode->getKeyCodeMiniInv();
	$interest_penalty = $keyvalue['interst_late'];
	
	$frm = $this->frm_search;
	$frms = $this->formFilter;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_INSTALLMENT_COLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_INSTALLMENT_COLLECT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
  	<form method="post">
  		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('adv_search');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('branch_id');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('members');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frms->getElement('category');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('end_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
           	</div>
        </div>
	</form>
	<div id="divPrint">
		<style>
			.style{
				line-height: 20px;font-size: 12px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			table tr td ul li{list-style: none;line-height: 25px;}
			th{padding: 5px;}
			
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			th{ text-align: center;}
		table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data thead tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:12px; 
			height: 23px;
		}
		
		table.tb-footer{
			font-family: 'Times New Roman','Khmer OS Battambang'; 
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:12px;
			width:100%;
		}
		table.tb-footer tr.style-head{
			line-height: 24px; 
			text-align: center; 
			background: #ccd9ff;
		}
	</style>
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
		            	<tr>
		                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
		                	<td width="60%" valign="top">
		                	<ul>
	                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
	                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_INSTALLMENT_COLLECT");?></li>
	                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['end_date'])){?><?php echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
	                		</ul>
	                    </td>
		                    <td width="20%"><strong style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><label id="lbl_customer"></label></strong></td>
		                </tr>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="content-data" border="1"​ width="100%">
		             <thead>
		                 <tr class="style-head" >
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("INSTALLMENT_NO");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PHONE")." / ".$tr->translate("ADDRESS");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAID_TIME");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LATE_DAY");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LATE");?>&nbsp;</td>
		                    <td colspan="2">&nbsp;<?php echo $tr->translate("PAYMENT");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("TOTAL_PAYMENT");?>&nbsp;</td>
		                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAY_DATE");?>&nbsp;</td>
		                </tr>
		                <tr class="style-head" >
		                    <td><?php echo $tr->translate("OS_AMOUNT");?></td>
		                    <td><?php echo $tr->translate("INTEREST");?></td>
		                 </tr>
		               </thead> 
		                <?php 
	                	    $amt_d1 = 0;
	                	    $amt_d2 = 0;
	                	    $amt_d3 = 0;
	                	    $amt_d4 = 0;
	                	    $total_d=0;
	                	    $result=0;
	                	    $pene_amd=0;
	                	    $dbc = new Application_Model_DbTable_DbGlobal();
							$dbl = new Loan_Model_DbTable_DbLoanILPayment();
							$end_dat = $this->list_end_dates;
			           ?>
		               <?php if(!empty($tran))foreach($tran as $key =>$row){
			               	$loan_number = $row["sale_no"];
			               
			               	$total_pay=($row['principle_after']+$row['total_interest_after']);
			               	$total_day=strtotime($end_dat)-strtotime($row['date_payment']);
			               	$amount_lateday=$total_day/(60*60*24)-$free_day;
			               	$total_late_day=$total_day/(60*60*24);
			               	$currentlate =$total_day/(60*60*24);
		               	?>
		               	<tr class="style-rowdata hover" align="center" >
		                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1; ?></td>
		                    <td align="left">&nbsp;<?php echo $row['branch_namekh'];?>&nbsp;</td>
		                    <td align="left">&nbsp;<?php echo $row['sale_no'];?>&nbsp;</td>
		                    <td align="left" style="min-width:60px;">&nbsp;<?php echo $row['name_kh'];?>&nbsp;</td>
		                    <td style="line-height: 18px; white-space: normal !important;max-width: 150px;width: 150px;padding: 5px;overflow-wrap: break-word;">
		                    	<?php 
		               				echo $row["phone_number"];
		               				echo empty($row['village_name'])?"":",".$row['village_name'];
		               				echo empty($row['commune_name'])?"":",".str_replace("Commune","",$row['commune_name']);
		               				echo empty($row['district_name'])?"":",".$row['district_name'];
		               				echo empty($row['province_en_name'])?"":",".$row['province_en_name'];
		               			?>
		                    </td>
		                    <?php $str_day = date('D',strtotime($row['date_payment']));
		                    	$day_as_khmer = $dayin_khmer[$str_day];
		                    ?>
		                    <td align="center">&nbsp;<?php echo $row["item_name"];?>&nbsp;</td>
		                    <td align="center">&nbsp;<?php //echo $row["amount_late"]." ដង";?>&nbsp;</td>
		                    <td align="center">&nbsp;<?php echo  $total_late_day." ថ្ងៃ";?>&nbsp;</td>
		                   
		                    <td align="center">&nbsp;<?php echo $row['times']."/".$row['duration'];?>&nbsp;</td>
		                    <td align="center">&nbsp;<?php echo ($row['principle_after']); ?>&nbsp;</td>
		                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest_after'],2));?>&nbsp;</td>
		                    <td>
		                    <?php 
		                    $total_pay=($row['principle_after']+$row['total_interest_after']);
		                    if($row['last_pay_date']==null or $row['last_pay_date']==""){
		                    	$total_day=strtotime($end_dat)-strtotime($row['date_payment']);
		                    	$amount_lateday=$total_day/(60*60*24)-$free_day;
		                    	$late_day = $total_day/(60*60*24);
		                    }else {
		                    	$total_day=strtotime($end_dat)-strtotime($row['last_pay_date']);
		                    	$amount_lateday=$total_day/(60*60*24);
		                    	$late_day = $total_day/(60*60*24);
		                    }
		                    $pay_term="";
		                   ?>
		                    	<strong >
		                    	<?php $total_payment =$row['principle_after']+$row['total_interest_after'];
		                    	echo str_replace('.00', '', number_format($total_payment,2));//." ".$row['currencyname'];?>
		                    	</strong>
		                    </td>
		                    <td align="center">&nbsp<?php echo date_format(date_create($row["date_payment"]),'d-m-Y');?>&nbsp;;&nbsp;</td>
		                </tr>
			                <?php 
			                	$penelize =0;
					            $amt_d1 = $amt_d1+$row['principle_after'];
								$amt_d2 = $amt_d2+$row['total_interest_after'];
								$amt_d3 = $amt_d3+$penelize;
								$amt_d4 = $amt_d4+$total_payment;
								$total_d=$amt_d4;
			               ?>
		                <?php }?>
		            </table>
		            <!-- 
		            <div style="font-family:'khmer os battambang';display: block;height: 30px;"><?php echo$tr->translate("REPORT_LOAN_LATE");?></div>
		            <table  border="1"​ style="margin-top:-30px;border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
	    			<thead><tr bgcolor="#ccc" class="style" align="center" style="line-height: 24px;font-size:11px; background: #ccd9ff; font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;">
	                    <td><?php echo $tr->translate("NUM");?></td>
	                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td><?php echo $tr->translate("SALE_NO");?></td>
	                    <td><?php echo $tr->translate("CLIENT_NUM");?></td>
	                    <td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
	                    <td><?php echo $tr->translate("PHONE")." / ".$tr->translate("ADDRESS");?></td>
	                    <td><?php echo $tr->translate("ITEM_NAME");?></td>
	                    <td><?php echo $tr->translate("PAID_TIME");?></td>
	                    <td><?php echo $tr->translate("LATE_DAY");?></td>
	                 ​​​	<td><?php echo $tr->translate("LATE");?></td>
	                    <td><?php echo $tr->translate("OS_AMOUNT");?></td>
	                    <td><?php echo $tr->translate("INTEREST");?></td>
	                    <td><strong><?php echo $tr->translate("PAYMENT");?></strong></td>
	                    <td><?php echo $tr->translate("PAY_DATE");?></td>
	                </tr></thead>
	                <?php $i=1; $currentlate = 0;?>
	               <?php /*if(!empty($this->loanlate_list))foreach ($this->loanlate_list as $index => $rs){ ?>
	               		<?php 	$end_dat = $this->list_end_dates;
		               			$total_pay=($rs['principle_after']+$rs['total_interest_after']);
	               				$total_day=strtotime($end_dat)-strtotime($rs['date_payment']);
	               				$amount_lateday=$total_day/(60*60*24)-$free_day;
	               				$total_late_day=$total_day/(60*60*24);
		               			$currentlate =$total_day/(60*60*24);
		               			$pay_term="";
		               			if($amount_lateday<0){
		               				$amount_lateday=0;
		               				$result=0;
		               			}
               				$total_late=($rs['principle_after']+$rs['total_interest_after']);
               				if ($pay_term==1){
               					$result=$total_pay*($interest_penalty*($rs['interest_rate']/100)/1)*($amount_lateday);
               				}
               				if ($pay_term==2){
               					$result=$total_pay*($interest_penalty*($rs['interest_rate']/100)/7)*($amount_lateday);
               				}
               				if ($pay_term==3){
               					$result=$total_pay*($interest_penalty*(($rs['interest_rate']/100)/30))*($amount_lateday);
               				}
		               		$total_payment =$rs['principle_after']+$rs['total_interest_after'];
	               	?>
	               <?php if($currentlate>0){?>
	                <tr class="style hover" style=" line-height: 24px; font-size:11px; font-family: 'Times New Roman','Khmer OS Battambang'; white-space: nowrap;">
	               		<td style="text-align: center;"><?php echo $i++;?></td>
	               		<td>&nbsp;<?php echo $rs["branch_namekh"];?>&nbsp;</td>
	               		<td>&nbsp;<?php echo $rs["sale_no"];?>&nbsp;</td>
	               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
	               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
	               		<td>&nbsp;<?php echo $rs["phone_number"].",".$rs['village_name'].",".str_replace("Commune","",$rs['commune_name']).",".$rs['district_name'].",".$rs['province_en_name'];?>&nbsp;</td>
	               		<td align="center">&nbsp;&nbsp;<?php echo $rs["item_name"];?> &nbsp;</td>
	               		<td align="center">&nbsp;&nbsp;<?php echo $rs["amount_late"]." ដង";?> &nbsp;</td>
	               		<td align="center">&nbsp;&nbsp;<?php echo number_format($total_late_day,0)." Days";?> &nbsp;</td>
	               		<td align="center">&nbsp;&nbsp;<?php echo $rs['times']."/".$rs['duration'];?> &nbsp;</td>
	               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["principle_after"],2);?>&nbsp;</td>
	               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_interest_after"],2);?>&nbsp;</td>
	               		<td align="right" style="white-space: nowrap;"><strong style="font-family:'arial';">&nbsp;<?php echo number_format($total_payment,2);?></strong>&nbsp;</td>
	               		<td align="center">&nbsp;&nbsp;<?php echo date_format(date_create($rs["date_payment"]),'d-m-Y');?>&nbsp;</td>
	                </tr>
	                <?php }?>
	                <?php 
	               		 $penelize =0;
			             $amt_d1 = $amt_d1+$rs['principle_after'];
						 $amt_d2 = $amt_d2+$rs['total_interest_after'];
						 $pene_amd=$pene_amd+$penelize;
						 $amt_d4 = $amt_d4+$total_payment;
			             $amount_days = strtotime($this->list_end_dates)-strtotime($rs["date_payment"]);
			             $amount_days =  floor($amount_days/(60*60*24));
	               ?>
	                <?php } */?>
	            </table>
	             -->
		    	</td>
		    </tr>
		</table>
		<br />
		<table width="100%">
			<tr>
	    	<td style="font-family:'Times New Roman','Khmer OS Battambang';">
	             <table class="tb-footer" border="1"​ cellspacing="0">				 
					 <thead>
					 <tr class="style-head">
	                    <td><?php echo $tr->translate("TOTAL_PRINCIPLE");?></td>
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
	                    <td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
	                </tr>
					</thead>
	                 <tr>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
	                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1+$amt_d2,2);?>&nbsp;</td>
	                </tr>
	              </table> 
	               <table align="center" width="100%">
				   	<thead>
					   <tr style="font-size: 14px;">
				        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
				        <td></td>
				        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
				        <td></td>
				        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
					</thead>
				</table>
	    	</td>
	    </tr>
		</table>
	</div>
</div>
<script>
dojo.require("dojo.html");
	dojo.ready(function(){		
	});
function popupCheckCO(){
}
</script>