<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Report Selling Installing"));
 $frm = $this->form_search;
 
 $selingTypeSerch =  $this->search['selling_type'];
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('Report Selling Installing');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="card-box">
					<div class="row g-3">
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("adv_search");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("branch_id");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("shop_id");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("customer");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("start_date");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("end_date");?>
					   </div>
					</div>
					<div class="row g-3">
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("category");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="selling_type" id="selling_type" >
								<option value="-1"><?php echo $tr->translate('ជ្រើសរើសប្រភេទលក់');?></option>
								<option value="1" <?php if ($this->search['selling_type']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('ទិញដាច់');?></option>
								<option value="2" <?php if ($this->search['selling_type']==2){ echo 'selected="selected"';}?>><?php echo $tr->translate('បង់រំលស់');?></option>
							</select>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="product_type" id="product_type" >
								<option value="-1"><?php echo $tr->translate('PRODUCT_TYPE');?></option>
								<?php if (!empty($this->producttype)) foreach ($this->producttype as $pt){?>
								<option value="<?php echo $pt['id'];?>" <?php if ($this->search['product_type']==$pt['id']){ echo 'selected="selected"';}?>><?php echo $pt['name'];?></option>
								<?php }?>
							</select>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("completed_status");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("status");?>
					   </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
							<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					   </div>
					</div>
				</div>
			</form>
		</div>	
	</div>
	
	<style>
		.noneprint{
			display: table-cell !important; 
		}
	</style>
	<div class="card-body">
		<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px;}
				th{padding: 5px;}
				.hover:hover{ background:#ccc;}
				a.repLink{
					color: #000;
					text-decoration: none;
				}
				table.content-data { page-break-inside:auto }
				table.content-data  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				a.repLink.btn {
				    color: #008;
				    font-weight: 600;
				}
				.btn {
				    min-width: 50px;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
			</style>
			<table width="100%" >
				<thead>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0; border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="60%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("Report Selling Installing");?></li>
			                			<li style="text-align:center; font-size:13px;"><?php if (!empty($this->search['start_date'])){ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
			                		</ul>
			                    </td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
			        </td>
			    </tr>
			    </thead>
			    <tr>
			    	<td id="exportExcel">
			    		<table class="content-data" border="1"​  cellspacing="0">
			                <thead>
			                	<tr class="style-head" >
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("SHOP_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("INSTALLMENT_NO");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CUSTOMER_CODE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("CATEGORY");?>&nbsp;</td> 
				                    <td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("Buy Type");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("PAMENT_METHOD");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("INSTALLMENT_DURATION");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("SELLING_PRICE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("PAYMENTED");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("BALANCE");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("DATE");?>&nbsp;</td>
				                </tr>
			                </thead>
			                <?php 
			                	$location="";
			                	$gTotalSell=0;
			                	$paid=0;
			                	$balance = 0;
								$sellingType="";
			                    if(!empty($this->sale)) 
			                	foreach ($this->sale as $key => $rs){ 
				                	$gTotalSell = $gTotalSell + $rs["selling_price"];
				                	$paid=$paid+$rs["paid"];
				                	$balance = $balance+$rs["balance"];
				                	if ($rs["selling_type"]==2){
				                	}
			                    ?>
			                    <?php 
			                    if ($location != $rs['branch_id']){
			                    ?>
			                     <tr class="style hover" style=" line-height:20px; font-family:'Times New Roman','Khmer OS Muol Light';">
			                     	<td colspan="16" align="center" ><?php echo $rs["branch_namekh"];?></td>
			                     </tr>
			                    <?php }$location = $rs['branch_id'];?>
								<?php 
			                    if ($sellingType != $rs['selling_type']){
			                    ?>
			                     <tr class="style hover" style=" line-height:20px; font-weight:bold;">
			                     	<td colspan="15" align="center" ><?php echo $rs["sellingTypeTitle"];?></td>
			                     </tr>
			                    <?php }$sellingType = $rs['selling_type'];?>
				                <tr  class="context-menu-one style-rowdata hover"  oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;">
				               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["shop_name"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["sale_no"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["client_name_kh"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["catName"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["item_code"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["item_name"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["sellingTypeTitle"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["paymentMethodTitle"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["duration"].$tr->translate("MONTH");?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["selling_price"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["paid"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["balance"],2);?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php  echo date("d-M-Y",strtotime($rs["date_sold"]));?>&nbsp;</td>
				                </tr>
			                <?php }?>
			                	<tr style="border-bottom: solid 1px #fff;border-left: solid 1px #fff;border-right: solid 1px #fff;">
			                		<td colspan="11"></td>
			                		<td align="right">&nbsp;<strong><?php echo "$ ".number_format($gTotalSell,2)?></strong>&nbsp;</td>
			                		<td colspan="" align="right">&nbsp;<strong><?php echo "$ ".number_format($paid,2)?></strong>&nbsp;</td>
			                		<td colspan="" align="right">&nbsp;<strong><?php echo "$ ".number_format($balance,2)?></strong>&nbsp;</td>
			                		<td></td>
			                	</tr>
			             </table>
			    	</td>
			    </tr>
			</table>
			<br />
			<?php echo $this->footerReport;?>
		</div>
	</div>
</div>

<script>
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="agreement"){
				url='<?php echo $this->baseUrl()."/report/installments/agreement/id/";?>';
			}else if(key=="schedule"){
				url='<?php echo $this->baseUrl()."/report/installments/saleschedule/id/";?>';
			}
			else if(key=="invoice"){
				url='<?php echo $this->baseUrl()."/report/installments/saleinvoice/id/";?>';
			}
			
			gotoAction();
		},
		items: {
			"schedule": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text", accesskey: "c"},
			"invoice": {name: "<?php echo $tr->translate("INVOICE");?>", icon: "fa-money", accesskey: "c o p y"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}</script>