<?php $tran = $this->schedule;
$filter = $this->form_filter;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$sale = $this->sale;
$data = $this->data;

$brachLogo = $this->baseUrl()."/images/logo.jpg";
if (file_exists(PUBLIC_PATH."/images/branch/".$sale['logo_branch'])){
	$brachLogo = $this->baseUrl().'/images/branch/'.$sale['logo_branch'];
}
$scheduleSetting=INS_SCHEDULE_OPTION;
?>
<title><?php echo $tr->translate('Schedule Payment');?></title>
<style>
	td p{ margin-top:0px !important;}
</style>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('Schedule Payment');?></h5>
	</div>
	<div id="divPrint">
	<style type="text/css">
		.style{
			line-height: 20px;font-size: 13px;
			font-family: 'Times New Roman','Khmer OS Battambang';
		}
		.font_bold{
			font-family:'Times New Roman','Khmer OS Muol Light';
			font-size: 12px;
		}
		td p{ margin-top:-12px;}
		table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data {
			font-size:14px; 
		}
		table.content-data  tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:14px; 
			height: 23px;
		}
		table.tb-head tr td p {
		    line-height: 22px;
		}
	</style>
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
					<tr>
	                	  <td width="30%" valign="top"><!-- <img src="<?php //echo $this->baseUrl();?>/images/logo.jpg" /> --> </td>
	                	  <td width="40%" align="left" >
		                 </td>
	                	  <td width="30%" align="left" ></td>
	                </tr>
	                <tr>
						<td align="left" >
							<img src="<?php echo $brachLogo;?>"  style="height:80px; max-width:100%;">
						</td>
	                	<td align="center">
	                			<h2 style=" font-weight:normal; text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol';white-space: nowrap;">
		                	  	<?php 
									echo $this->sale['branch_nameen'];
								?><br />
		                	  </h2>
	                		<h2 style="font-weight:normal; text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol'"><?php echo $tr->translate('Schedule Payment');?></h2>
	               		</td>
						<td align="left" ></td>
	                </tr> 
	                <tr>
	                	<td colspan="3">
	                		<table class="tb-head" width="100%" style="font-family:">
			                	<tr style="font-size:15px;line-height: 25px;font-family:'Times New Roman','Khmer OS Battambang'" >
				                   <td width="35%">
				                   		<p><?php echo "". $tr->translate('CLIENT_NO')." : ".$sale['client_number']?></p>
				                	    <p><?php echo $tr->translate('CUSTOMER_NAME');?>: <?php echo $sale['client_name_kh'];?></p>
				                		<p><?php echo "",$tr->translate("TEL")."";?> : <?php echo $sale['phone'];?></p>
				                	</td>
				                    <td valign="top" style="" width="33%">
				                        <p><?php echo $tr->translate("AMOUNT_TERM_FUND");?> : <?php  echo $sale['duration']." ខែ"; ?></p>
				                        <p><?php echo $tr->translate("SELLING_DATE");?> : <?php echo date('d-m-Y',strtotime($sale['date_sold']));?> </p>
				                    	<p><?php echo $tr->translate("FIRST_PAYMENT");?> : <?php echo date('d-m-Y',strtotime($sale['first_payment'])); ?></p>
				                     </td>
				                    <td valign="top">
				                   	  <p><?php echo $tr->translate("INSTALLMENT_NO");?> : <b><?php echo $sale['sale_no'];?></b></p>
				                      <?php if($scheduleSetting!=1){?>
									  <p><?php echo $tr->translate("INTEREST")." : ".$sale['interest_rate']." %"?> </p>
				                      <?php }?>
									  <p><?php echo $tr->translate("TOTAL_INSTALL_AMOUNT");?>  : <strong><?php echo number_format($sale['balance'],(!strrpos($sale['balance'],". "))? 0 : 2);echo '&nbsp;'." $";?></strong></p>
									  <p><?php echo $tr->translate("SHOP_NAME");?>  : <strong><?php echo $sale['shop_name'];?></strong></p>
				                    </td>
				                </tr>
				                <tr style="font-size:15px;font-family:'Times New Roman','Khmer OS Battambang'" >
				                	<td colspan="2">
				                		<p style="padding-top:8px;"><?php echo $tr->translate("ADDRESS");?>:<?php echo $sale['village_name'].' '.$sale['commune_name'].' '.$sale['district_name'].' '.$sale['province_kh_name'];?>
				                	</td>
				                	<td></td>
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel" class="content-data" border="1"​>
	                 <tr class="style-head" >
	                    <td><?php echo $tr->translate("TYPE");?></td>
	                    <td><?php echo $tr->translate("ឆ្នាំផលិត");?></td>
	                    <td><?php echo $tr->translate("លេខតួ");?></td>
	                    <td><?php echo $tr->translate("លេខម៉ាស៊ីន");?></td>
	                    <td><?php echo $tr->translate("ស្លាកលេខ");?></td>
	                </tr>
	                <tr class="style-rowdata hover" >
	                    <td>&nbsp;<?php echo $sale['item_name'];?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $sale['year'];?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $sale['frame'];?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $sale['engine'];?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $sale['frame_no'];?>&nbsp;</td>
	                </tr>
	             </table>
	             <br />
	            <table id="exportExcel" class="content-data" border="1"​ >
	                 <tr class="style-head" >
	                    <td><?php echo $tr->translate("NUM");?></td>
	                    <td><?php echo $tr->translate("ថ្ងៃ-ខែ ឆ្នាំ");?></td>
	                    <td><?php echo $tr->translate("AMOUNT_DATE");?></td>
	                    <td><?php echo $tr->translate("PRINCIPLE");?></td>
	                    <td><?php echo $tr->translate("OS_AMOUNT");?></td>
						<?php if($scheduleSetting!=1){?>
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
						<?php }?>
	                    <td><?php echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?></td>
	                    <td><?php echo $tr->translate("OTHER");?></td>
	                </tr>
	               <?php 
	               $is_panelty=0;
	               $record=0;
	               if(!empty($tran)) foreach($tran as $key =>$row){?>
	               	
               		<?php if($row['is_completed']==1 and $row['status']==0){?>
               			<tr>
               				<td colspan="9" align="center" style="background: #97b1ff; padding:5px 0 !important; font-family: 'Times New Roman','Khmer OS Battambang';font-size: 14px;">អតិថិជនបានបង់ប្រាក់រំលស់ដើមចំនួន <?php echo number_format($row['principal_permonth'],2);?> នៅថ្ងៃទី <?php echo date("d-m-Y",strtotime($row['date_payment']));?> </td>
               			</tr>
               		<?php }else{?>
		               	<tr class="style-rowdata hover" align="center">
		                    <td>&nbsp;<?php echo ($key+1<10)?"0":"";echo $key+1;?>&nbsp;</td>
		                    <?php $str_day = date('D',strtotime($row['date_payment']));
		                    	$day_as_khmer = $dayin_khmer[$str_day];
		                    ?>
		                    <td align="left">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_payment']));?>&nbsp;<?php echo $day_as_khmer; ?>&nbsp;</td>
		                    <td>&nbsp;<?php echo $row['amount_day'];?>&nbsp;</td>
		                    <td>&nbsp;<?php echo str_replace('.00', '', number_format($row['outstanding'],2));?>&nbsp;</td>
		                    <td>&nbsp;<?php echo str_replace('.00', '', number_format($row['principal_permonth'],2));?>&nbsp;</td>
		                    <?php if($scheduleSetting!=1){?>
							<td>&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest'],2));?>&nbsp;</td>
		                    <?php }?>
							<td>&nbsp;<strong><?php echo str_replace('.00', '', number_format($row['total_payment'],2)); ?></strong>&nbsp;</td>
		                    <td>&nbsp;<?php echo ($row['is_completed']==1)?"បង់ដាច់":""?>&nbsp;</td>
		                </tr>
	               <?php }}
	               	if(!empty($record))for($record = $key;$record<11;$record++){
	               ?>
	               		<tr>
	               			<td>&nbsp;</td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               		</tr>
	               <?php }?>
	            </table>
	            <table>
	            	<tr>
	            		<td align="left" style="font-size: 14px;" ><?php echo $tr->translate("NOTED_SCHEDULE");?></td>
	            	</tr>
	            	<tr>
	            		<td align="left" style="font-size: 14px;" >អតិថិជនអាចវេរប្រាក់តាម ទ្រូម៉ានី វឺង អ៊ីម៉ានី មកលេខ : <?php echo $this->sale['branch_tel'];?></td>
	            	</tr>
	            </table>
	            <table width="100%" cellpadding="3">
	            	<tr class="font_bold" style="height:25px;">
	            		<td align="center" valign="bottom" style="font-family:'Times New Roman','Khmer OS Muol'"><?php echo $tr->translate('ACCOUNTING_SIGN');?></td>
	            		<td align="center" valign="bottom" style="font-family:'Times New Roman','Khmer OS Muol'"><?php echo $tr->translate('GUARAATEE_SIGN');?></td> 
	            		<td align="center" valign="bottom" style="font-family:'Times New Roman','Khmer OS Muol'"><?php echo $tr->translate('BORROWER');?></td>
	            	</tr>
	            	<tr class="font_bold">
	            		<td align="center" height="80px" valign="bottom" style="font-size:15px;font-family:'Times New Roman','Khmer OS Battambang'"><?php echo $sale['user_name'];?></td>
	            		<td align="center"  valign="bottom" style="font-size:15px;line-height: 30px;font-family:'Times New Roman','Khmer OS Battambang'" >
	            		</td>
	            		<td align="center" height="75px" valign="bottom" style="font-size:15px;font-family:'Times New Roman','Khmer OS Battambang'">
	            			<?php echo $sale['client_name_kh'];?></td>
	            	</tr>
	            </table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>