<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Sumary Stock Report"));
 $frm = $this->formFilter;
 $dbInventory  = new Report_Model_DbTable_DbInventory();
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Sumary Stock Report');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('branch_id');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement("product_type");?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement("category");?>
               </div>
            </div>
            <div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('start_date');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement("end_date");?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('status');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
	</form>
	<div id="divPrint">
			<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px;}
				th{padding: 2px;}
				.hover:hover{ background:#ccc;}
				tr.foot td {
				    padding: 10px 0;
				}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				th {
				    padding: 0px;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
				table.tb-footer{
					font-family: 'Times New Roman','Khmer OS Battambang'; 
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:12px;
					width:100%;
				}
				table.tb-footer tr.style-head{
					line-height: 24px; 
					text-align: center; 
					background: #ccd9ff;
				}
			</style>
			<table width="100%" >
				<thead>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="60%" valign="top">
			                	    <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("Sumary Stock Report");?></li>
			                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
			                		</ul>
			                    </td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
			        </td>
			    </tr>
			    </thead>
			    <tr>
			    	<td id="exportExcel">
			            <table class="content-data" border="1" cellspacing="0">
			                <thead>
			                	<tr class="style-head" >
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PRODUCT_CATEGORY");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
				                    <td colspan="2">&nbsp;<?php echo $tr->translate("BEGINNING_STOCK");?>&nbsp;</td>
				                    <td colspan="2">&nbsp;<?php echo $tr->translate("STOCK_IN");?>&nbsp;</td>
				                    <td colspan="2">&nbsp;<?php echo $tr->translate("STOCK_OUT");?>&nbsp;</td>
				                    <td colspan="2">&nbsp;<?php echo $tr->translate("CURRENT_QTY");?>&nbsp;</td> 
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
				                </tr>
				                <tr class="style-head" >
				                    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("Value");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("Value");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("Value");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("Value");?>&nbsp;</td>
				                </tr>
			                </thead>
			                <?php 
			                	$location="";
			                	$tQtyPurchase=0;
			                	$tPricePurchase=0;
			                	$tQtySale=0;
			                	$tPriceSale=0;
			                	
			                	$tQtyStock=0;
			                	$tPriceStock=0;
			                    if(!empty($this->sumaryStok))
			                	foreach ($this->sumaryStok as $key => $rs){ 
			                    ?>
			                    <?php 
			                    if ($location != $rs['location_id']){
			                    ?>
			                     <tr class="style hover" style=" line-height:20px; ">
			                     	<td colspan="13" align="center"><?php echo $rs["branch_namekh"];?></td>
			                     </tr>
			                    <?php }$location = $rs['location_id'];?>
			                    <?php 
			                    	$purchaseQty=0;
			                    	if (!empty($rs["purchaseQty"])){
			                    		$purchaseQty = $rs["purchaseQty"];
				                    }
				                    $costPrice = $rs["purchaseAmount"];
				                    $tQtyPurchase = $tQtyPurchase +$purchaseQty;
				                    $tPricePurchase = $tPricePurchase + $costPrice;
				                    
				                    $stockOut = 0;
				                    if (!empty($rs["stockOut"])){
				                    	$stockOut = $rs["stockOut"];
				                    }
				                    $price =$rs['stockOutAmount'];
				                    $tQtySale = $tQtySale +$stockOut;
				                    $tPriceSale = $tPriceSale + $price;
				                    
				                    $balanceValue = $rs["qty"]*$rs["cost_price"];
				                    $tQtyStock = $rs["qty"] +$tQtyStock;
				                    $tPriceStock = $tPriceStock + $balanceValue;
				                    
				                    $closingstock = $dbInventory->getProductClosingStock($rs['id'], $rs['location_id'], $this->search);
			                    ?>
				                <tr class="style-rowdata hover">
				               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["categoryName"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["item_code"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["item_name"];?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo empty($closingstock['currentQty'])?0:$closingstock['currentQty'];?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo empty($closingstock['currentCost'])?0:$closingstock['currentCost'];?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo $purchaseQty;;?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($costPrice,2);?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo $stockOut;?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($price,2);?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo $rs["qty"];?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($balanceValue,2);?>&nbsp;</td>
				               		<td >&nbsp;<?php echo $rs["note"];?>&nbsp;</td>
				                </tr>
			                <?php }?>
			                	<tr>
			                		<td colspan="13" style="border-left: solid 1px #fff; border-right: solid 1px #fff;">&nbsp;</td>
			                	</tr>
			                	<tr class="foot">
			                		<td colspan="2">&nbsp;<?php echo $tr->translate("Grand Total");?>&nbsp;</td>
			                		<td colspan="2">&nbsp;&nbsp;</td>
			                		<td align="center">&nbsp;<?php //echo $tQtyPurchase;?>&nbsp;</td>
			                		<td align="right">&nbsp;<?php //echo number_format($tPricePurchase,2);?>&nbsp;</td>
			                		<td align="center">&nbsp;<?php echo $tQtyPurchase;?>&nbsp;</td>
			                		<td align="right">&nbsp;<?php echo number_format($tPricePurchase,2);?>&nbsp;</td>
			                		<td align="center">&nbsp;<?php echo $tQtySale;?>&nbsp;</td>
			                		<td align="right">&nbsp;<?php echo number_format($tPriceSale,2);?>&nbsp;</td>
			                		<td align="center">&nbsp;<?php echo $tQtyStock;?>&nbsp;</td>
			                		<td align="right">&nbsp;<?php echo number_format($tPriceStock,2);?>&nbsp;</td>
			                		<td>&nbsp;&nbsp;</td>
			                	</tr>
			             </table>
			    	</td>
			    </tr>
			</table>
			<br />
			 <table align="center" width="100%">
			   <tr style="font-size: 14px;">
			        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
			        <td></td>
			        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
			        <td></td>
			        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
			   </tr>
			</table>
		</div>
</div>