<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_holiday;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("LIST HOLIDAY");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('LIST HOLIDAY');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("start_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("end_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('search_status');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               </div>
            </div>
        </div>
    </form>
    <div id="divPrint">
    	   <style>
				.style{
					line-height: 20px;font-size: 11px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table { page-break-inside:auto; font-family: 'Times New Roman','Khmer OS Battambang'; }
			    tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
				}
				th{padding: 5px;}
			</style>
    	  <table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang'; margin:0; padding:0; border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
	                	<h2 style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_HOLIDAY");?></h2>
						<h2 style="text-align:center; font-size:13px;"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></h2>
					</td>
					<td width="20%"></td>
				</tr> 
                
            </table>
       	 	<table id="exportExcel" align="center" border="1" width="100%" style="border-collapse:collapse; font-size: 12px;" bordercolor="black" >
				    <thead> 
					    <tr bgcolor="#ccc" class="style" align="center" style="height:25px; font-weight:bold; line-height: 14px; background: #ccd9ff; font-size:12px; padding:5px 0px; ">
					        <td><?php echo $tr->translate("NUM");?></td>
					        <td><?php echo $tr->translate("HOLIDAY_NAME");?></td>
					        <td><?php echo $tr->translate("DATE");?></td>
					        <td><?php echo $tr->translate("AMOUNT_DAY");?></td>
					        <td><?php echo $tr->translate("NOTE");?></td>
					    </tr>
				     </thead> 
					<?php $amount_day = 0;
					 
					if(!empty($this->holiday_list)) 
						foreach($this->holiday_list as $key =>$row){
					 	$amount_day=$amount_day+$row['amount_day'];
					 	?>
					     <tr style="font-size: 10px;" align="center">
					        <td><?php echo $key + 1; ?></td>
					        <td><?php echo $row['holiday_name']?></td>
					        <td><?php echo $row['start_date']?></td>
					        <td><?php echo $row['amount_day']?></td>
					        <td><?php echo $row['note']?></td>
					    </tr>
					    <?php }?>
					 <?php if(!empty($key)) for($i=$key; $i<=14;$i++){?>
						  <tr align="center">
						        <td><?php $key++; echo $key+1; ?></td>
						        <td></td>
						        <td></td>
						        <td></td>
						        <td></td>
						    </tr>
					 <?php }?>
				
				    <tr align="center">
				        <td colspan="2"></td>
				        <th><?php echo $tr->translate('TOTAL');?></th>
				        <td><?php echo $amount_day; ?></td>
				        <td></td>
				    </tr>
				</table>
			<br />
			<?php echo $this->footerReport;?>	
	</div>
</div>
