<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("BRAND_ZONE"));
$frm = $this->frm_zone;
?>
<meta charset="utf-8">
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('BRAND_ZONE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('search_status');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
         </div>
     </form>
     <div id="divPrint">
    	  <style>
				.style{
					line-height: 20px;font-size: 11px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				th{padding: 5px;}
				table { font-family: 'Times New Roman','Khmer OS Battambang'; }
				table.content-data { page-break-inside:auto; }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
			
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
					
			</style>
        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang'; margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_ZONE");?><?php //echo $this->data['brand_zone'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                
            </table>
			<table id="exportExcel" class="content-data" width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
		      <thead> 
		    	<tr bgcolor="#ccc" class="style" align="center" style="height:25px; font-weight:bold; line-height: 20px; background: #ccd9ff; font-size:12px; padding:5px 0px; ">
		        	<td><?php echo  $tr->translate("NUM");?></td>
		        	<td><?php echo  $tr->translate("BRANCH_NAME");?></td>
		            <td><?php echo  $tr->translate("ZONE_NAME");?></td>
		            <td><?php echo  $tr->translate("ZONE_NUMBER");?></td>
		            <td><?php echo  $tr->translate("DATE");?></td>
		         </tr>
		        </thead>
		        <?php if(!empty($this->zone_list))foreach($this->zone_list as $key =>$row){?>
				   <tr align="center" style="font-size: 11px;line-height: 18px;" >
				     <td>&nbsp;&nbsp;<?php echo $key+1; ?></td>
				     <td align="left">&nbsp;&nbsp;<?php echo $row['branch']?></td>
				     <td align="left">&nbsp;&nbsp;<?php echo $row['zone_name']?></td>
					 <td>&nbsp;&nbsp;<?php echo $row['zone_num']?></td>
					 <td>&nbsp;&nbsp;<?php echo $row['modify_date']?></td>
					</tr>
				<?php }?>
				 <?php if(!empty($key)) for($i=$key; $i<=14;$i++){?>
					<tr align="center">
					 <td><?php $key; echo $i+1; ?></td>
					 <td></td>
					 <td></td>
					 <td></td>
				    </tr>
				<?php }?>
		
		    </table>
		    <br />
		   <?php echo $this->footerReport;?>	
		 </div>
</div>
 