<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("VILLAGE_LIST"));
$frm = $this->frm_village;
$this->result['province_name'];
?>
<title><?php echo $tr->translate("BRAND_VILLAGE");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('BRAND_VILLAGE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="row g-3">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php  echo $frm->getElement('province_name');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("from_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("to_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('search_status');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
    </form>
    <div id="divPrint">
    	<style>
			.style{
				line-height: 20px;font-size: 13px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			th{padding: 5px;}
				
			table { font-family: 'Times New Roman','Khmer OS Battambang'; }
			table.content-data { page-break-inside:auto; }
			table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
			
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			#exportExcel tr td{
				padding: 1px;
			}
		</style>
        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_VILLAGE");?><?php //echo $this->data['village'];?></h2>
					<h2 style="text-align:center; font-size:13px;"><?php if(!empty($this->result['start_date'])){?><?php echo date("d-M-Y",strtotime($this->result['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->result['end_date']));}?></h2></td>					
                    <td width="20%"></td>
                </tr> 
            </table>
        	<table id="exportExcel" class="content-data" align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
			    <thead>
			    <tr class="style" align="center" style="height:25px; font-weight:bold;  background: #ccd9ff; line-height: 14px; font-size:12px; padding:5px 0px; ">
			        <td><?php echo $tr->translate("NUM");?></td>
			        <td><?php echo $tr->translate("VILLAGE_NAME");?></td>
			        <td><?php echo $tr->translate("VILLAGE_NAME");?></td>
			        <td><?php echo $tr->translate("COMMUNE");?></td>
			        <td><?php echo $tr->translate("DISTRICT_NAME");?></td>
			        <td><?php echo $tr->translate("PROVINCE_NAME");?></td>
			        <td><?php echo $tr->translate("DATE");?></td>				        
			    </tr>
			    </thead>
				<?php 
				 if(!empty($this->village_list))foreach($this->village_list as $key =>$row){
				 	?>
				     <tr style="text-align:left; ">
				        <td align="center"><?php echo $key+1; ?></td>
				        <td>&nbsp;<?php echo $row['village_namekh']?>&nbsp;</td>
				        <td>&nbsp;<?php echo $row['village_name']?>&nbsp;</td>
				        <td><?php echo $row['commune_name']?></td>
				        <td><?php echo $row['district_name']?></td>
				        <td><?php echo $row['province_en_name']?></td>
				        <td align="center"><?php echo date('d/m/Y',strtotime($row['modify_date']));?></td>
				    </tr>
				    <?php }?>
		   </table>
		   <br />
	  		<?php echo $this->footerReport;?>	
	</div>
</div>
 
 <script type="text/javascript">  
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ObjectStore");
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	dijit.byId('province_name').attr('value',<?php echo $this->result['province_name'];?>);
	
	new dijit.form.FilteringSelect({
	store: district_store,
	autoComplete: true,
	required: false,		           
	name: "district_name",
	id: "district_name",
	searchAttr: "name",
	class: 'fullside',
	value:"<?php echo $this->result['district_name'];?>",
		onChange: function() {
				filterCommune();
	    }
	}, "district_name");

	
	 
	new dijit.form.FilteringSelect({
	store:commune_store,
	autoComplete: true,
	query: {
		district_id: "<?php echo $this->result['district_name'];?>"
	},            
	required: false,		           
	name: "commune_name",
	id: "commune_name",
	searchAttr: "name",
	class: 'fullside',
	value:"<?php echo $this->result['commune_name'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
  }
	}, "commune_name");

	
});
/*
url_getdistrict = '<?php //echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province_name').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district_name').set('store', district_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php //echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district_name').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune_name').set('store', commune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}*/
</script>
 