<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_staff;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT STAFF");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT STAFF');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("adv_search");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("co_khname");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('search_status');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("start_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement("end_date");?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
   </form>
   <div id="divPrint">
    	 	<style>
				.style{
					line-height: 20px;font-size: 13px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
					}
					th{padding: 5px;}
					
				 table { page-break-inside:auto ; font-family: 'Times New Roman','Khmer OS Battambang';}
				 tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				#exportExcel tr td{
						padding: 1px;
				}
			</style>
        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
	                	<h2 style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_STAFF");?></h2>
					</td>	
                    <td width="20%"></td>
                </tr> 
            </table>
			<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">  
		    	 <thead> 
			    	<tr bgcolor="#ccc" class="style" align="center" style=" height:25px; font-weight:bold; line-height: 14px; background: #ccd9ff; font-size:12px; padding:5px 0px; " >
			        	<td><?php echo $tr->translate("NUM");?></td>
			            <td><?php echo $tr->translate("BRANCH_NAME");?></td>
			            <td><?php echo $tr->translate("STAFF_ID");?></td>
			            <td><?php echo $tr->translate("CO_NAME");?></td>
			            <td><?php echo $tr->translate("SEX");?></td>
			            <td><?php echo $tr->translate("PHONE");?></td>
			            <td><?php echo $tr->translate("NATIONAL_ID");?></td>
			            <td><?php echo $tr->translate("ADDRESS");?></td>
			            <td><?php echo $tr->translate("EMAIL");?></td>
			            <td><?php echo $tr->translate("SALARY");?></td>
			            <td><?php echo $tr->translate("START_DATE");?></td>
			            <td><?php echo $tr->translate("END_DATE");?></td>
			            <td><?php echo $tr->translate("POSITION");?></td>
			            <td><?php echo $tr->translate("NOTE");?></td>
			         </tr>
		        </thead> 
		       <?php if(!empty($this->staff_list))foreach($this->staff_list as $key =>$row){?>
				   <tr style="font-size: 12px;" align="left">
				     <td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
				     <td>&nbsp;<?php echo $row['branch_name']?>&nbsp;</td>
				     <td>&nbsp;<?php echo $row['co_code']?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['co_khname'] ." - ".$row['co_firstname']?>&nbsp;</td>
					 
					 <td>&nbsp;<?php echo $row['sex']?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['tel']?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['national_id']?>&nbsp;</td>
					 <td style="white-space: pre;">&nbsp;<?php echo $row['address']?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['email']?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['basic_salary']?>&nbsp;</td>
					 <td align="center">&nbsp;<?php echo date('d/m/Y',strtotime($row['start_date']));?>&nbsp;</td>
					 <td align="center">&nbsp;<?php echo date('d/m/Y',strtotime($row['end_date']));?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['position']?>&nbsp;</td>
					 <td>&nbsp;<?php echo $row['note']?>&nbsp;</td>
					</tr>
				<?php }?>
				
		    </table>
			<br />
		   <?php echo $this->footerReport;?>	
	   </div>
</div>
