<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
$this->headTitle('SRMS | '.$tr->translate('ADD_USER'));
echo $this->headTitle();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require('dijit.Dialog');
</script>
<div class="card">
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-users" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('ADD_USER');?></h5>
		<span id="message" style="color: red; display: block;"></span>
	</div>
	<div class="card-body">
		<form action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				is_duplicate = dijit.byId('is_duplicate').get('value');
				if(is_duplicate==1){
					dijit.byId('user_name').focus();
					return false;
				}
				if(dojo.byId('password').value != dojo.byId('con_password').value ){
					alert('សូមពិនិត្រ ពាក្យសំងាត់ទាំង 2 របស់អ្នក មិនដូចគ្នាទេ, សូមបញ្ចូល ម្តងទៀត..');
					dojo.byId('password').value = '';
					dojo.byId('con_password').value = '';
					dijit.byId('password').focus();
					return false;
				}				
				dojo.byId('agent').value = dijit.byId('agent_id').item.id;
				return true;
			}

			return false;
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("USER_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LAST_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" required="true" name="last_name" id="last_name" placeholder="នាមត្រកូល" 
													dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នកភ្លេចបំពេញ នាមត្រកូល!" class='fullside'/>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FIRST_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" required="true" name="first_name" id="first_name" placeholder="នាមខ្លួន" 
													dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នកភ្លេចបំពេញ នាមខ្លួន!" class='fullside'/>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("USER_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="text" onKeyup="checkTitle();" required="true" name="user_name" id="user_name" placeholder="ឈ្នោះអ្នកប្រើប្រាស់" 
													dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នកភ្លេចបំពេញ ឈ្មោះអ្នកប្រើប្រាស់!" class='fullside'/>
													<input type="hidden" name="is_duplicate" id="is_duplicate" dojoType="dijit.form.TextBox" />
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PASSWORD");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="password" required="true" name="password" id="password" placeholder="ពាក្យសំងាត់" 
													regExp="\w{6,}" invalidMessage="ពាក្យសំងាត់យ៉ាងតិច មាន 6 តួអក្សរ"
													dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នកភ្លេចបំពេញ ពាក្យសំងាត់!" class='fullside'/>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CONFIRM_PASSWORD");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input type="password" required="true" name="con_password" id="con_password" placeholder="បញ្ជាក់ពាក្យសំងាត់" 
													regExp="\w{6,}" invalidMessage="ពាក្យសំងាត់យ៉ាងតិច មាន 6 តួអក្សរ"
													dojoType="dijit.form.ValidationTextBox"  missingMessage="អ្នកភ្លេចបំពេញ បញ្ជាក់ ពាក្យសំងាត់!" class='fullside'/>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("USER_TYPE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="user_type" />
							   </div>
							</div>
						</div>
					</div>
	             </div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("Assign Branch Access");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
								<div class="form-check form-check-primary mt-3">
									<input class="form-check-input checkbox" type="checkbox" value="" name="check_all" id="check_all" value="all" OnChange="CheckAllTotal(0);" />
									<label class="form-check-label" for="check_all"><?php echo $tr->translate('ALL');?></label>
								</div>
								<ul class="opt-school">
									<?php $identityCheck = ""; if (!empty($this->rs_branch)) foreach ($this->rs_branch as $rs){?>
									<li class="opt-items"> 
										<div class="form-check form-check-primary mt-1">
											<input class="form-check-input checkbox" type="checkbox" id="checkItems<?php echo $rs['br_id'];?>" value="<?php echo $rs['br_id'];?>" name="selector[]" onClick="CheckAllTotal(1);" checked />
											<label class="form-check-label" for="checkItems<?php echo $rs['br_id'];?>"><?php echo $rs['branch_namekh'];?></label>
										</div>
									</li>
										
									<?php if (empty($identityCheck)){ $identityCheck = $rs['br_id'];}else{$identityCheck = $identityCheck.",".$rs['br_id'];}?>
									<?php }?>
								</ul>
							</div>
						</div>
					</div>
	            </div>
	         </div>
			 
			 <!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-2 py-2 text-center">
					<input type="button" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="Save" label="<?php echo $tr->translate("SAVE");?>" id="submitButton" dojoType="dijit.form.Button"  /> 	
					
    			</div>
    		</div>
	    	<!--/. Button Save  -->
			
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;overflow-y:scroll;" id="popup_usertype" >
		<form  id='frm_usertype' name='frm_usertype' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<div class="card card-form mb-4">
				<div class="card-header d-flex justify-content-between">
					<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("USER_TYPE_INFO");?></h5>
				</div>
				<div class="card-body">
					<div class="row g-3">
					   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PARENT");?>
					   </label>
					   <div class="col-md-7 col-sm-7 col-xs-12">
							<select class='fullside' id="parent_id"  name="parent_id" required="true" missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect"> 
						 	<?php foreach ($this->user_typelist as $key => $ust) : ?>
								<option value="<?php echo $ust['id'];?>"><?php echo $ust['name'];?></option>
							<?php endforeach;?>																															
						</select> 
					   </div>
					</div>
					<div class="row g-3">
					   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("USER_TYPE");?>
					   </label>
					   <div class="col-md-7 col-sm-7 col-xs-12">
							<input type="text" required="true" name="user_typename" id="user_typename" placeholder="User Type" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->usertype['user_type'];?>" missingMessage="Invalid User type!" class='fullside'/>
					   </div>
					</div>
					<!-- Button Save  -->
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
						
							<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" onclick="addUsrType();" value="រក្សាទុក" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button" /> 
							
						</div>
					</div>
					<!--/. Button Save  -->
				</div>
			</div>
		</form>
	</div>
</div>
<style>
ul.opt-school {
    list-style-type: none;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<script>
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  

var usertype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->user_type));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: usertype_store,
		autoComplete: true,                        
		id: "user_type",
		name: "user_type",
		class: "fullside", 		
		placeHolder:"Select User Type",          
		onChange: function() {  
			user_type = dijit.byId('user_type').get('value');
			if(user_type==-1){
				dijit.byId("popup_usertype").show();
			}
		}
	}, "user_type");
});

function getpopupUsertype(){
	user_type = dijit.byId("user_type").get("value");
	if(user_type==-1){
		dijit.byId("popup_usertype").show();
	}
}
var url_addusertype = '<?php echo $this->url(array("module"=>"rsvacl","controller"=>"usertype","action"=>"addusertype")); ?>';
function addUsrType(){
	if(dijit.byId('frm_usertype').validate()){
		dijit.byId('save_usertype').set('disabled',true);
		dojo.xhrPost({
			url:url_addusertype,
			form: dojo.byId("frm_usertype"),
			handleAs:"json",
			load: function(data) {
				var myNewItem = {					
						id: data,
						name: dijit.byId('user_typename').get('value')
				};			
				addDataToSelectbox(dijit.byId('user_type'), usertype_store, myNewItem, data);
				dijit.byId("frm_usertype").reset();
				dijit.byId("popup_usertype").hide();
				dijit.byId('save_usertype').set('disabled',false);
				
			},
			error: function(err) {
				dijit.byId('save_usertype').set('disabled',false);
			}
		});
   }
}


function CheckAllTotal(index){
	if(index==0){
			if($('#check_all').is(":checked")){
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = true;  
				});
			}else{
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = false;  
				});
			}
	}else{
		var a = $("input:checked").val();
		 var identity = [];
	     $('.checkbox:checked').each(function(i){
	    	 identity[i] = $(this).val();
	     });
	}
}

url_CheckTitle = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'check-title'));?>';
function checkTitle(){
	user_name = dijit.byId('user_name').get('value');
	if(user_name==''){ return false;}
	dojo.xhrPost({
		url:url_CheckTitle,	
		content:{ 
			'user_name': user_name ,
		},
		handleAs:"json",
		load: function(data) {	
			if(data !== false ){
				document.getElementById('message').innerHTML ='<?php echo '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> '.$tr->translate("USER_EXISTING_READY");?>';
				dijit.byId('user_name').focus();
				dijit.byId('is_duplicate').attr('value',1);
			}else{
				document.getElementById('message').innerHTML ='';
				dijit.byId('is_duplicate').attr('value',0);
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>