<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS System | User page'); 
	echo $this->headTitle();
?>	
<style>
	#grid{
		margin: 0 auto;
	}
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<div class="card">
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-users" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('USER_LIST');?></h5>
		<div class="d-flex justify-content-between align-items-center ">
			<form name="frmlist_users" action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="row g-3">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<input class="fullside" type="text" name="txtsearch" id="txtsearch" placeholder="តាម (នាមត្រកូល , នាមខ្លួន  និង អ្នកប្រើប្រាស់)"  dojoType="dijit.form.TextBox" style="height: 30px;" value='<?php echo $this->txtsearch;?>'/>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<select class="fullside" name="user_type" id="user_type"  onChange="document.frmlist_agent.submit();" style=" height: 30px;" dojoType="dijit.form.FilteringSelect"> 
							<option value="-1" <?php if($this->user_type == -1) echo 'selected="selected"';?> ><?php echo $tr->translate('SELECT_USER_TYPE');?></option> 
							<?php foreach ($this->user_typelist as $key => $ut) : ?>
								<option value="<?php echo $ut['id'];?>" <?php if($ut['id'] == $this->user_type) echo 'selected'?>><?php echo $ut['name'];?></option>
							<?php endforeach;?>	 
						</select>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<select class="fullside" name="active" id="active"  onChange="document.frmlist_agent.submit();" style=" height: 30px;" dojoType="dijit.form.FilteringSelect"> 
							<option value="-1" <?php if($this->active == -1) echo 'selected="selected"';?> ><?php echo $tr->translate('SELECT_STATUS');?></option> 
							<?php foreach ($this->activelist as $key => $at) : ?>
								<option value="<?php echo $key;?>" <?php if($key == $this->active) echo 'selected'?>><?php echo $at;?></option>
							<?php endforeach;?>	 
						</select>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>


