<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_COMMUNE'));
?>	
<?php  $commune = $this->frm_commune;?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-marker" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('ADD_COMMUNE');?></h5>
	</div>
	<div class="card-body">
		<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
               		if(dijit.byId('province_name').get('value')==0){
				 		alert('<?php echo $tr->translate('Please Select Province');?> !');
                 		dijit.byId("province_name").focus();
                 		return false;
               		 }
             		if(dijit.byId('district_name').get('value')==''){
                 		alert('<?php echo $tr->translate('Please Select District');?> !');
				 		dijit.byId("district_name").focus();
                 		return false;
              		}
					loadingBlock();
                	dijit.byId("save_new").set("disabled",true);
 					dijit.byId("save_close").set("disabled",true);
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('code');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE_NAME");//$tr->translate("COMMUNE_NAME_KH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('commune_namekh');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('province_name');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="district_name" ><?php  //echo $commune->getElement('district_name');?>
	                </div>
					
					<!-- Button Save  -->
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
							<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
							<input type="button" onclick="submitDataClose();" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("GO_EDIT")?>" name='save_close' id='save_close' value='save_close' dojoType="dijit.form.Button"  />
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("GO_EDIT")?>" name='save_new' id='save_new' value='save_new' dojoType="dijit.form.Button"  />
						</div>
					</div>
					<!--/. Button Save  -->
					
	            </div>
	         </div>
		</form>
	</div>
</div>

<div class="dijitHidden">
				<div data-dojo-type="dijit.Dialog"  id="frm_distict" >
			<form id="form_distict" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit">
					if(this.validate()) {
						return true;
					}else {
						return false;
					}
		       </script><table style="margin: 0 auto; width:500px;" cellspacing="7">
					<tr>
						<td><input dojoType="dijit.form.TextBox" id="province_names" name="province_names" value="" type="hidden" /><?php echo $tr->translate("PROVINCE_NAME")?></td>
						<td><input dojoType="dijit.form.TextBox" readonly="readonly" class="fullside" id="txt_province" name="txt_province" value="" type="text"></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("DISTRICT_NAME")?></td>
						<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="pop_district_namekh" name="pop_district_namekh" value="" type="text"></td>
					</tr>
					<tr>
						<td colspan="4" align="center">
						<input type="button" value="Save" label="<?php echo $tr->translate("GO_SAVE");?>" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDistrict();"/>
						</td>
					</tr>
				</table></form>		</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.Dialog");
dojo.ready(function(){	 
	new dijit.form.FilteringSelect({
	store: district_store,
	required: false,		           
	name: "district_name",
	id: "district_name",
	searchAttr: "name",
	placeHolder:"<?php echo $tr->translate("DISTRICT")?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			district_id = dijit.byId('district_name').get('value');
			if(district_id==-1){
				dijit.byId('province_names').attr('value',dijit.byId('province_name').get('value'));
				dijit.byId('txt_province').attr('value',dijit.byId('province_name').attr('displayedValue'));
				dijit.byId('frm_distict').show();
			}
        }
	}, "district_name");
});
function filterDistrict(){
	district_id =  dijit.byId('province_name').get('value');
	getAllDistrict(district_id);
}
var district_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_district = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district')); ?>';
function getAllDistrict(pro_id){
	dojo.xhrPost({
		url:url_district,
		content:{
			'pro_id':pro_id
			},
		handleAs:"json",
		load: function(data) {
			district_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('district_name').set('store',district_store);   
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_adddistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-district')); ?>';
function addDistrict(){
	if(dijit.byId('form_distict').validate()){
		dojo.xhrPost({
			url:url_adddistrict,
			form: dojo.byId("form_distict"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('pop_district_name').get('value')
				};			
				addDataToSelectbox(dijit.byId('district_name'), district_store, Itemmake, data);
				dijit.byId('form_distict').reset();
				dijit.byId("frm_distict").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

function submitDataClose(){
	if(dijit.byId('province_name').get('value')==0){
		 alert('<?php echo $tr->translate('Please Select Province');?> !');
       dijit.byId("province_name").focus();
       return false;
      }
   if(dijit.byId('district_name').get('value')==''){
       alert('<?php echo $tr->translate('Please Select District');?> !');
		 dijit.byId("district_name").focus();
       return false;
    }
	if(dijit.byId('add_techer').validate()) {
		loadingBlock();
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_techer"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/other/commune";
			},
			error: function(e) {
			}
		});
	}
}
</script>