<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("COMMUNE_LIST"));
$frm = $this->frm_district;
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('COMMUNE_LIST');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('search_status');?>
			   		</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>