<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("INSTALL_PAYMENT"));
$frm = $this->frm_search;
$url_delete = $this->baseUrl()."/installment/payment/delete/id/";
$url_receipt = $this->baseUrl()."/report/installments/recieptpayment/id/";
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('INSTALL_PAYMENT');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('member');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('paymnet_type');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
   <div class="card-body">
	  <?php echo $this->list;?>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>


<script>
var row=0;
var url="";
var indexkey="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			indexkey="";
			var m = "clicked: " + key;
			var newPageTitle="";
			var actionType=1;
			
			if(key=="delete"){
				url='<?php echo $url_delete;?>';
				indexkey = 'delete';
				actionType=2;
			 }else if(key=="receipt"){
					url='<?php echo $url_receipt;?>';
					newPageTitle='<?php echo $tr->translate("PAYMENT_RECEIPT");?>';
			}
			if(actionType==1){
				addTab(newPageTitle,url+row+'?inFrame=true');
			}else{
				gotoAction();
			}
		},
		items: {
			"receipt": {name: "<?php  echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-print"},
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "fa-trash-o", accesskey: "c o p y"},
			
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	if(indexkey=='delete'){
	    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
	    	window.location.href = url+row;
	    } else {
	    	 return false;
	    }
	}else{
	 	window.open(url+row, '_self');
	}
}
</script>