<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("INSTALL_PAYMENT"));
$frm = $this->frm_search;
$url_delete = $this->baseUrl()."/installment/payment/delete/id/";
$url_receipt = $this->baseUrl()."/report/installments/recieptpayment/id/";
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-money " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('INSTALL_PAYMENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('member');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			   	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('paymnet_type');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			</form>
    	</div>
    	<div class="card-box">
    		<?php echo $this->list;?>
    	</div>
    </div>
</div>


<script>
var row=0;
var url="";
var indexkey="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			indexkey="";
			var m = "clicked: " + key;
			 if(key=="delete"){
				url='<?php echo $url_delete;?>';
				indexkey = 'delete';
			 }else if(key=="receipt"){
					url='<?php echo $url_receipt;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"receipt": {name: "<?php  echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-print"},
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "fa-trash-o", accesskey: "c o p y"},
			
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	if(indexkey=='delete'){
	    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
	    	window.location.href = url+row;
	    } else {
	    	 return false;
	    }
	}else{
	 	window.open(url+row, '_blank');
	}
}
</script>