<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('GENERAL_SETTING')); 
echo $this->headTitle();
$frm = $this->frm_general;
if(!empty($this->logo['keyValue'])){
	$profile=$this->logo['keyValue'];
}else{
	$profile ="camapp.png";
}
?>
<style>
div.cke_contents.cke_reset {
    height: 200px !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<style>

img#image_viewbg {
    height: 50px;
}
.button_browse{
	margin-top:0 !important;
}
.button_browse span {
    padding: 0 5px;
}
tr.header {
    background: #008;
    color: #fff;
}
tr.header td {
    padding: 5px;
}
td.bold {
    font-weight: 600;
}
img.image_view {
    width: 190px;
    /* height: 100px; */
}


.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 30px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
    padding: 0 5px;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 35px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
</style>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-settings"></i>&nbsp;<?php echo $tr->translate('GENERAL_SETTING');?></h5>
	</div>
	<div class="card-body">
		<form action="" dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data" >
			<script type="dojo/method" event="onSubmit">				
					if(this.validate()) {
						return true;
					}
					return false;
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">				
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Address Client");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('branchAddClient');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Client Website");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('client_website');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Tel Client");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('telClient');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Email Client");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('email_client');?>
							   </div>
							</div>
							
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Client");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('brand_client');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Holiday");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('brand_holiday');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Call");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('brand_call');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Comment");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('comment');?>
							   </div>
							</div>							
						</div>
					</div>
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("PENALTY_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("graicePariod");?>
							   </label>
							   <div class="col-md-4 col-sm-4 col-xs-12">
									<?php  echo $frm->getElement('graicePariod');?>
							   </div>
							   <div class="col-md-3 col-sm-3 col-xs-12">
									<?php  echo $frm->getElement('penaltyCalculateDay');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("penaltyType");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('penaltyType');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("penaltyValue");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<div class="row g-3">
									   <div class="col-md-4 col-sm-4 col-xs-12">
											R <?php  echo $frm->getElement('penaltyValue');?>
									   </div>
									   <div class="col-md-4 col-sm-4 col-xs-12">
											USD <?php  echo $frm->getElement('penaltyValueDollar');?>
									   </div>
									   <div class="col-md-4 col-sm-4 col-xs-12">
											BATH <?php  echo $frm->getElement('penaltyValueBath');?>
									   </div>
									</div>
							   </div>
							</div>
						</div>
					</div>
	            </div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">	
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Company Name");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('client_company_name');?>
							   </div>
							</div>	
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Label Animation");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('label_animation');?>
							   </div>
							</div>	
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SMS Warnning KH");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('smsWarnningKH');?>
							   </div>
							</div>	
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Reciept KH");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('reciept_kh');?>
							   </div>
							</div>	
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Exchange Reciept");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('exchange_reciept');?>
							   </div>
							</div>	
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Exchange Rate Title");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('exchange_ratetitle');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Transfer Title KH");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('rptTransferTitleKh');?>
							   </div>
							</div>
							<div class="row g-3">
							   <img class="image_view" id="image_view" src="<?php echo $this->baseUrl().'/images/'.$profile;?>" alt=""  />
									<div class="button_browse">
										<span>Change Logo<span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
										<input class="btn_borwse_image"  type="file" id="photo" name="photo" onchange="loadImage()">
									</div>
							</div>
							<?php $eas=0; if ($eas==1){?>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Power By");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('power_by');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Email");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('branch_email');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Tel");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('branchTel');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Branch Address");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('branch_add');?>
							   </div>
							</div>
						<?php }?>
						</div>		
					</div>		
				</div>		
			</div>	

			<div class="card-box">
	         	<div class="col-sm-12 border-top mt-2 py-2 text-center">
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon glyphicon-repeat" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button"  onclick="window.history.back();" />
										<input class="button_success" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE');?>" id="save_close" dojoType="dijit.form.Button" /> 
				</div>
	         </div>			
		</form>
	</div>
</div>

<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.form.Textarea");
function loadImage(){
	 var output = document.getElementById('image_view');
  output.src = URL.createObjectURL(event.target.files[0]);
}

function CheckPenalty(){
	penaltyType = dijit.byId("penaltyType").get('value');
	if(penaltyType==1){
		penaltyValue = dijit.byId("penaltyValue").get('value');
		if(penaltyValue>100){
			alert("<?php echo $tr->translate('ប្រាក់ពិន័យជាភាគរយមិនអាចលើសពី ១០០%ឡើយ');?>");
			dijit.byId('penaltyValue').attr('value',100);
			return false;
		}
		
		penaltyValueDollar = dijit.byId("penaltyValueDollar").get('value');
		if(penaltyValueDollar>100){
			alert("<?php echo $tr->translate('ប្រាក់ពិន័យជាភាគរយមិនអាចលើសពី ១០០%ឡើយ');?>");
			dijit.byId('penaltyValueDollar').attr('value',100);
			return false;
		}
		
		penaltyValueBath = dijit.byId("penaltyValueBath").get('value');
		if(penaltyValueBath>100){
			alert("<?php echo $tr->translate('ប្រាក់ពិន័យជាភាគរយមិនអាចលើសពី ១០០%ឡើយ');?>");
			dijit.byId('penaltyValueBath').attr('value',100);
			return false;
		}
	}
}
</script>