<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle('SRMS | '.$tr->translate('Add User Type'));
echo $this->headTitle();
	$cancel_url=$this->url(array(
			'module'=>'rsvacl',
			'controller'=>'usertype',
			'action'=>'index',
		));
?>
<div class="card">
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('Add User Type');?></h5>
	</div>
	<div class="card-body">
		<form action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">										
				if(this.validate()) {		
					loadingBlock();						
					return true;
				}
				return false;
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" required="true" name="user_type" id="user_type" placeholder="<?php echo $tr->translate("TITLE");?>" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->usertype['user_type'];?>"
											missingMessage="Invalid User type!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Parent Name");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select onchange="disabledAgent(this.value);" class='fullside' name="parent_id" required="true" id="parent_id" 
								 missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect"> 
								 	<?php foreach ($this->usertype_list as $key => $ust) : ?>
										<option value="<?php echo $key;?>"  <?php if($this->usertype['parent_id'] == $key) echo 'selected';?> ><?php echo $ust;?></option>
									<?php endforeach;?>																																
								</select> 
	                   </div>
	                </div>
					<!-- Button Save  -->
					<div class="clearfix"></div>
					<div class="card-box">
						<div class="col-sm-12 border-top mt-2 py-2 text-center">
							
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="Save" label="<?php echo $tr->translate("SAVE");?>" id="submitButton" dojoType="dijit.form.Button"  /> 	
						</div>
					</div>
					<!--/. Button Save  -->
					
	            </div>
	        </div>
		</form>
	</div>
</div>	

<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>