<?php
	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SYSTEM_SETTING"));
	
	$data =$this->data;
?>
 <script>
	 dojo.require("dijit/form/CheckBox");
	 dojo.require("dijit/form/NumberTextBox");
 </script>
 <div class="card" id="mysetting">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom" style="text-align: left;">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cog" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SYSTEM_SETTING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="<?php echo $this->url(array('module'=>'setting','controller'=>'setting','action'=>'')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit">				
				if(this.validate()) {
					return true;
				}

				return false;
				</script>
			<div class="card-box">
				<div class="col-md-8 col-sm-8 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Saturday Working");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="radio" <?php if($data['work_saturday']==1)echo'checked="checked"'; ?> data-dojo-type="dijit/form/RadioButton" name="work_saturday" id="radioOne" value="1"/> <label for="radioOne" style="padding-right:40px;"><?php echo $tr->translate("Work");?></label>
 							<input type="radio" <?php if($data['work_saturday']==0)echo'checked="checked"'; ?>  data-dojo-type="dijit/form/RadioButton" name="work_saturday" id="radioTwo" value="0"/> <label for="radioTwo"><?php echo $tr->translate("Not Work");?></label>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Suday Working");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="radio" <?php if($data['work_sunday']==1)echo'checked="checked"'; ?> data-dojo-type="dijit/form/RadioButton" name="work_sunday" id="saturday_work1" value="1"/> <label for="saturday_work1" style="padding-right:40px;"><?php echo $tr->translate("Work");?></label>
 							<input type="radio" <?php if($data['work_sunday']==0)echo'checked="checked"'; ?> data-dojo-type="dijit/form/RadioButton" name="work_sunday" id="saturday_work2" value="0"/> <label for="saturday_work2"><?php echo $tr->translate("Not Work");?></label>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Admin Fee");?> (%)
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" required="true" name="adminfee"​ placeholder="adminfee" 
											dojoType="dijit.form.NumberTextBox" require="true" value="<?php echo $this->data['adminfee'];?>"
											class='fullside'/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Penal Multiplier");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" required="true" name="interest_late"​ placeholder="interest_late" 
											dojoType="dijit.form.NumberTextBox" value="<?php echo $this->data['interest_late'];?>"
											require="true" class='fullside'/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Graice Pariod Late");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="graice pariod_late" placeholder="លេខសម្ងាត់  Database" 
											dojoType="dijit.form.NumberTextBox" value="<?php echo $this->data['graice_pariod_late'];?>"
											require="true" class='fullside'/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Reschedule Postfix Label");?> (eg.PPL00004R)
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="reschedule_postfix" 
											dojoType="dijit.form.TextBox" value="<?php echo $this->data['reschedule_postfix'];?>"
											require="true" class='fullside'/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Prefix CO Staff");?> (eg.ST-001)
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="co_prefix" dojoType="dijit.form.TextBox" value="<?php echo $this->data['co_prefix'];?>" require="true" class='fullside'/>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Theme Style");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select id="theme_setting" name="theme_setting" dojoType="dijit.form.FilteringSelect" class='fullside'>
								<option value="1" <?php if($this->data['theme_setting']==1){echo "selected='selected'";} ?>><?php echo $this->data['claro']; ?></option>
								<option value="2" <?php if($this->data['theme_setting']==2){echo "selected='selected'";}?>><?php echo $this->data['nihilo']; ?></option>
								<option value="3" <?php if($this->data['theme_setting']==3){echo "selected='selected'";}?>><?php echo $this->data['soria']; ?></option>
								<option value="4" <?php if($this->data['theme_setting']==4){echo "selected='selected'";}?>><?php echo $this->data['tundra']; ?></option>
							</select>
	                   </div>
	                </div>
	                 <div class="row g-3">
	                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                   		<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 
	                   </div>
	                </div>
	           </div>
	        </div>
		</form>
    </div>
 </div>
	


