<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frmExchange;
	$this->headTitle($tr->translate('Add Condiction Trasfer'));
	echo $this->headTitle();
?>	
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-report-money"></i>&nbsp;<?php echo $tr->translate('Add Condiction Trasfer');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
 				dijit.byId("save_close").set("disabled",true);
				dijit.byId("save_new").set("disabled",true);
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("Currency Information");?> 
	                   </label>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Currency");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('currency_id');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('note');//echo $frm->getElement('for_date');?>
	                   </div>
	                </div>
	                 <?php $sq =0; if ($sq==1){?>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('status');?>
	                   </div>
	                </div>
	                <?php }?>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="row g-3">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("Condiction Information");?> 
	                   </label>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("From Amount");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('fromAmount');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("To Amount");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('toAmount');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Total Fee");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('totalFee');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Commision Fee");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('commisionFee');?>
	                   </div>
	                </div>
	            </div>
	         </div>
	          <div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
	    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"  label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" />
	    		</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require('dijit.form.Form');
dojo.require('dijit.form.Button');
dojo.require('dijit.form.NumberTextBox');
dojo.require('dijit.form.Textarea');
dojo.require("dijit.Dialog");
</script>