<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frmExchange;
	$this->headTitle($tr->translate('Edit Condiction Trasfer'));
	echo $this->headTitle();
?>	
<script type="text/javascript">
dojo.require('dijit.form.Form');
dojo.require('dijit.form.Button');
dojo.require('dijit.form.NumberTextBox');
dojo.require('dijit.form.Textarea');
dojo.require("dijit.Dialog");
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Edit Condiction Trasfer');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
 				dijit.byId("save_close").set("disabled",true);
				dijit.byId("save_new").set("disabled",true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("Currency Information");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Currency");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('currency_id');?>
							 <input type="hidden" value="<?php echo $this->row['id'];?>" class="fullside" readonly="readonly" required="required" id="id" name="id" dojoType="dijit.form.TextBox" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('note');//echo $frm->getElement('for_date');?>
	                   </div>
	                </div>
	                 <?php $sq =0; if ($sq==1){?>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('status');?>
	                   </div>
	                </div>
	                <?php }?>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("Condiction Information");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("From Amount");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('fromAmount');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("To Amount");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('toAmount');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Total Fee");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('totalFee');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Commision Fee");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('commisionFee');?>
	                   </div>
	                </div>
	            </div>
	         </div>
	          <div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	    			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
					 iconClass="dijitIconClear"/>
					<input type="submit"   label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose'​​ value='saveclose' dojoType="dijit.form.Button"
					 iconClass="dijitIconNewTask"/>
	    		</div>
			</div>
		</form>
	</div>
</div>
