<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('TRANSFER CONDICTION'));
	echo $this->headTitle();
	$frm = $this->frm_search;
	$frmes = $this->frmExchange;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form name="frmlist_mt" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frmes->getElement('currencySearch');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('status');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   					</div>
   				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>

