<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_PROVINCE')); 
?>
<?php  $province= $this->frm_province;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
 			<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_PROVINCE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="add_province" action="<?php echo $this->url(array('module'=>'other','controller'=>'province','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
                	dijit.byId("save_new").set("disabled",true);
					dijit.byId("save_close").set("disabled",true);
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("code");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("KH_PROVINCE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("kh_province");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EN_PROVINCE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("en_province");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("status");?>
	                   </div>
	                </div>
	                <div class="form-group">
		                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		                	<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
							<input type="button" onclick="submitDataClose();" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
							<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
			    		</div>
		    		 </div>
	            </div>
	         </div>
		</form>
	</div>
</div>

<script>
function submitDataClose(){
	if(dijit.byId('add_province').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'other','controller'=>'province','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_province"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/other/province";
			},
			error: function(e) {
			}
		});
	}
}
</script>