<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_PROVINCE')); 
?>
<?php  $province= $this->frm_province;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
 			<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PROVINCE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="add_province" action="<?php echo $this->url(array('module'=>'other','controller'=>'province','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("code");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("KH_PROVINCE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("kh_province");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EN_PROVINCE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("en_province");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $province->getElement("status");?>
	                   </div>
	                </div>
	                <div class="form-group">
		                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		                	 <input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"
                           iconClass="dijitIconClear" />
							<input type="submit" iconClass="dijitEditorIcon dijitEditorIconSave" value="<?php echo $tr->translate("GO_EDIT");?>" label="<?php echo $tr->translate("SAVECLOSE");?>" 
							id="submitButton" dojoType="dijit.form.Button" 
							 iconClass=""/>
			    		</div>
		    		 </div>
	            </div>
	         </div>
		</form>
	</div>
</div>
