<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PROVINCE_LIST"));
?>	
<?php $frm =  $this->frm_search;?>
<div class="card ">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('PROVINCE_LIST');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'province','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement("title");?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('status_search');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>

