<?php 
	header('Cache-Control: no cache'); //no cache
	session_cache_limiter('private_no_expire'); // works
	
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$vdgb = new Application_Model_DbTable_DbGlobal();
	$currentlang = $vdgb->currentlang();
	
	$session_user=new Zend_Session_Namespace(SYSTEM_SES);
	$username = $session_user->first_name;
	$them_style ='soria';
	$level =  $session_user->level;
	if (empty($session_user->user_id)){
		Application_Form_FrmMessage::redirectUrl("/");
	}
	$db = new Application_Model_DbTable_DbUsers();
	$CheckAccess = $db->getAccessUrl("pawnshop","index","index");
	$CheckAccessSaleIns = $db->getAccessUrl("installment","index","index");
	$userInfo = $db->getCurrentUserInfor();
	
	$rs = $vdgb->getCustomerNearlyPaymentLoan();
	
	$rsPawn=array();
	if (!empty($CheckAccess)){
		$rsPawn = $vdgb->getCustomerNearlyPaymentPawn();
	}
	
	$rsSaleIns=array();
	if (!empty($CheckAccessSaleIns)){
		$rsSaleIns = $vdgb->getCustomerNearlyPaymentSaleInstall();
	}
	
	$inFrame = $request->getParam("inFrame");
	$classShow = empty($inFrame) ? "" : "hiddenBlog";
	$classContentInframe = empty($inFrame) ? "" : "content-inframe";
	$padLeftContent = empty($inFrame) ? "" : "mrg-left-none";
?>
<!DOCTYPE html>
<html lang="en" class="light-style layout-navbar-fixed layout-menu-fixed layout-compact " dir="ltr" data-theme="theme-default" data-assets-path="<?php echo $this->baseUrl();?>/admin/assets/" data-template="vertical-menu-template">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
		<!-- Favicon -->
		<link rel="icon" type="image/x-icon" href="<?php echo $this->baseUrl()."/images/icon.ico";?>" />
		<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>js/dojo-1.6.1/dijit/themes/<?php echo $them_style."/".$them_style?>.css" />
    
		<!-- Icons -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/fonts/tabler-icons.css"/>
	
		<!-- Core CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/css/rtl/core.css" class="system-theme-skin-core-css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/css/rtl/theme-default.css" class="system-theme-skin-theme-css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/css/custom.css" />
		
		<!-- Vendors CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/node-waves/node-waves.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css">
	
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/sweetalert2/sweetalert2.css" />
		<link href="<?php echo $this->baseUrl();?>/admin/assets/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	
		<!-- Helpers -->
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/js/helpers.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/js/system-theme.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/js/config.js"></script>
		
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/jquery/jquery.js"></script>
  		<!-- Core JS -->
		
		<!-- build:js assets/vendor/js/core.js -->
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/popper/popper.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/js/bootstrap.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/node-waves/node-waves.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/hammer/hammer.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/i18n/i18n.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/js/menu.js"></script>
  
		<!-- endbuild -->
		<!-- Vendors JS -->
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js"></script>
		<script src="<?php echo $this->baseUrl();?>/admin/assets/vendor/libs/sweetalert2/sweetalert2.js"></script>

  
		<?php if ($module!=="home" AND ( $action=="index" OR $module=='report')){?>
		<link href="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.contextMenu.css" rel="stylesheet" type="text/css" />
		<script src="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.contextMenu.js" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.ui.position.min.js" type="text/javascript"></script>
	
		<script>
		$(document).ready(function() {
			$('#datatable-responsive').DataTable( {
				responsive: true,
			 "dom": '<"top"i>rt<"bottom"flp><"clear">',
				searching: false,
				"pageLength": 50
			} );
		} );
		</script>
		<?php }?>
  <?php if($module=='home' AND $controller=="index" AND $action=="index"){?>
	
   <?php }else{?>   
   <script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
   <script>dojoConfig = {parseOnLoad: true}</script>
	    <script>
			require(["dijit/form/Form","dijit/form/FilteringSelect","dijit/form/Button","dijit/Dialog"]);
      </script>
	<?php } ?>
	
	</head>
	<body class="<?php echo $them_style;?>">
		<!-- Layout wrapper -->
		<div class="layout-wrapper layout-content-navbar  ">
			<div class="layout-container">
				<!-- Menu -->
				<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme <?php echo $classShow;?>">
					<div class="app-brand system-skin ">
						<a href="<?php echo $this->baseUrl()."/home";?>" class="app-brand-link">
						  
						</a>
						<a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
						  <i class="ti menu-toggle-icon d-none d-xl-block ti-sm align-middle"></i>
						  <i class="ti ti-x d-block d-xl-none ti-sm align-middle"></i>
						</a>
					</div>
					<div class="menu-inner-shadow"></div>
					<?php echo $this->render('menuleft.phtml')?>
				</aside>
				<!-- / Menu -->
				<!-- Layout container -->
				<div class="layout-page <?php echo $padLeftContent;?>">
					<!-- Navbar -->
					<nav class=" <?php echo $classShow;?> layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
						<div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0   d-xl-none ">
							<a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
							  <i class="ti ti-menu-2 ti-sm"></i>
							</a>
						</div>
						  
						<div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
							
							
							<ul class="navbar-nav flex-row align-items-center ms-auto">
							  
							  <!-- Language -->
							  <li class="nav-item dropdown-language dropdown me-2 me-xl-0">
								<a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
								  <i class='ti ti-language rounded-circle ti-md'></i>
								</a>
								<ul class="dropdown-menu dropdown-menu-end">
								  <li>
									<a class="dropdown-item" href="javascript:void(0);" onclick="changeLange(1);" data-language="kh" data-text-direction="ltr">
									  <span class="align-middle">ភាសាខ្មែរ</span>
									</a>
								  </li>
								  <li>
									<a class="dropdown-item" href="javascript:void(0);" onclick="changeLange(2);" data-language="en" data-text-direction="ltr">
									  <span class="align-middle">English</span>
									</a>
								  </li>
								  
								</ul>
							  </li>
							  <!--/ Language -->
							  
							  
							  <!-- Style Switcher -->
							  <li class="nav-item dropdown-style-switcher dropdown me-2 me-xl-0">
								<a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
								  <i class='ti ti-md'></i>
								</a>
								<ul class="dropdown-menu dropdown-menu-end dropdown-styles">
								  <li>
									<a class="dropdown-item" href="javascript:void(0);" data-theme="light">
									  <span class="align-middle"><i class='ti ti-sun me-2'></i>Light</span>
									</a>
								  </li>
								  <li>
									<a class="dropdown-item" href="javascript:void(0);" data-theme="dark">
									  <span class="align-middle"><i class="ti ti-moon me-2"></i>Dark</span>
									</a>
								  </li>
								</ul>
							  </li>
							  <!-- / Style Switcher-->
							  

							  <?php 
									echo $this->render('notificationbar.phtml');
							  ?>
							  <!-- User -->
							  <li class="nav-item navbar-dropdown dropdown-user dropdown">
								<a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
								  <div class="avatar avatar-online">
									<img src="<?php echo $this->baseUrl()?>/images/user.png" alt class="h-auto rounded-circle">
								  </div>
								</a>
								<ul class="dropdown-menu dropdown-menu-end">
								  <li>
									<a class="dropdown-item" href="pages-account-settings-account.html">
									  <div class="d-flex">
										<div class="flex-shrink-0 me-3">
										  <div class="avatar avatar-online">
											<img src="<?php echo $this->baseUrl()?>/images/user.png" alt class="h-auto rounded-circle">
										  </div>
										</div>
										<div class="flex-grow-1">
										  <span class="fw-medium d-block"><?php echo $username;?></span>
										  <small class="text-muted"><?php echo $userInfo["userTypeTitle"]; ?></small>
										</div>
									  </div>
									</a>
								  </li>
								  <li>
									<div class="dropdown-divider"></div>
								  </li>
								  <li>
									<div id="systemModeClick">
									<a class="dropdown-item system-theme-skin-open-btn" href="javascript:void(0)">
									  <i class="ti ti-device-laptop me-2 ti-sm"></i>
									  <span class="align-middle"><?php echo $tr->translate("settingMode");?></span>
									</a>
									</div>
								  </li>
								  <li>
									<a class="dropdown-item" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>">
									  <i class="ti ti-settings me-2 ti-sm"></i>
									  <span class="align-middle"><?php echo $tr->translate("Change Password");?></span>
									</a>
								  </li>
								  <li>
									<div class="dropdown-divider"></div>
								  </li>
								  <li>
									<a class="dropdown-item" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>">
									  <i class="ti ti-logout me-2 ti-sm"></i>
									  <span class="align-middle"><?php echo $tr->translate("SIGN_OUT");?></span>
									</a>
								  </li>
								</ul>
							  </li>
							  <!--/ User -->
							</ul>
						  </div>

						  
						  <!-- Search Small Screens -->
						  <div class="navbar-search-wrapper search-input-wrapper  d-none">
							<input type="text" class="form-control search-input container-xxl border-0" placeholder="Search..." aria-label="Search...">
							<i class="ti ti-x ti-sm search-toggler cursor-pointer"></i>
						  </div>
					</nav>
					<!-- / Navbar -->
					<!-- Content wrapper -->
					<div class="content-wrapper">
						<!-- Content -->
						<div class="<?php if(empty($classShow)){ ?>container-xxl container-p-y<?php } ?> flex-grow-1 ">
							<script>
								window.isRtl = window.Helpers.isRtl(),
								window.isDarkStyle = window.Helpers.isDarkStyle();
								let menu, animate, isHorizontalLayout = !1;
							 </script>
							 <div id="tt" class="easyui-tabs  <?php echo $classContentInframe;?>" style="width:100%; ">
								<div id="firstTabs" title="Home" >
									<?php 
										$rs = $db->getAccessUrl($module,$controller,$action);
										if(!empty($rs) OR $action=='changepassword'){
											echo $this->layout()->content;
										}else{
											echo $this->render('pagenotfund.phtml');
										}
									 ?>
								</div>
							</div>
						</div>
						<!-- / Content -->
						<!-- Footer -->
						<footer class="content-footer footer bg-footer-theme <?php echo $classShow;?>">
						  <div class="container-xxl">
							<div class="footer-container d-flex align-items-center justify-content-between py-2 flex-md-row flex-column">
							  <div>
								©  All rights reserved & Developed By <a href="http://cam-app.com/" target="_blank" class="footer-link text-primary fw-medium">Cam App Technology</a>
							  </div>
							</div>
						  </div>
						</footer>
						<!-- / Footer -->
						 <div class="content-backdrop fade"></div>
					</div>
					<!-- / Content wrapper -->
				</div>
				<!-- / Layout container -->
			</div>
			<!-- Overlay -->
			<div class="layout-overlay layout-menu-toggle"></div>
			
			
			<!-- Drag Target Area To SlideIn Menu On Small Screens -->
			<div class="drag-target"></div>
		</div>
		<!-- / Layout wrapper -->
		
		<?php if($module!='report' AND $module!='home' AND $module!='default' ){?>
			<?php if(!empty($rs)){?>
			<div class="global-action <?php echo $classShow;?>">
				<?php if($action=='index' AND $module!='report' AND $module!='home'){?>
					<a class="btn btn-primary btn-global-action" title="<?php echo $tr->translate('ADD_NEW');?>" class='add-edit' href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>">
						
						<?php echo $tr->translate('ADD_NEW');?>&nbsp;&nbsp;<i class="fa fa-plus-circle animate-create" aria-hidden="true"></i>
					</a>
				<?php }elseif($action=='add' OR $action=='edit' OR $action=='quickchange' OR $action=='withdrawal' OR $module=='report' ){?>
					<a class="btn btn-primary btn-global-action" title="<?php echo $tr->translate('GO_BACK');?>" class='add-edit' href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>">
						<i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate('GO_BACK');?>
					</a>
				<?php }?>
			</div>
			<?php }?>
		<?php }else if($module=='report' AND $action!='index'){?>
			<div class="global-action">
				<div class="btn-group">
					<button type="button" class="btn btn-success dropdown-toggle hide-arrow" data-bs-toggle="dropdown" aria-expanded="false"><?php echo $tr->translate("ACTION");?> <i class="ti ti-dots-vertical"></i></button>
					<ul class="dropdown-menu">
					  <li><a href="javascript:void(0);" onclick="preview();" class="dropdown-item d-flex align-items-center"><i class="ti ti-file-search scaleX-n1-rtl"></i><?php echo $tr->translate("Preview");?></a></li>
					  <li><a href="javascript:void(0);" onclick="doPrint();" class="dropdown-item d-flex align-items-center"><i class="ti ti-printer scaleX-n1-rtl"></i><?php echo $tr->translate("PRINT");?></a></li>
					  <li><a href="javascript:void(0);" onclick="exportExcel();" class="dropdown-item d-flex align-items-center"><i class="ti ti-file-x scaleX-n1-rtl"></i><?php echo $tr->translate("Export");?></a></li>
					  
					</ul>
				</div>
			</div>
		<?php }?>
				
	<div class="overlay">
		<div class="d-flex align-items-center justify-content-center " style="height: 100vh;">
			<div class="text-center">
				<div class="sk-grid sk-primary">
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				  <div class="sk-grid-cube"></div>
				</div>
				<p class="text-primary">
					<?php echo $tr->translate("Loading");?>...
				</p>
			</div>
		</div>
	</div>	
<script>
$(document).ready(function() {
	var currentTitle = $(document).attr('title');
	$('#firstTabs').attr('title', currentTitle);
	var currentTab = $('#tt').tabs();
	$(".tabs-header ul.tabs" ).addClass( "hiddenBlog" );
	messageAlert('<?php echo $base_url.$module."/".$controller."/".$action;?>');
	
	setTimeout(function () {
		HideloadingBlock();
	}, 600);
});
function changeLange(lang){
	var urlChangelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
	jQuery.ajax({
		url: urlChangelang,
		type: "post",
		data:{'lange':lang},
		success: function(data){
			location.reload();
		},
		error:function(err){
			
		}
	});
}





</script>
  <!-- Main JS -->
  <script src="<?php echo $this->baseUrl();?>/admin/assets/js/main.js"></script>
  <!-- Easyui JS -->
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/admin/easyui/easyui.css">
  <script type="text/javascript" src="<?php echo $this->baseUrl()?>/admin/easyui/jquery.easyui.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl()?>/admin/system-js/global-func.js"></script>

</body>