<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$session_user=new Zend_Session_Namespace(SYSTEM_SES);
	$arr_module = $session_user->arr_acl;
	
	$menu = array();
$module = '';
$controller=array();
$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
			$lblcontroller = $rs['label'];
			if($rs['controller']=='index' AND $rs['module']=='group' ){
				$lblcontroller='CLIENT_INFO';
			}
			if($rs['controller']=='index' AND $rs['module']=='loan' ){
				$lblcontroller='IL_DISBURSE';
			}
			if($rs['module']=='installment' AND $rs['controller']=='index'){
				$lblcontroller='INSTALLMENT_MNG';
			}
			
			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>$tr->translate(strtoupper($lblcontroller)));
				$menu[$rs['module']]= $newarray;
				$old_module=$rs['module'];
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>$tr->translate(strtoupper($lblcontroller))));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;   
	$module = $request->getModuleName();
	$controller = $request->getControllerName();

	$array_icon = array(
      		'home'=>'<i class="menu-icon tf-icons ti ti-smart-home"></i>',
			'group'=>'<i class="menu-icon tf-icons ti ti-users-group"></i>',
			'loan'=>'<i class="menu-icon tf-icons ti ti-coins" ></i>',
			'pawnshop'=>'<i class="menu-icon tf-icons ti ti-cash" ></i>',
			'installment'=>'<i class="menu-icon tf-icons ti ti-cash" ></i>',
      		'tellerandexchange'=>'<i class="menu-icon tf-icons ti ti-text-wrap-disabled"></i>',
      		'capital'=>'<i class="menu-icon tf-icons ti ti-businessplan" ></i>',
			'other'=>'<i class="menu-icon tf-icons ti ti-forms"></i>',
      		'report'=>'<i class="menu-icon tf-icons ti ti-file-description"></i>',
      		'rsvacl'=>'<i class="menu-icon tf-icons ti ti-user-cog" ></i>',
      		'setting'=>'<i class="menu-icon tf-icons ti ti-settings"></i>',
      		'property'=>'<i class="menu-icon tf-icons ti ti-map"></i>',
      );
	
	$arr_module = $session_user->arr_module;
	$arr_acl = $session_user->arr_acl;
?>
<ul class="menu-inner py-1">

	<?php if(!empty($arr_module)){ foreach ($arr_module as $rs){
			$url =$this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);
			if ($rs=="project"){
					$title=$tr->translate("JOBS");
				}else{
					$title=$tr->translate(strtoupper($rs));
				}
			?>
			<li class="menu-item <?php if ($rs==$module ){ echo 'active open';}?> " >
				<?php if (count($arr_param_menu[$rs])>1){?>
					<a href="javascript:void(0);" class="menu-link menu-toggle">
						<?php echo $array_icon[$rs];?>
						<div data-i18n="<?php echo $title;?>"><?php echo $title;?></div>
					</a>
					<?php if (!empty($arr_param_menu[$rs])){?>
					<ul class="menu-sub">
					   <?php  foreach ($arr_param_menu[$rs] as $key => $sub){
						$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
						?>
						<li class="menu-item <?php if ($rs==$module AND $key==$controller){ echo 'active';}?>">
							<a href="<?php echo $urlsub;?>" class="menu-link">
								<div data-i18n="<?php echo $sub;?>"><?php echo $sub;?></div>
							</a>
						</li>
					   <?php }?>
					</ul>
					<?php }?>
				<?php }else{?>
					<?php  foreach ($arr_param_menu[$rs] as $key => $sub){
					$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
					$title=$tr->translate(strtoupper($key));
					if ($rs=="home" and $key=="index" ){
						$title=$tr->translate(strtoupper($rs));
					}
					?>
					<a href="<?php echo $urlsub;?>" class="menu-link">
						<?php echo $array_icon[$rs];?>
						<div data-i18n="<?php echo $title;?> "><?php echo $title;?> </div>
					  </a>
					<?php }?>
				<?php }?>
				<?php //}?>
			</li>
	<?php }
	}?>
			
    
  </ul>
