	<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$session_user=new Zend_Session_Namespace('authloan');
	$arr_module = $session_user->arr_acl;
	
	$menu = array();
$module = '';
$controller=array();
$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
			$lblcontroller = $rs['label'];
			if($rs['controller']=='index' AND $rs['module']=='group' ){
				$lblcontroller='CLIENT_INFO';
			}
			if($rs['controller']=='index' AND $rs['module']=='loan' ){
				$lblcontroller='IL_DISBURSE';
			}
			if($rs['module']=='installment' AND $rs['controller']=='index'){
				$lblcontroller='INSTALLMENT_MNG';
			}
			
			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>$tr->translate(strtoupper($lblcontroller)));
				$menu[$rs['module']]= $newarray;
				$old_module=$rs['module'];
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>$tr->translate(strtoupper($lblcontroller))));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;   
	$module = $request->getModuleName();
	$controller = $request->getControllerName();
?>
<?php 
	$array_icon = array(
      		'home'=>'<i class="fa fa-home" aria-hidden="true"></i>',
			'other'=>'<i class="fa fa-bookmark" aria-hidden="true"></i>',
			'group'=>'<i class="fa fa-users" aria-hidden="true"></i>',
			'loan'=>'<i class="fa fa-money" aria-hidden="true"></i>',
			'pawnshop'=>'<i class="fa fa-money" aria-hidden="true"></i>',
			'installment'=>'<i class="fa fa-money" aria-hidden="true"></i>',
      		'tellerandexchange'=>'<i class="fa fa-desktop" aria-hidden="true"></i>',
      		'capital'=>'<i class="fa fa-usd" aria-hidden="true"></i>',
      		'report'=>'<i class="fa  fa-file-text" aria-hidden="true"></i>',
      		'rsvacl'=>'<i class="fa  fa-cog" aria-hidden="true"></i>',
      		'setting'=>'<i class="fa  fa-cogs" aria-hidden="true"></i>',
			
      		'property'=>'<i class="fa  fa-cogs" aria-hidden="true"></i>',
      );
	
	$arr_module = $session_user->arr_module;
	$arr_acl = $session_user->arr_acl;
	?>
<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
	<div class="menu_section">
		<?php 
			$db = new Application_Model_DbTable_DbUsers();
			$rs = $db->getAccessUrl("loan","index","add");
			if(!empty($rs)){
		?>
		&nbsp;
		<div class="button-make-loan mb-10">
			<a href="<?php echo $this->baseUrl()."/loan/index/add"?>"  class="closebtn-makesale"  ><i class="fa fa-plus" aria-hidden="true"></i> <?php echo $tr->translate("Make Loan Disburse");?> </a>
		</div>
		<?php }?>
		<ul class="nav side-menu">
     	<?php if(!empty($arr_module)){ foreach ($arr_module as $rs){
             		$url =$this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);
            		if ($rs=="project"){
                			$title=$tr->translate("JOBS");
                		}else{
                			$title=$tr->translate(strtoupper($rs));
                		}
                	?>
                	<li>
                		<?php //if ($rs=="report"){?>
                			<!--
							<a href="<?php //echo $this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);;?>">
                			<?php //echo $array_icon[$rs];?> <?php //echo $title;?> 
	                		</a>
							-->
                		<?php //}else{?>
                		
                			<?php if (count($arr_param_menu[$rs])>1){?>
                		<a><?php echo $array_icon[$rs];?> <?php echo $title;?> 
                		<?php if (!empty($arr_param_menu[$rs])){?><span class="fa fa-chevron-down"></span><?php }?>
                		</a>
                		<?php if (!empty($arr_param_menu[$rs])){?>
                    <ul class="nav child_menu">
                       <?php  foreach ($arr_param_menu[$rs] as $key => $sub){
                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
                       	?>
                      <li><a href="<?php echo $urlsub;?>"><?php echo $sub;?></a></li>
                       <?php }?>
                    </ul>
                    <?php }?>
                    <?php }else{?>
                    	<?php  foreach ($arr_param_menu[$rs] as $key => $sub){
                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
                       	$title=$tr->translate(strtoupper($key));
                       	if ($rs=="home" and $key=="index" ){
                       		$title=$tr->translate(strtoupper($rs));
                       	}
                       	?>
                    <a href="<?php echo $urlsub;?>">
                			<?php echo $array_icon[$rs];?> <?php echo $title;?> 
                		</a>
                		<?php }?>
                    <?php }?>
                    <?php //}?>
                 	 </li>
            <?php }
            }?>
        </ul>
    </div>
 </div>
 <!-- /sidebar menu -->

 <!-- /menu footer buttons -->
 <div class="sidebar-footer hidden-small">
 	<a data-toggle="tooltip" data-placement="top" onClick="toggleFullScreen(document.body)" title="<?php echo $tr->translate("FullScreen");?>">
    	<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="<?php echo $tr->translate("SIGN_OUT");?>" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>">
    	<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
