<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('IL_PAYMENT'));
	$frm = $this->frm_ilpayment;
	
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$graiceperiod = $this->graiceperiod;
	$data = $this->keycode;
	$db_keycode = new Application_Model_DbTable_DbKeycode();
	$keyvalue = $db_keycode->getKeyCodeMiniInv();
	$interest_penalty = $keyvalue['interst_late'];
	
	$showreceipt = empty($this->keycode['showreceipt'])?2:$this->keycode['showreceipt'];
?>

<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('IL_PAYMENT');?></h5>
		<ul class="nav nav-tabs card-header-tabs" role="tablist">
          <li class="nav-item">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#panel21" role="tab" aria-selected="true"><i class="ti-xs ti ti-building-bank me-1"></i> <?php echo $tr->translate("ព៌ត័មាន បង់ប្រាក់ឥណទានទោល");?></button>
          </li>
          <li class="nav-item">
            <button class="nav-link " data-bs-toggle="tab" data-bs-target="#panel22" role="tab" aria-selected="false"><i class="ti-xs ti ti-coin me-1"></i> <?php echo $tr->translate("Loan Information");?></button>
          </li>
        </ul>
	</div>
	<div class="card-body">
		<form id='frm_add_group_pay' action="<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">
				if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if (branch_id=='' || branch_id==-1){
							infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> !');
							dijit.byId('branch_id').focus();
							return false;
					}
					service_charge = dijit.byId('service_charge').get('value');
					receive_amount = dijit.byId('amount_receive').get('value');
					option_pay = dijit.byId('option_pay').get('value');
					
					co_id = dijit.byId('co_id').get('value');
					client = dijit.byId('client_id').get('value');
					if (client=='' || client==-1){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?> !');
						dijit.byId('client_id').focus();
						return false;
					}if(co_id=='' || co_id==-1){
						infoMessageAlert('<?php echo $tr->translate("Please Select CO Name");?> !');
						dijit.byId('co_id').focus();
						return false;
					}
				   loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			
    		 <div class="tab-content tab-form">
				<div class="tab-pane fade active show" id="panel21" role="tabpanel">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("RECIEPT_INFO");?></h5>
								</div>
								<div class="card-body">
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id');?>
									   </div>
									</div>
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_NO");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="loan_number" />
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECIEPT_NO");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('reciept_no');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("បានបង់ពីមុនសរុប");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('paid_before');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRINCIPLE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('priciple_amount');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("បង់លើកទី");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('installment_no');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ថ្ងៃត្រូវបង់");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('payment_date');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ថ្ងៃគិតចាប់ពី");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('last_payment');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name">
										<label id="latedaylabel">
											<?php echo $tr->translate("យឺត");?> <span class="required">*</span> :
										</label>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('amount_late');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4  col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("PAYMENT_OPTION");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_OPTION");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('option_pay');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_PRINCIPLE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('os_amount');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_INTEREST");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('total_interest');?><input type="hidden" dojoType="dijit.form.TextBox" name="saving_amount" id="saving_amount" value="0" />
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_PENELIZE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('penalize_amount');?><?php echo $frm->getElement('old_penelize');?><input type="hidden" name="new_penelize" id="new_penelize">
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('service_charge');echo $frm->getElement('old_service_charge');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('total_payment');?><input type="hidden" dojoType="dijit.form.TextBox" name="oldTotalPay" id="oldTotalPay" />
									   </div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4  col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("PAYMENT_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COLLECT_DATE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('collect_date');?>
									   </div>
									</div>
					
									<div class="row g-3">
									   <label style="color:red;" class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_RECIEPT");?> <span class="required">*</span> :
									   </label>
									   <div class=" bold col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('amount_receive');?>
									   </div>
									</div>
									
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RETURN_AMOUNT");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('amount_return');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REMAIN");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('remain');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('note');?>
											<?php echo $frm->getElement('date_input');?>
											<?php echo $frm->getElement('last_payment_date'); ?>
											<?php echo $frm->getElement('installment_date');?>
											<?php echo $frm->getElement('amount_payment_term');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="panel22" role="tabpanel">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CUSTOMER_INFO");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NUM");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="client_code">
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="client_id">
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_LEVEL");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('load_level');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_PERIOD");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('loan_period');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_DATE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('release_date');echo $frm->getElement('old_release_date');?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('co_id');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("TERM_INSTALL");?></h5>
								</div>
								<div class="card-body">
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_AMOUNT");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('total_amount_loan');?>
									   </div>
									</div>
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST RATE");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('interest_ratelabel');?>
											<input dojoType="dijit.form.TextBox"  id="interest_rate" name="interest_rate" type="hidden">
									   </div>
									</div>
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TERM_CODITION");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('payment_term');?>
									   </div>
									</div>
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAMENT_METHOD");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('payment_method');?>
									   </div>
									</div>
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENCY");?> <span class="required">*</span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('currency_type');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-2 py-2 text-center">
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="រក្សាទុក & បិទ" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" name="save_close" dojoType="dijit.form.Button" onclick="submitDataClose()"  />
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-print" onClick="addPaymentByAjax();" value="រក្សាទុក & បោះពុម្ព" label="<?php echo $tr->translate('SAVE_PRINT');?>" id="saveprint"  name="saveprint" dojoType="dijit.form.Button" />
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" name="save_new" id="save_new" onclick="confirmBeforePrint();" value="រក្សាទុក" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" />
				</div>
    		</div>
	    	<!--/. Button Save  -->
			
			<div class="card card-form mb-4">
				<div class="card-header">
					<ul class="nav nav-tabs card-header-tabs" role="tablist">
					  <li class="nav-item">
						<a class="nav-link active" data-bs-toggle="tab" data-bs-target="#payemntPanel211" role="tab" aria-selected="true"><i class="ti-xs ti ti-calendar-dollar me-1"></i> <?php echo $tr->translate("SCHEDULE_PAYMENT");?></a>
					  </li>
					  <li class="nav-item">
						<a class="nav-link " data-bs-toggle="tab" data-bs-target="#payemntPanel212" role="tab" aria-selected="false"><i class="ti-xs ti ti-calendar me-1"></i> <?php echo $tr->translate("HISTORY_SCHEDULE_PAYMENT");?></a>
					  </li>
					  <li class="nav-item">
						<a class="nav-link " data-bs-toggle="tab" data-bs-target="#payemntPanel213" role="tab" aria-selected="false"><i class="ti-xs ti ti-calendar-time me-1"></i> <?php echo $tr->translate("HISTORY_SCHEDULE_PAYMENTED");?></a>
					  </li>
					</ul>
				</div>
				<div class="card-body p-0">
					<div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div style=" max-height: 400px; min-height;400px;   overflow-y: auto;">
								<div class="tab-content p-3">
									<div class="tab-pane fade active show" id="payemntPanel211" role="tabpanel">
										<div id='data_table' name='data_table'></div>
									</div>
									<div class="tab-pane fade" id="payemntPanel212" role="tabpanel">
										<div id='data_table1' name='data_table1'></div>
									</div>
									<div class="tab-pane fade" id="payemntPanel213" role="tabpanel">
										<div id='data_table_loan_haspay' name='data_table_loan_haspay'></div>
									</div>
								</div>
							 </div>
						</div>
						
					</div>
				</div>			
			</div>	
			<div class="clearfix">
				<input type="hidden" dojoType="dijit.form.TextBox" name="identity" id="identity">
				<input type="hidden" dojoType="dijit.form.TextBox" name="record_id" id="record_id">
				<input type="hidden" dojoType="dijit.form.TextBox" name="curr" id="curr">
				<?php  echo $frm->getElement('reciever');?>
			</div>
			
		</form>
	</div>
</div>
	
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'បោះពុម្ភ វិក័យបត្រ', onCancel:hideDialog" id="frm_client" style="width:25cm">
		
		<div id="rpt_print" style="width: 100%;height: 14.8cm ; padding: 0px; margin: 0px;">
			<?php 
				echo $this->loanReceipt;
			?>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
		<div id="rpt_print1" style="width: 100%;height: 14.8cm ; padding: 0px; margin: 0px;">
		<?php if($showreceipt>1){?>
				<div style="border:2px dashed #000; vertical-align: middle; margin:40px 0px 40px 0px"></div>
			<?php }?>
			<label id="innerrpt_print1"></label>
		</div>	
		
		<input type="button" value="បោះពុម្ព" label="បោះពុម្ព" id="print" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="print();"/>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div id="alertBeforePrint" data-dojo-type="dijit.Dialog" style="width:10cm;height: 5cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("បោះពុម្ពបង្កាន់ដៃ");?>'"  >
		<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style="height:4cm;color:red; font-family: 'Khmer OS Battambang' !important;font-size:15px !important;white-space:nowrap;">
			<tr>
				<td align="center" >
					តើលោកអ្នកពិតជាចង់រក្សាទុក ទិន្នន័យនេះមែនទេ? <br />
					Do you really want to save ?
				</td>
			</tr>
			<tr>
				<td align="center">
					<button dojoType="dijit.form.Button" class="button-class button-danger" iconClass="glyphicon glyphicon-remove"   type="button" onclick="hideDialog1();"><?php echo $tr->translate("ទេ / No");?></button>
					<button dojoType="dijit.form.Button" class="button-class button-primary" iconClass="glyphicon glyphicon-ok"    type="button" onclick="submitData();"><?php echo $tr->translate("យល់ព្រម / Yes");?></button>
				</td>
			</tr>
		</table>
	</div>
</div>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog", "dijit/layout/TabContainer"]);
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.data.ObjectStore");
	
function confirmBeforePrint(){
	dijit.byId('alertBeforePrint').show();
}
function hideDialog1(){
	dijit.byId('alertBeforePrint').hide();
}
var graice_period = <?php echo $graiceperiod["value"] ?>;
function submitDataClose(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'add')); ?>';
		service_charge = dijit.byId('service_charge').get('value');
		receive_amount = dijit.byId('amount_receive').get('value');
		option_pay = dijit.byId('option_pay').get('value');
		total_payments = dijit.byId('total_payment').get('value');
		if(receive_amount<0){
			infoMessageAlert('Please fill Recieve Amount');
			dijit.byId('amount_receive').focus();
		}else{
			if(option_pay==2 || option_pay==3 || option_pay==4){
				if(receive_amount<total_payments){
					infoMessageAlert('You Can not paymnet in this option! Please Input Recieve Amount more than or squar Total Paymnet!');
					dijit.byId('amount_receive').focus();
				}else{
					loading();
					dojo.xhrPost({
						url: url_submit,	
						form: dojo.byId("frm_add_group_pay"),		    
						load: function(data) {
							HideloadingBlock();		
							infoMessageAlert('<?php echo $tr->translate('INSERT_SUCCESS');?> !',1);
							window.location.href ="<?php echo $this->baseUrl();?>/loan/payment";
						},
						error: function(e) {
						}
					});
				}
			}else{
				loading();
					dojo.xhrPost({
						url: url_submit,	
						form: dojo.byId("frm_add_group_pay"),		    
						load: function(data) {
							HideloadingBlock();		
							infoMessageAlert('<?php echo $tr->translate('INSERT_SUCCESS');?> !',1);
							window.location.href ="<?php echo $this->baseUrl();?>/loan/payment";
						},
						error: function(e) {
						}
					});
			}
		}
}
function submitData(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'add')); ?>';
	service_charge = dijit.byId('service_charge').get('value');
	receive_amount = dijit.byId('amount_receive').get('value');
	option_pay = dijit.byId('option_pay').get('value');
	total_payments = dijit.byId('total_payment').get('value');
	
	if(receive_amount<0){
		infoMessageAlert('Please fill Recieve Amount');
		dijit.byId('amount_receive').focus();
	}else{
		if(option_pay==2 || option_pay==3 || option_pay==4){
			if(receive_amount<total_payments){
				infoMessageAlert('You Can not paymnet in this option! Please Input Recieve Amount more than or squar Total Paymnet!');
				dijit.byId('amount_receive').focus();
			}else{
				loading();
				dojo.xhrPost({
						url: url_submit,	
						form: dojo.byId("frm_add_group_pay"),		    
						load: function(data) {
							HideloadingBlock();	
							//infoMessageAlert('<?php //echo $tr->translate('INSERT_SUCCESS');?> !',1);
							window.location.href ="<?php echo $this->baseUrl();?>/loan/payment/add";
						},
						error: function(e) {
						}
					});
				}
			}else{
				loading();
					dojo.xhrPost({
						url: url_submit,	
						form: dojo.byId("frm_add_group_pay"),		    
						load: function(data) {
							HideloadingBlock();		
							//infoMessageAlert('<?php //echo $tr->translate('INSERT_SUCCESS');?> !',1);
							window.location.href ="<?php echo $this->baseUrl();?>/loan/payment/add";
						},
						error: function(e) {
						}
					});
			}
		}
}
function showReciept(data){
	//curr_type = dijit.byId('currency_type').get('value');
	//if(curr_type==1){
		//symbal =" ៛";
	//}else if(curr_type==2){
		//symbal =" $";
	//}else{
		//symbal =" B";
	//}
	//var returnAmount = dijit.byId('amount_return').attr('displayedValue');
	//if(returnAmount==''){returnAmount=0;}
	date = new Date(data.date_payment);
	var month = date.getMonth()+1;
	var noDate = date.getDate();
	var year = date.getFullYear()
	if(noDate<=9){
		noDate="0"+noDate;
	}
	if(month<=9){
		month="0"+month;
	}
	var monthNames = [
	                  "Jan", "Feb", "Mar",
	                  "Apr", "May", "Jun", "Jul",
	                  "Aug", "Sep", "Oct",
	                  "Nov", "Dec"
	                ];


	dojo.byId("lbl_reciept_no").innerHTML = data.receipt_no;
	dojo.byId("lbl_branch_id").innerHTML = data.branch_name;
	dojo.byId("lbl_loan_number").innerHTML = data.loan_number;
	dojo.byId("lbl_group_member").innerHTML = data.client_name;
	dojo.byId("lbl_co_id").innerHTML = data.co_name;

	dojo.byId("lbl_priciple_amount").innerHTML = data.begining_balance;
	dojo.byId("lbl_total_payment").innerHTML = dojo.number.format(data.total_paymentpaid,{places:2});
	dojo.byId("lbl_paidTime").innerHTML = data.paid_times;
	dojo.byId("lbl_collect_date").innerHTML = noDate+"/"+monthNames[date.getMonth()]+"/"+year;
	
	dojo.byId("lbl_os_amount").innerHTML = data.principal_paid;
	dojo.byId("lbl_interest_paid").innerHTML = data.interest_paid;
	dojo.byId("lbl_penalty_amount").innerHTML = data.penalize_paid;
	dojo.byId("lbl_totalpaid").innerHTML = data.currency_typeshow+" "+dojo.number.format(data.total_paymentpaid,{places:2});

	dojo.byId("lbl_note").innerHTML = data.note;

	dojo.byId("ClientLbl").innerHTML = data.client_name;
	
	printReciept();
}
dojo.ready(function(){	
		var loan_data = new dojo.store.Memory({
		    data: <?php print_r(Zend_Json::encode($this->loan_number));?>
		});
		new dijit.form.FilteringSelect({
			store: dojo.data.ObjectStore({objectStore: loan_data}),
			required: false,		           
			name: "loan_number",
			id: "loan_number",
			searchAttr: "name",
			autoComplete: false,
			queryExpr: "*${0}*",
			class: 'fullside',
			onChange: function() {
				getLaonPayment(1);//tab1
				getAllLaonPayment(1);//tab2
				getLaonHasPayByLoanNumber();//tab3
				dijit.byId("amount_receive").focus();
			}
		}, "loan_number");
		
	var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->client));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "client_id",
	readOnly:true,
	id: "client_id",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		if(not_submit==0){
	   }
}
	}, "client_id");

	var clientCode_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->clientCode));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: clientCode_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "client_code",
	readOnly:true,
	id: "client_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		if(not_submit==0){
		}
	}
	}, "client_code");

    not_submit = 0;
	document = dojo.byId("loan_number");
	dojo.connect(document, "onkeyup", function(event) {
		key_number = (event.keyCode);
		if(key_number==13){
			not_submit = 1;
			getLaonHasPayByLoanNumber();
			getLaonPayment(1);
		}
	});
	dijit.byId("branch_id").attr("value",1);
	rsid ='<?php echo $this->rsid;?>';	
	if(rsid>0){
		dijit.byId("branch_id").attr("value",<?php echo $this->rsloan['branch_id'];?>);
		dijit.byId("loan_number").attr("value",<?php echo $this->rsloan['id'];?>);
	}

	<?php 
	if($this->user_type!=1){?>
		dijit.byId('total_interest').attr('readOnly',true);
		<?php $settingEnalbleDate =1;
		if ($settingEnalbleDate==1){?>
		dijit.byId('collect_date').attr('readOnly',true);
		<?php }?>
	<?php }?>
});
function filterLoanNumber(){
	//infoMessageAlert(dijit.byId('branch_id').get('value'));
	 dijit.byId('loan_number').query.branch_id = dijit.byId('branch_id').get('value');
}
is_change=0;
function filterClient(){
	getbranchinfo();
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_id').query.branch_id = branch_id;
	dijit.byId('client_code').query.branch_id = branch_id;
	if(is_change==0){
		dijit.byId('client_id').reset();
		dijit.byId('client_code').reset();
	}
}
    var tran_store  = getDataStorefromJSON('','name',null);
	var tran_status = {};
function print(){
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
	submitData();
}
function hideDialog() {		
	dijit.byId("frm_client").hide();
	//submitData()
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('frm_client').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
   // hideDialog();
}
var url_branchifo = '<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'getbranch')); ?>';
var bchange = 1;
function getbranchinfo(){
	branch_id = dijit.byId('branch_id').get('value');
	
	if(branch_id==''){
		infoMessageAlert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_branchifo,	
		content:{ 
			    'branch_id':branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			if(bchange!=1){
				dijit.byId('loan_number').reset();
				dijit.byId('client_id').reset();
				dijit.byId('client_code').reset();
			}
			
			dojo.byId('br_address').innerHTML=data.br_address;
			dojo.byId('branch_tel').innerHTML=data.branch_tel;
			bchange = 2;
		},
		error: function(err) {
			
		}
	});
}
</script>
<script type="text/javascript">
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
dojo.ready(function(){
	loan_number = dijit.byId('loan_number').focus();
	dijit.byId('currency_type').attr('readOnly','readOnly');
	dijit.byId('payment_term').attr('readOnly','readOnly');
	dijit.byId('interest_rate').attr('readOnly','readOnly');
});
function payOption(){
	var ids =dijit.byId('record_id').get('value');
	var arrays = ids.split(',');
	calculateTotal();
}
var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'get-il-loan-Detail')); ?>';
function getLaonPayment(type){//tab ទី1
	dijit.byId('option_pay').attr('value',1);
	dijit.byId('identity').attr('value',"");
	try{
	tem='';	is_set=0;//
	var loan_number = dijit.byId('loan_number').get('value');
	 loadingBlock()
		dojo.xhrPost({
		    url: url_submit,
		    content:{ 
			    'loan_number':loan_number,
			    'type':type,
			},	
			handleAs:"json",
			load: function(respone) {
				tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
					+'<thead><tr><th class="tdheader"><?php echo $tr->translate('NO');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('បង់លើក');?></th>'
					+'<th class="tdheader"><input type="checkbox" OnChange="checkAll();" name="check_all" id="check_all" /></th>'
					+'<th class="tdheader" colspan="2"><?php echo $tr->translate('PAY_DATE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PRINCIPLE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PRINCIPLE_PERMONTH');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('INTEREST');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PENALIZE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('AMOUNT_PAYMENT');?></th>'
				+'</thead>';
				if(respone!=""){
					num=0;
					total=0;
					counts =0;
					principal_permonth=0;
					interest=0;
					payment=0;
					collect_date = dijit.byId("collect_date").get('value');
					for(i=0;i<respone.length;i++){
						inx = i+1;
						num++;
						date = new Date(respone[i].date_payment);
						str_day = getDayString(date.getDay());
						date_pay = respone[i].date_payments;
						curr =getCurrencyType(respone[i].currency_type);
						id = respone[i].id;
						pay_option = dijit.byId('option_pay').get('value');
						if(is_set!=1){
							getdataPaymentToForm(respone[i]);
							is_set=1;
						}
						
						if(pay_option==1){
								date = new Date(respone[i].date_payment);
								date_now = new Date();
								a = date-date_now;
								checked='';
								if(inx==1 || a<=0){
									
									checked ="checked='checked'";
								}
							}else{
								  checked ="checked='checked'";
							}
							tem+= '<tr id=tr_'+inx+' style="background-color:none">';
							tem += '<td>&nbsp;'+num+'</td>';
							tem += '<td align="center">&nbsp;'+respone[i].installment_amount+'</td>';
							tem += '<td>&nbsp;<input style="margin:0px;padding:0px;" onclick="return false" onkeydown="return false" '+checked+' type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" OnChange="calculateTotal('+inx+')" /></td>';
						    tem += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;</td>';
						    tem += '<td style="white-space: nowrap;">&nbsp;'+date_pay+'&nbsp;<input type="hidden" name="date_payment_'+inx+'" id="date_payment_'+inx+'" value="'+respone[i].date_payment+'" /><input type="hidden" name="last_pay_date'+inx+'" id="last_pay_date'+inx+'" value="'+respone[i].last_pay_date+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].outstanding_after)+' '+curr+'&nbsp;<input type="hidden" name="outstanding_'+inx+'" id="outstanding_'+inx+'" value="'+respone[i].outstanding_after+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].principle_after)+' '+curr+'&nbsp;<input type="hidden" name="principal_permonth_'+inx+'" id="principal_permonth_'+inx+'" value="'+respone[i].principle_after+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_interest_after)+' '+curr+'&nbsp;<input type="hidden" name="interest_'+inx+'" id="interest_'+inx+'" value="'+respone[i].total_interest_after+'" /><input type="hidden" name="interest_before'+inx+'" id="interest_before'+inx+'" value="'+respone[i].total_interest+'" /></td>';
							tem += '<td>&nbsp;<label id="lb_penelize_'+inx+'">'+dojo.number.format(respone[i].penelize_service)+' '+curr+'</label>&nbsp;<input type="hidden" name="penelize_'+inx+'" id="penelize_'+inx+'" value="'+respone[i].penelize_service+'" /></td>';
						    tem += '<td>&nbsp;<label id="lb_payment_'+inx+'">'+dojo.number.format(respone[i].total_payment_after)+' '+curr+'</label>&nbsp;<input type="hidden" name="total_payment_after_'+inx+'" id="total_payment_after_'+inx+'" value="'+respone[i].total_payment_after+'" /></td>';
							
						  tem += '</tr>';
						if(inx!=1) {
							var identity = dijit.byId('record_id').get('value');
							dijit.byId('record_id').attr('value',identity+','+inx);
						} else {
							dijit.byId('record_id').attr('value',inx);
							dijit.byId('identity').attr('value',1);
						}
					}
				}else{
				}
				tem+='</table>';
				dojo.byId('data_table').innerHTML = tem;
				calculateTotal();
				 HideloadingBlock();
			},
			error: function(e) {
				 HideloadingBlock();
			}
		});
	}catch(err){
	}	
}
function getdataPaymentToForm(data){//គណនាថ្ងៃយឺតអោយត្រូវគ្រប់ករណី
	is_change = 1;
	dijit.byId('client_id').attr('value',data.client_id);
	principal_paid = data.principal_paid;
	principal_paid = (principal_paid==null)?0:principal_paid;
	
	dijit.byId('paid_before').attr('value',principal_paid);
	dijit.byId('priciple_amount').attr('value',data.outstanding_after);
	dijit.byId('installment_no').attr('value',data.installment_amount);
	
	dijit.byId('payment_date').attr('value',data.date_payment);
	dijit.byId('last_payment').attr('value',data.prev_paymentdate);
	
	payment_date = new Date(dijit.byId("collect_date").attr("value"));
	date_installment = new Date(data.date_payment);
	if(data.last_pay_date==null){//អត់មានលុត្រាតែមិនទាន់ដែលបង់
		dijit.byId('last_payment').attr('value',data.loan_releate);
	}else{
		var timeDiff = ( collect_date.getTime()-date_installment.getTime() );
		var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24)); 
	}
	if(diffDays>0){
		dijit.byId("amount_late").attr("value",diffDays);
	}else{
		dijit.byId("amount_late").attr("value",0);
	}
	
	dijit.byId('os_amount').attr('value',data.principle_after);
	dijit.byId('total_interest').attr('value',data.total_interest_after);
	//dijit.byId('penalize_amount').attr('value',data.penelize_service);use
	dijit.byId('interest_ratelabel').attr('value',data.interest_rate);
	
	dijit.byId('client_code').attr('value',data.client_id);
	dijit.byId('co_id').attr('value',data.co_id);
	dijit.byId('interest_rate').attr('value',data.interest_rate);
	dijit.byId('release_date').attr('value',data.date_release);
	dijit.byId('payment_term').attr('value',data.collect_typeterm);
	dijit.byId('currency_type').attr('value',data.currency_type);
	dijit.byId('reciever').attr('value',data.collect_by);
	dijit.byId('amount_payment_term').attr('value',data.amount_collect_principal);
	dijit.byId('release_date').attr('value',data.date_release);
	dijit.byId('old_release_date').attr('value',data.release_date);
	dijit.byId('load_level').attr('value',data.level);
	dijit.byId('total_amount_loan').attr('value',data.loan_amount);
	dijit.byId('loan_period').attr('value',data.total_duration);
	dijit.byId('payment_method').attr('value',data.payment_method);
	dijit.byId('load_level').attr('value',data.level);
	var today = new Date();
	dijit.byId('collect_date').attr('value',today);
	calTotal();
	getRPNumber(data.co_id);//for get order receipt by co
}
function calculateTotal(index){//for គណនាប្រាក់ត្រូវបង់សរុប
	try{
		var payOption = dijit.byId('option_pay').get('value');//វិធីសាស្ត្របង់មកវិញ
		var payment_term = dijit.byId('payment_term').get('value');//ខ្ចីជា =>3 month
		var interest_rate = dijit.byId('interest_rate').get('value');
		
		collect_date = new Date(dijit.byId("collect_date").attr("value"));
		last_payment = new Date(dijit.byId("last_payment").attr("value"));
		payment_date = new Date(dijit.byId("payment_date").attr("value"));	
				
		var timeDiff = ( collect_date.getTime()-payment_date.getTime() );
		var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24)); 

		if(diffDays>0){
			dojo.byId('latedaylabel').innerHTML = '<?php echo $tr->translate("Number of days late paid")?>';
		}else{
			dojo.byId('latedaylabel').innerHTML = '<?php echo $tr->translate("Number of days prepaid")?>';
		}
		dijit.byId("amount_late").attr("value",diffDays);

		var timeDiff = ( collect_date.getTime()-last_payment.getTime() );
		var interest_day = Math.ceil(timeDiff / (1000 * 3600 * 24)); 
		
		var amount_lateday = dijit.byId('amount_late').get('value');
		var amount_collect_term = dijit.byId('amount_payment_term').get('value');
		var cu_type = dijit.byId('currency_type').get('value');
		var amount_late = dijit.byId('amount_late').get('value');
		graice_period = '<?php echo $graiceperiod["value"]?>';
		interest_penalty = '<?php echo $interest_penalty?>';
		
		total_latedate = amount_late-graice_period;
		principal_permonth = 0;
		interest =0;
		total_payment = 0;
		total_penalty = 0;
		principal_permonth_late = 0;

		if(payment_term==1){
		     term_amountday = 1;
		}else if(payment_term==2){
			term_amountday = 7;
		}else{
			term_amountday = 30;
		}
		
		var ids =dijit.byId('record_id').get('value');
		var arrays = ids.split(',');
		dijit.byId("identity").attr('value','');
		for(var i=0;i<arrays.length;i++){//calculate record row				
			if($('#mfdid_'+arrays[i]).attr('checked')){	
				var iden = dijit.byId("identity").get('value');
				if(iden!="") {
					dijit.byId("identity").attr('value',iden+','+arrays[i]);
				}else { 
					dijit.byId("identity").attr('value',arrays[i]);
				}
				if(payOption==1 || payOption==2){//បង់មុន
					principal_permonth = principal_permonth+parseFloat($('#principal_permonth_'+arrays[i]).val());
					interest = interest+parseFloat($('#interest_'+arrays[i]).val());
				}else if(payOption==3){//បង់រំលស់ប្រាក់ដើម
					principal_permonth = principal_permonth+parseFloat($('#principal_permonth_'+arrays[i]).val());
					interest = 0;
				}else if(payOption==4){
					principal_permonth_late = principal_permonth_late+parseFloat($('#principal_permonth_'+arrays[i]).val());
				}
			 }
			if(payOption==4){////បង់ផ្តាច់
				principal_permonth = principal_permonth+parseFloat($('#principal_permonth_'+arrays[i]).val());
				payment_date = new Date($('#date_payment_'+arrays[i]).val());
				
				var timeDiff = ( collect_date.getTime()-payment_date.getTime() );
				var amount_day = Math.ceil(timeDiff / (1000 * 3600 * 24)); 
				
				if(amount_day>=0){
					interest = interest+parseFloat($('#interest_'+arrays[i]).val());
				}else{
					payment_date = $('#date_payment_'+(arrays[i]-1)).val();
					if (typeof payment_date == 'undefined'){
						payment_date = dijit.byId("last_payment").attr("value");
					}					
					if(payment_date!=null || payment_date!="null"){
						payment_date = new Date(payment_date);
						var timeDiff = ( collect_date.getTime()-payment_date.getTime() );
						var amount_day = Math.ceil(timeDiff / (1000 * 3600 * 24)); 
						if(amount_day>0){
							//interest = interest+parseFloat($('#interest_'+arrays[i]).val());//only for battambang
							interest = parseFloat(interest+((parseFloat($('#outstanding_'+arrays[i]).val())*interest_rate/term_amountday/100)*amount_day));
						}
					}
				}
			}
		}
		if(payOption==4){
			dijit.byId('total_interest').attr('readOnly',false);
			if(total_latedate>0){
				total_penalty = (principal_permonth_late+interest)*(interest_penalty*interest_rate/term_amountday/100)*total_latedate;
			}
			installment_no = dijit.byId("installment_no").get("value");
			
			if(installment_no<=4){
				total_penalty=$("#interest_before1").val();
			}
		}else if(payOption==1 && total_latedate>0){
			total_penalty=0;//above is used by for loan at battambang ot use
		}
		total_penalty= roundhundred(total_penalty);
		interest= roundhundred(interest);
		dijit.byId("penalize_amount").attr("value",total_penalty);//use
		dijit.byId("os_amount").attr("value",principal_permonth);
		dijit.byId("total_interest").attr("value",interest);
		dijit.byId("total_payment").attr("value",principal_permonth+interest+total_penalty);
		<?php 
	if($this->user_type!=1){?>
		dijit.byId('total_interest').attr('readOnly',true);
		<?php 
		if ($settingEnalbleDate==1){?>
		dijit.byId('collect_date').attr('readOnly',true);
		<?php }?>
	<?php }?>
		calTotal();
	}catch(err){
	}
}
function getAllLaonPayment(type){//tabl2 
	types=1;
	var loan_numbers = dijit.byId('loan_number').get('value');
	var url_submits = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'get-all-il-loan-Detail')); ?>';
	dojo.xhrPost({
	    url: url_submits,
	    content : { 
		    'loan_numbers':loan_numbers,
		    'types':types,
		},	
		handleAs:"json",
		load: function(data) {
			tmp='';	is_sets=0;
			tmp='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
				+'<thead><tr><th class="tdheader"><?php echo $tr->translate('NO');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PAY_DATE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PRINCIPLE_PERMONTH');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('TOTAL_INTEREST');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('AMOUNT_PAYMENT');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('STATUS');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('NOTE');?></th></tr>'
				+'</thead>';
			nums=0;
			if(data!=""){
				for(j=0;j<data.length;j++){
					statuss='<label style="color:red;"><?php echo $tr->translate('NOT_COMPLETED');?></label>';
					++nums;
					var is_apprs="";
					ds = new Date(data[j].date_payment);
					str_days = getDayString(ds.getDay());
					currs =getCurrencyType(data[j].currency_type);
					datePayment = new Date(ds);
					 tmp+= '<tr>';
					    tmp += '<td>&nbsp;'+nums+'</td>';
					   	tmp += '<td style="white-space: nowrap;">&nbsp;'+data[j].date_payments+'&nbsp;</td>';
						tmp += '<td>&nbsp;'+dojo.number.format(data[j].principle_after)+' '+currs+'&nbsp;</td>';
					    tmp += '<td>&nbsp;'+dojo.number.format(data[j].total_interest_after)+' '+currs+'&nbsp;</td>';
					    tmp += '<td>&nbsp;'+dojo.number.format(data[j].total_payment_after)+' '+currs+'&nbsp;</td>';
						if(data[j].is_completed==1){
							statuss = '<label style="color:blue;"><?php echo $tr->translate('COMPLETED');?></label>';
							if(data[j].is_approved==1){is_apprs='<label style="color:blue;">Approved</label>';}
						}else{
							is_apprs='';
						}
						tmp += '<td>&nbsp;<label style="font-size:10px;">'+statuss+'</label></td>';
						tmp += '<td>&nbsp;<label style="font-size:10px;">'+is_apprs+'</label></td>';
					    tmp += '</tr>';
				}
			}
			tmp+='</table>';
			dojo.byId('data_table1').innerHTML = tmp;
		},
		error: function(e) {
		}
	});
}
var amount_completed=0;
function getLaonHasPayByLoanNumber(){//ប្រវត្តិបង់//tab3
	try{
		amount_completed=0;
		var loan_number = dijit.byId('loan_number').get('value');
		var url_submits = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'get-loan-has-pay-by-loan-number')); ?>';
			dojo.xhrPost({
			    url: url_submits,
			    content : { 
				    'loan_number':loan_number,
				},	
				handleAs:"json",
				load: function(data_loan) {
					temp='';	
					temp='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
					+'<thead><tr><th class="tdheader"><?php echo $tr->translate('NO');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('RECIEPT_NO');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PAID_TIME');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PAY_DATE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('DATE_INPUT');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PAID_PRINCIPAL');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('INTEREST');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('PENALIZE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('SERVICE_CHARGE');?></th>'
					+'<th class="tdheader"><?php echo $tr->translate('RECEIVE_AMOUNT');?></th>'
					+'</thead>';
					nums=0;
					if(data_loan!=""){
						 amount_completed=data_loan.length;
						for(k=0;k<data_loan.length;k++){
							statuss='<label style="color:red;"><?php echo $tr->translate('NOT_COMPLETED');?></label>';
							++nums;
							var is_apprs="";
							total_pay = parseFloat(data_loan[k].total_principal_permonth)+parseFloat(data_loan[k].total_interest)+parseFloat(data_loan[k].service_charge)+parseFloat(data_loan[k].penalize_amount);
							currs =getCurrencyType(data_loan[k].currency_type);
							temp+= '<tr>';
								temp += '<td>&nbsp;'+nums+'</td>';
								temp += '<td>&nbsp;'+data_loan[k].receipt_no+'&nbsp;</td>';
								temp += '<td>&nbsp;'+data_loan[k].paid_times+'&nbsp;</td>';
								temp += '<td style="white-space: nowrap;">&nbsp;'+data_loan[k].date_payment+'&nbsp;</td>';
								temp += '<td style="white-space: nowrap;">&nbsp;'+data_loan[k].date_input+'&nbsp;</td>';
								temp += '<td>&nbsp;'+dojo.number.format(data_loan[k].principal_paid)+' '+currs+'&nbsp;</td>';
								temp += '<td>&nbsp;'+dojo.number.format(data_loan[k].interest_paid)+' '+currs+'&nbsp;</td>';
								temp += '<td>&nbsp;'+dojo.number.format(data_loan[k].penalize_paid)+' '+currs+'&nbsp;</td>';
								temp += '<td>&nbsp;'+dojo.number.format(data_loan[k].service_paid)+' '+currs+'&nbsp;</td>';
								temp += '<td>&nbsp;'+dojo.number.format(data_loan[k].total_paymentpaid)+' '+currs+'&nbsp;</td>';
								if(data_loan[k].is_completed==1){
									statuss = '<label style="color:blue;"><?php echo $tr->translate('COMPLETED');?></label>';
									if(data_loan[k].is_approved==1){is_apprs='<label style="color:blue;">Approved</label>';}
								}else{
									is_apprs='';
								}
							temp+= '</tr>';
						}
					}
					temp+='</table>';
					dojo.byId('data_table_loan_haspay').innerHTML = temp;
				},
				error: function(e) {
				}
			});
	}catch(err){
	}
}
function shortFormatdate(date){
	return (date.getMonth() + 1) + 
    "/" +  date.getDate() +
    "/" +  date.getFullYear();
}
function getRPNumber(co_id){
	try{
		var url_submits = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'getrpnumber')); ?>';
			dojo.xhrPost({
			    url: url_submits,
			    content : { 
				    'co_id':co_id,
				},	
				handleAs:"json",
				load: function(data_loan) {
					dijit.byId('reciept_no').attr('value',data_loan);
				},
				error: function(e) {
				}
			});
	}catch(err){
	}
}
function getDayString(num){
	var days= ["អាទិត្យ","ច័ន្ទ", "អង្គារ", "ពុធ", "ព្រហ","សុក្រ","សៅរ៏"];
	return days[num];
}
function getCurrencyType(type){
	var option=["៛","$","B"];
	return option[type-1];
}
function totalReturn(){
	receive_amount = dijit.byId('amount_receive').get('value');
	total_payments = dijit.byId('total_payment').get('value');
	
	option_pay = dijit.byId('option_pay').get('value');
	if(option_pay==3){
		dijit.byId('os_amount').attr('value',receive_amount);
	}
	
	amonut_return = parseFloat(receive_amount)-parseFloat(total_payments);
	remain_amount = parseFloat(total_payments)-parseFloat(receive_amount);
	if(amonut_return<0){
	}else{
	}
	if(remain_amount>0){
		dijit.byId('remain').attr('value',remain_amount.toFixed(2));
	}else{
		dijit.byId('remain').attr('value',0);
	}
}
function loading(){
    loadingBlock()
}
function roundhundred(n){
	cu_type = dijit.byId('currency_type').get('value');
	if(cu_type==1){
		var x= n%100 > 0 ? (n-(n%100)+100) : n;
	}else{
		total = parseFloat(n);
		x = total.toFixed(2);
	}
    
    return x;
  }
  function calTotal(){//គណនាប្រាក់ត្រូវបង់សរុប
	service_charge = dijit.byId('service_charge').get('value');
	service_charge=isNaN(service_charge)?0:service_charge;
	penelize = dijit.byId('penalize_amount').get('value');
	penelize=isNaN(penelize)?0:penelize;
	interest = dijit.byId('total_interest').get('value');
	interest=isNaN(interest)?0:interest;
	old_total_pay = dijit.byId('os_amount').get('value');	
	total_pay = parseFloat(old_total_pay)+parseFloat(service_charge)+parseFloat(penelize)+parseFloat(interest);	
	dijit.byId('total_payment').attr('value',total_pay.toFixed(2));
	dijit.byId('amount_receive').attr('value',total_pay.toFixed(2));
	totalReturn();
}
  var url_addsaleprint = '<?php echo $this->url(array('module'=>'loan','controller'=>'payment','action'=>'addpaymentajax')); ?>';
  function addPaymentByAjax(){
	  if(dijit.byId('frm_add_group_pay').validate()){
		branch_id = dijit.byId('branch_id').get('value');
    	if (branch_id=='' || branch_id==-1){
    		infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> !');
	   			dijit.byId('branch_id').focus();
	   			return false;
   		}
		service_charge = dijit.byId('service_charge').get('value');
		receive_amount = dijit.byId('amount_receive').get('value');
		option_pay = dijit.byId('option_pay').get('value');
		
			co_id = dijit.byId('co_id').get('value');
			client = dijit.byId('client_id').get('value');
			if (client=='' || client==-1){
				infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?> !');
				dijit.byId('client_id').focus();
				return false;
			}if(co_id=='' || co_id==-1){
				infoMessageAlert('<?php echo $tr->translate("Please Select CO Name");?> !');
				dijit.byId('co_id').focus();
				return false;
			}
			if(receive_amount<0){
				infoMessageAlert('<?php echo $tr->translate("Please fill Recieve Amount");?> !');
				dijit.byId('amount_receive').focus();
				return false;
			}
			total_payments = dijit.byId('total_payment').get('value');
		    /*
			dijit.byId("save_close").set("disabled",true);
			dijit.byId("save_new").set("disabled",true);
			dijit.byId("saveprint").set("disabled",true);
		    */

			loadingBlock();
			
			dojo.xhrPost({
				url: url_addsaleprint,
				form: dojo.byId("frm_add_group_pay"),
				handleAs:"json",
				load: function(data) {
					showReciept(data);
				},
				error: function(err) {
					infoMessageAlert(err);
					HideloadingBlock();
				}
			});
		}
  }
  function printReciept(){
		dojo.byId("innerrpt_print1").innerHTML = dojo.byId('rpt_print').innerHTML;
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML<?php if($showreceipt>1){ ?> + dojo.byId('rpt_print1').innerHTML<?php }?>;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    loading();
	    window.location.href = "<?php echo $this->baseUrl()."/loan/payment"?>";
	}
</script>
