<?php
	
	
	$frm = $this->frm_ilpayment;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("EDIT_PAYMENT_RECEIPT")); 
	echo $this->headTitle();
	$key = new Application_Model_DbTable_DbKeycode();
	$data=$key->getKeyCodeMiniInv(TRUE);
	$baseurl=Zend_Controller_Front::getInstance()->getBaseUrl();
	$loanPayment=$this->loanPayment;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");	
</script>

<div style="min-height:35cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	 <form dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded" >
		 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
						
				dijit.byId('btn_save_close').set('disabled',true);
				return true;
			}else {
				return false;
			}
		</script>
	<div id="divPrint">
			<div id="divPrint1" style="width: 100%; height: 14.8cm ; padding: 0px; margin: 0px;">
				
			<style type="text/css">
				
				td.bgBorderColor {
				    height: 5px;
				    border-top: solid 1px #133b84;
				}
				span.lbtitle {
				    min-width: 100px;
				    display: inline-block;
				}
				span.value{ line-height:12px; min-width:80px; display: inline-block; text-align: center; padding: 0 2px;}
				span.border_bt.value {
				    border-bottom: dashed 1px #000; padding: 0 10px;
				}
				span.borderCo.value {
				    border: 1px solid #133b84;
				    min-height: 40px;
				    width: 100%;
				}
				td.lbtitlev {
				    padding-left: 14px;
				}
				span.borderCo.value label {
				    line-height: 40px;
					margin-bottom: 0;
				}
				table tr td{
					color: #133b84 !important;
					padding: 1px;
				}
		         table table tr td ul li{text-align: center;list-style: none;line-height: 20px; }
			</style>
			    		<table cellspacing="0" style=" color: #133b84 !important; width:25cm; max-height:14.85cm; white-space:nowrap; font-family:'Times New Roman','Khmer OS Battambang'; font-size: 10px; ">
							 <tbody><tr valign="top">
								<td align="center" colspan="6" valign="top" height="80">
									<table cellpadding="0" cellspacing="0" style="font-family: :'Times New Roman','Khmer OS Battambang';padding:0; width:100%;white-space:nowrap;">
								   		<tbody><tr style="line-height:10px;">
								   			<td width="28%" id="projectlogo"><img src="<?php echo $baseurl.'/images/logo.jpg';?>" style="padding-left: 8px; "></td>
								   			<td valign="top">
									   			<ul style="padding-top: 5px; ">
						                			<li style=" line-height: 25px; text-align:center; font-size:18px !important; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $data['client_company_name'];?></li>
						                			<li style=" line-height: 25px; text-align:center; font-size:17px !important; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("PAYMENT_RECEIPT");?></li>
						                			<li style=" line-height: 25px; text-align:center; font-size:17px !important;font-family:'Times New Roman'; font-weight: bold;">PAYMENT RECEIPT</li>
						                		</ul>
							                </td>
							                <td width="28%" valign="bottom">
							                	<ul style="padding-top: 5px;">
													<li style="text-align:left; font-size:14px !important; font-family:'Times New Roman','Khmer OS Muol Light'"><span class="lbtitle">កាលបរិច្ឆេទ</span> : <span class=" value"><strong class="fonttel" style="font-size:12px;"><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="date_input" name="date_input" value="<?php echo $loanPayment['date_pay'];?>" type="text"></strong></span></li>
						                			<li style="text-align:left; font-size:14px !important; font-family:'Times New Roman','Khmer OS Muol Light'"><span class="lbtitle">បង្កាន់ដៃលេខ</span> : <span class=" value"><label style="color:#f90909" id="lbl_reciept_no"><input  dojoType="dijit.form.TextBox"  class="fullside" id="receipt_no" name="receipt_no" value="<?php  echo $loanPayment['receipt_no'];?>" type="text"></label></span></li>
						                		</ul>
							                </td>
										</tr>
										<tr>
			                				<td colspan="3">
					                    	</td>
					                   </tr>  
									</tbody></table>
								</td>
			    			</tr>
			    			<tr>
				    			<td align="center" colspan="6" valign="top" height="80">
				    				<table cellpadding="2" style=" line-height: 30px;  font-family: 'Times New Roman','Khmer OS Battambang' ;font-size:16px !important;white-space:nowrap; width:24cm; margin: 0 auto;">
										<tbody><tr class="fontsize">
											<td class="lbtitlev" valign="top" width="17%">សាខា </td>
											<td><span class="borderCo value"><label id="lbl_branch_id"><?php echo $loanPayment['branch_name'];?></label></span></td>
											<td class="lbtitlev">ប្រាក់ដើមមុនបង់ </td>
											<td>
												<span class="borderCo value">
													<input dojoType="dijit.form.TextBox" class="fullside" id="receipt_id" name="receipt_id" value="<?php echo $loanPayment['id'];?>" type="hidden">
													<label style="color:red" id="lbl_priciple_amount"><?php echo number_format($loanPayment['begining_balance'],2);?></label>
												</span>
											</td>
											<td class="lbtitlev">ប្រាក់ដើមបានបង់</td>
											<td>
												<span class="borderCo value">
													<label style="color:red" id="lbl_os_amount"><?php echo number_format($loanPayment['principal_paid'],2);?></label>
												</span>
											</td>
					                   </tr>
					                   <tr>
											<td class="lbtitlev">លេខឥណទាន</td>
											<td>
												<span class="borderCo value">
													<strong class="fonttel"><label id="lbl_loan_number"><?php echo  $loanPayment['loan_number'];?></label></strong>
												</span>
											</td>
											<td class="lbtitlev">ចំនួនប្រាក់ត្រូវបង់សរុប</td>
											<td>
												<span class="borderCo value">
													<label style="color:red" id="lbl_total_payment"><?php echo  number_format($loanPayment['total_paymentpaid'],2);?></label>
												</span>
											</td>
											<td class="lbtitlev">ការប្រាក់បានបង់</td>
											<td>
												<span class="borderCo value">
													<label style="color:red" id="lbl_interest_paid"><?php echo number_format($loanPayment['interest_paid'],2);?></label>
												</span>
											</td>
									  </tr>
									  <tr>
											<td class="lbtitlev">ឈ្មោះអតិថិជន</td>
											<td>
												<span class="borderCo value">
													<label id="lbl_group_member"><?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['client_name'])));?></label>
												</span>
											</td>
											<td class="lbtitlev">បង់លើកទី</td>
											<td>
												<span class="borderCo value">
													<label id="lbl_paidTime"><?php echo  $loanPayment['paid_times'];?></label>
												</span>
											</td>
											
											<td class="lbtitlev">ប្រាក់ពិន័យបានបង់</td>
											<td>
												<span class="borderCo value">
													<label style="color:red" id="lbl_penalty_amount"><?php echo number_format($loanPayment['penalize_paid'],2);?></label>
												</span>
											</td>
									</tr>
									<tr class="fontsize">
											<td class="lbtitlev">ឈ្មោះមន្រ្តីឥណទាន</td>
											<td>
												<span class="borderCo value">
													<label id="lbl_co_id"><?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['co_name'])));?></label>
												</span>
											</td>
											<td class="lbtitlev">ថ្ងៃបានបង់ប្រាក់</td>
											<td>
												<span class="borderCo value">
													<label style="color:red" id="lbl_collect_date"><?php echo date("d/M/Y",strtotime($loanPayment['date_payment']));?></label>
												</span>
											</td>
											<td class="lbtitlev" style="min-width: 100px;">ប្រាក់បានបង់សរុប </td>
											<td>
												<span class="borderCo value" style="min-width: 100px;font-weight: bold;">
													<label style="color:red" id="lbl_totalpaid"><?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['currency_typeshow'].' '.number_format($loanPayment['total_paymentpaid'],2))));?></label>
												</span>
											</td>
																
									</tr>
									<tr>
											<td class="lbtitlev">សម្គាល់</td>
											<td colspan="5">
												<span class="borderCo value" style="  min-height: 85px;">
													<input style="  min-height: 85px; width:100%;" dojoType="dijit.form.Textarea"  class="fullside" id="note" name="note" value="<?php echo $loanPayment['note'];?>" type="text"/>
													
													<label id="lbl_note">
													
													</label>
												</span>
											</td>
									</tr>
									<tr style="white-space: nowrap;" height="35px;">
										<td colspan="6" align="center">
											<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" id="btn_save_close" label="<?php echo $tr->translate('GO_EDIT');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
										</td>
									</tr>
									
									
				    			
			    			
			    		</tbody></table>
			    	</td>
			    </tr>
			</tbody>
			</table>
		</div>
	</div>
</div>
</script>