<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH')); 
 $frm = $this->frm_branch;?>
<script>
       dojo.require("dijit.form.Textarea");
       dojo.require("dijit.form.DateTextBox");
</script>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-university" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('ADD_BRANCH');?></h5>
		<ul class="nav nav-tabs card-header-tabs" role="tablist">
          <li class="nav-item">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#tabs-branch-info" role="tab" aria-selected="true"><i class="ti-xs ti ti-building-bank me-1"></i> <?php echo $tr->translate('BRANCH_INFO');?></button>
          </li>
          <li class="nav-item">
            <button class="nav-link " data-bs-toggle="tab" data-bs-target="#tabs-mg-info" role="tab" aria-selected="false"><i class="ti-xs ti ti-users me-1"></i> <?php echo $tr->translate('MANAGER_INFO');?></button>
          </li>
        </ul>
	</div>
	<div class="card-body">
		
		<form id="frm_branch" action="<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
               		loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="tab-content tab-form">
				<div class="tab-pane fade active show" id="tabs-branch-info" role="tabpanel">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_NAME");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_CODE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">	
											<?php echo $frm->getElement("branch_code");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_namekh");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SHOPNAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_nameen");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("description");?>
									   </div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_ADDRESS");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PREFIX_CODE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("prefix_code");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_tel");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_ADDRESS");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("br_address");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NOTE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_note");?>
									   </div>
									</div>
								</div>
							</div>
						 </div>
						 <div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_IMAGE");?></h5>
								</div>
								<div class="card-body">
									<div class="d-flex align-items-start align-items-sm-center gap-4">
									  <img src="<?php echo $this->baseUrl().'/images/no-image.png';?>" alt="user-avatar" class="d-block w-px-100 h-px-100 rounded" id="uploadedAvatar" />
									  <div class="button-wrapper">
										<label for="photo" class="btn btn-primary me-2 mb-3" tabindex="0">
										  <span class="d-none d-sm-block"><?php echo $tr->translate("Upload new photo");?></span>
										  <i class="ti ti-upload d-block d-sm-none"></i>
										  <input type="file" id="photo" name="photo" class="account-file-input" hidden accept="image/png, image/jpeg" />
										</label>
										<button type="button" class="btn btn-label-secondary account-image-reset mb-3">
										  <i class="ti ti-refresh-dot d-block d-sm-none"></i>
										  <span class="d-none d-sm-block"><?php echo $tr->translate("RESET");?></span>
										</button>

										<div class="text-muted">Allowed JPG, GIF or PNG. Max size of 800K</div>
									  </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="tabs-mg-info" role="tabpanel">
					<div class="row">
						 <div class="col-md-6 col-sm-6 col-xs-12">
							<div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_MANAGER");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_name");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_sex");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_dob");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_nationality");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATION_ID");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_nation_id");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ISSUE_DATE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_issue_date");?>
									   </div>
									</div>
									 <div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("JOB_TYPE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_occupation");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENT_ADDRESS");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("gm_address");?>
									   </div>
									</div>
								</div>
							</div>
						 </div>
						 <div class="col-md-6 col-sm-6 col-xs-12">
							 <div class="card card-form mb-4">
								<div class="card-header d-flex justify-content-between">
									<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("WITH_BRANCH_MANAGER");?></h5>
								</div>
								<div class="card-body">
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_name");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_sex");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_dob");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_nationality");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATION_ID");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_nation_id");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ISSUE_DATE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_issue_date");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("JOB_TYPE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_occupation");?>
									   </div>
									</div>
									<div class="row g-3">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("with_gm_is");?>
									   </div>
									</div>
								</div>
							</div>
						 </div>
					 </div>
				</div>
			 </div>
			
			
			<!-- Button Save  -->
	        <div class="clearfix"></div>
		  	<div class="card-box">
            	<div class="col-sm-12 border-top mt-2 py-2 text-center">
		    		<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVECLOSE");?>" name='save_close' id='save_close' value='saveclose' dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVENEW");?>" name='save_new' id='save_new' value='saveclose' dojoType="dijit.form.Button" />
					
    			</div>
    		</div>
	    	<!--/. Button Save  -->
			
		</form>
	</div>
</div>
		
<script>

$( document ).ready(function() {
   let e = document.getElementById("uploadedAvatar");
        const l = document.querySelector(".account-file-input")
          , c = document.querySelector(".account-image-reset");
        if (e) {
            const r = e.src;
            l.onchange = ()=>{
                l.files[0] && (e.src = window.URL.createObjectURL(l.files[0]))
            }
            ,
            c.onclick = ()=>{
                l.value = "",
                e.src = r
            }
        }
});

</script>