<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("INSTALLMENT_MNG"));
	$frm = $this->frm_search;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	
	$url_payment = $this->baseUrl()."/installment/payment/add/id/";
	$url_reschedule = $this->baseUrl()."/installment/reschedule/add/id/";
	$url_schedule = $this->baseUrl()."/report/installments/saleschedule/id/";
	$url_agreement = $this->baseUrl()."/report/installments/agreement/id/";
	$url_receipt = $this->baseUrl()."/report/installments/saleinvoice/id/";
	$urlPaymenthistory = $this->baseUrl()."/report/installments/paymenthistory/id/";
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-motorcycle"></i>&nbsp;<?php echo $tr->translate('PAWNSHOP');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('shop_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("member");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("repayment_method");?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="category_id" />
			   		</div>
				</div>
				<div class="row g-3">
					
			   		<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("completed_status");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="selling_type" id="selling_type" >
		 					<option value="-1"><?php echo $tr->translate('ជ្រើសរើសប្រភេទលក់');?></option>
		 					<option value="1"><?php echo $tr->translate('ទិញដាច់');?></option>
		 					<option value="2"><?php echo $tr->translate('បង់រំលស់');?></option>
		 				</select>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 

	function getmemberIdGroup(){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}
	function checkMember(){
		
	}	
	function filterClient(){
		branch_id= dijit.byId('branch_id').get('value');
		if(branch_id>0){
			getAllClientByBranch(branch_id);
		}
	}
	var cate_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_cate));?> );
	dojo.ready(function(){		
		
		 new dijit.form.FilteringSelect({
				store: cate_store,
				required: false,		           
				name: "category_id",
				id: "category_id",
				searchAttr: "name",
				autoComplete: false,
				queryExpr: "*${0}*",
				value:"<?php echo $this->rs['category_id'];?>",
				class: 'fullside',
				onChange: function() {
				}
		}, "category_id");

		 filterClient();
	});

	var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclieninstallment')); ?>';
	function getAllClientByBranch(branch_id){
		dojo.xhrPost({
			url:url_getclient,	
			content:{ 
			    'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {
				client_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('member').set('store', client_store);
			},
			error: function(err) {
			}
		});
	}
	

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var newPageTitle="";
				var actionType=1;
				var m = "clicked: " + key;
				 if(key=="payment"){
					url='<?php echo $url_payment;?>';
					actionType=2;
				}else if(key=="reschedule"){
					url='<?php echo $url_reschedule;?>';
					actionType=2;
				 }else if(key=="receipt"){
						url='<?php echo $url_receipt;?>';
						newPageTitle="<?php echo $tr->translate("PAYMENT_RECEIPT");?>";
				}else if(key=="schedule"){
					url='<?php echo $url_schedule;?>';
					newPageTitle="<?php echo $tr->translate("SCHEDULE_PAYMENT");?>";
				}else if(key=="agreement"){
					url='<?php echo $url_agreement;?>';
					newPageTitle="<?php echo $tr->translate("AGREEMENT");?>";
				}else if(key=="paymenthistory"){
					url='<?php echo $urlPaymenthistory;?>';
					newPageTitle="<?php echo $tr->translate("RPT_PAYMENT_HISTORY");?>";
				}
				if(actionType==1){
					addTab(newPageTitle,url+row+'?inFrame=true');
				}else{
					gotoAction();
				}
			},
			items: {
				"payment": {name: "<?php echo $tr->translate("ADD_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
				"schedule": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
				"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text"},
				"receipt": {name: "<?php echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-print"},
				"reschedule": {name: "<?php echo $tr->translate("REPAYMENTSCHEDULE");?>", icon: "fa-calendar"},
				"paymenthistory": {name: "<?php echo $tr->translate("RPT_PAYMENT_HISTORY");?>", icon: "fa-money"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}

	var recordid ='';
	function gotoAction(){
		 window.open(url+row, '_self');
	}
</script>