<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("INSTALLMENT_MNG"));
	$frm = $this->frm_search;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	
	$url_payment = $this->baseUrl()."/installment/payment/add/id/";
	$url_reschedule = $this->baseUrl()."/installment/reschedule/add/id/";
	$url_schedule = $this->baseUrl()."/report/installments/saleschedule/id/";
	$url_agreement = $this->baseUrl()."/report/installments/agreement/id/";
	$url_receipt = $this->baseUrl()."/report/installments/saleinvoice/id/";
	$urlPaymenthistory = $this->baseUrl()."/report/installments/paymenthistory/id/";
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-motorcycle " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('INSTALLMENT_MNG');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			    <div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("member");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("repayment_method");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="category_id" />
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("completed_status");?>
			   		</div>
			   </div>
			   <div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="selling_type" id="selling_type" >
		 					<option value="-1"><?php echo $tr->translate('ជ្រើសរើសប្រភេទលក់');?></option>
		 					<option value="1"><?php echo $tr->translate('ទិញដាច់');?></option>
		 					<option value="2"><?php echo $tr->translate('បង់រំលស់');?></option>
		 				</select>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   	</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
	
<script>
	function getmemberIdGroup(){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}
	function checkMember(){
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}	
	var cate_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_cate));?> );
	dojo.ready(function(){		
		 new dijit.form.FilteringSelect({
				store: cate_store,
				required: false,		           
				name: "category_id",
				id: "category_id",
				searchAttr: "name",
				autoComplete: false,
				queryExpr: "*${0}*",
				value:"<?php echo $this->rs['category_id'];?>",
				class: 'fullside',
				onChange: function() {
				}
		}, "category_id");
	});

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				 if(key=="payment"){
					url='<?php echo $url_payment;?>';
				 }else if(key=="receipt"){
						url='<?php echo $url_receipt;?>';
				}else if(key=="schedule"){
					url='<?php echo $url_schedule;?>';
				}else if(key=="agreement"){
					url='<?php echo $url_agreement;?>';
				}else if(key=="reschedule"){
					url='<?php echo $url_reschedule;?>';
				}else if(key=="paymenthistory"){
					url='<?php echo $urlPaymenthistory;?>';
				}
				gotoAction();
				//window.console && console.log(m) || alert(m); 
			},
			items: {
				"payment": {name: "<?php echo $tr->translate("ADD_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
				"schedule": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
				"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text"},
				"receipt": {name: "<?php echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-print"},
				"reschedule": {name: "<?php echo $tr->translate("REPAYMENTSCHEDULE");?>", icon: "fa-calendar"},
				"paymenthistory": {name: "<?php echo $tr->translate("RPT_PAYMENT_HISTORY");?>", icon: "fa-money"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}

	var recordid ='';
	function gotoAction(){
		 window.open(url+row, '_blank');
	}
</script>