<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_VILLAGE'));
?>	
<?php  $commune = $this->frm_village;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.Dialog");
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
 			<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_VILLAGE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE_CODE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('code');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");//$tr->translate("VILLAGE_KH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('village_namekh');?>
	                   		<?php  echo $commune->getElement('id'); //echo $commune->getElement('id')?>
	                   </div>
	                </div>
	                <!-- 
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  //echo $commune->getElement('village_name');?>
							
	                   </div>
	                </div>
	                 -->
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('province_name');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="district_name" ><?php  //echo $commune->getElement('district_name');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   	<input id="commune_name" > <?php  //echo $commune->getElement('commune_name');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php  echo $commune->getElement('status');?>
	                   </div>
	                </div>
	                <div class="form-group">
		                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		                	<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" id="" dojoType="dijit.form.Button"
				                  iconClass="dijitIconClear" />
							<input type="submit" value="កែប្រែទិន្នន័យ" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
			    		</div>
		    		 </div>
	            </div>
	         </div>
		</form>
	</div>
</div>

<script type="text/javascript">
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	 
	new dijit.form.FilteringSelect({
	store: district_store,//dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,      
	required: false,		           
	name: "district_name",
	id: "district_name",
	placeHolder:"<?php echo $tr->translate("DISTRICT")?>",
	searchAttr: "name",
	value: "<?php echo $this->row['dis_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			district = dijit.byId('district_name').get('value');
			if(district==-1){
				showPopupdistrict();
			}else{ filterCommune();
			}
	    }
	}, "district_name");

	new dijit.form.FilteringSelect({
	store: commune_store,//dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	required: false,		           
	name: "commune_name",
	id: "commune_name",
	placeHolder:"<?php echo $tr->translate("COMMUNE")?>",
	value: "<?php echo $this->row['commune_id'];?>",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			commune = dijit.byId('commune_name').get('value');
			if(commune==-1){
				showPopupCommune();
			}
  }
	}, "commune_name");
	filterDistrict();
	filterCommune();
	
});
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province_name').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district_name').set('store', district_store);
		    dijit.byId('district_name').attr('value','<?php echo $this->row['dis_id'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district_name').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune_name').set('store', commune_store);
		    dijit.byId('commune_name').attr('value','<?php echo $this->row['commune_id'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>

<?php 
echo $this->frm_popup_district;
echo $this->frm_popup_comm;
?>
<script>
function showPopupdistrict(){
	province_id = dijit.byId('province_name').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province_name').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name: dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district_name'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name: communekh,
				};			
				addDataToSelectbox(dijit.byId('commune_name'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function showPopupCommune(){
	district = dijit.byId('district_name').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district_name').focus();
	}
}
</script>