<?php 
	$client = $this->client;
	$loan = $this->loanInfo;
	$collateral = $this->collateral;
	$data = $this->data;
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$dbgb = new Application_Model_DbTable_DbGlobal();
?>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title><?php echo $tr->translate('AGREEMENT');?></title>

<div class="reportblog">
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
	    	<div class="col-sm-8 pd-0">
	   			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('AGREEMENT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<style>
		.noneprint{
			display: table-cell !important; 
		}
		.reff{ font-size: 20px !important; line-height:34px !important;}
		#divPrint tr td h2, #divPrint p,#divPrint pre,#divPrint span,#divPrint td span,#divPrint td{ font-size: 20px !important; line-height:34px !important;}
		#padding-left-p-2{
		 padding-left: 105px !important;	
		}
		.padding-buttom{
			margin-top: -5px !important;
		}
		#divPrint #printfooter{display: none !important;}
	</style>
	<div  id="exportword">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    		<div id="divPrint">
		    	 	<style>		
						td span {
						    line-height: 22px;
						}
					    #padding-left-p-2{
						 padding-left: 105px !important;	
						}
						.padding-buttom{
							margin-top: -5px !important;
						}
    	 				.reff{ font-size: 16px !important; line-height:34px !important;}
						tr td h2,p,pre,span{ font-size: 14px ; line-height:22px;}
						#padding-left{
						padding-left: 18px;
						}
						.padding-buttom{
							margin-top: -5px;
						}
						#padding-left-p-2{
						 margin-top:-1px; 
						 padding-left: 85px;	
						}
						#padding-left-p{
					    	padding-left: 105px;
						}
						th{padding: 5px;}
						span.value{ line-height:12px;display: inline-block; text-align: center; padding: 0 2px;}
						span.child {display:block; margin-left:25px; line-height: 20px;}
						div.pages-break{
							page-break-inside:auto; page-break-after:auto; 
						}
						body {
						    position: relative;
						}
						#printfooter {
						    position: absolute;
						    bottom: 0;
						    position: fixed;
						    display: block ;
						width: 100%;
						}
						ul.collateral-list {
						    width: 100%;
						    padding: 0;
						    margin: 0;
						    padding-left: 75px;
						}
						/*
						span.border_bt.value {
						    border-bottom: dashed 1px #000; padding: 0 10px;
						}
						* */
					    </style>
	    			<div class="pages-break">
	    				<table style="font-family:'Times New Roman','Khmer OS Battambang'; text-align: center; width: 100%; margin-left: 0px">
							<tbody>
								<tr style="text-align:center; line-height:24px; font-size:15px; font-family:'Times New Roman','Khmer OS Battambang';">
									 <td width="30%" align="left" valign="top"><span><img style="max-width:100%;" src="<?php echo $this->baseUrl()."/";?>images/logo.jpg" ></span>
									 </td>
									 <td width="40%" align="center" valign="top" style="padding-left: 25px;">
									 	<span style="line-height: 30px; font-family:'Khmer OS Muol Light';">
										 	ព្រះរាជាណាចក្រកម្ពុជា
										 	<br>
											  ជាតិ សាសនា ព្រះមហាក្សត្រ
										  </span>
										  <br>
										 <img src="<?php echo $this->baseUrl()."/";?>images/agreementsign.JPG" style="width: 80px;height: 17px;"><br>
										 <span style=" line-height:24px; font-size: 15px; font-family:'Khmer OS Muol Light'; text-decoration: underline;">កិច្ចសន្យាខ្ចីប្រាក់</span><br />
										
									 </td>
									 <td>
								 	</td>
								</tr>
								<tr>
						 			<td colspan="3">
						 				<span style=" text-align:left; display:inline-block; width:100%;  font-family:'Khmer OS Muol Light'; text-decoration: underline;">រវាងៈ</span>
						 				<span style="text-align: justify; display:inline-block; width:100%;">
						 					<span id="padding-left">&nbsp;</span>ឈ្មោះ <span class="value border_bt" style="font-family:'Times New Roman','Khmer OS Muol Light'; min-width: 100px;"><?php echo $loan['gm_name'];?></span> ភេទ <span class="value border_bt" style="min-width: 20px;"><?php echo $loan['gmSexTitle'];?></span> 
						 					កើតថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['gm_dob'])));?> ខែ<?php echo $month[date("m",strtotime($loan['gm_dob']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['gm_dob']))); ?> 
						 					សញ្ជាតិ <?php echo $loan['gm_nationality'];?> 
						 					កាន់អត្តសញ្ញាណប័ណ្ណលេខ <?php echo $dbgb->getNumberInkhmer($loan['gm_nation_id']);?> ចុះថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['gm_issue_date'])));?> ខែ<?php echo $month[date("m",strtotime($loan['gm_issue_date']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['gm_issue_date']))); ?> 
						 					<?php if (!empty($loan['with_gm_name'])){?>
						 					និងឈ្មោះ <span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $loan['with_gm_name'];?></span> 
						 					កើតថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['with_gm_dob'])));?> ខែ<?php echo $month[date("m",strtotime($loan['with_gm_dob']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['with_gm_dob']))); ?> 
						 					សញ្ជាតិ <?php echo $loan['with_gm_nationality'];?> 
						 					កាន់អត្តសញ្ញាណប័ណ្ណ លេខ<?php echo $dbgb->getNumberInkhmer($loan['with_gm_nation_id']);?> 
						 					ចុះថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['with_gm_issue_date'])));?> ខែ<?php echo $month[date("m",strtotime($loan['with_gm_issue_date']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['with_gm_issue_date']))); ?> 
						 					មុខរបរ <?php echo $loan['with_gm_occupation'];?> ត្រូវជា <?php echo $loan['with_gm_is'];?> 
						 					<?php }?>
						 					មានទីលំនៅ <?php echo $loan['gm_address'];?> ជាភាគីម្ចាស់បា្រក់ចាប់ពីពេលនេះតទៅហៅកាត់ថាភាគីអក្ស “ក” ។
						 				</span>
						 				<span style=" text-align:left; display:inline-block; width:100%;  font-family:'Khmer OS Muol Light'; text-decoration: underline;">និងៈ</span>
						 				<span style="text-align: justify; display:inline-block; width:100%;">
						 					<span id="padding-left">&nbsp;</span>ឈ្មោះ <span class="value border_bt" style="font-family:'Times New Roman','Khmer OS Muol Light'; min-width: 100px;"><?php echo $client['name_kh'];?></span> ភេទ <span class="value border_bt" style="min-width: 20px;"><?php echo $client['sexKH'];?></span> 
						 					កើតថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($client['dob'])));?> ខែ<?php echo $month[date("m",strtotime($client['dob']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($client['dob']))); ?> 
						 					សញ្ជាតិ <?php echo $client['nationality'];?> កាន់<?php echo $client['docTypKH'];?>លេខ<?php echo $dbgb->getNumberInkhmer($client['nation_id']);?> 
						 					ចុះថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($client['dob'])));?> ខែ<?php echo $month[date("m",strtotime($client['dob']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($client['dob']))); ?> 
						 					
						 					<?php if (!empty($client['join_with'])){?>
						 					និងឈ្មោះ<span class="value border_bt" style="font-family:'Times New Roman','Khmer OS Muol Light'; min-width: 80px;"><?php echo $client['join_with'];?></span>ភេទ <span class="value border_bt" style="min-width: 20px;"><?php echo $client['join_sexKH'];?></span> 
						 					កើតថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($client['dob'])));?> ខែ<?php echo $month[date("m",strtotime($client['dob']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($client['dob']))); ?> 
						 					សញ្ជាតិ <?php echo $client['with_nationality'];?> កាន់<?php echo $client['joinDocTypKH'];?>លេខ<?php echo $dbgb->getNumberInkhmer($client['join_nation_id']);?> 
						 					ចុះថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($client['dob_join_acc'])));?> ខែ<?php echo $month[date("m",strtotime($client['dob_join_acc']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($client['dob_join_acc']))); ?> 
						 					មុខរបរ <?php echo $client['with_job'];?> ត្រូវជា <?php echo $client['relate_with'];?>
						 					<?php }?>
						 					
						 					មានទីលំនៅភូមិ <?php echo $client['villageName'];?> 
						 					ឃុំ/សង្កាត់ <?php echo $client['communeName'];?> 
						 					ស្រុក/ខណ្ឌ/ក្រុង <?php echo $client['district_name'];?> 
						 					ខេត្ត/រាជធានី <?php echo $client['province_kh_name'];?>។ 
						 					<br />
						 					<span id="padding-left">&nbsp;</span>ជាភាគីអ្នកខ្ចីបា្រក់ចាប់ពីពេលនេះតទៅហៅកាត់ថាភាគីអក្ស “ខ” ភាគីទាំងពីរបានព្រមព្រៀងគ្នាតាមប្រការខាងក្រោម: 
						 				</span>
						 			</td>
						 		</tr>
						 		<tr>
						 			<td colspan="3">
						 				<span style=" text-align:center; display:inline-block; width:100%;  text-decoration: underline;">កម្មវត្ថុនៃកិច្ចសន្យា</span>
						 				<span style="text-align: justify; display:inline-block; width:100%;">
						 					<?php $durationType=""; $day=1; 
						 						if ($loan['pay_term']==1){ $durationType="ថ្ងៃ";
						 						}else if ($loan['pay_term']==1){ 
						 							$day=7; $durationType="សប្តាហ៏";
						 						}else if ($loan['pay_term']==3){ 
						 							$day=30; $durationType="ខែ";
						 						}?>
						 					<span style="text-decoration: underline; font-weight: 600;">ប្រការ១:</span> 
						 					ភាគី“ខ” បានខ្ចីបា្រក់ពីភាគី “ក” ចំនួន<span class="value border_bt" style="min-width: 120px;"><strong><?php echo number_format($loan['loan_amount'],2)." ".$loan['currency_type'];?></strong></span>(<span class="value border_bt" style="min-width: 110px;"><span id="lable_loankhmer"></span> <?php echo $loan['currency_type'];?></span>) 
						 					រយៈពេល <?php echo $dbgb->getNumberInkhmer($loan['total_duration']);?> (<?php echo $durationType;?>) 
						 					គិតចាប់ពីថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['first_payment'])));?> ខែ<?php echo $month[date("m",strtotime($loan['first_payment']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['first_payment']))); ?> 
						 					រហូតដល់ ថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['date_line'])));?> ខែ<?php echo $month[date("m",strtotime($loan['date_line']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['date_line']))); ?>  ។
						 					<script>
													a_sold ='<?php echo ($loan['loan_amount']) ?>';
													money_khmersold=read_money_in_khmer(a_sold);
													
													decimalmoney_khmersold='<?php echo substr(number_format($loan['loan_amount'],2),-2);?>';
													str_centsold = 'សេន';
													if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
													last_number_sold='<?php echo substr(number_format($loan['loan_amount'],2),-2);?>';
													
													if(last_number_sold<=0){last_number_sold='';}
													money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
													dojo.byId('lable_loankhmer').innerHTML=money_khmersold+" ";
													//dojo.byId('lable_pricekhmer1').innerHTML=money_khmersold+" ";
											</script>
						 				</span>
						 				<span style="text-align: justify; display:inline-block; width:100%;">
						 					<span style="text-decoration: underline; font-weight: 600;">ប្រការ២:</span> ភាគី “ខ” សន្យាថានិងផ្តល់ការបា្រក់ ចំនួន <?php echo $loan['interest_rate'];?>% (<span id="lable_interestkhmer"></span>ភាគរយ) ក្នុងមួយ<?php echo $durationType;?>ទៅ 
						 					អោយភាគី “ក”ដោយស្ម័គ្រចិត្តហើយសន្យាថានិងសងបា្រក់មកអោយភាគី “ក” 
						 					វិញគ្រប់ចំនួននៅថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['date_line'])));?> ខែ<?php echo $month[date("m",strtotime($loan['date_line']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['date_line']))); ?> ជាកំហិត ។ 
						 					<script>
													a_interest ='<?php echo ($loan['interest_rate']) ?>';
													money_khmerInterest=read_money_in_khmer(a_interest);
													
													decimalmoney_khmerInterest='<?php echo substr(number_format($loan['interest_rate'],2),-2);?>';
													str_centsold = '';
													if(decimalmoney_khmerInterest>0){string_sold='ចុច';}else{string_sold="";str_cent_sold='';}
													last_number_sold='<?php echo substr(number_format($loan['interest_rate'],2),-2);?>';
													
													if(last_number_sold<=0){last_number_sold='';}
													money_khmerInterest = money_khmerInterest+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmerInterest)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
													dojo.byId('lable_interestkhmer').innerHTML=money_khmerInterest+" ";
											</script>
						 				</span>
						 				<span style="text-align: justify; display:inline-block; width:100%;">
						 					<span id="padding-left">&nbsp;</span>
						 					ភាគី“ខ”អះអាងថាខ្លួនខ្ចីបា្រក់នេះពីភាគី“ក”ដោយខ្លួនបានតម្កល់: 
						 					<?php if (!empty($collateral)){?>
						 						<ul class="collateral-list">
									    		<?php foreach ($collateral as $key => $col){
									    			?>
									    			<li>
									    		<?php echo $col['calleteralTitle'];?> លេខ <?php echo $dbgb->getNumberInkhmer($col['number_collecteral']);?> ចុះថ្ងៃទី <?php if (!empty($col['issue_date'])){ echo $dbgb->getNumberInkhmer(date("d",strtotime($col['issue_date'])))." ខែ ".$month[date("m",strtotime($col['issue_date']))]." ឆ្នាំ ".$dbgb->getNumberInkhmer(date("Y",strtotime($col['issue_date'])));}?> ចេញដោយ  <?php echo $col['note'];?>។
									    			</li>
									    		<?php }?>
									    		</ul>
									    	<?php }?>
									    	<span id="padding-left">&nbsp;</span>ដើម្បីដាក់ធានាសំណងអោយភាគី“ក” ហើយក្នុងករណីដែលឯកសារខាងលើមានបញ្ហាក្នុងករណីណាមួយ ខ្ញុំបាទសុខចិត្តទទួលខុសត្រូវទាំងស្រុងចំពោះមុខច្បាប់  ។
						 					<br />
						 					<span id="padding-left">&nbsp;</span>
						 					ដើម្បីដាក់ធានាសំណងអោយភាគី “ក” ក្នុងករណីដែលខ្លួនគ្មានបា្រក់គ្រប់ចំនួនសងទៅអោយភាគី “ក” នោះទេនោះខ្លួនសុខចិត្តប្រគល់នូវទ្រព្យធានា ខាងលើដែលមានតម្កល់ជូន ដល់ភាគី “ក” ទៅជាម្ចាស់សិទ្ធិករដោយ ពុំទាមទារអ្វីទាំងអស់ ។ 
						 				</span>
						 				<span style="text-align: justify; display:inline-block; width:100%;">
						 					<span style="text-decoration: underline; font-weight: 600;">ប្រការ៣:</span> លក្ខខណ្ឌនៃកិច្ចសន្យា 
						 					<br />
						 					<span id="padding-left">&nbsp;</span>
						 					ភាគី “ក” និងភាគី “ខ” សន្យាគោរពយ៉ាងម៉ឺងម៉ាត់តាមរាល់កិច្ចសន្យាខាងលើក្នុងករណីមានការអនុវត្តផ្ទុយឬដោយរំលោភ លើលក្ខខ័ណ្ឌណាមួយនៃកិច្ចសន្យានេះភាគីដែលល្មើសត្រូវទទួលខុសត្រូវចំពោះមុខច្បាប់ជាធរមាន រាល់សោហ៊ុយចំណាយទាក់ទងក្នុងការដោះស្រាយលើវិវាទជាបន្ទុករបស់ភាគីដែលរំលោភបំពានលើកិច្ចសន្យា ។
					 						<br />
					 						<span id="padding-left">&nbsp;</span>
					 						កិច្ចសន្យានេះត្រូវបានធ្វើឡើងដោយមានការព្រមព្រៀងពិតប្រាកដដោយសេរីគ្មានការបង្ខិតបង្ខំពីភាគីណាមួយឡើយហើយមានប្រសិទ្ធភាពចាប់ពីថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['date_release'])));?> ខែ<?php echo $month[date("m",strtotime($loan['date_release']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['date_release']))); ?>។
						 					<br />
						 						<span id="padding-left">&nbsp;</span>
						 						កិច្ចសន្យានេះត្រូវបានធ្វើឡើងជា ២ច្បាប់ ១ច្បាប់ដើម សំរាប់ភាគី“ក” និង១ច្បាប់ថតចម្លង    សំរាប់ ភាគី“ខ”  ។
					 					</span>
						 			</td>
						 		</tr>	
						 		<tr>
						 			<td colspan="3" style=" text-align: right; font-size: 14px">
						 				ធ្វើនៅរាជធានីភ្នំពេញចុះថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d",strtotime($loan['date_release'])));?> ខែ<?php echo $month[date("m",strtotime($loan['date_release']))];?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y",strtotime($loan['date_release']))); ?>
						 			</td>
						 		</tr>
						 		<tr>
						 			<td colspan="3">
						 				<table border="0" style="width: 100%;">
						 					<tr style="font-family:'Times New Roman','Khmer OS Muol Light'; text-align: center;">
						 						<td width="30%">ស្នាមមេដៃស្តាំភាគី ម្ចាស់ប្រាក់</td>
							 					<td></td>
							 					<td width="30%">ស្នាមមេដៃស្តាំភាគីអ្នកខ្ចីប្រាក់</td>
						 					</tr>
						 					<tr>
						 						<td style="height: 60px;">&nbsp;</td>
						 					</tr>
						 					<tr style="font-family:'Times New Roman','Khmer OS Muol Light'; text-align: center;">
						 						<td>ឈ្មោះ <?php echo $loan['gm_name'];?></td>
						 						<td></td>
						 						<td><?php echo $client['name_kh']; echo empty($client['join_with'])?"":" និង ".$client['join_with']?></td>
						 					</tr>
						 					<tr style="font-family:'Times New Roman','Khmer OS Muol Light'; text-align: center;">
						 						<td colspan="3">
						 						<br /><br />
						 						ស្នាមមេដៃស្តាំភាគី សាក្សី</td>
						 					</tr>
						 					<tr>
						 						<td style="height: 60px;">&nbsp;</td>
						 					</tr>
						 					<tr style="font-family:'Times New Roman','Khmer OS Muol Light'; text-align: center;">
						 						<td colspan="3" >
						 						ឈ្មោះ  
						 						<?php if (!empty($client['spouse_name'])){
						 							echo $client['spouse_name'];
						 							?>
						 						<?php }else{?>
						 						<span style="display: inline-block; width: 100px;">&nbsp;</span>
						 						<?php }?>
						 						</td>
						 					</tr>
						 				</table>
						 			</td>
						 		</tr>				
							  </tbody>
						  </table>
			        </div>
			         <div id="printfooter">
			        	</div>
		        </div>
        	 </td>	
		</tr>
	</table>
	</div>
</div>

