<?php 
	$client = $this->client;
	$loan = $this->loanInfo;
	$collateral = $this->collateral;
	$data = $this->data;
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$dbgb = new Application_Model_DbTable_DbGlobal();
?>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title>Agreement</title>
<style>
#divPrint #printfooter{display: none !important;}
</style>
	<div  id="exportword" style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    		<div id="divPrint">
		    	 	<style>		
						td span {
						    line-height: 12px;
						}
					    #padding-left-p-2{
						 padding-left: 105px !important;	
						}
						.padding-buttom{
							margin-top: -5px !important;
						}
    	 				.reff{ font-size: 16px !important; line-height:34px !important;}
						tr td h2,p,pre,span{ font-size: 14px ; line-height:22px;}
						#padding-left{
						padding-left: 18px;
						}
						.padding-buttom{
							margin-top: -5px;
						}
						#padding-left-p-2{
						 margin-top:-1px; 
						 padding-left: 85px;	
						}
						#padding-left-p{
					    	padding-left: 105px;
						}
						th{padding: 5px;}
						span.value{ line-height:12px;display: inline-block; text-align: center; padding: 0 2px;}
						span.child {display:block; margin-left:25px; line-height: 20px;}
						div.pages-break{
							page-break-inside:auto; page-break-after:auto; 
						}
						body {
						    position: relative;
						}
						#printfooter {
						    position: absolute;
						    bottom: 0;
						    position: fixed;
						    display: block ;
						width: 100%;
						}
						span.border_bt.value {
						    border-bottom: dashed 1px #000; padding: 0 10px;
						}
					    </style>
	    			<div class="pages-break">
	    				<table style="font-family:'Times New Roman','Khmer OS Battambang'; text-align: center; width: 100%; margin-left: 0px">
							<tbody>
								<tr style="text-align:center; line-height:24px; font-size:15px; font-family:'Times New Roman','Khmer OS Battambang';">
									 <td width="30%" align="left" valign="top"><span><img style="max-width:100%;" src="<?php echo $this->baseUrl()."/";?>images/logo.jpg" ></span>
									 </td>
									 <td width="40%" align="center" valign="top" style="padding-left: 25px;"><span style="line-height: 30px; font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា<br>
									  ជាតិ សាសនា ព្រះមហាក្សត្រ</span><br>
									 <img src="<?php echo $this->baseUrl()."/";?>images/agreementsign.JPG" style="width: 80px;height: 17px;"><br>
									 <span style=" line-height:24px; font-size: 15px; font-family:'Khmer OS Muol Light';">កិច្ចសន្យាខ្ចីបរិភោគ</span>
									 </td>
								    <td width="30%" align="center" valign="top" style="font-size: 12px;">
									  <!-- 
									  	អតិថិជនអាចផ្ញើប្រាក់តាមៈ<br><img src="<?php //echo $this->baseUrl()."/";?>images/agreement/master cart.jpg" style="width: 70%;"><br>
									  	<strong><?php //echo $data['tel-client'];?></strong>
									   -->
								 	</td>
								</tr>
								<tr style="text-align: left; line-height: 10px;">
									<td align="center" colspan="3">
										<table style="white-space: nowrap;" cellspacing="0">
											<tr>
												<td><span>លេខ</span></td>
												<th >&nbsp;<span style=" display: inline-block; min-width: 100px; border-bottom: dashed 1px #151515; line-height: 10px; text-align: center;"><?php echo $loan['loan_number'];?></span>&nbsp;</th>
												<!-- style=" border:solid 1px #000; width:100px; color:red; font-weight: 600;" -->
											</tr>
										</table>
									</td>
						 		</tr>
						 		<tr>
						 			<td colspan="3">
						 				<p style="text-align:center; text-decoration: underline; font-size:16px; padding-left:25px;"><strong>កិច្ចសន្យានេះធ្វើឡើងរវាង</strong></p>
						 				<p style="text-align: justify;">
						 					<span id="padding-left"><strong><?php echo $loan['shop_name'];//$data['client_company_name'];?></strong></span> ជាក្រុមហ៊ុនឯកជនតំណាងស្របច្បាប់ដោយលោក <strong>ផូ ប៉ុក</strong> តួនាទី <strong>ប្រធានគ្រប់គ្រងទូទៅ</strong> ដែលមានអាសយដ្ឋាន <?php echo $loan['br_address'];//$data['branch-add-client'];?> (ដែលហៅថា <strong>អ្នកឲ្យខ្ចី</strong>)។
						 					<span style="text-align:center; display:block; width:100%; font-weight: 600;">និង</span>
						 					ឈ្មោះ <span class="value border_bt" style="min-width: 100px;"><?php echo ($client['displayby']==1)? $client['name_kh']: $client['name_en'] ;?></span>ភេទ <span class="value border_bt" style="min-width: 20px;"><?php echo ($client['displayby']==1)? $client['sexKH']: $client['sexEN'] ;?></span> ថៃ្ងខែឆ្នាំកំណើត<span class="value border_bt" style="min-width: 50px;"><?php if(!empty($client['dob'])){ echo $dbgb->getNumberInkhmer(date("d",strtotime($client['dob'])))." ".$month[date("m",strtotime($client['dob']))]." ".$dbgb->getNumberInkhmer(date("Y",strtotime($client['dob'])));}?></span> <!-- សញ្ជាតិ<span class="value border_bt" style="min-width: 30px;">ខ្មែរ<?php //echo $sale['catName'];?></span> -->
											ឯកសារសម្គាល់អត្តសញ្ញាណ<span class="value border_bt" style="min-width: 20px;"><?php echo ($client['displayby']==1)? $client['docTypKH']: $client['docTypEN'] ;?></span>លេខ<span class="value border_bt" style="min-width: 20px;"><?php echo $dbgb->getNumberInkhmer($client['nation_id']);?></span> <!-- ចុះថ្ងៃទី<span class="value border_bt" style="min-width: 50px;"><?php //echo $sale['catName'];?></span>ចេញដោយ<span class="value border_bt" style="min-width: 90px;"><?php //echo $sale['catName'];?></span> -->
											និងឈ្មោះ<span class="value border_bt" style="min-width: 80px;"><?php echo $client['join_with'];?></span>ភេទ <span class="value border_bt" style="min-width: 20px;"><?php echo ($client['displayby']==1)? $client['join_sexKH']: $client['join_sexEN'] ;?></span>
											<!-- សញ្ជាតិ<span class="value border_bt" style="min-width: 30px;"><?php //echo $sale['catName'];?></span> -->ថ្ងៃខែឆ្នាំកំណើត<span class="value border_bt" style="min-width: 50px;"><?php if(!empty($client['dob_join_acc'])){ echo $dbgb->getNumberInkhmer(date("d",strtotime($client['dob_join_acc'])))." ".$month[date("m",strtotime($client['dob_join_acc']))]." ".$dbgb->getNumberInkhmer(date("Y",strtotime($client['dob_join_acc'])));}?></span>
											ឯកសារសម្គាល់អត្តសញ្ញាណ<span class="value border_bt" style="min-width: 20px;"><?php echo ($client['displayby']==1)? $client['joinDocTypKH']: $client['joinDocTypEN'] ;?></span>លេខ<span class="value border_bt" style="min-width: 20px;"><?php echo $dbgb->getNumberInkhmer($client['join_nation_id']);?></span>
											<!-- ចុះថ្ងៃទី<span class="value border_bt" style="min-width: 50px;"><?php //echo $sale['catName'];?></span>ចេញដោយ<span class="value border_bt" style="min-width: 90px;"><?php //echo $sale['catName'];?></span>
											 -->ត្រូវជា<span class="value border_bt" style="min-width: 70px;"><?php echo $client['relate_with'];?></span>នៃអ្នកខ្ចី ដែលមានអាសយដ្ឋានផ្ទះលេខ<span class="value border_bt" style="min-width: 30px;"><?php echo $client['house'];?></span>ផ្លូវលេខ<span class="value border_bt" style="min-width: 30px;"><?php echo $client['street'];?></span>ក្រុមទី<span class="value border_bt" style="min-width: 20px;"><?php echo $client['group_no'];?></span>ភូមិ<span class="value border_bt" style="min-width: 40px;"><?php echo str_replace("ភូមិ", "", $client['village_name']);?></span>ឃុំ/សង្កាត់<span class="value border_bt" style="min-width: 40px;"><?php echo $client['communeName'];?></span>ស្រុក/ខណ្ឌ/ក្រុង<span class="value border_bt" style="min-width: 40px;"><?php echo $client['district_name'];?></span>
											ខេត្ត/រាជធានី<span class="value border_bt" style="min-width: 40px;"><?php echo $client['province_kh_name'];?></span>(ដែលហៅថា <strong>អ្នកខ្ចី</strong>)។
						 				</p>
				 					<table style="font-size: 14px ;  line-height: 22px; text-align: justify;">
				 						<tr>
				 							<td colspan="2" align="center">
				 								<strong>ក្រោយពីបានពិភាក្សាគ្នារួចមកភាគីទាំងពីរបានព្រមព្រៀងគ្នាដូចខាងក្រោម៖</strong>
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ១:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 								<strong> អ្នកឲ្យខ្ចី</strong>សម្រេចផ្តល់ឥណទានទៅ<strong>អ្នកខ្ចី</strong> ទឹកប្រាក់ចំនួន <span class="value border_bt" style="min-width: 120px;"><strong><?php echo number_format($loan['loan_amount'],2)." ".$loan['currency_type'];?></strong></span>ជាអក្សរ <span class="value border_bt" style="min-width: 110px;"><span id="lable_loankhmer"></span> <?php echo $loan['currency_type'];?></span>ហើយ
							 					<strong>អ្នកខ្ចី</strong> យល់ព្រមទទួលនូវឥណទាននេះ ស្របតាមកិច្ចសន្យាឥណទានដែលបានធ្វើឡើង។
							 					<?php $durationType=""; $day=1; if ($loan['pay_term']==1){ $durationType="ថ្ងៃ";}else if ($loan['pay_term']==1){ $day=7; $durationType="សប្តាហ៏";}else if ($loan['pay_term']==3){ $day=30; $durationType="ខែ";}?>
							 					ដោយអត្រាការប្រាក់សើ្ម<span class="value border_bt" style="min-width: 80px;"><strong><?php echo $loan['interest_rate'];?>%</strong></span>/ រយពេល<strong><?php echo str_replace("ប្រចាំ", "១", $loan['payTermKH']);?></strong> ហើយមានរយៈពេលខ្ចី<span class="value border_bt" style="min-width: 40px;"><strong><?php echo $loan['total_duration']*$day;?></strong></span>ថ្ងៃ<?php //echo $durationType;?>ចាប់គិតពីថ្ងៃបើកប្រាក់ទៅ។
							 					  <script>
														a_sold ='<?php echo ($loan['loan_amount']) ?>';
														money_khmersold=read_money_in_khmer(a_sold);
														
														decimalmoney_khmersold='<?php echo substr(number_format($loan['loan_amount'],2),-2);?>';
														str_centsold = 'សេន';
														if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
														last_number_sold='<?php echo substr(number_format($loan['loan_amount'],2),-2);?>';
														
														if(last_number_sold<=0){last_number_sold='';}
														money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
														dojo.byId('lable_loankhmer').innerHTML=money_khmersold+" ";
														//dojo.byId('lable_pricekhmer1').innerHTML=money_khmersold+" ";
												</script>
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ២:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 							<strong>អ្នកខ្ចី</strong> យល់ព្រមបង់ថ្លៃសេវារដ្ឋបាលចំនួន<span class="value border_bt" style="min-width: 150px;"><?php echo number_format($loan['other_fee'],2)." ".$loan['currency_type'];?></span>នៅថ្ងៃបើកប្រាក់តែម្តង។
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ៣:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 							<strong>អ្នកខ្ចី</strong> ត្រូវទូទាត់សងឥណទានតាមកាលបរិច្ឆេទសងប្រាក់របស់ <?php echo $loan['shop_name'];//$data['client_company_name'];?> ឲ្យបានទៀងទាត់ និងគ្រប់ចំនួន។
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ៤:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 							ការដាក់ទ្រព្យធានា <strong>អ្នកខ្ចី</strong>យល់ព្រមដាក់អចលនវត្ថុធានាកម្ចីមានៈ
				 							<?php if (!empty($collateral)){?>
									    		<?php foreach ($collateral as $key => $col){
									    		//if ($col['owner_type']==2){
									    			?>
									    		<br />
									    		<span id="padding-left">- <?php echo $col['calleteralTitle'];?> លេខ <?php echo $dbgb->getNumberInkhmer($col['number_collecteral']);?> ចុះថ្ងៃទី <?php if (!empty($col['issue_date'])){ echo $dbgb->getNumberInkhmer(date("d",strtotime($col['issue_date'])))." ខែ ".$month[date("m",strtotime($col['issue_date']))]." ឆ្នាំ ".$dbgb->getNumberInkhmer(date("Y",strtotime($col['issue_date'])));}?>  កម្មសិទ្ធ <?php echo $col['ownerType'];?> ចេញដោយ <?php echo $col['note'];?></span>។
									    		<?php //}
									    		}?>
									    	<?php }?>
				 							<!-- 	................................................និង.........................លេខ.......................... ចុះថ្ងៃទី............... ចេញដោយ...........................................។ -->
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ៥:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 							 <strong>អ្នកឲ្យខ្ចី</strong> មានសិទ្ធិទាមទាឲ្យ  <strong>អ្នកខ្ចី</strong> លក់ទ្រព្យដាក់ធានាប្រសិនបើ <strong>អ្នកខ្ចី</strong>មិនបានគោរពតាមគោលការណ៍ឥណទាន និង ប្រការ៣ ប្រការ៤ នៃកិច្ចសន្យាបរិភោគ។
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ៦:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 							អវសាននៃឥណទាន ឬកិច្ចសន្យានេះ ត្រូវចងភ្ជាប់កាតព្វកិច្ចទៅអ្នកពាក់ព័ន្ធដូចជា ឳពុក ម្តាយ កូន ឬអ្នកដែលមានសិទ្ធិ	មកលើទ្រព្យដាក់ធានានេះ។ កិច្ចសន្យានេះអស់សុពលភាពក្រោយពេល <strong>អ្នកខ្ចី</strong> សងផ្តាច់។
				 							</td>
				 						</tr>
				 						<tr>
				 							<td valign="top" align="left" width="10%"><strong>ប្រការ៧:</strong></td>
				 							<td valign="top" align="left" width="90%">
				 							ភាគីទាំងអស់បានអាន និងយល់ច្បាស់នូវលក្ខខណ្ឌនីមួយៗក្នុងកិច្ចសន្យានេះ ហើយសន្យាអនុវត្ដន៍រាល់ប្រការនៃកិច្ចសន្យានេះ។ ករណីភាគីណាមួយមិនអនុវត្ដន៍តាមកិច្ចសន្យានេះ ភាគីនោះត្រូវទទួលខុសត្រូវចំពោះមុខច្បាប់ជាធរមាន។ ការកែប្រែប្រការណាមួយនៃកិច្ចសន្យានេះអាចធ្វើទៅបានកាលណាមានការព្រមព្រៀមគ្នាពីភាគីពាក់ព័ន្ធជាមុន។
				 							</td>
				 						</tr>
				 					</table>
						 			</td>
						 		</tr>	
						 		<tr>
						 			<td colspan="3" style=" text-align: right; font-size: 14px">
						 				ធ្វើនៅ<span class="value border_bt" style="min-width: 50px;"></span>ថ្ងៃទី<span class="value border_bt" style="min-width: 30px;"></span>ខែ<span class="value border_bt" style="min-width: 50px;"></span>ឆ្នាំ២០<span class="value border_bt" style="min-width: 20px;"></span>
						 			</td>
						 		</tr>
						 		<tr>
						 			<td colspan="3">
						 				<table style="font-family:'Times New Roman','Khmer OS Battambang'; width: 100%; font-size: 14px; padding: 0px 1px; text-align: right; margin: 0px;">
										  	<tr>
										  		<td valign="top"  align="center" style=" width:20%;">
										  			<span style="display: block; margin-bottom: 10px;">សាក្សី</span>
										  			<div style="display: inline-block; height: 130px; width: 100px; border: solid 1px #000;">
										  			&nbsp;
										  			</div>
										  		</td>
										  		<td valign="top" align="center" style="width:40%;">
										  			<span style="display: block; margin-bottom: 10px;">អ្នកខ្ចី</span>
										  			<div style="height: 130px;width: 100px;border: solid 1px #000;display: inline-block;margin-right: 10px;">
										  			&nbsp;
										  			</div>
										  			<div style="height: 130px;width: 100px;border: solid 1px #000;display: inline-block; ">
										  			&nbsp;
										  			</div>
										  		</td>
										  		<td valign="top"  align="right" style="width:40%;">
													<table  style=" width:100%; font-size:14px; ">
												  		<tr align="center">
												    		<td>
												    			<span >អ្នកឲ្យខ្ចី</span>
												    			<br /><br />
												    			<span>ភ្នាក់ងារឥណទាន</span>
												    		</td>
											  			</tr>
													</table>
												</td>
										  	</tr>
										  	<tr align="center">
										  		<td align="center">
										  			<div style="width: 100px;border-bottom: dashed 1px #000;display: inline-block;margin-right: 10px;">
										  				<span class="value">&nbsp;<?php echo $client['spouse_name'] ;?>&nbsp;</span>
										  			</div>
										  		</td>
										  		<td align="center">
										  			<div style="width: 100px;border-bottom: dashed 1px #000;display: inline-block;margin-right: 10px;">
										  				<span class="value">&nbsp;<?php echo $client['name_kh'] ;?>&nbsp;</span>
										  			</div>
										  			<div style="width: 100px;border-bottom: dashed 1px #000;display: inline-block;margin-right: 10px;">
										  				<span class="value">&nbsp;<?php echo $client['join_with'] ;?>&nbsp;</span>
										  			</div>
										  		</td>
										  		<td align="center">
										  		</td>
										  	</tr>
									  </table>
						 			</td>
						 		</tr>				
							  </tbody>
						  </table>
			        </div>
			         <div id="printfooter">
			         		<!-- border-top: 2px solid #000; -->
			        		<table  width="100%" style="background: #fff;font-family: 'Khmer OS Battambang'; font-size:10px;line-height: 15px;white-space:nowrap;"> 
								<tbody>
									<tr style="white-space:nowrap;line-height: 12px;">
										<td width="40%"><?php echo "ទម្រង់ ០០១";//$this->keyValue['website'];?></td>
										<td width="40%" align="right"><?php echo $loan['shop_name'];//$data['client_company_name'];?> ជាក្រុមហ៊ុនឯកជន&nbsp;&nbsp;</td>
									</tr>
								</tbody>
							</table>
			        	</div>
		        </div>
        	 </td>	
		</tr>
	</table>
	</div>
