<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលស់ប្រាក់ដើម",4=>"បង់ផ្តាច់");
$session_user=new Zend_Session_Namespace('authloan');
$level =$session_user->level;
$loanPayment = $this->loanPayment;
$data = $this->data;

$showreceipt = empty($this->data['showreceipt'])?2:$this->data['showreceipt'];
?>
<title><?php echo $tr->translate("PAYMENT_RECEIPT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>

<div style="min-height:35cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div id="divPrint">
			<div id="divPrint1" style="width: 100%; height: 14.8cm ; padding: 0px; margin: 0px;">
				<?php echo $this->loanReceipt;?>
			</div>
		<?php if($showreceipt>1){?>
			<div id="divPrint2" style="width: 100%;height: 14.8cm ; padding: 0px; margin: 0px;">
				<div style="border:2px dashed #000; vertical-align: middle; margin:70px 0px 40px 0px"></div>
				<div id="printblog2"></div>
			</div>
		<?php }?>
	</div>
</div>
<script>
require(["dojo/ready"], function(ready){
	 ready(function(){
		 loadingBlock();
		 getBranchInfo();
		 printSave();
		 setTimeout(function () {
			 <?php if($showreceipt>1){?>
			 dojo.byId('printblog2').innerHTML = dojo.byId('divPrint1').innerHTML;
			 <?php }?>
	        HideloadingBlock();
	    }, 500);
		 
	 });
});
var url_branchifo = '<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'getbranch')); ?>';
function getBranchInfo(){
	branch_id = '<?php echo empty($loanPayment['branch_id'])?0:$loanPayment['branch_id'];?>';
	if(branch_id==''){
		return false;
	}
	dojo.xhrPost({
		url:url_branchifo,	
		content:{ 
			    'branch_id':branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			dojo.byId('br_address').innerHTML=data.br_address;
			dojo.byId('branch_tel').innerHTML=data.branch_tel;
		},
		error: function(err) {
			
		}
	});
}

function printSave(){
	dojo.byId("lbl_reciept_no").innerHTML = '<?php echo $loanPayment['receipt_no'];?>';
	dojo.byId("lbl_branch_id").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['branch_name'])));?>';
	dojo.byId("lbl_loan_number").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['loan_number'])));?>';
	dojo.byId("lbl_group_member").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['client_name'])));?>';
	dojo.byId("lbl_co_id").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['co_name'])));?>';

	dojo.byId("lbl_priciple_amount").innerHTML = '<?php echo number_format($loanPayment['begining_balance'],2);?>';
	dojo.byId("lbl_total_payment").innerHTML = '<?php echo number_format($loanPayment['total_paymentpaid'],2);?>';
	dojo.byId("lbl_paidTime").innerHTML = '<?php echo $loanPayment['paid_times'];?>';
	dojo.byId("lbl_collect_date").innerHTML = '<?php echo date("d/M/Y",strtotime($loanPayment['date_payment']));?>';
	
	dojo.byId("lbl_os_amount").innerHTML = '<?php echo number_format($loanPayment['principal_paid'],2);?>';
	dojo.byId("lbl_interest_paid").innerHTML = '<?php echo number_format($loanPayment['interest_paid'],2);?>';
	dojo.byId("lbl_penalty_amount").innerHTML = '<?php echo number_format($loanPayment['penalize_paid'],2);?>';
	dojo.byId("lbl_totalpaid").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['currency_typeshow'].' '.number_format($loanPayment['total_paymentpaid'],2))));?>';

	dojo.byId("lbl_note").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['note'])));;?>';

	dojo.byId("CurrentUserLBL").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['by_user'])));?>';
	dojo.byId("ClientLbl").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($loanPayment['client_name'])));?>';

	//dojo.byId("br_address").innerHTML = '<?php echo $loanPayment['receipt_no'];?>';
	//dojo.byId("branch_tel").innerHTML = '<?php echo $loanPayment['receipt_no'];?>';
	
}
</script>