<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("REPORT_LOANINCOMESTAEMENT"));
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលស់ប្រាក់ដើម",4=>"បង់ផ្តាច់");

$showLoan=1; //1=show,0 = hidden
$showPawn=1; //1=show,0 = hidden
$showSaleInstal=1; //1=show,0 = hidden
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('REPORT_LOANINCOMESTAEMENT');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('currency_type');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 20px;font-size: 10px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				
				table.content-data { page-break-inside:auto }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				
				.styleover:hover{ background: #ccc; }
				table tr td ul li{list-style: none;line-height: 25px;}
				ul li{list-style: none;line-height: 25px; }
				th{padding: 2px;}
				span.title-row {
					font-weight: bold;
				}
			</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang'; margin:0; padding:0; border:none;">
							<tr>
								<td width="20%"><span id="projectlogo"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" style="height: 85px;max-width: 100%;"></span></td>
								<td width="60%" valign="top">
									<ul>
										<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOANINCOMESTAEMENT");?></li>
										<li style="text-align:center; font-size:14px;">
											<span id="projectName"></span>
										</li>
										<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
						</table>
					</td>
				</tr>    
				<tr>
					<td id="exportExcel">
					<div>
						<table class="content-data"  style="border-collapse:collapse; font-size:14px; white-space: nowrap;" width="100%" cellspacing="0">
							<?php 
								 $rsincome = $this->rsincome;
									$incomed = 0;
									$incomer = 0;
									$incomeb = 0;
									
									$expenseD = 0;
									$expenseR = 0;
									$expenseB = 0;
							?>
							<thead style="font-family:'Times New Roman','Khmer OS Muol Light'">
								<tr style="background:#ccd9ff">
									<td style="padding: 5px;">ប្រភេទគណនី</td>
									<td></td>
									<td>ដុល្លារ-USD</td>
									<td>រៀល-KHR</td>
									<td>បាត-BTH</td>
								<tr>
							</thead>
							<?php if($showLoan==1){?>
							<tr class="styleover " >
								<td><span class="title-row">ចំណូល/Revenue</span></td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការប្រមូលការប្រាក់សរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome["interest_paidd"],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome["interest_paidr"],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome["interest_paidb"],2);?></td>
							</tr>
							 <tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការផាកពិន័យសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome["penalize_paidd"],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome["penalize_paidr"],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome["penalize_paidb"],2);?></td>
							</tr>
							<tr class="styleover " >
								<td>&nbsp;-&nbsp;ចំណូលពី សេវាផ្សេងៗសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome["service_paidd"],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome["service_paidr"],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome["service_paidb"],2);?></td>
							</tr>
							 <tr class="styleover " >
								<td>&nbsp;-&nbsp;ចំណូលពី សេវារដ្ឋបាលសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome["adminfee_d"]+$rsincome["other_feed"],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome["adminfee_r"]+$rsincome["other_feer"],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome["adminfee_b"]+$rsincome["other_feeb"],2);?></td>
							</tr>
							
							<?php 
								$incomed = $rsincome["interest_paidd"]+$rsincome["penalize_paidd"]+$rsincome["service_paidd"]+($rsincome["adminfee_d"]+$rsincome["other_feed"]);
								$incomer = $rsincome["interest_paidr"]+$rsincome["penalize_paidr"]+$rsincome["service_paidr"]+($rsincome["adminfee_r"]+$rsincome["other_feer"]);
								$incomeb = $rsincome["interest_paidb"]+$rsincome["penalize_paidb"]+$rsincome["service_paidb"]+($rsincome["adminfee_b"]+$rsincome["other_feeb"]);
							}
							
							?>
							<?php if($showPawn==1){?>
							<tr class="styleover" >
								<td><span class="title-row">ចំណូលពីបញ្ចាំ</span></td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការប្រាក់សរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['pawn_interestd'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome['pawn_interestr'],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome['pawn_interestb'],2);?></td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការផាកពិន័យសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['pawn_penalized'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome['pawn_penalizer'],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome['pawn_penalizeb'],2);?></td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី សេវារដ្ឋបាលសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['pawn_adminfeed'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome['pawn_adminfeer'],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome['pawn_adminfeeb'],2);?></td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការលក់ទ្រព្យបញ្ចាំ</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['pawn_selling_amount'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format(0,2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format(0,2);?></td>
							</tr>
							<?php 
								$incomed = $incomed+($rsincome['pawn_interestd']+$rsincome['pawn_penalized']+$rsincome['pawn_adminfeed']+$rsincome['pawn_selling_amount']);
								$incomer = $incomer+($rsincome['pawn_interestr']+$rsincome['pawn_penalizer']+$rsincome['pawn_adminfeer']);
								$incomeb = $incomeb+($rsincome['pawn_interestb']+$rsincome['pawn_penalizeb']+$rsincome['pawn_adminfeeb']);
							}
							
							?>
							
							<?php if($showSaleInstal==1){?>
							<tr class="styleover" >
								<td><span class="title-row">ចំណូលពីការលក់ និង​រំលស់</span></td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ប្រាក់ដើម</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['saleTotalPrincipalPaid'],2);?></td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការប្រាក់សរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['saleTotalInterestPaid'],2);?></td>
							</tr>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណូលពី ការផាកពិន័យសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['saleTotalPenalizePaid'],2);?></td>
							</tr>
							<?php 
								$incomed = $incomed+($rsincome['saleTotalPrincipalPaid']+$rsincome['saleTotalInterestPaid']+$rsincome['saleTotalPenalizePaid']);
							} ?>
							
							<tr class="styleover" >
								<td><span class="title-row">ចំណូលផ្សេងៗសរុប</span></td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['other_incomed'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome['other_incomer'],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome['other_incomeb'],2);?></td>
								<?php 
									$incomed = $incomed+$rsincome['other_incomed'];
									$incomer = $incomer+$rsincome['other_incomer'];
									$incomeb = $incomeb+$rsincome['other_incomeb'];
									
								?>
							</tr>
							
							<tr class="styleover">
								<td>&nbsp;&nbsp;<span style="font-family:'Times New Roman','Khmer OS Muol Light';font-size: 14px;">ចំណូលសរុបរួមទាំងអស់</span></td>
								<td>&nbsp;&nbsp;</td>
								<td><span style="border-bottom: 1px double #000;font-family:'Arial','Times New Roman','Khmer OS Battambang'; ">&nbsp;$&nbsp;<?php echo number_format($incomed,2);?></span></td>
								<td><span style="border-bottom: 1px double #000;font-family:'Arial','Times New Roman','Khmer OS Battambang'; ">&nbsp;៛&nbsp;<?php echo number_format($incomer,2);?></span></td>
								<td><span style="border-bottom: 1px double #000;font-family:'Arial','Times New Roman','Khmer OS Battambang'; ">&nbsp;฿&nbsp;<?php echo number_format($incomeb,2);?></span></td>
							</tr>
							 <tr class="styleover" >
								<td><span class="title-row">ចំណាយ/Expense</span></td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;&nbsp;</td>
							</tr>
							<?php if($showLoan==1){  ?>
							<tr class="styleover " >
								<td>&nbsp;-&nbsp;កម្ចីខូច/Loan Writeoff</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['badloan_d'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome['badloan_r'],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome['badloan_b'],2);?></td>
							</tr>
							<?php 
								$expenseD = $rsincome['badloan_d'];
								$expenseR = $rsincome['badloan_r'];
								$expenseB = $rsincome['badloan_b'];
								
							} 
							?>
							<?php if($showSaleInstal==1){?>
							 <tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណាយលើ ការបញ្ជារទិញរាយ</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['sale_retailPurchase'],2);?></td>
								
							</tr>
							 <tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណាយលើ ការបញ្ជារទិញដុំ</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['sale_purchase'],2);?></td>
							</tr>
							<?php
								$expenseD = $expenseD+$rsincome['sale_retailPurchase']+$rsincome['sale_purchase'];
							}?>
							<tr class="styleover" >
								<td>&nbsp;-&nbsp;ចំណាយផ្សេងៗសរុប</td>
								<td>&nbsp;&nbsp;</td>
								<td>&nbsp;$&nbsp;<?php echo number_format($rsincome['expense_d'],2);?></td>
								<td>&nbsp;៛&nbsp;<?php echo number_format($rsincome['expense_r'],2);?></td>
								<td>&nbsp;฿&nbsp;<?php echo number_format($rsincome['expense_b'],2);?></td>
							</tr>
							<?php 
								$expenseD = $expenseD+$rsincome['expense_d'];
								$expenseR = $expenseR+$rsincome['expense_r'];
								$expenseB = $expenseB+$rsincome['expense_b'];
							?>
							<tr class="styleover">
								<td>&nbsp;&nbsp;<span style="font-family:'Times New Roman','Khmer OS Muol Light';font-size: 14px;">Net Income/Lost ចំណេញ/ខាត សរុប</span></td>
								<td>&nbsp;&nbsp;</td>
								<td><span style="border-bottom: 1px double #000;font-family:'Arial';background:#ccc;padding:5px;">&nbsp;$&nbsp;<?php echo number_format($incomed-$expenseD,2);?></span></td>
								<td><span style="border-bottom: 1px double #000;font-family:'Arial','Times New Roman','Khmer OS Battambang';background:#ccc;padding:5px;">&nbsp;៛&nbsp;<?php echo number_format($incomer-$expenseR,2);?></span></td>
								<td><span style="border-bottom: 1px double #000;font-family:'Arial';background:#ccc;padding:5px;">&nbsp;฿&nbsp;<?php echo number_format($incomeb-$expenseB,2);?></span></td>
							</tr>
						</table>
						<br />
					</td>
				</tr>
			</table>
			<br />
			 <?php echo $this->footerReport;?> 
		</div>
	</div>
</div>

<script>

require(["dojo/ready"], function(ready){
	ready(function(){
		getBranchInfo();
		
	});
});
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->list_end_date['branch_id'])?0:$this->list_end_date['branch_id'];?>';
	if(branch_id==""|| branch_id==0 || branch_id==-1){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/branch/"?>'+arr.images_branch+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;
			document.getElementById('projectName').innerHTML = arr.branch_namekh;

		},
		error: function(e) {
		}
	});
}
</script>