<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('REPORT_LOAN_WRITE_OFF'));
 $frm = $this->frm_loan;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
	<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_LOAN_WRITE_OFF');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>	
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('adv_search');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('branch');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('client_name');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('co_id');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('Term');?>
               </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement('cash_type');?>
               </div>
             </div>
             <div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('start_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $frm->getElement('end_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
             </div>
        </div>
	</form>
<div id="divPrint">
	<style>
	.style{
		line-height: 20px;font-size: 12px !important;
		font-family: 'Times New Roman','Khmer OS Battambang';
	}
	table tr td ul li{list-style: none;line-height: 25px; }
	th{padding: 5px;}
	.hover:hover{ background:#ccc;}
	
	table { page-break-inside:auto }
	  tr{ page-break-inside:avoid; page-break-after:auto; }
	#header {
	  display: table-header-group;
	  page-break-inside:avoid; page-break-after:auto;
	}
		table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data thead tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:12px; 
			height: 23px;
		}
		
		table.tb-footer{
			font-family: 'Times New Roman','Khmer OS Battambang'; 
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:12px;
			width:100%;
		}
		table.tb-footer tr.style-head{
			line-height: 24px; 
			text-align: center; 
			background: #ccd9ff;
		}
		.border_bottom {
		    border-bottom: 1px solid #000;
		}
	</style>
	<table width="100%" >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
	                	<td width="60%" valign="top">
	                	    <ul>
	                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
	                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOAN_WRITE_OFF");?></li>
	                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
	                		</ul>
	                    </td>
	                    <td width="20%"></td>
	                </tr> 
	               
	            </table>
	        </td>
	    </tr>
	    <?php if(!empty($this->LoanCollectionco_list)){?>
	    <tr>
	    	<td id="exportExcel">
	            <table class="content-data" width="100%" border="1"  cellspacing="0">
	                <?php 
	                	  $amt_r1 = 0;$amt_r2 = 0;
	                	  $amt_d1 = 0;$amt_d2 = 0;
	                	  $amn_b1 = 0; $amn_b2 = 0;
						  $co_id=0;
						  $count_d = 0;$count_r=0;$count_b=0;
						  $count_ld = 0;$count_lr=0;$count_lb=0;
						  $tcount_ld=0;$tcount_lr=0;$tcount_lb=0;
						  $amt_r = 0;$amt_d = 0;$amt_b = 0;
	                ?>
	                <?php $record = 0;  foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
	                <?php  if($co_id!=$rs['co_id']){ $record=0;
	                if($key>0){
	                ?>
	               <tr>
	                	<td colspan="15" style=" border-left: #ffff solid 1px; border-right: #ffff solid 1px;">&nbsp;</td>
	                </tr>
	                <tr style=" border: #ffff solid 1px;">
	                	<td colspan="15">
	                		<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right">&nbsp;</td>
				                    <td></td>
				                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("AMT_LOAN");?></span>&nbsp;</td>
				                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCEPLE");?></span></td>
				                     <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_ld;?>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("REILS");?></td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_lr;?>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("BATH");?></td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_lb;?>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				            </table>
	                	</td>
	                </tr>
	            </table>
	                 <table class="content-data" border="1" cellspacing="0">
	                <?php } $count_ld=0;$count_lr=0;$count_lb=0; 
	                $amt_r = 0;$amt_d = 0;$amt_b = 0;
	                ?>
					<thead>
					<tr class="style" align="center" style="line-height: 20px; font-size:12px; padding:10px 0px; ">
						<td colspan="15">&nbsp; ឈ្មោះមន្ត្រីឥណទាន <?php echo $rs['co_name']; ?></td>
					</tr>
					<tr class="style-head" >
	                    <td><?php echo $tr->translate("NUM");?></td>
	                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td><?php echo $tr->translate("LOAN_NO");?></td>
	                    <td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
						<td><?php echo $tr->translate("PHONE");?> / <?php echo $tr->translate("ADDRESS");?></td> 
	                    <td><?php echo $tr->translate("LOAN_AMOUNT");?></td> 
	                    <td><?php echo $tr->translate("INTEREST_RATE");?></td>
	                    <td><?php echo $tr->translate("LOAN_PERIOD");?></td>
	                    <td>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
	                    <td><?php echo $tr->translate("ចំនួនប្រាក់ខូច");?></td> 
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td> 
	                    <!--<th><?php //echo $tr->translate("INTEREST_RECEIVEABLE");?></td>
	                    <td><?php //echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?></td>--> 
	                    <td><?php echo $tr->translate("LOSS_DATE");?></td>
	                    <td><?php echo $tr->translate("STATUS");?></td>
	                </tr>
					</thead>
					<?php } $record  = $record +1; $co_id=$rs['co_id'];?>
	                <?php 
	                  if($rs["curr_type"]==1){//reil
	                  	$amt_r1 = $amt_r1+$rs["total_amount"];
	                  	$amt_r = $amt_r+$rs["total_amount"];
	                  	$count_r=$count_r+1;
	                  	$count_lr = $count_lr+1;
	                  }elseif($rs["curr_type"]==2){
	                  	$amt_d1 = $amt_d1+$rs["total_amount"];
	                  	$amt_d = $amt_d+$rs["total_amount"];
	                  	$count_d=$count_d+1;
	                  	$count_ld = $count_ld+1;
	                  }else{
	                  	$amn_b1 = $amn_b1+$rs["total_amount"];
	                  	$amt_b = $amt_b+$rs["total_amount"];
	                  	$count_b=$count_b+1;
	                  	$count_lb = $count_lb+1;
	                  }
	                ?>
	                <tr class="style-rowdata hover" >
	               		<td align="center">&nbsp;<?php echo $record; ?>&nbsp;</td>
	               		<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
	               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
	               		<td>&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
	               		<td style="line-height: 18px; white-space: normal !important;max-width: 150px;width: 150px;padding: 5px;overflow-wrap: break-word;">
	               		<?php 
	               						echo empty($rs['phone'])?"":$rs['phone'];
										echo empty($rs['village_name'])?"":' '.$rs['village_name'];
										echo empty($rs['commune_name'])?"":','.str_replace("Commune", "", $rs['commune_name']);
										echo empty($rs['district_name'])?"":$rs['district_name'];
										echo empty($rs['province_en_name'])?"":$rs['province_en_name'];
								?>
	               		
	               		</td>
						<td align="center">&nbsp;<strong><?php echo number_format($rs["loan_amount"],2);?></strong>&nbsp;<?php echo $rs['currency_type'];?></td>
	               		<td align="center">&nbsp;&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo $rs['total_duration'].$rs['termborrow'];//$rs['pay_term'];?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
	               		<td style="text-align: center;background:#eeeeee;"><strong><?php echo number_format($rs["total_amount"],2);?></strong>&nbsp;<?php echo $rs['currency_type'];?></td>
	               		<td style="text-align: center;background:#eeeeee;"><strong><?php echo number_format($rs["interest_amount"],2);?></strong>&nbsp;<?php echo $rs['currency_type'];?></td>
	               		<td>&nbsp;<?php echo date("d-m-Y",strtotime($rs["loss_date"]));?></td>
	               		<td style="font-size: 12px;text-align: center;"><?php echo $rs["condition_term"];?></td>
	                </tr>
	                <?php }?>
	                 <tr>
	                	<td colspan="15" style=" border-left: #ffff solid 1px; border-right: #ffff solid 1px;">&nbsp;</td>
	                </tr>
	                <tr style=" border: #ffff solid 1px;">
	                	<td colspan="15">
	                		<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right">&nbsp;</td>
				                    <td></td>
				                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("AMT_LOAN");?></span>&nbsp;</td>
				                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCEPLE");?></span></td>
				                     <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_ld;?>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("REILS");?></td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_lr;?>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("BATH");?></td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_lb;?>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				            </table>
	                	</td>
	                </tr>
					
	            </table>
	             <div style="border:1px dashed #000;margin:10px 0px; "><strong>Total Only Loan Disbursed</strong></div>
	            <br />
	            <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
	                    <td align="right">&nbsp;</td>
	                    <td></td>
	                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("AMT_LOAN");?></span>&nbsp;</td>
	                    <td align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCEPLE");?></span></td>
	                     <td align="right">&nbsp;</td>
	                 </tr>
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
	                    <td align="right"></td>
	                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_d;?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
	                    <td align="right">&nbsp;</td>
	                 </tr>
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
	                    <td align="right"></td>
	                    <td align="right"><?php echo $tr->translate("REILS");?></td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_r;?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
	                    <td align="right">&nbsp;</td>
	                 </tr>
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
	                    <td align="right"></td>
	                    <td align="right"><?php echo $tr->translate("BATH");?></td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo $count_b;?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
	                    <td align="right">&nbsp;</td>
	                 </tr>
	            </table>
            
	             
				<br />
				<?php echo $this->footerReport;?> 
				</td>
			</tr>
			<?php }?>
		</table>
	</div>
</div>