<?php 
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<title><?php echo $tr->translate("LOAN_OUTSTADING");?></title>
<div class="card report-page" >
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-receipt"></i>&nbsp;<?php echo $tr->translate('LOAN_OUTSTADING');?></h5>
		<div class="justify-content-between align-items-center ">
			<form method="post">
				<div class="row g-3">
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('pay_every');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('member');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('co_id');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<select class="fullside" name="status_use" id="status_use" dojoType="dijit.form.FilteringSelect" >
							<option value="-1" <?php if($this->statusopt==-1){echo "selected";}?> >ជ្រើសរើសស្ថានការណ៏កម្ចី</option>
							<option value="0" <?php if($this->statusopt==0){echo "selected";}?> >តែកម្ចីដំណើរការ</option>
							<option value="-2" <?php if($this->statusopt==-2){echo "selected";}?> >ទាំងកម្ចីដំណើការនិងខូច</option>
						</select>
				   </div>
				</div>
				<div class="row g-3">
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">	
						<?php echo $frm->getElement('status');?>
				   </div>
				   <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   </div>
				</div>
			</form>
		</div>	
	</div>
	<div class="card-body">
		<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 20px;font-size: 13px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px;}
				th{padding: 5px;}
				table.content-data { page-break-inside:auto }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					text-align: center;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				
				table.tb-footer{
					font-family: 'Times New Roman','Khmer OS Battambang'; 
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:12px;
					width:100%;
				}
				table.tb-footer tr.style-head{
					line-height: 24px; 
					text-align: center; 
					background: #ccd9ff;
				}
				.border_bottom {
						border-bottom: 1px solid #000;
					}
				span.cl-info {
					text-align: left;
					display: block;
					width: 130px;
					white-space: pre-line;
					font-size: 90%;
					padding: 2px 0;
				}
			</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
				<tr>
					<td align="center">
						<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;">
							<tr>
								<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
								<td width="60%" valign="top">
									<ul>
										<li style="text-align:center; font-size:16px; font-family:Khmer OS Muol Light"><?php echo $tr->translate("BRAND_TITLE");?></li>
										<li style="text-align:center; font-size:14px; font-family:Khmer OS Muol Light"><?php echo $tr->translate("LOAN_OUTSTADING");?></li>
										<li style="text-align:center; font-size:14px;"><?php echo date('D-d-m-Y',strtotime($this->fordate));?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
						</table>
					</td>
				</tr>
				<tr>
					<td id="exportExcel">
						<table class="content-data" border="1" width="100%" cellspacing="0">
							<thead>
								<tr class="style-head">
									<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
									<td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
									<td rowspan="2"><?php echo $tr->translate("LOAN_NO");?></td>
									<td rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
									<td rowspan="2"><?php echo $tr->translate("Collateral");?></td>
									<td rowspan="2"><?php echo $tr->translate("NUMBER_COLLTERAL");?></td>
									<td colspan="7"><?php echo $tr->translate("ILLOAN_INFO");?></td>
								</tr>
								<tr class="style-head">
									<td><?php echo $tr->translate("RELEASE_DATE");?></td>
									<td><?php echo $tr->translate("LIFE_LOAN");?></td>
									<td><?php echo $tr->translate("LOAN_AMOUNT");?></td>
									<td><?php echo $tr->translate("LOAN_PERIOD");?></td>
									<td><?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?></td>
									<td><?php echo $tr->translate("PERCENTAGE");?></td>
									<td><?php echo $tr->translate("NOT_TO_REPAY");?></td>
								</tr>
							</thead>
						   <?php 
							   $db = new Report_Model_DbTable_DbLoan();
							   $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;$result_b=0;$result_r=0;$result_d=0;
							   $count_d=0;$count_r=0;$count_b=0;
							   $amt_loanmonth=0;$amt_loanweek=0;$amt_loanday=0;
							   $i=0;
							   
							   $monthDolar=0;
							   $weekDolar=0;
							   $dayDolar=0;
							   
							   $monthRiel=0;
							   $weekRiel=0;
							   $dayRiel=0;
							   
							   $monthBath=0;
							   $weekBath=0;
							   $dayBath=0;
							   
							   $coId="";
						   if(!empty($this->outstandloan)) foreach($this->outstandloan as $key =>$row){?>
						   <?php 
							  if($row['total_principaid']>=$row['total_capital'] OR $row['total_capital']<=0){
								continue;
							  }
							  
							  $i++;
								if($row['termborrow']==1){
									$amt_loanday=$amt_loanday+1;
								}elseif($row['termborrow']==2){
									$amt_loanweek=$amt_loanweek+1;
								}else{
									$amt_loanmonth = $amt_loanmonth+1;
								}
								$total_receive= $row['total_principaid'];
								
							   if($row['curr_type']==1){
									$amt_r = $amt_r+$row['total_capital'];
									$amn_r = $amn_r+$total_receive;
									$result_r=number_format(($amn_r/$amt_r)*100,2).' %';
									$count_r=$count_r+1;
										if($row['termborrow']==1){
											$dayRiel=$dayRiel+1;
										}elseif($row['termborrow']==2){
											$weekRiel=$weekRiel+1;
										}else{
											$monthRiel = $monthRiel+1;
										}
							   }elseif($row['curr_type']==2){
									$amt_d = $amt_d+$row['total_capital'];
									$amn_d = $amn_d+$total_receive;
									$result_d=number_format(($amn_d/$amt_d)*100,2).' %';
									$count_d=$count_d+1;
										
										if($row['termborrow']==1){
											$dayDolar=$dayDolar+1;
										}elseif($row['termborrow']==2){
											$weekDolar=$weekDolar+1;
										}else{
											$monthDolar = $monthDolar+1;
										}
							   }else{
									$amt_b = $amt_b+$row['total_capital'];
									$amn_b = $amn_b+$total_receive;
									$result_b=number_format(($amn_b/$amt_b)*100,2).' %';
									$count_b=$count_b+1;
									
									if($row['termborrow']==1){
										$dayBath=$dayBath+1;
									}elseif($row['termborrow']==2){
										$weekBath=$weekBath+1;
									}else{
										$monthBath = $monthBath+1;
									}
							   }
						   ?>
							<?php if($coId !=$row['co_id'] ){ ?>
							<tr class="style-rowdata hover" align="left">
								<td colspan="13"><?php echo $row['co_name']; ?></td>
							</tr>
							<?php } 
							$coId =$row['co_id'];
							?>
							
								<tr class="style-rowdata hover" align="center">
									<td><?php echo $i; ?></td>
									<td style="line-height: 12px; white-space: nowrap;"><?php echo $row['branch_name']; ?></td>
									<td><?php echo $row['loan_number'];?></td>
									<td align="left" style="font-size:12px; line-height: 13px; white-space: nowrap;"><?php echo $row['client_kh']; ?></td>
									<td><span class="cl-info"><?php echo $row['collecteralTitleKh'];?></span></td>
									<td><span class="cl-info"><?php echo $row['collecteralNumber'];?></span></td>
									<td style="white-space: nowrap;"><?php echo date('d-m-Y',strtotime($row['date_release']));?></td>
									<td style="white-space: nowrap;"><?php echo date('d-m-Y',strtotime($row['date_line']));?></td>
									<td style="white-space:nowrap; text-align: right;"><?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?></td>
									<td style="white-space: nowrap;"><?php echo number_format($row['total_duration']).$row['pay_term'];?></td>
									<td style="white-space:nowrap; text-align: right;"><?php echo number_format($total_receive,2).' '.$row['currency_type'];?></td>
									<td>
									<?php 
										echo (round(($total_receive/$row['total_capital']),2)*100).' %';
									?></td>
									<td><?php echo number_format(($row['total_capital']-$total_receive),2).' '.$row['currency_type'];?></td>
								</tr>
							<?php }?>
						</table>
						<br />
						
						<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
							 
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
									<td rowspan="2" align="right">&nbsp;</td>
									<td rowspan="2" align="right">&nbsp;</td>
									<td colspan="4" align="center"><span class="border_bottom"><?php echo $tr->translate("FOR_LOAN_TYPE");?></span></td>
									<td rowspan="2">&nbsp;</td>
									<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("LOAN_AMOUNT");?></span></td>
									<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?></span></td>
									<td rowspan="2"align="right"><span class="border_bottom"><?php echo $tr->translate("PERCENTAGE");?></span></td>
									<td  rowspan="2"align="right"><span class="border_bottom"><?php echo $tr->translate("NOT_TO_REPAY");?></span></td>
									<td rowspan="2"  align="right">&nbsp;</td>
							 </tr>
							 
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
									<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
									<td align="center"><span class="border_bottom"><?php echo $tr->translate("WEEK");?></span></td>
									<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
									<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
							 </tr>
							 
								
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("DOLLAR");?></td>
								<td align="center"><?php echo $monthDolar;?></td>
								<td align="center"><?php echo $weekDolar;?></td>
								<td align="center"><?php echo $dayDolar;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_d;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_d;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d-$amn_d,2);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("REILS");?></td>
								<td align="center"><?php echo $monthRiel;?></td>
								<td align="center"><?php echo $weekRiel;?></td>
								<td align="center"><?php echo $dayRiel;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_r;?>&nbsp;</td>
								 <td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
								
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_r;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r-$amn_r);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 
							
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
								<td align="right"></td>
								<td align="right"><?php echo $tr->translate("BATH");?></td>
								<td align="center"><?php echo $monthBath;?></td>
								<td align="center"><?php echo $weekBath;?></td>
								<td align="center"><?php echo $dayBath;?></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_b;?>&nbsp;</td>
								<td>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
								 <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo $result_b;?>&nbsp;</td>
								<td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b-$amn_b);?>&nbsp;</td>
								<td align="right">&nbsp;</td>
							 </tr>
							 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px;border-top: 4px double #000 !important;">
								<td align="right"></td>
								<td align="right"></td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanmonth;//number_format($count_d,2);?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanweek;//number_format($count_d,2);?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanday;//number_format($count_d,2);?>&nbsp;</td>
								<td align="center" style="font-weight:bold;">&nbsp;<?php echo $i;?>&nbsp;</td>
								<td colspan="6">&nbsp;</td>
							 </tr>
							
						</table>
						  <br />
						  <?php echo $this->footerReport;?> 	
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>