
<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$dayin_khmer = $this->day_inkhmer;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("DIALYAMOUNT_LOAN");?></title>
<div class="reportblog">
	<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('DIALYAMOUNT_LOAN');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('adv_search');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('branch_id');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('client_name');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('co_id');?>
               </div>
            </div>
            <div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('pay_every');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('start_date');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('end_date');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
	</form>
	<div id="divPrint" style="width: 100%;">
		<style>
		.style{
			line-height: 20px;font-size: 13px !important;
			font-family: 'Times New Roman','Khmer OS Battambang';
		}
		table tr td ul li{list-style: none;line-height: 25px; }
		th{padding: 2px;}
		
		table { page-break-inside:auto }
		  tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data thead tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:12px; 
			height: 23px;
		}
		
		table.tb-footer{
			font-family: 'Times New Roman','Khmer OS Battambang'; 
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:12px;
			width:100%;
		}
		table.tb-footer tr.style-head{
			line-height: 24px; 
			text-align: center; 
			background: #ccd9ff;
		}
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;">
		            	<tr>
		                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("DIALYAMOUNT_LOAN");?></li>
		                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="content-data"  border="1"​ width="100%" cellspacing="0">
		                <thead>
		                	<tr class="style-head" >
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("CLIENT_NO");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("TEL");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LOAN_LEVEL");?>&nbsp;</td>
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("CO_NAME");?>&nbsp;</td>
			                    
			                    <td colspan="6">&nbsp;<?php echo $tr->translate("ILLOAN_INFO");?>&nbsp;</td>
			                    <td colspan="4">&nbsp;<?php echo $tr->translate("PAYMENT_INFO");?>&nbsp;</td>
			                  
			                </tr>
		                	 <tr class="style-head" >
			                    
			                    <td>&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("INTEREST RATE");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("TERM_BORROW");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("PAMENT_METHOD");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
			                    
			                    <td>&nbsp;<?php echo $tr->translate("INSTALL_PAID");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("INSTALL_REMAIN");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("ចំនួនដង់យឺត");?>&nbsp;</td>
			                    <td>&nbsp;<?php echo $tr->translate("ទឹកប្រាក់យឺត");?>&nbsp;</td>
			                </tr>
		                </thead>
		               <?php 
		               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
		               $other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
		               
		               $count_ld=0;$count_lr=0;$count_lb=0;
		               $old='';
		               $amount_loan = 0;
		               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
		               <?php 
		              	$str_day = date('D',strtotime($row['first_payment']));
		                $day_as_khmer = $dayin_khmer[$str_day];
		               if($old!=$str_day){
		               	if($key>0){
		               	?>
		               	 <tr align="center" style="line-height: 25px; white-space: nowrap;" class="hover">
							<td colspan="18" style="text-align:center; font-size:12px;  font-family:'Times New Roman','Khmer OS Muol Light'">សរុបចំនួនទាំងអស់ <?php echo $amount_loan; ?></td>
					    </tr>
		               	<?php } $amount_loan=0;?>
		               <tr align="center" style="line-height: 25px; white-space: nowrap;" class="hover">
							<td colspan="18" style="background:#ccc;text-align:center; background: #ccd9ff; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'">តារាងបង់ប្រាក់សំរាប់ថ្ងៃ<?php echo $day_as_khmer; ?></td>
					   </tr>
		               <?php } 
		               $amount_loan=$amount_loan+1;
		               ?>
							<tr align="center" class="style-rowdata hover" >
							<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
							<td >&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
							<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
							<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
							<td align="left" style="line-height:15px;min-width:90px; ">&nbsp;
								<a target="_blank" title="click here to preview payment schedule" style="color:#000; text-decoration: none;">&nbsp;<?php echo $row['client_name']; ?></a>&nbsp;
							</td>	
							<td>&nbsp;<?php echo $row['phone'];?>&nbsp;</td>
							<td>&nbsp;<?php echo $row['loan_level'];?>&nbsp;</td>
							<td align="left" style="min-width:75px;"><span style="line-height:15px;">&nbsp;<?php echo $row['co_name']; ?></span>&nbsp;</td>	
							<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
							<td style="white-space:nowrap;">&nbsp;<?php echo $row['interest_rate']; ?>&nbsp;</td>
							<td>&nbsp;<?php echo $row['total_duration'].$row['name_en'];?>&nbsp;</td>
							<td>&nbsp;<?php echo $row['payment_name'];?>&nbsp;</td>
							<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?>&nbsp;</td>
							<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_line']));?>&nbsp;</td>
							<td align="center">&nbsp;<?php echo $row['installment_paid']; ?></td>			
							<td align="center" >&nbsp;<?php echo $row['total_duration']-$row['installment_paid']; ?>&nbsp;</td>	
							<td align="center" >&nbsp;<?php echo $row['amount_late']; ?>&nbsp;</td>	
							<td align="left" >&nbsp;<?php echo number_format($row['principle_after']+$row['total_interest_after'],2).' '.$row['currency_type']; ?>&nbsp;</td>	
						</tr>
						<?php  $old=$str_day; }?>
						<tr align="left" style="line-height: 25px; white-space: nowrap;" class="hover">
							<td colspan="18" style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'">សរុបចំនួនទាំងអស់ <?php echo $amount_loan; ?></td>
					    </tr>
		            </table>
		              <br />
		              <?php echo $this->footerReport;?> 	
		    	</td>
		    </tr>
		</table>
	</div>
</div>