<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<title><?php echo $tr->translate("RESCHEDULE_RPT");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RESCHEDULE_RPT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('adv_search');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('branch_id');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('client_name');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('pay_every');?>
               </div>
            </div>
            <div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $filter->getElement('start_date');?>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                	<?php echo $filter->getElement('end_date');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
               </div>
            </div>
       </div>
	</form>
	<div id="divPrint" style="width: 100%;">
	<style>
	.style{
		line-height: 20px;font-size: 12px !important;
		font-family: 'Times New Roman','Khmer OS Battambang';
	}
	table tr td ul li{list-style: none;line-height: 25px; }
	th{padding: 5px;}
	
	table { page-break-inside:auto }
	  tr{ page-break-inside:avoid; page-break-after:auto; }
	#header {
	  display: table-header-group;
	  page-break-inside:avoid; page-break-after:auto;
	}
table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data thead tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:12px; 
			height: 23px;
		}
		
		table.tb-footer{
			font-family: 'Times New Roman','Khmer OS Battambang'; 
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:12px;
			width:100%;
		}
		table.tb-footer tr.style-head{
			line-height: 24px; 
			text-align: center; 
			background: #ccd9ff;
		}
	</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;">
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
	                	<td width="60%" valign="top">
	                	   <ul>
	                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
	                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("RESCHEDULE_RPT");?></li>
	                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
	                		</ul>
	                	</td>
	                    <td width="20%"></td>
	                </tr> 
	               
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table class="content-data" border="1"​  cellspacing="0">
	                <thead>
	                <tr class="style-head" >
	                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("CLIENT_NO");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("INTEREST RATE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("RESCHEDULE_AMOUNT");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("INTEREST RATE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("RESCHEDULE_DATE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("TERM_BORROW");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("PAMENT_METHOD");?>&nbsp;</td>
	                </tr>
	                </thead>
	               <?php 
	               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
	               $other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
	               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
	               <?php 
	              if($row['curr_type']==1){
	               		$amt_r = $amt_r+$row['re_amount'];
	               		$total_r=$amt_r+$amn_r+$other_fee_r;
	               }elseif($row['curr_type']==2){
	               		$amt_d = $amt_d+$row['re_amount'];
	               		$total_d=$amt_d+$amn_d+$other_fee_d;
	               }else{
	               		$amt_b = $amt_b+$row['re_amount'];
	               		$total_b=$amt_b+$amn_b+$other_fee_b;
	               }
	              
	               ?>
					<tr align="center">
						<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td >&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['re_loan_number'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
						<td align="left" style="line-height:15px;">&nbsp;<?php  echo $row['client_name']; ?>&nbsp;</td>	
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['interest_rate']; ?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?>&nbsp;</td>
						<td>&nbsp;<?php echo number_format($row['re_amount'],2).' '.$row['currency_type']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['re_interest_rate'];?>&nbsp;</td>
						<td>&nbsp;<?php echo date('d/m/Y',strtotime($row['reschedule_date']));; ?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['maturity']));?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo $row['total_duration'].$row['Term Borrow'];?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['from_paymentmethod'].'-'.$row['re_payment_method'];?>&nbsp;</td>				
					</tr>
					<?php }?>
	            </table>
	            <br />
	             <table class="tb-footer" border="1"​ cellspacing="0">
	                 <thead>
					 <tr class="style-head" align="center">
	                    <td><?php echo $tr->translate("CURRENT_TYPE");?></td>
	                    <td><?php echo $tr->translate("TOTAL_AMOUNT");?></td>
	                </tr>
					</thead>
	                 <tr>
	                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
	                    <td>&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
	                 </tr>
	                 <tr>
	                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
	                    <td>&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
	                </tr>
	                 <tr>
	                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
	                </tr>
	              </table>
	              <br />
	              <table align="center" width="100%">
					   <tr style="font-size: 11px;">
					        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
				</table>
			</td>
	    </tr>
	</table>
	</div>
</div>