<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("REPORT_LOAN_PAYOFF"));
	$frm = $this->frm_search;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_LOAN_PAYOFF');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>	
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement("advance_search");?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('client_name');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('start_date');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('end_date');?>
               </div>
            </div>
            <div class="form-group">
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('branch_id');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('status');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<?php echo $frm->getElement('co_id');?>
               </div>
               <div class="col-md-3 col-sm-3 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
        </div>
	</form>
<div id="divPrint">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Times New Roman','Khmer OS Battambang';
		}
		.style1:hover{ background: #ccc;}
		table tr td ul li{list-style: none;line-height: 25px; }
		table { page-break-inside:auto }
		  tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		table.content-data{
			border-collapse:collapse;
			width:100%;
			border:1px solid #000; 
			font-family:'Times New Roman','Khmer OS Battambang';
			font-size:13px;
			white-space: nowrap;
			margin:0 auto;
		}
		table.content-data thead tr.style-head {
		   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
			background: #ccd9ff;
			text-align: center;
		}
		table.content-data tr.style-rowdata {
			font-size:12px; 
			height: 23px;
		}
		
		table.tb-footer{
			font-family: 'Times New Roman','Khmer OS Battambang'; 
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:12px;
			width:100%;
		}
		table.tb-footer tr.style-head{
			line-height: 24px; 
			text-align: center; 
			background: #ccd9ff;
		}
		.border_bottom {
		    border-bottom: 1px solid #000;
		}
	</style>
	<table width="100%">
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
	                	<td width="60%" valign="top">
	                	   <ul>
	                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
	                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOAN_PAYOFF");?></li>
	                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
	                		</ul>
	                	</td>
	                    <td width="20%"></td>
	                </tr> 
	               
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table class="content-data" border="1"​  cellspacing="0">
	                <thead>
					<tr class="style-head" >
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("CO_NAME");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td> 
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("INTEREST_RATE");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
	                    <td colspan="5" >&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?>&nbsp;</td>
	                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("RECEIPT");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("TOTAL_PAYMENTED");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("DAY_PAYMENT");?>&nbsp;</td>
	                </tr>
	                <tr class="style-head" >
	                	<td>&nbsp;<?php echo $tr->translate("OS_AMOUNT");?>&nbsp;</td>                    
	                    <td>&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>                    
	                    <td>&nbsp;<?php echo $tr->translate("SERVICE CHARGE");?>&nbsp;</td>
	                    <td>&nbsp;<?php echo $tr->translate("PAYMENT");?>&nbsp;</td>
	                </tr>
					</thead>
	                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$amt_r6 = 0;$amt_loanday = 0;
	                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$amt_d6 = 0;$amt_loanweek = 0;
	                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$amn_b6 = 0;$amt_loanmonth = 0;
	                	 
	                	 $monthDolar=0;
	                	 $weekDolar=0;
	                	 $dayDolar=0;
	                	 	
	                	 $monthRiel=0;
	                	 $weekRiel=0;
	                	 $dayRiel=0;
	                	 	
	                	 $monthBath=0;
	                	 $weekBath=0;
	                	 $dayBath=0;
	                ?>
	                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
	                <?php 
                		if($rs['pay_term']==1){
                			$amt_loanday = $amt_loanday+1;
                		}elseif($rs['pay_term']==2){
                			$amt_loanweek = $amt_loanweek+1;
                		}else{
                			$amt_loanmonth = $amt_loanmonth+1;
                		}
		               if($rs['curr_type']==1){
		               		$amt_r1 = $amt_r1+$rs['principal_paid'];
		               		$amt_r2 = $amt_r2+$rs['interest_paid'];
		               		$amt_r3 = $amt_r3+$rs['penalize_paid'];
		               		$amt_r5 = $amt_r5+$rs['service_paid'];
		               		$amn_r4 = $amt_r5+$rs['total_paymentpaid'];
		               		
		               		if($rs['pay_term']==1){
		               			$dayRiel=$dayRiel+1;
		               		}elseif($rs['pay_term']==2){
		               			$weekRiel=$weekRiel+1;
		               		}else{
		               			$monthRiel = $monthRiel+1;
		               		}
		               		
		               }elseif($rs['curr_type']==2){
							$amt_d1 = $amt_d1+$rs['principal_paid'];
							$amt_d2 = $amt_d2+$rs['interest_paid'];
							$amt_d3 = $amt_d3+$rs['penalize_paid'];
							$amt_d5 = $amt_d5+$rs['service_paid'];
							$amt_d4 = $amt_d5+$rs['total_paymentpaid'];
							
							if($rs['pay_term']==1){
								$dayDolar=$dayDolar+1;
							}elseif($rs['pay_term']==2){
								$weekDolar=$weekDolar+1;
							}else{
								$monthDolar = $monthDolar+1;
							}
							
		               }else{
		               		$amn_b1 = $amn_b1+$rs['principal_paid'];
							$amn_b2 = $amn_b2+$rs['interest_paid'];
							$amn_b3 = $amn_b3+$rs['penalize_paid'];
							$amn_b5 = $amn_b5+$rs['service_paid'];
							$amn_b4 = $amn_b5+$rs['total_paymentpaid'];
							
							if($rs['pay_term']==1){
								$dayBath=$dayBath+1;
							}elseif($rs['pay_term']==2){
								$weekBath=$weekBath+1;
							}else{
								$monthBath = $monthBath+1;
							}
		               }
	               ?>
	                <tr class="style-rowdata hover context-menu-one" oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;">
	               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
	               		<td >&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
	               		<td >&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
	               		<td >&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
	               		<td >&nbsp;<?php echo $rs["co_name"];?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo number_format($rs["total_capital"],2).''.$rs['currency_type'];?></td>
	               		<td align="center">&nbsp;&nbsp;<?php echo $rs["interest_rate"];?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo $rs['total_duration'].$rs['termborrow'];//$rs['pay_term'];?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
	               		<td >&nbsp;<?php echo number_format( $rs["principal_amount"],2).' '.$rs['currency_type'];?></td>               		
	               		<td >&nbsp;<?php echo number_format($rs["interest_amount"],2).' '.$rs['currency_type'];?></td>
	               		<td >&nbsp;<?php echo number_format($rs["penelize"],2).' '.$rs['currency_type'];?></td>               		
	               		<td >&nbsp;<?php echo number_format($rs["service_chargeamount"],2).' '.$rs['currency_type'];?></td>
	               		<td >&nbsp;<strong><?php echo number_format($rs["total_payment"],2);?></strong>&nbsp;<?php echo $rs['currency_type'];?></td>
	               		<td >&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
	               		<td >&nbsp;<?php echo number_format($rs["total_paymentpaid"],2).' '.$rs['currency_type'];?>&nbsp;</td>
	               		<td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_payment"]));?>&nbsp;</td>
	                </tr>
	                <?php }?>
	            </table>
	            <br />
	            <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
	           			 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
	                 		<td rowspan="2" align="right">&nbsp;</td>
	                 		<td rowspan="2" align="right">&nbsp;</td>
	                 		<td colspan="4" align="center"><span class="border_bottom"><?php echo $tr->translate("FOR_LOAN_TYPE");?></span></td>
	                    	<td rowspan="2">&nbsp;</td>
	                    	<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PRINCEPLE");?></span></td>
	                     	<td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_INTEREST");?></span></td>
	                      	<td rowspan="2"align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PENELIZE");?></span></td>
	                       	<td  rowspan="2"align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL SERVICE CHARGE");?></span></td>
	                       	<td  rowspan="2"align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PAYMENTED");?></span></td>
	                     	<td rowspan="2"  align="right">&nbsp;</td>
		                 </tr>
	             		 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                 	  	<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
		                   		<td align="center"><span class="border_bottom"><?php echo $tr->translate("WEEK");?></span></td>
		                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
		                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
		                 </tr>
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
	                    <td align="right"></td>
	                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
	                    <td align="center"><?php echo $monthDolar;?></td>
	                 	<td align="center"><?php echo $weekDolar;?></td>
	                    <td align="center"><?php echo $dayDolar;?></td>
	                    <td align="center"><?php echo $monthDolar+$weekDolar+$dayDolar;?></td>
	                    <td>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d1+$amt_d2+$amt_d3+$amt_d5,2);?>&nbsp;</td>
	                    <td align="right">&nbsp;</td>
	                 </tr>
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
	                    <td align="right"></td>
	                    <td align="right"><?php echo $tr->translate("REILS");?></td>
	                    <td align="center"><?php echo $monthRiel;?></td>
	                 	<td align="center"><?php echo $weekRiel;?></td>
	                    <td align="center"><?php echo $dayRiel;?></td>
	                    <td align="center"><?php echo $monthRiel+$weekRiel+$dayRiel;?></td>
	                    <td>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_r1+$amt_r2+$amt_r3+$amt_r5,2);?>&nbsp;</td>
	                    <td align="right">&nbsp;</td>
	                 </tr>
		                
	                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
	                    <td align="right"></td>
	                    <td align="right"><?php echo $tr->translate("BATH");?></td>
	                    <td align="center"><?php echo $monthBath;?></td>
	                 	<td align="center"><?php echo $weekBath;?></td>
	                    <td align="center"><?php echo $dayBath;?></td>
	                    <td align="center"><?php echo $monthBath+$weekBath+$dayBath;?></td>
	                    <td>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
	                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b1+$amn_b2+$amn_b3+$amn_b5,2);?>&nbsp;</td>
	                    <td align="right">&nbsp;</td>
	                 </tr>
	                 
	                  <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px;border-top: 4px double #000 !important;">
		                    <td align="right"></td>
		                    <td align="right"></td>
		                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanmonth;//number_format($count_d,2);?>&nbsp;</td>
		                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanweek;//number_format($count_d,2);?>&nbsp;</td>
		                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $amt_loanday;//number_format($count_d,2);?>&nbsp;</td>
		                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo count($this->LoanCollectionco_list);?>&nbsp;</td>
		                    <td colspan="7">&nbsp;</td>
		                 </tr>
		                 
           	 </table>
	             
	               <br />
	               <?php echo $this->footerReport;?>
	    	</td>
	    </tr>
		</table>
	</div>
</div>
<?php $url_receipt=$this->url(array("module"=>'report',"controller"=>"loan","action"=>'recieptpayment'))."?id=";?>
<script>
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="reciept"){
				url='<?php echo $url_receipt;?>';
			}
			gotoAction();
		},
		items: {
			"reciept": {name: "<?php echo $tr->translate("PAYMENT_RECEIPT");?>", icon: "fa-file-text", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
 </script>