<?php 
$tran = $this->tran_schedule;
$filter = $this->frm_search;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
$db = new Report_Model_DbTable_DbLoan();

$tran = $this->tran_schedule;
$client = $this->client;											
?>
<?php 
	$db_keycode = new Application_Model_DbTable_DbKeycode();
	$key_code= $db_keycode->getSystemSetting(9);
	$free_day=$key_code['value'];
	
	$keyvalue = $db_keycode->getKeyCodeMiniInv();
	$interest_penalty = $keyvalue['interst_late'];
?>
<style>
.hover:hover{background: #ccc;}
table.content-data thead tr.style-head {
   font-weight: bold !important;
}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_LOAN_COLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_LOAN_COLLECT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form method="post">
		<div class="card-box">
			<div class="form-group">
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('adv_search');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('branch_id');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('client_name');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('co_id');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('start_date');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('end_date');?>
               </div>
            </div>
            <div class="form-group">
            	<div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('repayment_method');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<?php echo $filter->getElement('province');?>
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<input id="district" >
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<input id="commune" >
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<input id="village" >
               </div>
               <div class="col-md-2 col-sm-2 col-xs-12">
               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
               </div>
            </div>
		</div>
	</form>
	<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
	<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		try{
			new dijit.form.FilteringSelect({
			store: district_store,
			required: false,		           
			name: "district",
			id: "district",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					district = dijit.byId('district').get('value');
					if(district==-1){
						}
						filterCommune();
				}  
			}, "district");
			 
			new dijit.form.FilteringSelect({
			store: commune,
			required: false,		           
			name: "commune",
			id: "commune",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					commune = dijit.byId('commune').get('value');
					if(commune==-1){
					}
					else{
						filterVillage();
					}
		  }
			}, "commune");
			 
			new dijit.form.FilteringSelect({
			store: village_store,
			autoComplete: true,	           
			name: "village",
			id: "village",
			searchAttr: "name",
			class: 'fullside',
			}, "village");
		}catch(e){
			alert(e);
		}
		filterDistrict();
	});

	url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
	var oldProvince = '<?php if (!empty($this->rsearch['province'])){ echo $this->rsearch['province'];}else{ echo 0;}?>';
	function filterDistrict(){
		pro_id = dijit.byId('province').get('value');
		if(pro_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getdistrict,	
			content:{ 
				'pro_id': pro_id
			},
			handleAs:"json",
			load: function(data) {	
				district_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('district').set('store', district_store);
			    if(oldProvince==pro_id){
				    <?php if (!empty($this->rsearch['district'])){?>
			    	 dijit.byId('district').set('value', <?php echo $this->rsearch['district'];?>);
			    	 <?php }?>
			    }
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
	url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
	var oldDistrict = '<?php if (!empty($this->rsearch['district'])){ echo $this->rsearch['district'];}else{ echo 0;}?>';
	function filterCommune(){
		distict_id = dijit.byId('district').get('value');
		if(distict_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getcommune,	
			content:{ 
				'district_id': distict_id
			},
			handleAs:"json",
			load: function(data) {	
				commune_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('commune').set('store', commune_store);
			    if(oldDistrict==distict_id){
			    	 <?php if (!empty($this->rsearch['commune'])){?>
			    	 dijit.byId('commune').set('value', <?php echo $this->rsearch['commune'];?>);
			    	 <?php }?>
			    }
			},
			error: function(err) {
				alert(err);
			}
		});
	}

	var oldcommune = '<?php if (!empty($this->rsearch['commune'])){ echo $this->rsearch['commune'];}else{ echo 0;}?>';
	url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
	function filterVillage(){
		commune_id = dijit.byId('commune').get('value');
		if(commune_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getvillage,	
			content:{ 
				'commune_id': commune_id
			},
			handleAs:"json",
			load: function(data) {	
				village_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('village').set('store', village_store);
			    if(oldcommune==commune_id){
			    	 <?php if (!empty($this->rsearch['village'])){?>
			    	 dijit.byId('village').set('value', <?php echo $this->rsearch['village'];?>);
			    	 <?php }?>
			    }
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	</script>
	<div id="divPrint" style="margin:0 auto;">
			<style>
				.style{
					line-height: 20px;font-size: 11px !important;
					font-family: 'Khmer OS Battambang';
				}
				table tr td ul li{list-style: none;line-height: 25px; }
				th{padding: 2px;}
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				thead tr td { text-align: center;}
				
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
					margin:0 auto;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
					white-space: nowrap;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
			</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0 auto;padding:0px; border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
			                	<td width="60%" valign="top">
			                	<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOAN_COLLECT");?></li>
		                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->rsearch['start_date'])){?><?php echo date("D-d-M-Y",strtotime($this->rsearch['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->rsearch['end_date']));}?></li>
		                		</ul>
		                    </td>
			                    <td width="20%"><span style="text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><label id="lbl_customer"></label></span></td>
			                </tr>
			                <?php 
			                ?> 
			               
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td id="exportExcel">
			            <table class="content-data" border="1"​ >
			             <thead>
			                 <tr class="style-head" align="center" >
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("NUM");?></td>
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("LOAN_NO");?></td>
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("REPAYMENT_TYPE");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></td>
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("PHONE")." / ".$tr->translate("ADDRESS");?></td>
			                    <!-- <th rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("RELEASE_DATE");?></td>
			                    <td rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("LIFE_LOAN");?></td>
			                    <th rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("TOTAL_AMOUNT");?></td>
			                    <td rowspan="2" ><?php //echo $tr->translate("INTEREST RATE");?></td>
			                    <td rowspan="2" ><?php //echo $tr->translate("LOAN_PERIOD");?></td> 
			                    <td rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("PAY_DATE");?></td>-->
			                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("PAID_TIME");?></td>
			                    <td colspan="3" style="padding:0px 2px;"><?php echo $tr->translate("PAYMENT");?></td>
			                    <td rowspan="2" style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("LATE_DAY");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("LATE");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("PAY_DATE");?></td>
			                </tr>
			                <tr class="style-head" >
			                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("PRINCIPAL");?></td>
			                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("INTEREST");?></td>
			                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
			                 </tr>
			               </thead> 
			                <?php 
			                $amt_r1 = 0;
			                $amt_r3 = 0;
			                $amt_r4 = 0;
			                $amt_d1 = 0;
			                $amt_d3 = 0;
			                $amt_d4 = 0;
			                $amn_b1 = 0;
			                $amt_b1=0; $amn_b3 = 0; 
			                $amn_b4 = 0;
			                $total_d=0;
			                $result=0;
		                    $pene_amr=0; $pene_amb=0;$pene_amd=0;
		                	$end_date = $this->rsearch['end_date'];
		                ?>
		                <?php $i=1; $currentlate = 0;?>
		               <?php if(!empty($this->loanlate_list))foreach ($this->loanlate_list as $index => $rs){ ?>
		               		<?php 
			               			$total_pay=($rs['principle_after']+$rs['total_interest_after']);
		// 	               			if ($rs['last_pay_date']==null or $rs['last_pay_date']==""){
			               				$total_day=strtotime($end_date)-strtotime($rs['date_payment']);
			               				$amount_lateday=$total_day/(60*60*24)-$free_day;
			               				$total_late_day=$total_day/(60*60*24);
		// 	               			}else {
		// 	               				$total_day=strtotime($end_dat)-strtotime($rs['last_pay_date']);
		// 	               				$total_late_day=$total_day/(60*60*24);
		// 	               				$amount_lateday=$total_day/(60*60*24);
		// 	               			}
			               			$currentlate =$total_day/(60*60*24);
			               			$pay_term=$rs['collect_typeterm'];
			               			if($amount_lateday<0){
			               				$amount_lateday=0;
			               				$result=0;
			               			}
		// 	               			else {
			               				$total_late=($rs['principle_after']+$rs['total_interest_after']);
			               				if ($pay_term==1){
			               					$result=$total_pay*($interest_penalty*($rs['interest_rate']/100)/1)*($amount_lateday);
			               				}
			               				if ($pay_term==2){
			               					$result=$total_pay*($interest_penalty*($rs['interest_rate']/100)/7)*($amount_lateday);
			               				}
			               				if ($pay_term==3){
			               					$result=$total_pay*($interest_penalty*(($rs['interest_rate']/100)/30))*($amount_lateday);
			               				}
		// 	               			}
			               			$penelize = $db->roundhundred($rs['penelize']+$result, $rs['curr_type']);
			               			$total_payment =$rs['principle_after']+$rs['total_interest_after'];
		               			?>
		               <?php //if($currentlate>0){?>
		                <tr class="style-rowdata hover" >
		               		<td style="text-align: center;"><?php echo $i++;?></td>
		               		<td>&nbsp;<?php echo $rs["branch_namekh"];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $rs["payment_method_title"];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>
		               		<td style="white-space: nowrap;">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
		               		<td style="line-height: 18px; white-space: normal !important;max-width: 150px;width: 150px;padding: 5px;overflow-wrap: break-word;">
		               			<?php 
		               				echo $rs["phone"];
		               				echo empty($rs['village_name'])?"":",".$rs['village_name'];
		               				echo empty($rs['commune_name'])?"":",".str_replace("Commune","",$rs['commune_name']);
		               				echo empty($rs['district_name'])?"":",".$rs['district_name'];
		               				echo empty($rs['province_en_name'])?"":",".$rs['province_en_name'];
		               			?>
		               		</td>
		               		<!-- <td align="right" style="white-space: nowrap;">&nbsp;<?php //echo date("d/m/Y",strtotime($rs["date_release"]));?>&nbsp;</td>
		               		<td align="right" style="white-space: nowrap;">&nbsp;<?php //echo number_format($rs["total_capital"],2).' '.$rs['currency_type'];?>&nbsp;</td>
		               		<td>&nbsp;<?php //echo $rs["interest_rate"];?>&nbsp;</td>
		               		<td>&nbsp;<?php //echo $rs["total_duration"]." ".$rs["Term Borrow"];?>&nbsp;</td> -->
		               		<td align="center">&nbsp;&nbsp;<?php echo $rs['times']."/".$rs['total_duration'];?> &nbsp;</td>
		               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["principle_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
		               		<td align="right" style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["total_interest_after"],2).' '.$rs['currency_type'];?>&nbsp;</td>
		               		<td align="right" style="white-space: nowrap;">&nbsp;<?php //echo $penelize.' '.$rs['currency_type'];?>&nbsp;</td> 
		               		<td align="right" style="white-space: nowrap;"><strong >&nbsp;<?php echo number_format($total_payment,2);?></strong>&nbsp;<?php echo $rs['currency_type'];?>&nbsp;</td>
		               		<td align="center">&nbsp;&nbsp;<?php echo $amount_lateday." Days";?> &nbsp;</td>
		               		<td align="center">&nbsp;&nbsp;<?php echo $rs["amount_late"]." ដង";?> &nbsp;</td>
		               		<td align="center">&nbsp;&nbsp;<?php echo date_format(date_create($rs["date_payment"]),'d-m-Y');?>&nbsp;</td>
		                </tr>
		                <?php //}?>
		                <?php 
				               if($rs['curr_type']==1){
				               		$amt_r1 = $amt_r1+$rs['principle_after'];
				               		$amt_r3 = $amt_r3+$rs['total_interest_after'];
				               		$pene_amr=$pene_amr+$penelize;
				               		$amt_r4 = $amt_r4+$total_payment;
				               }elseif($rs['curr_type']==2){
									$amt_d1 = $amt_d1+$rs['principle_after'];
									$amt_d3 = $amt_d3+$rs['total_interest_after'];
									$pene_amd=$pene_amd+$penelize;
									$amt_d4 = $amt_d4+$total_payment;
				               }else{
									$amt_b1 = $amt_b1+$rs['principle_after'];
									$amn_b3 = $amn_b3+$rs['total_interest_after'];
									$pene_amb= $pene_amb+$penelize;
									$amn_b4 = $amn_b4+$total_payment;
				               }
				               $amount_days = strtotime($this->rsearch['end_date'])-strtotime($rs["date_payment"]);
				               $amount_days =  floor($amount_days/(60*60*24));
		               ?>
		                <?php }?>
			            </table>
			    	</td>
			    </tr>
			</table>
			<br />
			<table width="100%">
				<tr>
		    	<td style="font-family:'Times New Roman','Khmer OS Battambang';">
		             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">				 
						 <thead>
						 <tr class="style" style="line-height: 24px; text-align: center; background: #ccd9ff; font-size:9px;">
		                     <td><?php echo $tr->translate('CURRENT_TYPE');?></td>    
		                    <td><?php echo $tr->translate("TOTAL_PRINCIPLE");?></td>
		                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
		                    <!-- <td><?php //echo $tr->translate("PENALIZE AMOUNT");?></td>-->
		                    <td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
		                </tr>
						</thead>
		                 <tr class="style" style=" line-height: 24px; ">
		                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
		                    <!--<td>&nbsp;&nbsp;<?php echo number_format($pene_amd,2);?>&nbsp;</td> -->
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; ">
		                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
		                    <!--<td>&nbsp;&nbsp;<?php //echo number_format($pene_amr,2);?>&nbsp;</td>-->
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
		                </tr>
		                 <tr class="style" style="line-height: 24px; ">
		                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
		                   <td>&nbsp;&nbsp;<?php echo number_format($amt_b1,2);?>&nbsp;</td>
		                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
		                    <!--<td>&nbsp;&nbsp;<?php echo number_format($pene_amb,2);?>&nbsp;</td>-->
		                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
		                </tr>
		              </table> 
		               <table align="center" width="100%">
					   		<thead>
							   <tr style="font-size: 14px;">
							        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'">
							        	<?php echo $tr->translate('APPROVED BY');?>
							        </td>
							        <td></td>
							        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'">
							        	<?php echo $tr->translate('VERIFYED BY');?>
							        </td>
							        <td></td>
							        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'">
							        	<?php echo $tr->translate('PREPARE BY');?>
							        </td>
								</tr>
							</thead>
						</table>
			    	</td>
			    </tr>
			</table>
	</div>
</div>
<script>
dojo.require("dojo.html");
	dojo.ready(function(){		
		co_id = dijit.byId('co_id').get('value');
		dijit.byId('start_date').set('value','<?php echo date("Y-m-d",strtotime($this->rsearch['start_date']));?>');
		
		if(co_id>0){
			document.getElementById('lbl_customer').innerHTML=dijit.byId('co_id').attr('displayedValue');;
		}
	});
function popupCheckCO(){
}
function CalculateDate(){
	
}
</script>