<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?></title>
<div class="reportblog">
	<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_LOAN_COLLECT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form method="post">
			<div class="card-box">
				<div class="form-group">
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('adv_search');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('branch_id');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('co_id');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('member');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('pay_every');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<select class='fullside' name="status" id="status" dojoType="dijit.form.FilteringSelect">
							<option value="-1" <?php if($this->statusopt==-1){echo "selected";}?>>ជ្រើសរើសការបង់ប្រាក់</option>
							<option value="1" <?php if($this->statusopt==1){echo "selected";}?>>បានបង់ដាច់</option>
							<option value="0" <?php if($this->statusopt==0){echo "selected";}?>>មិនទាន់បង់ដាច់</option>
						</select>
	               </div>
	            </div>
	            <div class="form-group">
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('start_date');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $filter->getElement('end_date');?>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               </div>
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               </div>
	            </div>
		</form>
		<div id="divPrint" style="width: 100%;">
				<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					ul li{text-align: center;list-style: none;line-height: 25px;  list-style-type: none;}
					td ul li{list-style: none; }
					
					table { page-break-inside:auto }
					  tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
					table.content-data{
						border-collapse:collapse;
						width:100%;
						border:1px solid #000; 
						font-family:'Times New Roman','Khmer OS Battambang';
						font-size:13px;
						white-space: nowrap;
						margin:0 auto;
					}
					table.content-data thead tr.style-head {
					   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #ccd9ff;
						text-align: center;
					}
					table.content-data tr.style-rowdata {
						font-size:12px; 
						height: 23px;
					}
					
					table.tb-footer{
						font-family: 'Times New Roman','Khmer OS Battambang'; 
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:12px;
						width:100%;
					}
					table.tb-footer tr.style-head{
						line-height: 24px; 
						text-align: center; 
						background: #ccd9ff;
					}
				.border_bottom {
				    border-bottom: 1px solid #000;
				}
				</style>
			<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="list-style:none; text-align:center; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="list-style:none;text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?></li>
			                			<li style="list-style:none;text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){?><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
			                		</ul>
			                    </td>
			                    <td width="20%"></td>
			                </tr> 
			                 
			            </table>
			        </td>
			    </tr>
			    <?php if(!empty($this->loanrelease_list)){?>
			    <tr>
			    	<td id="exportExcel">
			            <table class="content-data"  border="1"​  cellspacing="0">
			                   <?php  
			                    $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
			                    $co_id='';$other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
			                    $all_total_r=0;$all_total_b=0;$all_total_d=0;$num=1;
			                    $count_ld = 0;$count_lr=0;$count_lb=0;$tcount_ld=0;$tcount_lr=0;$tcount_lb=0;
			                    
			                    $monthDolar=0;
			                    $weekDolar=0;
			                    $dayDolar=0;
			                    
			                    $monthRiel=0;
			                    $weekRiel=0;
			                    $dayRiel=0;
			                    
			                    $monthBath=0;
			                    $weekBath=0;
			                    $dayBath=0;
			                    
			                    $tmonthDolar=0;
			                    $tweekDolar=0;
			                    $tdayDolar=0;
			                     
			                    $tmonthRiel=0;
			                    $tweekRiel=0;
			                    $tdayRiel=0;
			                     
			                    $tmonthBath=0;
			                    $tweekBath=0;
			                    $tdayBath=0;
			                    
				                foreach($this->loanrelease_list as $key =>$row){
			               ?>
			               <?php if($row['curr_type']==1){
			               	$all_total_r=$all_total_r+$row["total_capital"];
			               	$tcount_lr=$tcount_lr+1;
			               	
			               }elseif($row['curr_type']==2){
			               		$all_total_d=$all_total_d+$row["total_capital"];
			               		
			               		$tcount_ld=$tcount_ld+1;
			               }else{
			               		$all_total_b=$all_total_b+$row["total_capital"];
			               		$tcount_lb=$tcount_lb+1;
			               };
			               ?>
			                <?php 
			                if($co_id!=$row['co_id']){
			                	$num=1;
			                ?>
			                <?php if($key>0){?>
							
							
							
			                <tr>
			                	<td colspan="13" style=" border-left: #ffff solid 1px; border-right: #ffff solid 1px;">&nbsp;</td>
			                </tr>
			                <tr style=" border: #ffff solid 1px;">
			                	<td colspan="13">
		                			<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
		                				<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
						                     <td rowspan="2" align="right">&nbsp;</td>
						                     <td rowspan="2">&nbsp;</td>
						                     <td colspan="4" align="center"><span class="border_bottom"><?php echo $tr->translate("FOR_LOAN_TYPE");?></span></td>
						                     <td rowspan="2">&nbsp;</td>
						                     
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_AMOUNT");?></span>&nbsp;</td>
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_FEE");?></span></td>
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("OTHER_FEE");?></span></td>
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
						                    
						                     <td rowspan="2" align="right">&nbsp;</td>
						                 </tr>
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
						                   	<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
					                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("WEEK");?></span></td>
					                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
					                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
						                 </tr>
				                 
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
						                    <td align="right"></td>
						                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
						                    <td align="center"><?php echo $monthDolar;?></td>
						                 	<td align="center"><?php echo $weekDolar;?></td>
						                    <td align="center"><?php echo $dayDolar;?></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_ld;?>&nbsp;</td>
						                    <td>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($other_fee_d,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
						                    <td align="right">&nbsp;</td>
						                 </tr>
			                
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
						                    <td align="right"></td>
						                    <td align="right"><?php echo $tr->translate("REILS");?></td>
						                    <td align="center"><?php echo $monthRiel;?></td>
						                 	<td align="center"><?php echo $weekRiel;?></td>
						                    <td align="center"><?php echo $dayRiel;?></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_lr;?>&nbsp;</td>
						                    <td>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
						                     <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($other_fee_r,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
						                    <td align="right">&nbsp;</td>
						                 </tr>
			                
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
						                    <td align="right"></td>
						                    <td align="right"><?php echo $tr->translate("BATH");?></td>
						                    <td align="center"><?php echo $monthBath;?></td>
						                 	<td align="center"><?php echo $weekBath;?></td>
						                    <td align="center"><?php echo $dayBath;?></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_lb;?>&nbsp;</td>
						                    <td>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($other_fee_b,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
						                    <td align="right">&nbsp;</td>
						                 </tr>
					               		 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px; border-top: 4px double #000 !important;">
						                    <td align="right"></td>
						                    <td align="right"></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthDolar+$monthRiel+$monthBath;?>&nbsp;</td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $weekDolar+$weekRiel+$weekBath;?>&nbsp;</td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $dayDolar+$dayRiel+$dayBath;?>&nbsp;</td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthDolar+$monthRiel+$monthBath+$weekDolar+$weekRiel+$weekBath+$dayDolar+$dayRiel+$dayBath;?>&nbsp;</td>
						                    <td colspan="6">&nbsp;</td>
						                 </tr>
						            </table>
			                	</td>
			                </tr>
							
			                </table>
			                    <br />
			                <table border="1"​ class="content-data"  cellspacing="0">
			                
			                <?php  $count_ld=0;$count_lr=0;$count_lb=0; 
			                
			                $monthDolar=0;
			                $weekDolar=0;
			                $dayDolar=0;
			                 
			                $monthRiel=0;
			                $weekRiel=0;
			                $dayRiel=0;
			                 
			                $monthBath=0;
			                $weekBath=0;
			                $dayBath=0;
			                } 
				                $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
				                $other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
			                ?>
			             <?php ?>
			                <thead>
			                <tr>
			                	<td colspan="13" class="style" style="background:#a0baf5;">&nbsp;<span style="text-align:center;"><?php //echo $tr->translate("CO_NAME");?> </span><?php  echo $row['co_code'].' , '.$row['co_name'].' - '.$row['co_name_en'].' '//.($row['sex']=1?'ភេទ ប្រុស':'ភេទ  ស្រី'); ?></td>
			                </tr>
			                 <tr class="style-head" >
			                   <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("LOAN_LEVEL");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("INTEREST RATE");?>%&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("AMIN_FEE");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
			                   <td>&nbsp;<?php echo $tr->translate("LOAN_TYPE");?>&nbsp;</td>
			                </tr>
			                </thead>
			                <?php }
			              
			                $co_id = $row['co_id'];
			                ?>
			               <?php 
			               if($row['curr_type']==1){
			               		$amt_r = $amt_r+$row['total_capital'];
			               		$amn_r = $amn_r+$row['admin_fee'];
			               		$other_fee_r=$other_fee_r+$row['other_fee'];
			               		$total_r=$amt_r+$amn_r+$other_fee_r;
			               		
			               		$count_lr=$count_lr+1;
			               		//$count_lr=$count_lr+1;
			               		
			               		if($row['pay_term_id']==1){
			               			$dayRiel=$dayRiel+1;
			               			$tdayRiel=$tdayRiel+1;
			               		}elseif($row['pay_term_id']==2){
			               			$weekRiel=$weekRiel+1;
			               			$tweekRiel=$tweekRiel+1;
			               		}else{
			               			$monthRiel = $monthRiel+1;
			               			$tmonthRiel = $tmonthRiel+1;
			               		}
			               		
			               }elseif($row['curr_type']==2){
			               		$amt_d = $amt_d+$row['total_capital'];
			               		$amn_d = $amn_d+$row['admin_fee'];
			               		$other_fee_d=$other_fee_d+$row['other_fee'];
			               		$total_d=$amt_d+$amn_d+$other_fee_d;
			               		//$count_ld=$count_ld+1;
			               		$count_ld=$count_ld+1;
			               		
			               		if($row['pay_term_id']==1){
			               			$dayDolar=$dayDolar+1;
			               			$tdayDolar=$tdayDolar+1;
			               		}elseif($row['pay_term_id']==2){
			               			$weekDolar=$weekDolar+1;
			               			$tweekDolar=$tweekDolar+1;
			               		}else{
			               			$monthDolar = $monthDolar+1;
			               			$tmonthDolar = $tmonthDolar+1;
			               		}
			               		
			               }else{
			               		$amt_b = $amt_b+$row['total_capital'];
			               		$amn_b = $amn_b+$row['admin_fee'];
			               		$other_fee_b=$other_fee_b+$row['other_fee'];
			               		$total_b=$amt_b+$amn_b+$other_fee_b;
			               		//$count_lb=$count_lb+1;
			               		
			               		$count_lb=$count_lb+1;
			               		
			               		if($row['pay_term_id']==1){
			               			$dayBath=$dayBath+1;
			               			$tdayBath=$tdayBath+1;
			               		}elseif($row['pay_term_id']==2){
			               			$tweekBath=$tweekBath+1;
			               		}else{
			               			$tmonthBath = $tmonthBath+1;
			               		}
			               }
			               ?>
								<tr class="style-rowdata hover" align="center" >
									<td>&nbsp;<?php echo $num; $num++;?>&nbsp;</td>
									<td style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
									<td align="left">&nbsp;<?php echo $row['client_number']; ?>&nbsp;</td>
									<td align="left">&nbsp;<?php echo $row['client_khname']; ?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['level'];?>&nbsp;</td>
									<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
									<td >&nbsp;<?php echo $row['interest_rate']; ?>&nbsp;</td>
									<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['admin_fee'],2).' '.$row['currency_type']?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['total_duration'].$row['name_en'];?>&nbsp;</td>
									<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?>&nbsp;</td>
									<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_line']));?>&nbsp;</td>
									<td>&nbsp;<?php echo $row['loan_type'];?>&nbsp;</td>
									
								</tr>
							<?php } //echo $a;?>
							 <tr>
			                	<td colspan="13" style=" border-left: #ffff solid 1px; border-right: #ffff solid 1px;">&nbsp;</td>
			                </tr>
			            	 <tr style=" border: #ffff solid 1px;">
			                	<td colspan="13">
		                			<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
		                				<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
						                     <td rowspan="2" align="right">&nbsp;</td>
						                     <td rowspan="2">&nbsp;</td>
						                     <td colspan="4" align="center"><span class="border_bottom"><?php echo $tr->translate("FOR_LOAN_TYPE");?></span></td>
						                     <td rowspan="2">&nbsp;</td>
						                     
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_AMOUNT");?></span>&nbsp;</td>
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL_FEE");?></span></td>
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("OTHER_FEE");?></span></td>
						                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
						                    
						                     <td rowspan="2" align="right">&nbsp;</td>
						                 </tr>
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
						                   	<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
					                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("WEEK");?></span></td>
					                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
					                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
						                 </tr>
				                 
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
						                    <td align="right"></td>
						                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
						                    <td align="center"><?php echo $monthDolar;?></td>
						                 	<td align="center"><?php echo $weekDolar;?></td>
						                    <td align="center"><?php echo $dayDolar;?></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_ld;?>&nbsp;</td>
						                    <td>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($other_fee_d,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
						                    <td align="right">&nbsp;</td>
						                 </tr>
			                
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
						                    <td align="right"></td>
						                    <td align="right"><?php echo $tr->translate("REILS");?></td>
						                    <td align="center"><?php echo $monthRiel;?></td>
						                 	<td align="center"><?php echo $weekRiel;?></td>
						                    <td align="center"><?php echo $dayRiel;?></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_lr;?>&nbsp;</td>
						                    <td>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
						                     <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($other_fee_r,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
						                    <td align="right">&nbsp;</td>
						                 </tr>
			                
						                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
						                    <td align="right"></td>
						                    <td align="right"><?php echo $tr->translate("BATH");?></td>
						                    <td align="center"><?php echo $monthBath;?></td>
						                 	<td align="center"><?php echo $weekBath;?></td>
						                    <td align="center"><?php echo $dayBath;?></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $count_lb;?>&nbsp;</td>
						                    <td>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($other_fee_b,2);?>&nbsp;</td>
						                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
						                    <td align="right">&nbsp;</td>
						                 </tr>
					               		 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px; border-top: 4px double #000 !important;">
						                    <td align="right"></td>
						                    <td align="right"></td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthDolar+$monthRiel+$monthBath;?>&nbsp;</td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $weekDolar+$weekRiel+$weekBath;?>&nbsp;</td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $dayDolar+$dayRiel+$dayBath;?>&nbsp;</td>
						                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $monthDolar+$monthRiel+$monthBath+$weekDolar+$weekRiel+$weekBath+$dayDolar+$dayRiel+$dayBath;?>&nbsp;</td>
						                    <td colspan="6">&nbsp;</td>
						                 </tr>
						            </table>
			                	</td>
			                </tr>
			              </table>
			             <div style="border:1px dashed #000;margin:10px 0px; "><strong>Total Only Loan Disbursed</strong></div>
			    	</td>
			   		</tr>
			     	<tr>
			     		<td>
			     			<table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
			     				<tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                     <td rowspan="2" align="right">&nbsp;</td>
				                     <td rowspan="2">&nbsp;</td>
				                     <td colspan="4" align="center"><span class="border_bottom"><?php echo $tr->translate("FOR_LOAN_TYPE");?></span></td>
				                     <td rowspan="2">&nbsp;</td>
				                     <td rowspan="2" align="right"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span>&nbsp;</td>
				                     <td rowspan="2" align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                   	<td align="center"><span class="border_bottom"><?php echo $tr->translate("MONTH");?></span></td>
			                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("WEEK");?></span></td>
			                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("DAY");?></span></td>
			                    	<td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("DOLLAR");?></td>
				                    <td align="center"><?php echo $tmonthDolar;?></td>
				                 	<td align="center"><?php echo $tweekDolar;?></td>
				                    <td align="center"><?php echo $tdayDolar;?></td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tcount_ld;?>&nbsp;</td>
				                     <td>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($all_total_d,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("REILS");?></td>
				                    <td align="center"><?php echo $tmonthRiel;?></td>
				                 	<td align="center"><?php echo $tweekRiel;?></td>
				                    <td align="center"><?php echo $tdayRiel;?></td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tcount_lr;?>&nbsp;</td>
				                    <td>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($all_total_r,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; padding:2px 0px; height: 25px;">
				                    <td align="right"></td>
				                    <td align="right"><?php echo $tr->translate("BATH");?></td>
				                    <td align="center"><?php echo $tmonthBath;?></td>
				                 	<td align="center"><?php echo $tweekBath;?></td>
				                    <td align="center"><?php echo $tdayBath;?></td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tcount_lb;?>&nbsp;</td>
				                    <td>&nbsp;</td>
				                    <td align="right" style="font-weight:bold;">&nbsp;<?php echo number_format($all_total_b,2);?>&nbsp;</td>
				                    <td align="right">&nbsp;</td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;padding:2px 0px;height: 25px; border-top: 4px double #000 !important;">
				                    <td align="right"></td>
				                    <td align="right"></td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tmonthDolar+$tmonthRiel+$tmonthBath;?>&nbsp;</td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tweekDolar+$tweekRiel+$tweekBath;?>&nbsp;</td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo $tdayDolar+$tdayRiel+$tdayBath;?>&nbsp;</td>
				                    <td align="center" style="font-weight:bold;">&nbsp;<?php echo count($this->loanrelease_list);?>&nbsp;</td>
				                    <td colspan="3">&nbsp;</td>
				                 </tr>
				            </table>
            
			              <br />
			               <?php echo $this->footerReport;?> 
			        </td>
			       </tr>   
			       <?php }?>
			</table>
	</div>
</div>
