<?php 
	$tran = $this->tran_schedule;
	$client = $this->client;
	$filter = $this->form_filter;
	$dayin_khmer = $this->day_inkhmer;
	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_barcode = $this->url(array("module"=>"loan","controller"=>"ilpayment","action"=>"generatebarcode","loan_code"=>$client['loan_number']),null,true);																							

?>
<title><?php echo $tr->translate('REPORT WEEK');?></title>
<style>
td p{ margin-top:0px !important;}
.hover:hover{ background:#ccc;}
table.content-data  tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div style=" width:26cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
	<table width="100%">
  		<tr>
  			<td align="left" width="25%">
  				<div class="card-box" id="hideStampSetting">
  					<label class="control-label custom-switch float-end ">
  						<a href="javascript:void(0);" class="switchButton status"><span class="glyphicon glyphicon-pawn"></span> &nbsp; <?php echo $tr->translate("SHOW_HEADER"); ?></a>
  						<input type="checkbox" id="stamp" name="stamp" class="custom-switch-input" onclick="stampDisplay()" checked>
  						<span class="custom-switch-indicator custom-radius switch-status"></span>
  					</label>
  				</div>
  			</td>
  			<td align="right"></td>
  		</tr>
  	</table>
	<div id="divPrint">
		<style type="text/css">
			.style{
				line-height: 20px;font-size: 13px;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			.font_bold{
				font-family:'Khmer MEF2';
				font-size: 12px;
			}
			td p{ margin-top:-12px;}
			p{margin: 0 00px !important;}
			table.content-data{	
				border-collapse:collapse;
				width:100%;
				border:1px solid #000; 
				font-family:'Times New Roman','Khmer OS Battambang';
				font-size:13px;
				white-space: nowrap;
				margin:0 auto;
			}
			table.content-data  tr.style-head {
			   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
				text-align: center;
			}
			table.content-data tr.style-rowdata {
				font-size:12px; 
				height: 23px;
			}
			table.tb-footer{
				font-family: 'Times New Roman','Khmer OS Battambang'; 
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:12px;
				width:100%;
			}
			table.tb-footer tr.style-head{
				line-height: 24px; 
				text-align: center; 
				background: #ccd9ff;
			}
		</style>
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center" >
	        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Muol Light';margin:0 auto;padding:0px; border:none;">
					<tr id="header">
	                	  <td style=" " valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" /> </td>
	                	  <td colspan="2" align="left" >
	                	  <h2 style="font-weight:normal; text-align:left; font-size:12px; font-family:'Khmer os battambang';"><?php echo $client['branchAddress'];//$tr->translate("ADDRESS_COMPANY");?>
	                	  	<br /><?php echo $tr->translate("PHONE")." : ".$client['branchTel'];//$tr->translate("TEL_COMPANY");?>
	                	  </h2>
	                	  </td>
	                </tr >
	                <tr >
	                	<td colspan="3" align="center">
	                		<h2 style="font-weight:normal; text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('rpt-paymentschedule');?> <?php echo ($client['loan_type']==1)?$tr->translate('RPT_ILLOAN'):$tr->translate('RPT_GROULOAN') ;?></h2>
	               		</td>
	                </tr> 
	                <?php 
	                	  $db = new Application_Model_DbTable_DbGlobal();
	                	  $row = $db->getClientByType(null,$client['client_id'],1);
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%" style="font-family:">
			                	<tr style="font-size:15px;line-height: 25px;font-family:'Times New Roman','Khmer OS Battambang'" >
				                   <td width="35%">
				                   		<p> <?php echo "<span>". $tr->translate('CLIENT_NO')."</span> : ".$client['client_number']?></p>
				                	    <p><span><?php echo $tr->translate('CUSTOMER_NAME');?></span>: <?php echo ($client['displayclient']==1)? $client['client_name_kh']: $client['client_name_en'] ;?> </p>
				                		<p><?php echo "<span>",$tr->translate("TEL")."</span>";?> : <?php echo $client['client_phone'];?></p>
				                	</td>
				                    <td valign="top" style="" width="33%">
				                        <p><?php echo $tr->translate("សងរំលស់");?> : <?php echo $client['total_duration']." ".Application_Model_DbTable_DbGlobal::getPaymentTermById($client['pay_term']); ?></p>
				                        <p><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម ");?> : <?php echo date('d-m-Y',strtotime($client['date_release']));?> </p>
				                    	<p><?php echo $tr->translate("FIRST_PAYMENT");?> : <?php echo date('d-m-Y',strtotime($client['first_payment'])); ?></p>
				                    </td>
				                    <td valign="top">
				                   	  <p><?php echo $tr->translate("LOAN_NO");?> : <b><?php echo $client['loan_number'];?></b></p>
				                      <p><?php //echo $tr->translate("INTEREST")." : ".$client['interest_rate']." %"?> </p>
				                      <p><?php echo $tr->translate("LOAN_AMOUNT");?>  : <?php echo number_format($client['total_capital'],(!strrpos($client['total_capital'],". "))? 0 : 2);echo '&nbsp;'.$client['currency_type'];?></p>
				                      <p><?php echo $tr->translate("LEVEL");?> : <?php echo $client['level'];?></p>
				                    </td>
				                </tr>
				                <tr style="font-size:15px;font-family:'Times New Roman','Khmer OS Battambang'" >
				                	<td colspan="2">
				                		<p style="padding-top:8px;"><span><?php echo $tr->translate("ADDRESS");?></span>:<?php echo $row['village_name'];?> ,<?php echo $row['commune_name'];?> <?php echo $row['district_name'];?> ,  <?php echo $row['province_en_name'];?>
				                	</td>
				                	<td></td>
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel" class="content-data"  border="1"​ >
	                 <tr class="style-head" align="center" style="line-height: 40px;">
	                    <td><?php echo $tr->translate("NUM");?></td>
	                    <td><?php echo $tr->translate("ថ្ងៃ-ខែ-ឆ្នាំ");?></td>
	                    <td><?php echo $tr->translate("AMOUNT_DATE");?></td>
						<?php if($client['pay_term']!=1){?>
	                    <td><?php echo $tr->translate("PRINCIPLE");?></td>
	                    <td><?php echo $tr->translate("OS_AMOUNT");?></td>
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
						<?php } ?>
	                    <td><?php echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?></td>
	                    <!--<td><?php //echo $tr->translate("PENALIZE AMOUNT");?></td> -->
	                    <td><?php echo $tr->translate("OTHER");?></td>
	                </tr>
	               <?php 
	               $is_panelty=0;
	               $record=0;
	               if(!empty($tran)) foreach($tran as $key =>$row){?>
	               	
               		<?php if($row['is_completed']==1 and $row['status']==0){?>
               			<?php if($row['saving_amount']>0){//ខ្ចីថែម?>
	               			<tr>
	               				<td colspan="9" align="center" style="font-family: Khmer OS Battambang;font-size: 14px;background:#c5c5ff;font-weight: bold;"><?php echo !empty($row['old_loanid'])?$row['old_loanid']:"អតិថិជនបានខ្ចីបន្ថែមចំនួន";?> <?php echo $row['principal_permonth'];?> នៅថ្ងៃទី <?php echo date("d-m-Y",strtotime($row['date_payment']));?> </td>
	               			</tr>
               			<?php }else{//បានរំលស់ប្រាក់ដើម?>
	               			<tr>
	               				<td colspan="9" align="center" style="font-family: Khmer OS Battambang;font-size: 14px;">អតិថិជនបានបង់ប្រាក់រំលស់ដើមចំនួន <?php echo $row['principal_permonth'];?> នៅថ្ងៃទី <?php echo date("d-m-Y",strtotime($row['date_payment']));?> </td>
	               			</tr>
               			<?php }?>
               		<?php }else{?>
		               	<tr class="style-rowdata hover" align="center" style=" height: 20px;" >
		                    <td><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
		                    <?php $str_day = date('D',strtotime($row['date_payment']));
		                    	$day_as_khmer = $dayin_khmer[$str_day];
		                    ?>
		                    <td align="left">&nbsp;<?php echo $day_as_khmer; ?>&nbsp;<?php 
		                    //echo date('d-m-Y',strtotime($row['date_payment']));
		                    $date = new DateTime($row['date_payment']);
		                    echo $date->format("d-m-Y");
		                    
		                    ?></td>
		                    <td><?php echo $row['amount_day'];?></td>
							<?php if($client['pay_term']!=1){?>
		                    <td><?php echo number_format($row['outstanding'],2);?></td>
		                    <td><?php echo number_format($row['principal_permonth'],2);?></td>
		                    <td><?php echo number_format($row['total_interest'],2);?></td>
							<?php } ?>
		                    <td style="font-family:'arial';font-size:12px;font-weight: bold;"><?php echo number_format($row['total_payment'],2); ?></td>
		                    <td style="font-family:'arial';font-size:12px;font-weight: bold;"><?php if($row['is_penalty']==1){ echo number_format($row['total_interest'],2);}?></td>
		                    <td><?php echo ($row['is_completed']==1)?"បង់ដាច់":""?></td>
		                </tr>
	               <?php }}
	               	if(!empty($record))for($record = $key;$record<11;$record++){
	               ?>
	               		<tr>
	               			<td>&nbsp;</td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
							<?php if($client['pay_term']!=1){?>
	               			<td></td>
	               			<td></td>
	               			<td></td>
							<?php }?>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               		</tr>
	               <?php }?>
	            </table>
	            <table>
	            	<tr>
	            		<td align="left" style="font-size: 12px;" > <?php echo $tr->translate("NOTED_SCHEDULE");?></td>
	            	</tr>
	            </table>
	            <table width="100%" cellpadding="3">
	            	<tr class="font_bold" style="height:25px;">
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('ACCOUNTING_SIGN');?></td>
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('ភ្នាក់ងារឥណទាន'); ?></td> 
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('BORROWER');?></td>
	            	</tr>
	            	<tr>
	            		<td height="40px">&nbsp;</td>
	            	</tr>
	            	<tr class="font_bold">
	            		<td align="center" height="80px" valign="bottom" style="font-size:15px;font-family:'Times New Roman','Khmer OS Battambang'"><?php echo $client['user_name'];?></td>
	            		<td align="center"  valign="bottom" style="font-size:15px;line-height: 30px;font-family:'Times New Roman','Khmer OS Battambang'" >
	            			<?php echo $client['co_khname'];?>
	            			<p><?php echo $tr->translate("TEL");?>  : <?php echo $client['tel'];?></p>   
	            		</td>
	            		<td align="center" height="75px" valign="bottom" style="font-size:15px;font-family:'Times New Roman','Khmer OS Battambang'">
	            			<?php echo ($client['displayclient']==1)? $client['client_name_kh']: $client['client_name_en'] ;?></td>
	            	</tr>
	            </table>
	    	</td>
	    </tr>
	</table>
	</div>
	
</div>
<script src="<?php echo $this->baseUrl(); ?>/js/help.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/admin/js/global.js" type="text/javascript"></script>
  <script type="text/javascript">
  	dojo.require("dojo.NodeList-manipulate");
  	dojo.require("dojo.data.ItemFileWriteStore");
  	dojo.ready(function() {
  		//dutySetting();
  	});
 

  	// function dutySetting() {

  	// 	<?php //if ($footerScoreDocument == 0) { ?>

  	// 		document.getElementById("stamp").checked = false;
  	// 		stampDisplay();
  	// 		var hideStampSetting = document.getElementById("hideStampSetting");
	// 		var teacher = document.getElementById("teachersigature");
	// 		var administrator = document.getElementById("administrator");

	// 		teacher.style.display = "block";
	// 		administrator.style.display = "block";

  	// 		hideStampSetting.style.display = "none";

  	// 	<?php //} else { ?>
  	// 		document.getElementById("stamp").checked = true;
  	// 		stampDisplay();
  	// 	<?php //} ?>

  	// }

  	function stampDisplay() {
  		var checkBox = document.getElementById("stamp");
  		var header = document.getElementById("header");

  		if (checkBox.checked == true) {
			header.style.display = "block";
  		} else {
			header.style.display = "none";
  		}
  	}
  </script>