<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("LOAN_RESCHEDULE"));
	$frm = $this->frm_search;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-calendar"></i>&nbsp;<?php echo $tr->translate('LOAN_RESCHEDULE');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("member");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("repayment_method");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="category_id" />
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("completed_status");?>
			   		</div>
				</div>
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<select dojoType="dijit.form.FilteringSelect" class="fullside"  name="selling_type" id="selling_type" >
		 					<option value="-1"><?php echo $tr->translate('ជ្រើសរើសប្រភេទលក់');?></option>
		 					<option value="1"><?php echo $tr->translate('ទិញដាច់');?></option>
		 					<option value="2"><?php echo $tr->translate('បង់រំលស់');?></option>
		 				</select>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 

	function getmemberIdGroup(){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}
	function checkMember(){
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}	
	var cate_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_cate));?> );
	dojo.ready(function(){		
		 new dijit.form.FilteringSelect({
				store: cate_store,
				required: false,		           
				name: "category_id",
				id: "category_id",
				searchAttr: "name",
				autoComplete: false,
				queryExpr: "*${0}*",
				value:"<?php echo $this->rs['category_id'];?>",
				class: 'fullside',
				onChange: function() {
				}
		}, "category_id");
	});
</script>