<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
echo $this->headTitle($tr->translate("ADD_INTEREST"));
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-businessplan"></i>&nbsp;<?php echo $tr->translate('ADD_INTEREST');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'interest','action'=>'add')); ?>" dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					dijit.byId("save_close").set("disabled",true);
					dijit.byId("save_new").set("disabled",true);
					loadingBlock();
					return true;
				}else {
				   
					return false;
				}
			</script>
			<div class="card card-form mb-4">
				<div class="card-header d-flex justify-content-between">
					<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("INTEREST_INFORMATION");?></h5>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_LABEL_ONE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('inter_one')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_VALUE_ONE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest1')?>
							   </div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_LABEL_TWO");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('inter_two')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_VALUE_TWO");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest2')?>
							   </div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_LABEL_THREE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('inter_three')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_VALUE_THREE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest3')?>
							   </div>
							</div>
						</div>
					</div>
				</div>
			 </div>
			 <div class="card card-form mb-4">
				<div class="card-header d-flex justify-content-between">
					<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("INTEREST_INFORMATION");?></h5>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_LABEL_FOUR");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('inter_four')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_VALUE_FOUR");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest4')?>
							   </div>
							</div>
						</div>
				 </div>
	         </div>
	         <div class="card-box">
				<div class="col-sm-12 border-top mt-2 py-2 text-center">
	    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"   /> 
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" onclick="submitDataClose()" value="បិទ" label="<?php echo $tr->translate("SAVECLOSE")?>" name="save_close" id="save_close" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="រក្សាទុកថ្មី" label="<?php echo $tr->translate("SAVENEW")?>" name="save_new" id="save_new" dojoType="dijit.form.Button" />
	    		</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

dojo.ready(function(){
	dijit.byId('dollar_current').set('readOnly',true);
	dijit.byId('bath_current').set('readOnly',true);
	dijit.byId('reil_current').set('readOnly',true);
});

var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'capitaltransfer','action'=>'getamountbybranceid'));?>'; 
function getAmounts(){
	var brance_id = dijit.byId('brance').get('value');
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance').get('value'),
		},	
		handleAs:"json",
		load: function(respone) {
			for(i=0;i<respone.length;i++){
				if(respone[i].account_id==1){
					dijit.byId('dollar_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bath_current').attr('value',respone[i].amount_bath);
					dijit.byId('reil_current').attr('value',respone[i].amount_riel);
				}else{
					dijit.byId('dollarbank_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bathbank_current').attr('value',respone[i].amount_bath);
					dijit.byId('reilbank_current').attr('value',respone[i].amount_riel);
					}
		   }
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function statusCheck(){
	var status = dijit.byId('status').get('value');
	if(status == -1){
		alert("សូមមេត្តាជ្រើសរើសស្ថានភាពយ៉ាងហោចមួយ!!");
	}
}

function submitDataClose(){
	if(dijit.byId('frm_add').validate()) {
		dijit.byId("save_close").set("disabled",true);
		dijit.byId("save_new").set("disabled",true);
		var url_submit = '<?php echo $this->url(array('module'=>'capital','controller'=>'interest','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/capital/interest";
			},
			error: function(e) {
			}
		});
	}
}

</script>
