<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
echo $this->headTitle($tr->translate("ADD_OTHER_INCOME"));
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.td{width:128px !important;} 
.tds{width:155px !important;}
</style>
<center>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom" style="text-align: left;">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_INTEREST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'interest','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('brance').get('value');
				if(branch_id==0){alert("សូមជ្រើសរើសសាខា");dijit.byId('brance').focus();return false;}
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_LABEL");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('inter_one')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_VALUE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('interest1')?><?php echo $frm->getElement('id')?>
	                   </div>
	                </div>
	                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="submit" value="បោះបង់" label="<?php echo $tr->translate("CANCEL")?>" name="cancel" id="cancel" dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
						<input type="submit" value="កែប្រែ" label="<?php echo $tr->translate("UPDATE")?>" name="save" id="save" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
		    		</div>
	           	</div>
	        </div>
		</form>
	</div>
</div>

</center>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

dojo.ready(function(){
	dijit.byId('dollar_current').set('readOnly',true);
	dijit.byId('bath_current').set('readOnly',true);
	dijit.byId('reil_current').set('readOnly',true);
});

var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'capitaltransfer','action'=>'getamountbybranceid'));?>'; 
function getAmounts(){
	var brance_id = dijit.byId('brance').get('value');
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance').get('value'),
		},	
		handleAs:"json",
		load: function(respone) {
			for(i=0;i<respone.length;i++){
				if(respone[i].account_id==1){
					dijit.byId('dollar_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bath_current').attr('value',respone[i].amount_bath);
					dijit.byId('reil_current').attr('value',respone[i].amount_riel);
				}else{
					dijit.byId('dollarbank_current').attr('value',respone[i].amount_dollar);
					dijit.byId('bathbank_current').attr('value',respone[i].amount_bath);
					dijit.byId('reilbank_current').attr('value',respone[i].amount_riel);
					}
		   }
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function statusCheck(){
	var status = dijit.byId('status').get('value');
	if(status == -1){
		alert("សូមមេត្តាជ្រើសរើសស្ថានភាពយ៉ាងហោចមួយ!!");
	}
}

</script>
