<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("INTEREST"));
$frm = $this->frm;
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-businessplan"></i>&nbsp;<?php echo $tr->translate('INTEREST');?></h5>
		
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>



