<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Edit Currency'));
	echo $this->headTitle();
	$frm = $this->frmcurrency;
	$row = $this->row;
?>	
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('Edit Currency');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
 					dijit.byId("save_close").set("disabled",true);
					dijit.byId("save_new").set("disabled",true);
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Currency KH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('curr_namekh');?>
	                   		<input type="hidden" value="<?php echo $row['id'];?>" class="fullside" readonly="readonly" required="required" id="id" name="id" dojoType="dijit.form.TextBox" />
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Currency EN");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('curr_nameen');//echo $frm->getElement('for_date');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SYMBOL");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('symbol');//echo $frm->getElement('for_date');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('status');?>
	                   </div>
	                </div>
	                <div class="col-sm-12 border-top mt-2 py-2 text-center">
		    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"   label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" />
		    		</div>
	            </div>
	       	</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require('dijit.form.Form');
dojo.require('dijit.form.Button');
dojo.require('dijit.form.NumberTextBox');
dojo.require("dijit.Dialog");
</script>
	
	