<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Currency'));
	echo $this->headTitle();
	$frm = $this->frm_search;
?>	

<script>
dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form method="post">
				<div class="form-group">
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<select class="fullside" style="text-align: left;"  name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true">
								<option value="-1" <?php echo (-1 == $this->list_search['status'])?"selected":"";?>><?php echo $tr->translate("All Status");?></option> 
								<option value="1" <?php echo (1 == $this->list_search['status'])?"selected":"";?>><?php echo $tr->translate("ACTIVE");?></option>
								<option value="0" <?php echo (0 == $this->list_search['status'])?"selected":"";?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select><!-- onchange="document.frmlist_mt.submit();" -->
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   					</div>
   				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>

