<?php
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Currency'));
	echo $this->headTitle();
	$frm = $this->frm_search;
?>	
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-money"></i>&nbsp;<?php echo $tr->translate('Currency');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
   						<select class="fullside" style="text-align: left;"  name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true">
								<option value="-1" <?php echo (-1 == $this->list_search['status'])?"selected":"";?>><?php echo $tr->translate("All Status");?></option> 
								<option value="1" <?php echo (1 == $this->list_search['status'])?"selected":"";?>><?php echo $tr->translate("ACTIVE");?></option>
								<option value="0" <?php echo (0 == $this->list_search['status'])?"selected":"";?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select><!-- onchange="document.frmlist_mt.submit();" -->
   					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
</script>

