<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_PURCHASE')); 
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>	
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/Dialog"]);
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-shopping-cart " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_PURCHASE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='suspend_service' action="<?php echo $this->url(array('module'=>'installment','controller'=>'purchase','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
 				pro_id=dijit.byId("pro_id").get('value');
				if(pro_id=='' || pro_id==null){
					dijit.byId("pro_id").focus();
					return false;
				}
                dijit.byId("save_close").attr("disabled",true);
				dijit.byId("save_new").attr("disabled",true);
				return true;
			} else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("SUPPLIER_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
	                   <label class="control-label bold col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("OLD_SUPPLIER");?> 
	                   	<input style=" padding: 0; margin: 0; height: auto;" type="checkbox" checked="checked" name="is_new_cu" id="is_new_cu" value="1" onClick="isNewCustomer()" >
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SUPPLIER_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<span id="new_cu">
					   			<input type="text" dojoType="dijit.form.ValidationTextBox" name="supplier_name"  id="supplier_name" value="" class="fullside" required="required">
					   		</span>
					   		<span id="old_cu">
					   			<select dojoType='dijit.form.FilteringSelect' autoComplete="false" queryExpr="*${0}*", id="sup_id" name="sup_id" onChange="getSuplierInfo();" class="fullside" required="false"​​  placeholder="ជ្រើសរើស ឈ្មោះអ្នកផ្គត់ផ្គង់">
						   			<option></option>
						   			<?php if(!empty($this->sup_ids)) foreach($this->sup_ids As $rs_sup){?>
						   			<option value="<?php echo $rs_sup['id'];?>"><?php echo $rs_sup['sup_name'];?></option>
						   			<?php }?>
					   			</select>
					   		</span>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Tel");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" dojoType="dijit.form.TextBox" name="phone"  id="phone" value="" class="fullside" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EMAIL");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" dojoType="dijit.form.ValidationTextBox" value=""   id="email" name="email" class="fullside" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ADDRESS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" dojoType="dijit.form.ValidationTextBox" value=""   id="address" name="address" class="fullside" />
	                   		<input type="hidden" id="identity" name="identity" />
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PURCHASE_INFO");?> 
	                   </label>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="branch"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="purchase_date" name="purchase_date" value="<?php echo date("Y-m-d");?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INVOICE_NO");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" dojoType="dijit.form.TextBox"   name="purchase_no"  id="purchase_no" value="<?php echo $this->pu_code;?>" class="fullside" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AMOUNT_DUE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" dojoType="dijit.form.ValidationTextBox" value=""   id="amount_due" name="amount_due" class="fullside" readOnly="true"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ITEM_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="pro_id" name="pro_id" />
	                   </div>
	                </div>
						
	            </div>
	        </div>
	        <div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	    			<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="button" onclick="submitDataClose();" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVECLOSE');?>"  dojoType="dijit.form.Button" 
					 iconClass="dijitEditorIcon dijitEditorIconSave" />
				 	<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVENEW');?>"  dojoType="dijit.form.Button" 
						 iconClass="dijitEditorIcon dijitEditorIconSave" />
	    		</div>
			</div>
			<div class="card-box">
				<div class="form-group">
					<table id="table_row" border="1" style="width:100%;border-collapse: collapse; border:1px solid #ccc;">
						<tr id="head-title" class="head-td" align="right"></tr>
					</table>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.Dialog");
	dojo.require("dojo.data.ItemFileWriteStore");  
	var pro_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->product));?> );
	var branch_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->bran_name));?> );
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			store: pro_store,
			autoComplete: false,
			queryExpr: "*${0}*",                      
			id: "pro_id",
			name: "pro_id",  
			style:'height:40px !important',         
			class: 'fullside',  
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_PRODUCT");?>",          
			onChange: function() {  
				pro_id   = dijit.byId('pro_id').get('value');
				if(pro_id==-1){
					branch = dijit.byId("branch").get("value");
					if(branch>0){
					 	$("#location_id").val(branch);
						dijit.byId("pop_product").show();
					}else{
						alert("Please select branch !!! ");
						dijit.byId("branch").focus();
					}
				}else{
					if(pro_id==''){return false;}
					addRow();
				}
			}
		}, "pro_id");
		
		new dijit.form.FilteringSelect({
		store: branch_store,
		autoComplete: false,
		queryExpr: "*${0}*",
		id: "branch",
		name: "branch",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_LOCATION");?>​",          
		onChange: function() {  
			branch_id = dijit.byId('branch').get('value');
			if(branch_id==-1){
				dijit.byId("popup_add_branch").show();
				}
			}
		}, "branch");

		isNewCustomer();
	});	
</script>


<script type="text/javascript">
var template = '';
var product_name = '<?php //echo $this->product; ?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
	label_proname = dijit.byId("pro_id").attr('displayedValue');
	pro_id=dijit.byId("pro_id").get("value");
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("ITEM_NAME");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("QTY");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("UNIT_PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMT_PAY");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="15px" align="center"  >'+no+'</td>';
			template+='<td width="20%">&nbsp;'+label_proname+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="product_name_'+col+'" name="product_name_'+col+'" value="'+pro_id+'" /></td>';

			template+='<td> <input type="text" required="true" name="qty_'+col+'" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;" onKeyup="getTotalePricePro('+col+');sumAmountDue();"/></td>';
			template+='<td> <input type="text" required="true" name="cost_'+col+'" id="cost_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;" onKeyup="getTotalePricePro('+col+');sumAmountDue();"/></td>';
			template+='<td> <input type="text"   name="amount_'+col+'" id="amount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100%;"  readOnly="true"/></td>';
			template+='<td> <input type="text"  name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" style="width:100%;" /></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

var url_getsuplier = "<?php echo $this->url(array('module'=>'installment','controller'=>'purchase','action'=>'get-supplier-info')); ?>";
function getSuplierInfo(){
			sup_id = dijit.byId('sup_id').get('value');
			if(sup_id !=''){
				dojo.xhrPost({
					url:url_getsuplier,
					content:{
						'sup_id':sup_id
						},
					handleAs:"json",
					load: function(data) {
						dijit.byId("supplier_name").attr("value",data.sup_name);
						//dijit.byId("sex").attr("value",data.sex);
						dijit.byId("phone").attr("value",data.tel);
						//dijit.byId("email").attr("value",data.email);
						dijit.byId("address").attr("value",data.address);
					},
					error: function(err) {
						alert(err);
					}
				});
			}
}
 
function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		sumAmountDue();
}
 
function getTotalePricePro(row){
	qty_id=dijit.byId('qty_'+row).get('value');
	cost_id=dijit.byId('cost_'+row).get('value');
	amount=qty_id*cost_id;
	dijit.byId('amount_'+row).attr('value',amount);
}
function isNewCustomer(){
	is_new = $('#is_new_cu').val();
	if($('#is_new_cu').is(':checked')){
		$('#old_cu').show();
		$('#new_cu').hide();
		dijit.byId('supplier_name').attr('required', false);
	}else{
		$('#old_cu').hide();
		$('#new_cu').show();
		dijit.byId('supplier_name').attr('required', true);
	}
}
function sumAmountDue() {
	t=0;
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0; i<arrays.length; i++){
			t+=dijit.byId('amount_'+arrays[i]).get('value');
		}
		dijit.byId('amount_due').attr('value',t);
		
}
var url_add_pro = '<?php echo $this->url(array('module'=>'accounting','controller'=>'purchase','action'=>'add-product')); ?>';
var product_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->product))?>);
function addNewProduct(){
	if(dijit.byId('frm_product').validate()){
			dojo.xhrPost({
				url:url_add_pro,
				form: dojo.byId("frm_product"),
				handleAs:"json",
				load: function(data) {
					var Itemcat = {					
							id: data,
						    name: dijit.byId('product_name').get('value')
					};			
					addDataToSelectbox(dijit.byId('pro_id'), product_store, Itemcat, data);
					dijit.byId('frm_product').reset();
					dijit.byId("pop_product").hide();
				},
				error: function(err) {
					alert(err);
				}
			});
		}
}
function hideDialog(){
	dijit.byId('frm_addbranch').reset();
	dijit.byId("popup_add_branch").hide();
}
function submitDataClose(){
	pro_id=dijit.byId("pro_id").get('value');
	if(pro_id=='' || pro_id==null){
		dijit.byId("pro_id").focus();
		return false;
	}
	if(dijit.byId('suspend_service').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'installment','controller'=>'purchase','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("suspend_service"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/installment/purchase";
			},
			error: function(e) {
			}
		});
	}
}
</script>