<title>User Access</title>
<style>
fieldset.fifthy {	
	border-right: 0px;
	width: 30%;
}
fieldset.fifthy table{
	padding-right: 1px;
}
table.user td{
	vertical-align: top;   
}
table tr td{
	border:solid 1px #e4e4e4;
}
</style>       

<?php $rs=$this->rs;
	
	  $acl=($this->acl=='')? array():$this->acl;
	  $acl_name=($this->acl_name=='')? array(): $this->acl_name;
	  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	  $df=$this->data;
	  
	  $module_str = array(
	  		'home'=>'HOME_PAGE',
	  		'rsvacl'=>'ACL',
	  		'setting'=>'SETTING',
	  		'accounting'=>'ACCOUNTING',
	  		'foundation'=>'ADMINISTRATION',
	  		'global'=>'OTHER_INFOMATION',
	  		'registrar'=>'REGISTRAR',
	  		'allreport'=>'ALL_REPORT',
	  		'library'=>'LIBRARY',
	  );
?>
<div class="card ">
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-settings" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('USERACCESS');?></h5>
	</div>
	<div class="card-body">
    	<div class="card-box">
    		<div class="col-md-6 col-sm-6 col-xs-12">
    			<div class="row g-3">
                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("USER_TYPE");?> :
                   </label>
                   <div class="col-md-7 col-sm-7 col-xs-12">
                    	<input type="text" required="true" name="user_type" id="user_type" placeholder="User Type" 
										dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs[0]['user_type'];?>"
										missingMessage="Invalid User type!" class='fullside' disabled/>
                   </div>
                </div>
               
	   		 </div>
    	</div>
    	<form name="frmsearch" action="" method="post">
	    	<div class="row">
	    		<div class="col-md-12 col-sm-12 col-xs-12">
	    			 <div class="row g-3">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name">
	                   <?php echo $tr->translate("SEARCH");?> <i class="fa fa-search" aria-hidden="true"></i> 
	                   </label>
	                </div>
	    		</div>
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MODULE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
							<select name="fmod" id="fmod" class='fullside' required="true" missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect">
								<?php echo $this->optoin_mod;?>
							</select>
	                   </div>
	                </div>
	    		</div>
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Controller");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="fcon" id="fcon" class='fullside' required="true" missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect">
	                   			<?php echo $this->optoin_con;?>
	                   		</select>
							<input type="hidden" name="fstatus" value="">
							<input type="hidden" name="fact" value="">
	                   </div>
	                </div>
	    		</div>
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="row g-3">
	    				<input type="submit" value="Search" name="btsave" label="<?php echo $tr->translate("SEARCH");?>" title="Search" dojoType="dijit.form.Button"/>
	    			</div>
	    		</div>
	    	</div>
    	</form>
    	<?php $show =0; if ($show==1){?>
    		<div class="row g-3">
                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Action");?> :
                   </label>
                   <div class="col-md-7 col-sm-7 col-xs-12">
                   		<select name="fact" id="fact" class='fullside' required="true" missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect">
							<?php echo $this->optoin_act;?>
						</select>
                   </div>
	        </div>
	        <div class="row g-3">
                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
                   </label>
                   <div class="col-md-7 col-sm-7 col-xs-12">
                   		<select name="fstatus" id="fstatus" class='fullside' required="true" missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect">
							<?php echo $this->optoin_status;?>
						</select>
                   </div>
	        </div>
		<?php }?>
		<div class="card-box">
		<table style="margin: 0 auto; width: 100%">
		<?php //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////	?>
			<tr>
				<td>
					<?php 
						$old_module = "";
					?>
					<div data-dojo-type="dijit/layout/TabContainer" style="width: 98%; height: 400px;" tabPosition="left-h" tabStrip="true">
						
						<?php if(!empty($this->rows)){foreach ($this->rows as $key=>$rs){ ?>
							<?php if($old_module != $rs['module']){
							   if($key==0){
							?>
								<div data-dojo-type="dijit/layout/ContentPane" title="<?php echo $tr->translate(strtoupper($rs['module']));?>" >
									<table width="100%" border="1" style="white-space: nowrap;border: 1px solid #ccc;border-collapse: collapse;">
										<tr align="center" style="background: #bcd5f0;">
											<td width="45%">
												<?php echo $tr->translate("USER_ACCESS");?>
											</td>
											<td width="45%">
												<?php echo $tr->translate("URL");?>
											</td>
											<td width="10%">
												<?php echo $tr->translate("STATUS");?>
											</td>
										</tr>
									
								<?php }?>
							<?php  if($key>0){?>
									</table>
							 	</div>
							 	<div data-dojo-type="dijit/layout/ContentPane" title="<?php echo $tr->translate(strtoupper($rs['module']));?>" >
							 	<table width="100%" border="1" style="white-space: nowrap;border: 1px solid #ccc;border-collapse: collapse;">
							 		<tr align="center" style="background: #bcd5f0;">
										<td width="45%">
											<?php echo $tr->translate("LABEL");?>
										</td>
										<td width="45%">
											<?php echo $tr->translate("URL");?>
										</td>
										<td width="10%">
											<?php echo $tr->translate("STATUS");?>
										</td>
									</tr>
							<?php }}?>
									
									<?php if($rs['is_menu'] == 1){
												$space="";
												$style="style='font-weight:bold;'";
											}else{
												$space="&nbsp;&nbsp;&nbsp;";
												$style="";
											}
									?>
									<style>
										.hover:hover{background: #ccc;}
									</style>
									<tr class="hover">
										<td <?php echo $style;?>>
											&nbsp;&nbsp; <?php echo $space.$tr->translate($rs['label']);?>
										</td>
										<td>
											&nbsp;&nbsp; <?php echo $rs['url']?>
										</td>
										<td align="center">
											<?php echo $rs['img']?>
										</td>
									</tr>
								
							<?php 
								
								//echo $rs['url'].$rs['img']."<br />";
								$old_module = $rs['module'];
							?>
						<?php }}?>
							</table>
						</div>
					</div>
				</td>
			</tr>
		<?php ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////?>	
		</table>
		</div>
    </div>
</div>
		
<style>
	.pointer{
		cursor: pointer;	
	}
</style>
<script>
$(function(){		
	$('#fmod').val('<?php echo $df['fmod']?>');
	$('#fcon').val('<?php echo $df['fcon']?>');
	$('#fact').val('<?php echo $df['fact']?>');
	$('#fstatus').val('<?php echo $df['fstatus']?>');
});
	function changeStatus(id, user_type){
		url = "<?php echo BASE_URL;?>/rsvacl/useraccess/update-status";
		status = "no";
		none_src = "<?php echo BASE_URL?>/images/icon/none.png";
		tick_src = "<?php echo BASE_URL?>/images/icon/tick.png";

		if( $("#img_" + id).attr("src") == tick_src){
			status = "yes";
		}
		
		$.post( url, { 'acl_id': id, 'status': status, 'user_type_id':user_type},
	      function( data ) {
			 img_src = none_src;
	         if(data == "yes"){
				img_src = tick_src;
	         }	         
	         $("#img_" + id).attr("src", img_src);
	      }
	    );
	}
</script>