<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle('SRMS | '.$tr->translate("Module Assignment List"));
	$url = Application_Form_FrmMessage::getUrl("/rsvacl/useraccess/view-user-access?id=");
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form name="frmlist" action="" dojoType="dijit.form.Form" method="post">
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
