<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle('SRMS | '.$tr->translate("Module Assignment List"));
	$url = Application_Form_FrmMessage::getUrl("/rsvacl/useraccess/view-user-access?id=");
?>
<div class="card">
	<div class="card-header ">
		<h5 class="card-title mb-0"><i class="ti ti-settings" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('USERACCESS');?></h5>
	</div>
	<div class="card-body">
		<?php echo $this->list;?>
	</div>
</div>
