<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_client_blacklist;
?>
<title> <?php echo $tr->translate("CLIENT_BLACK_LIST")?></title>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="ti ti-users"></i>&nbsp;<?php echo $tr->translate('CLIENT_BLACK_LIST');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					branch_id = dijit.byId('branch').get('value');
					  if (branch_id=='' || branch_id==-1){
						 infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?> ');
						 dijit.byId('branch').focus();
						 return false;
					  }
					if(dijit.byId('client_name').get('value')==''){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT");?> !');
					   dijit.byId('client_name').focus();
					   return false;
				   }
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
	    	<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("CUSTOMER_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('branch');?>
							   </div>
							</div>
							 <div class="row g-3">
								   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> :
								   </label>
									<div class="col-md-7 col-sm-7 col-xs-12">
										<input id="client_name" /><?php //echo $frm->getElement('client_name')?>
								   </div>
								</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('date');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REASON");?> :
							   </label>
								<div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('problem');?>
							   </div>
							</div>
						</div>
					</div>
	            </div>
	        </div>
			
			<!-- Button Save  -->
	        <div class="clearfix"></div>
			<div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" /> 
				    <input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"  value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"/> 
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="SAVE_NEW" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new" /> 
					
				</div>
			</div>
	    	<!--/. Button Save  -->
			
		</form>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
var client_store  = getDataStorefromJSON('id','name', [] );
require(["dojo/ready"], function(ready){
	 
	new dijit.form.FilteringSelect({
	store: client_store,
	required: false,		           
	name: "client_name",
	id: "client_name",
	searchAttr: "name",
	autoComplete: false,
	queryExpr: "*${0}*",
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('client_name').get('value');
		if(member==-1){
		}else{
		}
    }
	}, "client_name");


	
});
function filterClient(){
	branch_id = dijit.byId('branch').get('value');
	getAllClientByBranch(branch_id);
}
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('client_name').set('store', client_store);
		},
		error: function(err) {
		}
	});
	
}

</script>
