<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_client_blacklist;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title> <?php echo $tr->translate("CLIENT_BLACK_LIST")?></title>

<div class="card">
	<div class="card-content collapse show">
		
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'group','controller'=>'clientblacklist','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                if(dijit.byId('client_name').get('value')==''){
                   alert('Please Select Client Name');
                   dijit.byId('client_name').focus();
                   return false;
               }
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               		<div class="col-sm-12 border-botom">
		    			<div class="col-sm-8 pd-0">
		    				<h4 class="m-b-0"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CLIENT_BLACK_LIST');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BRANCH_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch'); echo $frm->getElement('id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('date');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REASON");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('problem');?>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_CODE");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="client_code" /><?php //echo $frm->getElement('client_code')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="client_name" /><?php //echo $frm->getElement('client_name')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                    <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('status')?>
	                   </div>
	                </div>
	            </div>
	        </div>
	        <div class="clearfix"></div>
			    <div class="card-box">
               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="submit" value="រក្សាទុក" name="btn_save" label="<?php echo $tr->translate('GO_EDIT');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
	    		</div>
	    	</div>
		</form>
	</div>
</div>

<script type="text/javascript">
function getmemberIdGroup(){
	client_code= dijit.byId('client_code').get('value');
	dijit.byId('client_name').attr('value',client_code);
}
function checkMember(){
	client_name= dijit.byId('client_name').get('value');
	dijit.byId('client_code').attr('value',client_name);
}
</script>
