<?php
	$this->headTitle('Loand Management System| Transfer'); 
	echo $this->headTitle();
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>	

<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>

<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form name="frmlist_mt" action="<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'transfer','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement("adv_search");?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('currency_type');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('status');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('start_date');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('end_date');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   					</div>
   				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>



