<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
$this->headTitle($tr->translate('EDIT_CATEOGY'));
echo $this->headTitle();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('EDIT_CATEOGY');?></h5>
	</div>
	<div class="card-body">
		<form id='frm_add_tran' action=""  dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="row">
	           	<div class="col-md-4 col-sm-4 col-xs-12">
	           		<div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('type');?>
	                   		<?php echo $frm->getElement('id');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PARENT");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="parent" />
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('title');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('note');?>
	                   </div>
	                </div>
	                <div class="row g-3">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('status');?>
	                   </div>
	                </div>
	                <div class="col-sm-12 border-top mt-2 py-2 text-center">
		    			<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVE")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" />
		    		</div>
	           	</div>
	       </div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/form/Textarea"]);
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.data.ObjectStore");
dojo.ready(function(){	
	category_store =  getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	new dijit.form.FilteringSelect({
		store: category_store,
		required: false,		           
		name: "parent",
		id: "parent",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
		onChange: function() {
		}
	}, "parent");

	getParentCategory();
});
var idcategory = '<?php echo $this->row['id']; ?>';
var	url_getparentcate = '<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'category','action'=>'get-parent'));?>';
function getParentCategory(){
	type = dijit.byId('type').get('value');
	if(type==0 || type==""){
		return false;
	}
	dojo.xhrPost({
		url: url_getparentcate,	
		content:{ 
			'type': type,'idcategory':idcategory
		},
		handleAs:"json",
		load: function(data) {	
			category_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('parent').set('store', category_store);
		    dijit.byId('parent').set('value', '<?php echo $this->row['parent']; ?>');
		    
		},
		error: function(err) {
		}
	});
}

</script>
