<?php 
$frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('CATEGORY_INCOME_EXPENSE'));
echo $this->headTitle();
?>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CATEGORY_INCOME_EXPENSE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement("adv_search");?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<select class="fullside"   name="type" id="type" dojoType="dijit.form.FilteringSelect" required="true">
							<option value="-1"><?php echo $tr->translate("SELECT_TYPE");?></option> 
							<option value="1" <?php echo ($this->search['type'] == 1)?"selected":"";?>><?php echo $tr->translate("INCOME");?></option>
							<option value="2" <?php echo ($this->search['type'] == 2)?"selected":"";?>><?php echo $tr->translate("EXPENSE");?></option>
					</select>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('status');?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   					</div>
   				</div>
			</form>
		</div>
		<div class="card-box">
			 <?php echo $this->list;?>
		</div>
	</div>
</div>


