<?php 
$frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('CATEGORY_INCOME_EXPENSE'));
echo $this->headTitle();
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-sitemap"></i>&nbsp;<?php echo $tr->translate('CATEGORY_INCOME_EXPENSE');?></h5>
		<div class="justify-content-between align-items-center ">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				
				<div class="row g-3">
					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement("adv_search");?>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<select class="fullside"   name="type" id="type" dojoType="dijit.form.FilteringSelect" required="true">
							<option value="-1"><?php echo $tr->translate("SELECT_TYPE");?></option> 
							<option value="1" <?php echo ($this->search['type'] == 1)?"selected":"";?>><?php echo $tr->translate("INCOME");?></option>
							<option value="2" <?php echo ($this->search['type'] == 2)?"selected":"";?>><?php echo $tr->translate("EXPENSE");?></option>
						</select>
   					</div>
   					<div class="col-md-2 col-sm-2 col-xs-12">
   						<?php echo $frm->getElement('status');?>
   					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="card-body">
		  <?php echo $this->list;?>
	</div>
</div>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>



