<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CLIENT'));
	 $frm = $this->frm_client;
?>
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 140px;
    height: 140px;
    border: solid 1px #eee;
}
.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 40px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 40px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 140px;
    height: 140px;
}
</style>
<!-- 
<section class="inputmask" >
	<div class="row">
    	<div class="col-sm-12">
-->
        	<div class="card">
               	<div class="card-content collapse show">
               		<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
               				<script type="dojo/method" event="onSubmit">			
								if(this.validate()) {
									if(dijit.byId('branch_id').get('value')==''){
										alert('Please Select Branch');
										dijit.byId('branch_id').focus();
										return false;
									}
									if(dijit.byId('province').get('value')==0){
										alert('Province required');
										dijit.byId('province').focus();
										return false;
									}
           							if(dijit.byId('situ_status').get('value')==''){
										alert('Province situ_status');
										dijit.byId('situ_status').focus();
										return false;
									}
									loadingBlock();
									return true;
								}else {
									return false;
								}
							</script>
							<div class="card-box">
			               		<div class="col-sm-12 border-botom">
					    			<div class="col-sm-8 pd-0">
					    				<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CLIENT');?></h4>
					    			</div>
					    			<div class="col-sm-4 text-right">
					    			</div>
					    		</div>
					    	</div>
		               		<div class="card-box">
					    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
						            <li class="nav-item active">
						                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("CLIENT");?></a>
						            </li>
						            <li class="nav-item">
						                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
						                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("JOIN_WITH");?>
						                </a>
						            </li>
						        </ul>
						    </div>
						    <div class="col-md-12">
						        <!-- Tab panels -->
						        <div class="tab-content vertical">
							        <!--Panel 1-->
							        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
					               		<div class="card-box">
											<div class="col-md-4 col-sm-4 col-xs-12">
												<div class="form-group">
								                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
								                   </label>
								                </div>
												<div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('branch_id');?>
														<?php echo $frm->getElement('is_group');?>
														<?php echo $frm->getElement('group_code');?>
														<?php echo $frm->getElement('group_id');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NO");?> <span class="required">*</span> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('client_no');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_KHMER");?> <span class="required">*</span> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('name_kh');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_ENG");?> <span class="required">*</span> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('name_en');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?> <span class="required">*</span> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('sex');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> <span class="required">*</span> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('dob_client');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SITU_STATUS");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('situ_status');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("JOB_TYPE");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('job');?>
								                   </div>
								                </div>
							                </div>
							                
								            <div class="col-md-4 col-sm-4 col-xs-12">
												<div class="form-group">
								                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CONTACT_INFO");?> 
								                   </label>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> <span class="required">*</span> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('phone');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Group No");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('group_no');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("HOUSE");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('house');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STREET");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('street');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE");?> <span class="required">*</span> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('province');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<input id="district" required="true" >
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<input id="commune" >
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<input id="village" >
								                   </div>
								                </div>
								            </div>
								            
								            <div class="col-md-4 col-sm-4 col-xs-12">
												<div class="form-group">
								                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_DOCUMENT");?> 
								                   </label>
								                </div>
								                <div class="form-group">
								                    <div class="col-md-12 col-sm-12 col-xs-12">
								                     <label class="control-label " for="first-name"><strong><?php echo $tr->translate("AUTO_COLLATERAL");?></strong> :
								                   	</label>
								                    	<?php  echo $frm->getElement('chackcall');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<input id="client_d_type" required="true"/>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("N_O");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('national_id');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHOTO");?> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php //echo $frm->getElement('photo');?>
														<div class="account-image">
															<div class="image-box">
																<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
															</div>
															<div class="button_browse">
															<div id='preview'></div>	
																	<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
																	<input class="btn_borwse_image" type="file" id="photo" name="photo" />
															</div>
														</div>
								                   </div>
								                </div>
								            </div>
					               		</div>
							
							        </div>
							        <!--/.Panel 1-->
							        <!--Panel 2-->
							        <div class="tab-pane fade in " id="panel22" role="tabpanel">
								    	<div class="card-box">
								    		<div class="col-md-4 col-sm-4 col-xs-12">
												<div class="form-group">
								                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("JOIN_ACCOUNT_INFO");?> 
								                   </label>
								                </div>
												<div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("JOIN_WITH");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('join_with');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?> <span class="required">*</span> :
								                   </label>
								                    <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('join_sex');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('relate_with');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('dob_join_acc');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<input id="join_d_type" />
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("N_O");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('join_nation_id');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEL");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('relate_tel');?>
								                   </div>
								                </div>
								            </div>
								            <div class="col-md-4 col-sm-4 col-xs-12">
												<div class="form-group">
								                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("GUARANTOR_INFO");?> 
								                   </label>
								                </div>
												<div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SPOUSE_NAME");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('spouse');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELATIVE_WITH");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('guarantor_with');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('dob_guarantor');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONAL_ID");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<input id="guarantor_d_type" />
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("N_O");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('spouse_nationid');?>
								                   </div>
								                </div>
								            </div>
								            <div class="col-md-4 col-sm-4 col-xs-12">
												<div class="form-group">
								                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CONTACT_INFO");?> 
								                   </label>
								                </div>
												<div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEL");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('guarantor_tel');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ADDRESS");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('guarantor_address');?>
								                   </div>
								                </div>
								                <div class="form-group">
								                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                    	<?php echo $frm->getElement('desc');?>
								                   </div>
								                </div>
								            </div>
								    	</div>
							        </div>
							        <!--/.Panel 2-->
						        </div>
						    </div>
						    <div class="clearfix"></div>
						    <div class="card-box">
			               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					    			<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
										 iconClass="dijitIconClear" /> 
									 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
										 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
									<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
										 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
					    		</div>
					    	</div>
					</form>
				    
            	</div>
        	</div>
    	<!-- </div>
	</div>
</section>-->
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog"  id="frm_jobtype" >
			<form id="form_job" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<table style="margin: 0 auto; width: 100%;" cellspacing="7">
					<tr>
						<td><?php echo $tr->translate("JOB_TITLE")?></td>
						<td>
							<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="job_name" name="job_name" value="" type="text"></td>
					</tr>
					<tr>
						<td colspan="2" align="center">
						<input type="button" value="Save" label="<?php echo $tr->translate("SAVECLOSE")?>" dojoType="dijit.form.Button"
						iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addjob();"/>
						</td>
					</tr>
				</table>
		</form>
	</div>
</div>
<?php 
	echo $this->frm_popup_district;
	echo $this->frm_popup_village;
	echo $this->frm_popup_comm;
	echo $this->frm_popup_clienttype;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	dojo.require("dijit.Dialog");

	function readURL(input) {
	    if (input.files && input.files[0]) {
	        var reader = new FileReader();
	        
	        reader.onload = function (e) {
	            $('#profile_wiew').attr('src', e.target.result);
	        }
	        reader.readAsDataURL(input.files[0]);
	    }
	}
	$("#photo").change(function(){
	    readURL(this);
	});
	
	function popupJobOption(){
		job = dijit.byId('job').get('value');
		if(job==-1){
			dijit.byId('frm_jobtype').show();
		}
	}
	url_job = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'addjob'));?>';
	function addjob(type){
		 if(dijit.byId('form_job').validate()){
			labeljob = dijit.byId('job_name').get('value');
			$('#job').val(labeljob);
			$('input[name="job"]').val(labeljob);				
			dijit.byId('frm_jobtype').hide();
		}
	}
	var d_datastore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
	var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	try{
	new dijit.form.FilteringSelect({
	store: district_store,
	required: false,		           
	name: "district",
	id: "district",
	placeHolder:"<?php echo $tr->translate("DISTRICT")?>",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			district = dijit.byId('district').get('value');
			if(district==-1){
				showPopupdistrict();
				}
				filterCommune();
		}  
	}, "district");
	 
	new dijit.form.FilteringSelect({
	store: commune,
	required: false,		           
	name: "commune",
	id: "commune",
	placeHolder:"<?php echo $tr->translate("COMMUNE")?>",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			commune = dijit.byId('commune').get('value');
			if(commune==-1){
				showPopupCommune();
			}
			else{
				filterVillage();
			}
  }
	}, "commune");
	 
	new dijit.form.FilteringSelect({
	store: village_store,
	autoComplete: true,	           
	name: "village",
	id: "village",
	placeHolder:"<?php echo $tr->translate("VILLAGE")?>",
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			vill = dijit.byId('village').get('value');
			if(vill==-1){
				showPopupVillage();
			}
		}
	}, "village");

	new dijit.form.FilteringSelect({
		store: d_datastore,       
		required: false,		           
		name: "client_d_type",
		id: "client_d_type",
		searchAttr: "name",
		placeHolder:"<?php echo $tr->translate("DOCUMENT_TYPE")?>",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('client_d_type').get('value');
				if(client_d_type==-1){
					doc_type=1;
					showPopupclientdtype();
				}
			}
		}, "client_d_type");

	new dijit.form.FilteringSelect({
		store: d_datastore,       
		required: false,		           
		name: "join_d_type",
		id: "join_d_type",
		searchAttr: "name",
		placeHolder:"<?php echo $tr->translate("DOCUMENT_TYPE")?>",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('join_d_type').get('value');
				if(client_d_type==-1){
					doc_type=2;
					showPopupclientdtype();
				}
			}
		}, "join_d_type");

	new dijit.form.FilteringSelect({
		store: d_datastore,
		required: false,		           
		name: "guarantor_d_type",
		id: "guarantor_d_type",
		placeHolder:"<?php echo $tr->translate("DOCUMENT_TYPE")?>",
		searchAttr: "name",
		autoComplete: false,
		queryExpr: "*${0}*",
		class: 'fullside',
			onChange: function() {
				client_d_type = dijit.byId('guarantor_d_type').get('value');
				if(client_d_type==-1){
					doc_type=3;
					showPopupclientdtype();
				}
			}
		}, "guarantor_d_type");
	
	}catch(e){
		alert(e);
	}
	filterDistrict();
});

url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': commune_id
		},
		handleAs:"json",
		load: function(data) {	
			village_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('village').set('store', village_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_group = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getgroupcode'));?>';
function getGroupCode(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch First');
		dijit.byId('branch_id').focus();
		return false;
	}
	group_id=dijit.byId('group_id').get('value');
	if(group_id==''){group_id=0;}
	if(dijit.byId('is_group').checked ==true){
		is_group=1;
		dijit.byId('group_code').attr('value','');
		dijit.byId('group_id').set('readOnly', true);
	}else{
		is_group=0;	
		dijit.byId('group_id').set('readOnly', false);
	}
	dojo.xhrPost({
		url:url_group,	
		content:{ 
		    'group_id':group_id,
		    'is_group':is_group,
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {	
			dijit.byId('group_code').attr('value',data);
		},
		error: function(err) {
		}
	});
}
client_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientcode'));?>';
function getFunction(){
		getGroupCode();
		branch_id = dijit.byId('branch_id').get('value');
		dojo.xhrPost({
			url:client_submit,	
			content:{ 
			    'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {	
				dijit.byId('client_no').attr('value',data);
			},
			error: function(err) {
			}
		});
}
client_village = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-village'));?>';
function addVillage(){
	if(dijit.byId('frm_village').validate()) {
		dojo.xhrPost({
			url:client_village,	
			form:dojo.byId('form_village'),
			handleAs:"json",
			load: function(data) {
				labelkh = dijit.byId('village_namekh').get('value');
				var villageItem1 = {					
						id: data,
						name:labelkh,
				};			
				addDataToSelectbox(dijit.byId('village'), village_store, villageItem1, data);	
				dijit.byId('frm_village').reset();
				dijit.byId('frm_village').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name:dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				//communeen = dijit.byId('commune_nameen').get('value');
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name:communekh,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var document_type_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-document-type'));?>';
function addNewDocumentType(){
	if(dijit.byId('frm_clienttype').validate()){
	dojo.xhrPost({
		url:document_type_url,	
		content:{ 
		    'title_en':dijit.byId('clienttype_namekh').get('value'),
		    'title_kh':dijit.byId('clienttype_namekh').get('value'),
		    'type':23,
		},
		handleAs:"json",
		load: function(data) {	
			clienttypekh = dijit.byId('clienttype_namekh').get('value');
			if(doc_type==1){
				document_type = dijit.byId('client_d_type');
				
			}else if(doc_type==2){
				document_type = dijit.byId('join_d_type');
			}else{
				document_type = dijit.byId('guarantor_d_type');
			}

			 var myNewItem1 = {					
						id: data,
						name: clienttypekh
				};			
				addDataToSelectbox(document_type, d_datastore, myNewItem1, data);		
				 
			dijit.byId('frm_clienttype').reset();
			dijit.byId('frm_clienttype').hide();
		},
		error: function(err) {
			alert(err);
		}
	});	
	}
}
function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}
function submitDataClose(){
	if(dijit.byId('branch_id').get('value')==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
    }
	if(dijit.byId('province').get('value')==0){
		alert('Province required');
		dijit.byId('province').focus();
		return false;
    }
    if(dijit.byId('situ_status').get('value')==''){
		alert('Province situ_status');
		dijit.byId('situ_status').focus();
		return false;
    }
	if(dijit.byId('add_client').validate()) {
		loadingBlock();
		var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_client"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/group/index";
			},
			error: function(e) {
			}
		});
	}
}
</script>