<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("CLIENT_LIST"));
	$frm = $this->frm_search;
	$frms=$this->frm_client;
	$url_profile = $this->baseUrl()."/group/index/view/id/";
	$url_edit = $this->baseUrl()."/group/index/edit/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
    	<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CLIENT_LIST');?></h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
        <div class="card-box">
	    	<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frms->getElement('province');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="district" >
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="commune" >
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="village" >
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
				<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?> 
		</div>
   </div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dijit.form.DateTextBox");
dojo.ready(function(){
	dijit.byId('province').attr('value',<?php echo $this->result['province_id'];?>);	
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		pro_id:"<?php echo $this->result['province_id'];?>"
	},            
	required: false,		           
	name: "district",
	id: "district",
	placeHolder:"<?php echo $tr->translate("DISTRICT")?>",
	autoComplete: false,
	queryExpr: "*${0}*",
	searchAttr: "name",
	value: "<?php echo $this->result['district_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district");
	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		district_id: "<?php echo $this->result['district_id'];?>"
	},            
	required: false,		           
	name: "commune",
	id: "commune",
	placeHolder:"<?php echo $tr->translate("COMMUNE")?>",
	autoComplete: false,
	queryExpr: "*${0}*",
	searchAttr: "name",
	value: "<?php echo $this->result['comm_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			filterVillage();
  }
	}, "commune");
	var village_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->village_name));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: village_data}),
	autoComplete: true,
	query: {
		commune_id:"<?php echo $this->result['comm_id'];?>"
	},            
	required: false,		           
	name: "village",
	id: "village",
	placeHolder:"<?php echo $tr->translate("VILLAGE")?>",
	autoComplete: false,
	queryExpr: "*${0}*",
	searchAttr: "name",
	value: "<?php echo $this->result['village'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
}
	}, "village");	
});
function filterDistrict(){
	dijit.byId('district').query.pro_id = dijit.byId('province').get('value');
}
function filterCommune(){
	dijit.byId('commune').query.district_id = dijit.byId('district').get('value');
}
function filterVillage(){
	id =dijit.byId('commune').get('value');
	dijit.byId('village').query.commune_id = dijit.byId('commune').get('value');
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="profle"){
				url='<?php echo $url_profile;?>';
			}else if(key=="edit"){
				url='<?php echo $url_edit;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "fa-edit", accesskey: "c o p y"},
			"profle": {name: "<?php echo $tr->translate("PROFILE");?>", icon: "fa-user", accesskey: "c o p y"},
			
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>