<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_BADLOAN'));
$frm = $this->frm_loan;
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-edit"></i>&nbsp;<?php echo $tr->translate('EDIT_BADLOAN');?></h5>
	</div>
	<div class="card-body">
    	<form id="add_province" action="<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
    				if(dijit.byId('branch').get('value')==''){
     					infoMessageAlert('Please Select Branch');
     					dijit.byId('branch').focus();
     					return false;
   					}
					if(dijit.byId('client_codeadd').get('value')==0 || dijit.byId('client_codeadd').get('value')==''){
     					infoMessageAlert('Please Select Client Code');
     					dijit.byId('client_codeadd').focus();
     					return false;
   					}
					if(dijit.byId('client_nameadd').get('value')==0 || dijit.byId('client_nameadd').get('value')==''){
     					infoMessageAlert('Please Select Client Name');
     					dijit.byId('client_nameadd').focus();
     					return false;
   					}
					loadingBlock();
    				return true;
   			}else {
    			return false;
   			}
			</script>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("BRANCH_INFO");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('branch');?>
									<?php echo $frm->getElement('id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_NO");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('get_laonnumber_edit');?>
									<?php echo $frm->getElement('oldloan_id');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('interest_rate');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CUSTOMER_INFO");?> 
							   </label>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_CODE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
								<input id="customer_code" /><?php //echo $frm->getElement('client_codeadd');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<input id="member" /><?php //echo $frm->getElement('client_nameadd')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_LEVEL");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('load_level');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_AMOUNT");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('total_amount_loan')?>
							   </div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("TERM_INSTALL");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TERM_INSTALL");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('payment_term')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TERM_BORROW");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('loan_period');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RELEASE_DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('release_date');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LIFE_LOAN");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('end_date');?>
							   </div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card card-form mb-4">
						<div class="card-header d-flex justify-content-between">
							<h5 class="card-title m-0 me-2 pt-1 mb-2 d-flex align-items-center"><i class="ti ti-list-details ms-n1 me-2"></i> <?php echo $tr->translate("ព៌ត័មាន កម្ចីខូច");?></h5>
						</div>
						<div class="card-body">
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OS");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Total_amount');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_INTEREST");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Interest_amount');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CURRENCY");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('cash_type');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TERM");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('Term');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOSS_DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('date_loss')?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('Date');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php  echo $frm->getElement('Note');?>
							   </div>
							</div>
							<div class="row g-3">
							   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
							   </label>
							   <div class="col-md-7 col-sm-7 col-xs-12">
									<?php echo $frm->getElement('status');?>
							   </div>
							</div>
						</div>
					</div>
	             </div>
	         </div>
	         <div class="card-box">
	         	<div class="col-sm-12 border-top mt-2 py-2 text-center">
	         		<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"  name="save_close" id="save_close" value="រក្សាទុក  + ចាកចេញ" label="<?php echo $tr->translate('SAVECLOSE')?>" id="submitBtn" dojoType="dijit.form.Button" />
	         	</div>
	         </div>
		</form>
   	</div>
</div>
<script>
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.html");
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);

dojo.require("dijit.form.NumberTextBox");

dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.html");
require(["dojo/ready"], function(ready){
	 ready(function(){
		//setFirstPaymentAndDateLine(3,<?php //echo date('d-m-Y');?>,1);
		//changeCollectType();
		getInfoByLoanNumber();
	  });
	  
	 var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		//getClientInfo(2);
	}
	}, "member");

	 var client_number = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient_number));?>
	});
		new dijit.form.FilteringSelect({
		store: dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,
		query: {
			branch_id: "-1"
		},            
		required: false,		           
		name: "customer_code",
		id: "customer_code",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
	}
		}, "customer_code");

	 
	 
	});
var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'getloaninfo')); ?>';
function getClientInfo(type){
	if(type==1){
		values = dijit.byId("client_nameadd").get('value');
	}else if(type==2){
		values = dijit.byId("client_codeadd").get('value');
	}else{
		values = dijit.byId("client_codeadd").get('value');
	} 
	dijit.byId('Total_amount').attr('value',0);
	//dijit.byId('Interest_amount').attr('value',0);
	//dijit.byId("cash_type").set('readOnly',false);
	//values=dijit.byId("client_code").get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'loan_id':values,
		  //  'type':type,
		},	
		handleAs:"json",
		load: function(data) {
			//infoMessageAlert(data);
			dijit.byId('Total_amount').attr('value',data.total_principal);
			dijit.byId('Interest_amount').attr('value',data.total_interest);
			//dijit.byId('loannumber').attr('value',data.loan_number);
			dijit.byId('load_level').attr('value',data.level);
			dijit.byId('interest_rate').attr('value',data.interest_rate);
			dijit.byId('payment_term').attr('value',data.pay_term);
			dijit.byId('loan_period').attr('value',data.total_duration);
		    dijit.byId('release_date').attr('value',data.date_release);
		    dijit.byId('end_date').attr('value',data.date_line);
			dijit.byId('total_amount_loan').attr('value',data.total_capital);
			dijit.byId('date_loss').attr('value',data.date_payment);
			dijit.byId('cash_type').attr('value',data.currency_type);
			dijit.byId("cash_type").set('readOnly',true);
			dijit.byId("client_nameadd").attr('value',values);
			dijit.byId("client_codeadd").attr('value',values);
		},
		error: function(err) {
			infoMessageAlert(err);
		
				        
		}
	});
	
}


function submitDataClose(){
	if(dijit.byId('branch').get('value')==''){
 		infoMessageAlert('Please Select Branch');
 		dijit.byId('branch').focus();
 		return false;
		}
	if(dijit.byId('client_codeadd').get('value')==0 || dijit.byId('client_codeadd').get('value')==''){
 		infoMessageAlert('Please Select Client Code');
 		dijit.byId('client_codeadd').focus();
 		return false;
		}
	if(dijit.byId('client_nameadd').get('value')==0 || dijit.byId('client_nameadd').get('value')==''){
 		infoMessageAlert('Please Select Client Name');
 		dijit.byId('client_nameadd').focus();
 		return false;
		}
	
	if(dijit.byId('add_province').validate()) {
		dijit.byId("save").set("disabled",true);
		dijit.byId("save_close").set("disabled",true);
		var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_province"),		    
			load: function(data) {
				infoMessageAlert('<?php echo $tr->translate('INSERT_SUCCESS');?> !',1);
				window.location.href ="<?php echo $this->baseUrl();?>/loan/badloan";
			},
			error: function(e) {
			}
		});
	}
}



var oldLoanId='<?php echo $this->row['loan_id'];?>';
function getInfoByLoanNumber(){
	var url_submiinfoall = '<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'getloaninfo-by-loanid')); ?>';
	var url_submiinfoedit = '<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'getloaninfo-by-loanidedit')); ?>';
	loan_id = dijit.byId('get_laonnumber_edit').get('value');
	if(loan_id==oldLoanId){
		url_submiinfo = url_submiinfoedit;
	}else{
		url_submiinfo=url_submiinfoall;
	}
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'loan_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('Total_amount').attr('value',data.total_principal);
			dijit.byId('Interest_amount').attr('value',data.total_interest);
			//dijit.byId('loannumber').attr('value',data.loan_number);
			dijit.byId('load_level').attr('value',data.level);
			dijit.byId('interest_rate').attr('value',data.interest_rate);
			dijit.byId('payment_term').attr('value',data.pay_term);
			dijit.byId('loan_period').attr('value',data.total_duration);
		    dijit.byId('release_date').attr('value',data.date_release);
		    dijit.byId('end_date').attr('value',data.date_line);
			dijit.byId('total_amount_loan').attr('value',data.total_capital);
			dijit.byId('date_loss').attr('value',data.date_payment);
			dijit.byId('cash_type').attr('value',data.currency_type);
			dijit.byId("cash_type").set('readOnly',true);
			//dijit.byId("client_nameadd").attr('value',values);
			//dijit.byId("client_codeadd").attr('value',values);
			dijit.byId('customer_code').set('readOnly',true);
			dijit.byId("customer_code").attr('value',data.client_id);
			dijit.byId("member").attr('value',data.client_id);
			dijit.byId('member').set('readOnly',true);
		},
		error: function(err) {
			//infoMessageAlert(err);
		}
	});
}
function getLoanInfoByLoanNumber(){
	
}
</script>


