<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('BAD_LOAN'));
 $frm = $this->frm_loan;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
 <div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
           	<div class="col-sm-12 border-botom">
	    		<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('BAD_LOAN');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'badloan','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('adv_search');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('client_name');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('client_code');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('Term');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('cash_type');?>
			   		</div>
			   	</div>
			   	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('status');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			</form>
    	</div>
    	<div class="card-box">
			<?php echo $this->list;?>
		</div>
   	</div>
 </div>       	
