<?php 
     $url_save = $this->url(array('module'=>'stock','controller'=>'productcategory','action'=>'add'));
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $status_view=$this->status_view;
	 
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	 echo $this->headTitle($tr->translate('PRODUCT_CATEGORY'));
?>
<div class="card">
	<div class="card-header">
		<h5 class="card-title mb-0"><i class="fa fa-sitemap"></i>&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?></h5>
	</div>
	<div class="card-body">
		<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
               		dijit.byId("save_new").attr("disabled",true);
					loadingBlock();
					return true;
				} else {
					return false;
				}
				</script>
				<div class="row">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="row g-3">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRODUCT_CATEGORY");?>
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="cat_name" name="cat_name" value="" type="text" required="required" >
		                   </div>
		                </div>
		                <div class="row g-3">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
								        <option value="1"><?php echo $tr->translate("ACTIVE");?></option>
								         <option value="0"><?php echo $tr->translate("DACTIVE");?></option>
								</select>
		                   </div>
		                </div>
						<div class="card-box">
							<div class="col-sm-12 border-top mt-2 py-2 text-center">
								<input type="reset" class="button-class button-danger " iconClass="glyphicon glyphicon-repeat" value="Clear" label="<?php echo $tr->translate("CLEAR");?>" dojoType="dijit.form.Button" />
								<input type="submit"  class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate("SAVENEW");?>" dojoType="dijit.form.Button"   />
							</div>
						</div>
		            </div>
		        </div>
		</form>
	</div>
</div>
	